### PR TITLE
Update automation-solution-startstopvm-psworkflow.md

### PR DESCRIPTION
**Pull request by milanio**
Small fix : Stop-AzureVMs commands have output which seems to belong to Start-AzureVMs

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@milanio__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@milanio : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@milanio - Thank you for taking the time to submit this request to correct errors identified.  I approve your recommended changes, but there are two additional changes you should include in your PR that I identified while reviewing.  1) The message for the second Stop-AzureVM should read "MyVM has been stopped" 2) The message for the third Stop-AzureVm should read "MyVM failed to stop".

**Comment by milanio** [comment]
@MGoedtel, thanks! Fixed.

**Comment by MGoedtel** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@Matt Goedtel Hi Matt
Your sign off did not work with the comment automation because your GitHub account is listed incorrectly in the article metadata: authors="mgoedtel"
It needs to match your GitHub account EXACTLY, including capitalization. Please fix your GitHub account in all your articles after this is merged. Thanks.

**Pull request merged**
