### PR TITLE
Update resource-manager-policy.md

### PR DESCRIPTION
**Pull request by cyl3392207**
Update the policy document from a few feedback from the readers

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cyl3392207__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
@cyl3392207 - When you say "nested conditions are not supported as described in the syntax above", do you mean nested conditions are not supported? I think we should remove "as described ..." to avoid any confusion. 

Also, the link cannot include "/en-us" so it works with localized content.

**Comment by cyl3392207** [comment]
Sounds good to me. Feel free to make necessary updates.

**Comment by tfitzmac** [comment]
I have re-submitted changes through another pull request. This one can be closed.

**Pull request closed without merging**
