### PR TITLE
Update active-directory-saas-amazon-web-service.md

### PR DESCRIPTION
**Pull request by sjwaight**
Changed attribute from 'mail' to 'userprincipalname' which is the actual field you should be integrating against as it is the primary user identifier. Utilising 'mail' will not always result in a successful integration depending on the AAD fields populated for the user.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sjwaight__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Reviewing w/Markus

**Comment by BryanLa** [comment]
Still waiting on review

**Comment by BryanLa** [comment]
Third ping. Will close if no response.

**Pull request merged**
