### PR TITLE
Update automation-first-runbook-graphical.md

### PR DESCRIPTION
**Pull request by venkatveeramanidaasan**
Added a note to caution the expected behavior of Start-VM activity when there is not resource available with the given name.

Thanks
Venkat

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@venkatveeramanidaasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@venkatveeramanidaasan : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@venkatveeramanidaasan I've reviewed your suggested change and I'm not agreeing with what you have proposed.  It is noted in the prerequisites section and in this section that an Azure VM needs to exist in order for you to proceed with this tutorial.  Thanks for taking the time to submit this for consideration; however in this case, I am not going to approve it.

**Comment by venkatveeramanidaasan** [comment]
@MGoedtel  fine :) it makes sense. I have missed the prereq part.

**Pull request closed without merging**
