### PR TITLE
update SDK link from management SDK to actual SDK

### PR DESCRIPTION
**Pull request by thematan**
and add a row in the management SDKs list with the previous link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thematan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@thematan - thanks very much for your contribution! As this PR has a merge conflict, can you please create a new PR against the current version of the article (`https://azure.microsoft.com/en-us/documentation/articles/key-vault-developers-guide/`), or resolve the conflict? 

@BrucePerlerMS - the change is suggesting that the Node.JS SDK link be changed FROM `http://azure.github.io/azure-sdk-for-node/azure-arm-keyvault/latest` TO `https://www.npmjs.com/package/azure-keyvault`. Can you please review when you have a change and let me know your thoughts?

**Comment by BrucePerlerMS** [comment]
I've looked at both links, the current and the suggested change; they are for two different artifacts. The original is for the generated SDK docs, the suggested change is for the package itself. I'll add a link for the package to the Key Vault Developer's Guide. This should address the problem. 
~ Bruce

**Comment by BryanLa** [comment]
Excellent, thanks @BrucePerlerMS . 
@thematan - I will close this PR given the merge conflict. Look for your suggestion to surface in a future version of this article, and thanks again!

**Pull request closed without merging**
