### PR TITLE
Update virtual-networks-public-ip-within-vnet.md

### PR DESCRIPTION
**Pull request by stegag**
i believe there is a typo in the DNS address
which has to be 168.63.129.16

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stegag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stegag). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@telmosampaio - Could you please review and let @stegag and me know if this can be merged?

**Comment by tysonn** [comment]
@telmosampaio - Second notice - please review

**Comment by jimdial** [comment]
@tysonn - This is a good catch, the IP should begin with 168, not 68 as it currently does.  Thanks @stegag!

**Comment by jimdial** [comment]
#sign-off

**Pull request merged**
