### PR TITLE
Added EDIFACT link and removed coming soon tag

### PR DESCRIPTION
**Pull request by padmavc**

### CODE REVIEW

**Comment by PRmerger** [comment]
@padmavc : Thanks for your contribution to the Azure documentation! The author, @msftman, has been notified to review your proposed change.

**Comment by padmavc** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by padmavc** [comment]
The author of the article is on 3 weeks’ vacation.  Erik, author manager, has provided sign off on behalf of him.  If that is not sufficient, suggest me what would be the best way to make corrections on the doc.


Thanks
Padma

**Comment by Erikre** [comment]
I'll #sign-off while @msftman is OOF.

**Comment by ggailey777** [comment]
PRMerger is a bot...not so good at conversation 😉 I will merge.

**Pull request merged**
