### PR TITLE
Update sql-data-warehouse-performance-scale.md

### PR DESCRIPTION
**Pull request by lodipalm**
Adding portal instructions and clarifying T-SQL instructions.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lodipalm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@barbkess 
Please review and approve here, thanks.

**Comment by barbkess** [comment]
Drew, in this sentence, do you mean "through the Azure Portal, or by using Transact-SQL via REST APIs or PowerShell cmdlets?
Increasing your compute power can be done through the Azure Portal, using T-SQL, via REST APIs or through Powershell.

**Comment by lodipalm** [comment]
No, the sentence is correct as is.  Although, a comma after APIs might help clarify if you think there is confusion.  There are 4 distinct ways that users can scale which this is listing. 

It seems like your suggestion is implying that TSQL is used in the REST APIs/cmdlets.  However these are three separate operations and have different, corresponding syntax.

**Comment by barbkess** [comment]
Can you change it to active voice and say this?
 "To increase compute power, use the Azure portal, Transact-SQL commands, REST APIs, or PowerShell cmdlets."

**Comment by rmca14** [comment]
@JennieHubbard 
This one is pending input from Drew DiPalma, but maybe he and Barb will need more discussion.

**Comment by lodipalm** [comment]
Have made changes to use the active voice.

**Comment by JennieHubbard** [comment]
#signoff

**Pull request merged**
