### PR TITLE
WMF4 and NET 4.5 are prereqs on 2008R2 and 2012 Server

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@snobu : Thanks for your contribution to the Azure documentation! The author, @MandiOhlinger, has been notified to review your proposed change.

**Comment by MandiOhlinger** [comment]
@snobu : Thank you for the addition. 
@ggailey777 - Let's merge as-is.

**Comment by ChrisCompy** [comment]
@snobu: I missed your submission.  My github work account is chriscompy   my ccompy predated working at MS and I kept it separate sadly when I started at MS.  Thanks for the change. 
@MandiOhlinger :  The change is good.  Thanks for following up on it.

**Pull request merged**
