### PR TITLE
Added samples using New-AzureRmSqlDatabaseCopy

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SvenAelterman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SvenAelterman : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@SvenAelterman - Thanks for the code snippets!

If you update the first code block description to say: 'Copy a database to the **same** server', and the 2 mentions of **commandlets** to **cmdlets**, I'll approve and get this pushed live.

Thanks!

**Comment by SvenAelterman** [comment]
@stevestein Done! Thanks.

**Comment by stevestein** [comment]
@SvenAelterman - Excellent, thanks again! 
@tysonn  - this PR is ready to merge.

#sign-off

**Comment by KatieCumming** [comment]
@stevestein - thanks for your close review. Merging.

**Pull request merged**
