### PR TITLE
Make it easier to integrate with Azure web sites

### PR DESCRIPTION
**Pull request by mxa0079**
It adds a reference link on how to configure client certificates in Azure Websites. I spent the full day getting this to work due to lack of knowledge about how to do it on websites (misleading that we can remote into IIS Manager and activate it there, even though that is the wrong way to do it). Until I finally found the link referenced and got it to work. If this link would have been part of the article, I would have finished configuring in 1 hour and not 8.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mxa0079__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@steved0x can you please verify this customer's contribution?

**Comment by steved0x** [comment]
@ggailey777 Please add this note.

@mxa0079 Thank you for your contribution, this link is a great addition to the article. Sorry that you had a struggle before finding that information.

**Comment by mxa0079** [comment]
@steved0x Glad to help!

**Comment by ggailey777** [comment]
Merged! Thanks @mxa0079 for your contribution to improving Azure docs and @steved0x for your fast response.

**Pull request merged**
