### PR TITLE
Update automation-troubleshooting-automation-errors.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@MGoedtel Matt, can you take a look at Aleksandar's contributions to your article and let me know if they are okay to merge? Please let him know as well. Thanks,

**Comment by MGoedtel** [comment]
Reviewed and approve for merge.

**Comment by MGoedtel** [comment]
@alexandair I've reviewed and am good with your suggested edits.

**Pull request merged**
