### PR TITLE
Create Network Access Control Lists

### PR DESCRIPTION
**Pull request by MAYAKARYA**
https://github.com/Azure/azure-content/blob/master/articles/virtual-network/virtual-networks-acl-powershell.md

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MAYAKARYA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MAYAKARYA : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@jimdial Hi Jim Please review the proposed changes. Thanks.

**Comment by jimdial** [comment]
@MAYAKARYA Please let me know what change you're proposing and why.  It's not clear to me in your proposal. Thanks

**Comment by jimdial** [comment]
It's not clear to me what changes are suggested for this article.  Since there's been no reply from @MAYAKARYA then #PLEASE-CLOSE @jomolnar .

**Pull request closed without merging**
