### PR TITLE
Update media-services-sspk.md

### PR DESCRIPTION
**Pull request by xpouyat**
Added Nintendo as Interim licensee

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@xpouyat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (xpouyat). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by xpouyat** [comment]
sign-off

**Comment by xpouyat** [comment]
#sign-off

**Comment by ggailey777** [comment]
@xpouyat this fix was made in the public repo, where there is no validation or staging and you don't need to #sign-off. You probably meant to do this in the private repo.

**Pull request merged**
