### PR TITLE
Update service-fabric-add-a-web-frontend.md

### PR DESCRIPTION
**Pull request by SychevIgor**
ASP.NET 5 to ASP.NET Core 1
https://github.com/aspnet/Announcements/issues/144

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SychevIgor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@seanmck - Could you please review this contribution from @SychevIgor and let me know if it should be merged? Thx.

**Comment by seanmck** [comment]
The current template included in our SDK is based on based on RC1, which was released under the ASP.NET 5 name. We will update the nomenclature to ASP.NET Core 1 once we integrate an RC2-based template.

**Comment by tysonn** [comment]
@seanmck - It sounds like the feedback is to close the PR without merging, so closing.

**Pull request closed without merging**
