### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
seems reasonable

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @TerryLanfear, has been notified to review your proposed change.

**Comment by TerryLanfear** [comment]
@4c74356b41 - Thank you for the update, your changes can be merged.

@BryanLa - This PR can be merged.

**Comment by TerryLanfear** [comment]
@4c74356b41 - My apologies, I am waiting for input from editorial.

@BryanLa - Please hold-off on merge, #hold-off

**Comment by 4c74356b41** [comment]
no worries, no haste. It might not be appropriate for you, its ok.

**Comment by 4c74356b41** [comment]
hello?

**Comment by TerryLanfear** [comment]
@4c74356b41 - Hi, Sorry for not replying to your last message. I get an email when someone messages me but I didn't know that only the first line of a message is in the email.  I didn't see your entire message.  Again, my apologies.  I'm also sorry that you have not received a response regarding your other PRs.  This week we all received an email about PRs that had not been responded to.  This should generate a response from the other writers for those articles.  I will also reach out to those writers and remind them that there is a PR that needs their attention.  Hope this helps.

**Comment by TerryLanfear** [comment]
@4c74356b41  - Looks like this can go as you have it.  Thank you for the update, your changes can be merged.

@BryanLa  - This PR can be merged.

**Pull request merged**
