### PR TITLE
Fix variable in snippet: cnxn to conn

### PR DESCRIPTION
**Pull request by edsfocci**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@edsfocci__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@meet-bhagdev  @jeffgoll 
Please check this change and let me know whether to accept the PR. Thanks!

**Comment by cjgronlund** [comment]
@edsfocci 
Thank you for your contribution. I'll check it with the article author, and get right back to you.
--Carolyn

**Comment by meet-bhagdev** [comment]
@cjgronlund I sign off on this! Please merge the PR

**Comment by jeffgoll** [comment]
#sign-off

**Pull request merged**
