### PR TITLE
Change all reference to xplat & cross-plat to Azure CLI

### PR DESCRIPTION
**Pull request by devigned**
The name for xplat-cli is changing to Azure Command-Line Interface (Azure CLI). This pull request should be all of the changes needed to remove all references of Cross-Platform and xplat including the .md file names.

This is my first ACOM contribution. Please let me know if I've done terrible things and I'll fix them up.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@devigned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dajustic). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
I think you've likely done them correctly, but perhaps overdone them. Should we rename _files_ at this stage of the game we're going to break all inbound links from msdn or blog entries (of which there are many) including github mentions as well. We could create redirects to handle this, but my suspicion is that we might want to hang out until after //build to fix the filenames...

**Comment by squillace** [comment]
I'll review them, but I really think this should be submitted against release-build, to get that massive merge out now, rather than when we move release-build into master.... what do you think?

**Comment by squillace** [comment]
also: did we not agree that it was going to be Azure CLI for Mac, Linux, and Windows? or were we spelling them all out for "Azure Command-Line Interface (CLI) for Mac, Linux, and Windows"?

I recall this: 
First use: Azure CLI for Mac, Linux, and Windows
Subsequent: Azure CLI
Code: azure-cli after the npm package name.

??? Just need to confirm, because i've already made tons of changes about this in release-build.

**Comment by devigned** [comment]
@squillace I still need to correct the file renaming. I think I should be able to get that done this evening.

Based on your feedback, I'll move the PR over to release-build.

**Comment by devigned** [comment]
@squillace It seems like it would be really verbose to say "for Mac, Linux, and Windows". I generally took the approach of spelling out the first usage Azure Command-Line Interface (Azure CLI) w/o the "for Mac, Linux, and Windows", then after referring to it as Azure CLI.

Thoughts?

**Comment by karthmut** [comment]
There appear to be a handful of "x-plat cli" left. They're sneaky :)

**Comment by devigned** [comment]
@karthmut are they in urls or are they in content. I had intentionally left urls that point to github and others unchanged, unless I had changed the file name myself.

**Comment by karthmut** [comment]
Content, there's are some in this file: /virtual-machines-create-multi-vm-deployment-azure-cli.md

Just noticed that it also has just CLI in some spots, not Azure CLI.

**Comment by devigned** [comment]
@karthmut thank you. I'll clean that up.

**Comment by squillace** [comment]
yea!!!

**Comment by tysonn** [comment]
Closing, as work has moved to another branch.

**Pull request closed without merging**
