### PR TITLE
Update data-lake-store-data-scenarios.md

### PR DESCRIPTION
**Pull request by sachincsheth**
I am PM on Azure Data Lake team.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sachincsheth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sachincsheth : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@sachincsheth . Thanks for your contribution. Could you please fix the formatting of the value you added in the table. In the final view, it is being rendered outside the table.

**Comment by sachincsheth** [comment]
There were issues with this pull request. Created a new one.

**Comment by azurecla** [comment]
Hi __@sachincsheth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request closed without merging**
