### PR TITLE
DTUs for P1, P2, P6/P3 updated

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@rothja 
Please review and approve/disapprove with a comment. Thanks.

**Comment by rmca14** [comment]
Follow-up mail sent for review request.

**Comment by jeffgoll** [comment]
@AlekseiPolkovnikov Thanks for contirbuting! Can you plz confirm that you're looking at DB creation on a V12 server? I tried to repo and saw definitely the limits in our table, which are correct. If you are seeing these limits on V12 server, it's a bug in the portal. Old limits are shown for creation on earlier ver servers, though. We have a note before the table that says these limits apply only to V12.

**Comment by AlekseiPolkovnikov** [comment]
@jeffgoll  I tried again, in "Server" blade, selecting "Create a new server" it says "Create V12 server (Latest update)" = "Yes" by default, I didn't change it. After that if I open "Pricing tier" blade the DTU numbers are as in the documentation.
But if I don't touch the "Server" blade and go straight to the "Pricing tier" blade the numbers are incorrect. However, "Learn more" link in "Choose your pricing tier" leads to the documentation page under question still with numbers for V12. Does this mean if I don't touch "Server" blade it uses V11?

**Comment by jeffgoll** [comment]
@AlekseiPolkovnikov Ah. Got it. Looks like a portal bug. Will reach out to team w/you on cc internally, Aleksei.

**Comment by AlekseiPolkovnikov** [comment]
@jeffgoll thanks! and sorry, indeed looks like the documentation is not the issue here.

**Comment by rmca14** [comment]
Thanks to everyone for your feedback. Closing this PR unmerged. If needed, it can be reopened.

**Pull request closed without merging**
