### PR TITLE
Introducing migAz tool

### PR DESCRIPTION
**Pull request by PauloRamosGit**
The Azure Service Management to Azure Resource Manager migration tool for IaaS workloads (migAz) is an additional option to migrate a complete set of Azure Service Management IaaS resources to Azure Resource Manager IaaS resources. 

migAz exports selected ASM resources into an ARM template you can use to redeploy the resources. Also included, is a powershell script that will help you on the blobs copy process.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@PauloRamosGit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@PauloRamosGit__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@PauloRamosGit : Thanks for your contribution to the Azure documentation! The author, @singhkay, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@PauloRamosGit - Paolo, when you author your own articles, that work needs to happen in the private repository. See the [Tools and Setup article](https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github) for information about permissions to the private repo, and see "[Authors working in the public repo](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Article%20authors%20working%20in%20the%20public%20repo.aspx)" for info about why you should work in the private repo.

**Pull request closed without merging**
