### PR TITLE
Update virtual-machines-capture-image-windows-server.md

### PR DESCRIPTION
**Pull request by mcroley**
clarified the Azure Backup service and placed a stronger recommendation to back up the virtual machine prior to being captured

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mcroley__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@mcroley thanks for the updates Matt.

**Comment by Jim-Parker** [comment]
@cynthn hey Cynthia, could you please review this contribution?

**Comment by cynthn** [comment]
#sign-off

**Pull request merged**
