### PR TITLE
Fix the router name mistaken.

### PR DESCRIPTION
**Pull request by kazubu**
Fix the router series name MX to SRX because the configuration only works with SRX series router.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kazubu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Cheryl, could you review this contribution from @kazubu and let me know if I can merge?

**Comment by cherylmc** [comment]
Hi @kazubu - I'm going to send this through to the product team guys so that we're all on the same page. Thanks so much for letting me know. It might take a few days for them to confirm, but as soon as they do, we'll be good to go on this.

**Comment by cherylmc** [comment]
Hi @kazubu - The product team confirmed right away. Thanks again for letting us know. @tysonn - could you please merge this?

**Comment by kazubu** [comment]
Thank you for merged it!

**Pull request merged**
