### PR TITLE
NSG typo

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@naziml can you verify this customer's tweak to the heading?

**Comment by ggailey777** [comment]
@tdykstra can you please verify for @naziml?

**Comment by tdykstra** [comment]
@ggailey777 Looks good, corrects a typo

**Comment by ggailey777** [comment]
@snobu thank you for finding and fixing this typo. We appreciate your help improving the quality of Azure docs.

**Pull request merged**
