### PR TITLE
Fix link in active-directory-aadconnect.md

### PR DESCRIPTION
**Pull request by FabienLavocat**
A link was broken in the file active-directory-aadconnect.md

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@FabienLavocat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@FabienLavocat : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
#sign-off

**Comment by Ja-Dunn** [comment]
@billmath - Hi Bill, please fix the merge conflicts. Thanks!

**Comment by ktoliver** [comment]
@FabienLavocat - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/active-directory/active-directory-aadconnect](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-aadconnect). Thanks for your understanding.

**Pull request closed without merging**
