### PR TITLE
Created a troubleshooting section

### PR DESCRIPTION
**Pull request by undernewmanagement**
There was a good Break/Fix issue addressed in the comments. I simply copied it from the Disqus comments into the docs.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@undernewmanagement__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@undernewmanagement__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tysonn** [comment]
@rgardler - Could you review this update from @undernewmanagement and let me know if I should merge. Note the changes came from a Disqus thread.

**Comment by rgardler** [comment]
Thank you @undernewmanagement 

This was an early workaround for an issue that we have now resolved. A root cause fix will be making its way into production in the next two weeks. We can merge this and remove it again when the fix is rolled out.

**Pull request merged**
