### PR TITLE
Linux doesn't have RDP...

### PR DESCRIPTION
**Pull request by rcarmo**
...tweaked the template to point to SSH instead.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rcarmo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rucarmo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rcarmo : Thanks for your contribution to the Azure documentation! The author, @davidmu1, has been notified to review your proposed change.

**Comment by squillace** [comment]
@rcarmo this is a good fix! Sorry about that. :-) Don't know WHAT  we were thinking. ;-) @davidmu1 LGTM....FWIW

**Comment by rcarmo** [comment]
@squillace nah, no worries. I know it's hard to do docs -- you stare at them for so long sometimes that things like this get by.

**Comment by davidmu1** [comment]
@rcarmo: Thank you very much for your feedback on the article.

**Comment by davidmu1** [comment]
#sign-off

**Pull request merged**
