### PR TITLE
Alternate way to get TenantId using powershell

### PR DESCRIPTION
**Pull request by loekd**
Using this alternative, the page width isn't exceeded by the long url pointing to the classic portal. Also, the reader is expected to be in PowerShell at the time of reading. Finally, it will display all tenant identifiers.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@loekd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@loekd : Thanks for your contribution to the Azure documentation! The author, @chackdan, has been notified to review your proposed change.

**Comment by ChackDan** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@ChackDan
Your sign off did not work with the comment automation because your GitHub account is listed incorrectly in the article metadata: authors="chackdan"
It needs to match your GitHub account EXACTLY, including capitalization. Please fix your GitHub account in all your articles after this is merged. Thanks.

**Pull request merged**
