### PR TITLE
Update key-vault-manage-with-cli.md

### PR DESCRIPTION
**Pull request by msfcolombo**
Replacing essay quotes by programming quotes, allowing copy-paste without surprises and edits.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@msfcolombo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (fcolombo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@BrucePerlerMS - I *think* we discussed this one offline, but can you review/approve when you have a minute?

**Comment by BrucePerlerMS** [comment]
Yep, this too is from a tracked conversation with the PM, dev and little ole' me.

**Comment by BryanLa** [comment]
Thanks @BrucePerlerMS , and thanks @msfcolombo for the contribution!

**Pull request merged**
