### PR TITLE
Update data-lake-analytics-manage-use-powershell.md

### PR DESCRIPTION
**Pull request by eloldag**
Just correcting a few simple typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@eloldag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@eloldag - Thanks for the updates. @edmacauley - please review and let @cjgronlund know if the changes can be merged.

**Comment by Cloudplusplus** [comment]
Looks good, @eloldag, thank you for the fixes!  Ready to be merged by @cjgronlund  whenever.

#sign-off

**Comment by edmacauley** [comment]
That's why you should never log in at home. :)

Sorry about the confusion, thanks again @elodag for your help.  @cjgronlund  all good to go.

#sign-off

**Pull request merged**
