### PR TITLE
Update powershell-install-configure.md

### PR DESCRIPTION
**Pull request by EvanBasalik**
Adding potential solution for where the modules aren't automatically installed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EvanBasalik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@coreyp-at-msft - Corey, could you review this proposed update from @EvanBasalik in the public repository?

**Comment by tysonn** [comment]
@coreyp-at-msft - Corey, please review this public repo PR -- second notice.

**Comment by coreyp-at-msft** [comment]
#sign-off

**Comment by coreyp-at-msft** [comment]
Thanks, EvanBasalik, for the contribution!

**Pull request merged**
