### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial - Could you review this update in the public repository?

**Comment by 4c74356b41** [comment]
Folks?

**Comment by jimdial** [comment]
@4c74356b41.  I issued a pull request (https://github.com/4c74356b41/azure-content/pull/5) to your proposed change. I added a colon to the end of line 139 to match the colon you added to the end of line 33.  

Thanks for the updates!

**Comment by 4c74356b41** [comment]
Thank you!

**Comment by jimdial** [comment]
#sign-off
Please merge, thanks again @4c74356b41.

**Pull request merged**
