### PR TITLE
Fix broken link on SDK downloads

### PR DESCRIPTION
**Pull request by seanfreiburg**
There was a 404 to the SDK downloads. I fixed it with the correct link.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seanfreiburg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by jimbe** [comment]
Sean - looks like the broken link fix is simple enough. But your pull request has merge conflicts. Can you resolve them? Thanks.

**Comment by tysonn** [comment]
Sent mail

**Comment by tysonn** [comment]
Sean, could you please resolve the merge conflicts and remove the /en-us/ part of the path you added to a link? That section breaks the localized experience by forcing users from a translated article back to the EN version of the article.

**Comment by tysonn** [comment]
Closing since merge conflict has not been resolved.

**Pull request closed without merging**
