### PR TITLE
Update resource-manager-vs-code.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @cmatskas, has been notified to review your proposed change.

**Comment by cmatskas** [comment]
@alexandair it looks good to me. Thanks for the fix :)

**Comment by alexandair** [comment]
@cmatskas Who can merge this?

**Comment by cmatskas** [comment]
Not me. But feel free to merge it
CM

Get Outlook for iOS




On Tue, Aug 2, 2016 at 1:53 PM +0100, "Aleksandar Nikolić" <notifications@github.com> wrote:












@cmatskas Who can merge this?

**Comment by alexandair** [comment]
@cmatskas I'm not allowed to merge it.

**Comment by alexandair** [comment]
@tysonn Do you know who can merge this one?

**Comment by tysonn** [comment]
Yes, I'll merge :)

**Pull request merged**
