### PR TITLE
Update virtual-machines-windows-extensions-dsc-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@tysonn Can someone check out this PR, please?

**Comment by tysonn** [comment]
@zjalexander - Could you please review these updates to your article in the public repo from @alexandair ?

**Comment by zjalexander** [comment]
looks good to me. Thanks, Alexandair! #sign-off

**Pull request merged**
