### PR TITLE
Update data-lake-store-copy-data-azure-storage-blob.md

### PR DESCRIPTION
**Pull request by sachincsheth**
I am the PM for ADLCopy. Editing the documentation to reflect the new features.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sachincsheth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sachincsheth : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@sachincsheth: Thanks for your contribution. As discussed, I am going to work on the other PR you submitted and close this one.

**Comment by nitinme** [comment]
@cjgronlund: Please close this PR. We don't need to merge this one. Informed the contributor.

**Pull request closed without merging**
