### PR TITLE
Fixed markdown formatting

### PR DESCRIPTION
**Pull request by TheBeardedLlama**
The use of a tab with a space for each paragraph made MD think that point 10 had a code block.

In addition, the placement of the anchor tag broke the ordered list sequence.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheBeardedLlama__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@TheBeardedLlama - Thanks.

@dvana - Derrick, could you please pull this update to your local private master branch and then stage it to verify the updates resolve the formatting issues in the article?

```
git pull https://github.com/TheBeardedLlama/azure-content.git patch-2
```

**Comment by TheBeardedLlama** [comment]
You're very welcome @tysonn!

For future reference there is no need to stage the changes

(You can view the changes directly in github)[https://github.com/TheBeardedLlama/azure-content/blob/patch-2/articles/power-bi-embedded/power-bi-embedded-faq.md]

**Comment by TheBeardedLlama** [comment]
is everything ok? should I fix something?

**Pull request merged**
