### PR TITLE
Update data-factory-azure-table-connector.md

### PR DESCRIPTION
**Pull request by lorenpaulsen**
Personally I found the description of azureTableInsertType terse and cryptic, so after discovering for myself how the property works, I'd like to share that knowledge

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lorenpaulsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@lorenpaulsen 
Thank you for this contribution. Good point! I'll send to the author for verification, and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@spelluru 
Hi, Sreedhar, Please check this PR and let me know whether to accept it. Thanks!

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
