### PR TITLE
Update active-directory-saas-salesforce-sandbox-tutorial.md

### PR DESCRIPTION
**Pull request by stevecookms**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stevecookms__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@stevecookms : Thanks for your contribution to the Azure documentation! The author, @jeevansd, has been notified to review your proposed change.

**Comment by jeevansd** [comment]
#sign-off

**Comment by PRmerger** [comment]
@stevecookms : Thanks for your contribution to the Azure documentation! The author, @jeevansd, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
The ready-to-merge label could not be added to this pull request. Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
@stevecookms - You can disregard some of the notices on this, we are trying to get some of our auto-labeling to work right :)

**Comment by stevecookms** [comment]
No problem!

Glad I could contribute!

**Comment by jeevansd** [comment]
No problem! Thanks.

**Comment by PRmerger** [comment]
@stevecookms : Thanks for your contribution to the Azure documentation! The author, @jeevansd, has been notified to review your proposed change.

**Pull request merged**
