### PR TITLE
Minor change to script: F variable is not used and the line does nothing

### PR DESCRIPTION
**Pull request by ashikv**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ashikv__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ashikv** [comment]
basename command may be absent from initramfs in Debian, this way it works

**Comment by ashikv** [comment]
Order of options and arguments is important to make it work on Debian, it still works on Ubuntu this way

**Comment by ashikv** [comment]
In case of minimal initramfs approach adding names modules to /etc/initramfs-tools/modules is required. Add support of ntfs in all scripts.

**Comment by azurecla** [comment]
Hi __@ashikv__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ashikv : Thanks for your contribution to the Azure documentation! The author, @YuriDio, has been notified to review your proposed change.

**Comment by azurecla** [comment]
__@ashikv__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by YuriDio** [comment]
@BryanLa pls merge it

**Pull request merged**
