### PR TITLE
Update documentdb-request-units.md

### PR DESCRIPTION
**Pull request by stephbaron**

### CODE REVIEW

**Comment by stephbaron** [comment]
@mimig1 forgot to update modified date to reflect latest edits

**Comment by azurecla** [comment]
Hi __@stephbaron__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stbaro). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mimig1** [comment]
@cjgronlund Please merge.

**Comment by mimig1** [comment]
@tysonn Can you please merge this date change? Content was updated yesterday. Thanks.

**Comment by PRmerger** [comment]
@stephbaron : Thanks for your contribution to the Azure documentation! The author, @stephbaron, has been notified to review your proposed change.

**Pull request closed without merging**
