### PR TITLE
Fixing typo in app-service-mobile node backend docs

### PR DESCRIPTION
**Pull request by jwallra**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jwallra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jawal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jwallra : Thanks for your contribution to the Azure documentation! The author, @adrianhall, has been notified to review your proposed change.

**Comment by adrianhall** [comment]
#sign-off

**Comment by ggailey777** [comment]
@jwallra thanks for helping improve Azure docs.

**Pull request merged**
