### PR TITLE
Release notes for SDK Version 2 beta 2

### PR DESCRIPTION
**Pull request by cijothomas**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cijothomas__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cijothomas** [comment]
@alancameronwills - Can you look and approve this please?

**Comment by alancameronwills** [comment]
Emailed f/b directly - I can't edit it here.

**Comment by alancameronwills** [comment]
The link in the first item: remove the space between ] and (.

**Comment by alancameronwills** [comment]
This is fine. Please accept PR.

**Pull request merged**
