### PR TITLE
escaping markdown

### PR DESCRIPTION
**Pull request by 4c74356b41**
hopefully correct

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @TomArcher, has been notified to review your proposed change.

**Comment by TomArcher** [comment]
**Thanks @4c74356b41 for the contribution!** 

I believe if  you replace the first tick and left angle bracket with **&lt;** and then remove the trailing tick, it will work. 

The following 

PaaSDiagnostics.'<RoleName>'.PubConfig.xml

changes to:

PaaSDiagnostics.&lt;RoleName>.PubConfig.xml

**Comment by TomArcher** [comment]
Hmm. GitHub shows the actual left angle bracket instead of the HTML code. It should be an **ampersand** and then **lt;**

**Comment by TomArcher** [comment]
The following works in my testing:

`PaaSDiagnostics.&lt;RoleName>.PubConfig.xml`

**Comment by 4c74356b41** [comment]
I've updated it. How do you test it?

**Comment by TomArcher** [comment]
@4c74356b41 - I used Visual Studio Code, which supports the preview of a saved MD file. **Thanks again for catching this!**

**Comment by TomArcher** [comment]
@tysonn #sign-off

**Comment by 4c74356b41** [comment]
That's a great piece of advice, thank you!

**Pull request merged**
