### PR TITLE
Update storage-powershell-guide-full.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typos and removing references to "Azure PowerShell console".

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @robinsh, has been notified to review your proposed change.

**Comment by robinsh** [comment]
hi @alexandair Thanks very much for updating this article. I inherited this article, and intend to split it out by service (blob, file, queue, table) and then put the management code in a separate article and link to it from all four of the other ones. One thing I note is that the management operations here are all for classic storage accounts. If you wouldn't mind, can you state that somewhere at the top, or where it creates the storage account, just as an FYI? It's okay; if you don't, I'll add it later. When I split the article up, I think it would be good to have one article for classic management and one for ARM management. Let me know if you agree/disagree, or if there are other changes that you think would be helpful (like including Azure Files!).

**Comment by robinsh** [comment]
@tysonn The changes to this article can be merged. Thanks very much!

Thanks again @alexandair for contributing!

**Comment by alexandair** [comment]
@robinsh I remember reviewing the original version of that article before you've joined the Storage team. I agree with you that we need classic and ARM management articles. Also, it would be easier to read articles dedicated to specific Storage services. This article is too long; shorter articles will be also easier to maintain.

**Comment by robinsh** [comment]
@alexandair Thanks for the feedback. I agree that this article is way too long! Would love for you to review the new set when they're done. If interested, e-mail me robin dot shahan at microsoft dot com and I'll let you know when it's ready.

**Pull request merged**
