### PR TITLE
Fixed typo in title.

### PR DESCRIPTION
**Pull request by njappboy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@njappboy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@njappboy : Thanks for your contribution to the Azure documentation! The author, @allclark, has been notified to review your proposed change.

**Comment by allclark** [comment]
@sign-off

**Comment by allclark** [comment]
#sign-off

**Comment by ggailey777** [comment]
@njappboy thanks for helping to improve the Azure docs.

**Pull request merged**
