### PR TITLE
Azure AD Connect: prereqs freshness

### PR DESCRIPTION
**Pull request by AndKjell**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndKjell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (andkjell). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AndKjell : Thanks for your contribution to the Azure documentation! The author, @andkjell, has been notified to review your proposed change.

**Comment by billmath** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by KatieCumming** [comment]
@billmath - Hi Bill, please fix the merge conflict. See the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx) if you need instructions for fixing it. Also, please update yourself as the GitHub author in the metadata for signoff. Thanks, Katie
 #hold-off

**Comment by AndKjell** [comment]
I've fixed the merge conflict, but I think the sign-off is supposed to happen in the -pr repo. Since I'm the author, I'll see if I can sign-off.

**Comment by AndKjell** [comment]
#sign-off

**Pull request merged**
