### PR TITLE
Update app-insights-sample-mscrm.md

### PR DESCRIPTION
**Pull request by arunvinoth**
update

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arunvinoth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by arunvinoth** [comment]
can you merge this quickly, the content is broken now. I did change to make it clean.

**Comment by arunvinoth** [comment]
Any ETA please?

**Comment by arunvinoth** [comment]
Hello

What’s going on with this pull request, no assignee assigned & no update after my request. Any help would be highly appreciated on merging this pull request.

FYI, this blog post was broken when I added <script> text in content & hence I removed the <> symbols to make it perfect. This broken blog content is impacting our followers.

Thanks
Arun

**Pull request merged**
