### PR TITLE
Remove incorrect note about ARM deployment model

### PR DESCRIPTION
**Pull request by sivaedupuganti**
Remove incorrect note about ARM deployment model

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sivaedupuganti__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sivae). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sivaedupuganti : Thanks for your contribution to the Azure documentation! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by telmosampaio** [comment]
#sign-off

**Comment by tysonn** [comment]
@telmosampaio - Please resolve the merge conflict so we can merge this. Thanks!

**Comment by tysonn** [comment]
#hold-off

**Comment by sivaedupuganti** [comment]
Change not required anymore. Fixed in https://github.com/Azure/azure-content/commit/c71479994868ab4198a775d1309f9c0c4b4b9048#diff-f5bfdb566646340a9573bde7d2b43d0e

**Pull request closed without merging**
