### PR TITLE
Update virtual-networks-nsg.md

### PR DESCRIPTION
**Pull request by timomta**
Updated the rule number that allows ICMP traffic on a vnet

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@timomta__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial / @cherylmc - Could one of you review this public repo update from @timomta?

**Comment by tysonn** [comment]
@jimdial / @cherylmc  - Second notice, please review

**Comment by jimdial** [comment]
# sign-off  Good catch, thank you! @cherylmc

**Comment by jimdial** [comment]
#sign-off

**Pull request merged**
