### PR TITLE
How to work with the data returned

### PR DESCRIPTION
**Pull request by ccasbre27**
We define a lambda function to work with the result from the api

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ccasbre27__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@ccasbre27__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by ggailey777** [comment]
@krisragh Can you take a look at this contribution. If it looks OK, I would like to do the merge so that the customer can get attribution.

**Comment by krisragh** [comment]
@ggailey777  ok, go for it. Code formatting appears broken, so please fix that (I don't have permissions to edit)

**Comment by ggailey777** [comment]
@ccasbre27 Can you please indent your code sample a few tabs so that it renders as code?

**Comment by ccasbre27** [comment]
Hello thanks for considering my contribution. Sorry I did not see the notification, please let me know if it works.

Thank you!

**Comment by ggailey777** [comment]
@ccasbre27 yes, that fixed it. Thanks for helping out with the Azure docs.

**Comment by ccasbre27** [comment]
My pleasure!

**Pull request merged**
