### PR TITLE
update samples to reflect the SDK refactor.

### PR DESCRIPTION
**Pull request by begoldsm**
move account name to the first parameter position.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@begoldsm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (begoldsm). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by nitinme** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@begoldsm @nitinme 
In the articles where you've added the "how to use" headings, I recommend deleting that heading and making the H3s below it H2s. Otherwise, you bury important steps in your heading hierarchy.

**Comment by cjgronlund** [comment]
@begoldsm @nitinme 
I can accept for tomorrow's publish, but I recommend the change above at your earliest convenience. Preference? Fix now or fix later? Thanks!

**Comment by begoldsm** [comment]
@cjgronlund I would say we can punt the recommended fixes for this PR. @nitinme can you take an action to address the recommended documentation changes in the next update?

**Comment by cjgronlund** [comment]
@begoldsm @nitinme 
Thanks! Will do. This will be publishing in tomorrow morning's run. :)

**Pull request merged**
