### PR TITLE
Merge branch 'master' of https://github.com/Azure/azure-content-pr in…

### PR DESCRIPTION
**Pull request by MAYAKARYA**
…to FromPrivateRepo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MAYAKARYA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MAYAKARYA : Thanks for your contribution to the Azure documentation! The author, @piyushjo, has been notified to review your proposed change.

**Comment by piyushjo** [comment]
#sign-off

**Comment by Saisang** [comment]
@tysonn please merge this PR.

**Pull request merged**
