### PR TITLE
Update active-directory-aadconnect-health-faq.md

### PR DESCRIPTION
**Pull request by karavar**
Small change for accuracy.

### CODE REVIEW

**Comment by karavar** [comment]
Alerts are resolved after 72 hours (not 48 hours)

**Comment by azurecla** [comment]
Hi __@karavar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vakarand). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@karavar - thanks very much for your contribution!
@billmath - FYI. @karavar is a PM in Identity Services.

**Comment by karavar** [comment]
@BryanLa Did I miss any step? Sorry if I created any confusion..

**Comment by BryanLa** [comment]
Hi @karavar - no, not at all! The changes were good and I merged the PR. I was just giving Bill a heads up, as he was the original author.

**Pull request merged**
