### PR TITLE
Update machine-learning-feature-selection-and-engineering.md

### PR DESCRIPTION
**Pull request by YanZhangADS**
Fixed a small typo, and modified the author list.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@YanZhangADS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zhangya). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
The authors field accepts only one author. Please edit the authors field. Thanks.
For guidance, see  https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/article-metadata.md

**Comment by rmca14** [comment]
Please resolve the merge conflict. For guidance, see   http://sharepoint/sites/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx

Thank you

**Comment by MonicaRush** [comment]
@YanZhangADS 
Yan Zhang -- Hello! I am working for Ross for the next few days. If you want to merge this pull request, as an alternative to resolving the merge conflict you can exchange the updated file for the existing file that you would bring down in a fresh branch. Let me know if you have any questions about this. Thanks a lot -- Monica

**Comment by azurecla** [comment]
Hi __@YanZhangADS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zhangya). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
Closed due to inactivity.

**Pull request closed without merging**
