### PR TITLE
Update service-fabric-architecture.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @rishirsinha, has been notified to review your proposed change.

**Comment by rishirsinha** [comment]
Thanks for the contribution, @alexandair. @tysonn, please merge the PR.

**Comment by alexandair** [comment]
@tysonn Could you merge this one, please?

**Comment by alexandair** [comment]
@tysonn This one is approved for merging. :) I also have a few PRs opened for more than 2 weeks. Could someone ping the authors, please?

**Comment by tysonn** [comment]
Hi @alexandair - Thanks for the prompt. I couldn't find a notification for this one in my mail folders, but they seem to be working today. We're working on automation and reporting to help improve people's response to contributions. In the meantime I periodically send manual reports to try to drive responses.

**Pull request merged**
