### PR TITLE
Fixed Small UI Mistake

### PR DESCRIPTION
**Pull request by danieldobalian**
Needed a new line in code snippet.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@danieldobalian__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by danieldobalian** [comment]
@dstrockis

**Comment by PRmerger** [comment]
@danieldobalian : Thanks for your contribution to the Azure documentation! The author, @dstrockis, has been notified to review your proposed change.

**Comment by danieldobalian** [comment]
#sign-off

**Comment by danieldobalian** [comment]
@BryanLa

**Pull request merged**
