### PR TITLE
Missing -EnableBGP True from 2 PowerShell commands

### PR DESCRIPTION
**Pull request by aicaffre**
Although the text explains to add this flag, it is easy to forget it users use the 'copy' feature for the PowerShell commands.
If you do not specify the flag, the default is False for the EnableBgp setting.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aicaffre__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@yushwang - Please review this proposed change from @aicaffre to your article in the public repository.

**Comment by yushwang** [comment]
The flag is not required to utilize BGP on Azure VPN gateway.

#please-close

**Comment by yushwang** [comment]
This property is a legacy field due to other non-Azure related requirement. It is no-op in the Azure VPN gateway resource. The reason setting it seems to work is because of the old gateways created before Azure BGP is released. Changing any properties on the gateway resource will trigger a sync and backfill of "new" properties, in this case, the BGP elements, in the existing gateway resource. That is why it seemed to enable BGP but in reality, changing any properties on the gateway would have the same effect.

**Pull request closed without merging**
