### PR TITLE
Update service-fabric-reverseproxy.md

### PR DESCRIPTION
**Pull request by TimHess**
10.0.05 is not a valid IP address, 10.0.0.5 is

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TimHess__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@TimHess : Thanks for your contribution to the Azure documentation! The author, @BharatNarasimman,vturecek, has been notified to review your proposed change.

**Comment by rwike77** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by BharatNarasimman** [comment]
#sign-off

**Pull request merged**
