### PR TITLE
Fix "realted" typo and incorrect its/it's usage, and update same-folder links to remove unnecessary ./ prefixes.

### PR DESCRIPTION
**Pull request by simonrolfe**
Small typo fix, realted -> related and it's -> its.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@simonrolfe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@simonrolfe : Thanks for your contribution to the Azure documentation! The author, @adamglick, has been notified to review your proposed change.

**Comment by adamglick** [comment]
#sign-off

**Comment by adamglick** [comment]
Thanks @simonrolfe!
@tysonn This is approved; please accept and merge.

**Comment by tysonn** [comment]
@adamglick - can you submit a pull request to simon's fork to remove the dot and slash from the article links in the modified text? When you link from one article to another article in the same GitHub folder, you need only the file name - the dot and slash are not needed. The [wiki contains info on how to  make a change to another users fork](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Make%20changes%20to%20another%20person%27s%20pending%20pull%20request.aspx).

**Comment by simonrolfe** [comment]
Added a second commit which removes the unnecessary ./ prefixes from same-folder links in the article. Hopefully that's useful!

**Comment by simonrolfe** [comment]
I've updated the PR title to more accurately reflect both of the commits - do I need to do anything else?

**Comment by adamglick** [comment]
#sign-off

**Comment by adamglick** [comment]
@simonrolfe Good stuff.  accepted.
@tysonn This is good to go, he's fixed the ./ removal.  Ready to merge.

**Pull request merged**
