### PR TITLE
Added option 'nofail' to fstab

### PR DESCRIPTION
**Pull request by malachma**
As suggested in https://github.com/Azure/azure-content/pull/7774 added the option 'nofail' to this document as well

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@malachma__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@malachma : Thanks for your contribution to the Azure documentation! The author, @rickstercdn, has been notified to review your proposed change.

**Comment by RicksterCDN** [comment]
#sign-off looks good to go @tysonn

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by malachma** [comment]
pull can be closed, after it went into main

**Pull request merged**
