### PR TITLE
some corrections

### PR DESCRIPTION
**Pull request by jiyongseong**
1. StorageUri parameter of New-AzureRmSqlDatabaseExport cmdlet misses dash
2. AdministratorPassword > AdministratorLoginPassword
3. $exportRequest .OperationStatusLink > $exportRequest.OperationStatusLink

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jiyongseong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jiyongseong : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@jiyongseong - thanks for the fix! Because it's a code edit I'll review and update in the next few days.

**Comment by stevestein** [comment]
@jiyongseong - thanks again for the fix!
@cjgronlund - this PR is ready to merge

**Comment by stevestein** [comment]
#sign-off

**Pull request merged**
