### PR TITLE
FQDN of R Server edge node is incorrect.

### PR DESCRIPTION
**Pull request by ksasagit**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ksasagit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jeffstokes72 - please review this public repo PR. Note you will need to patch the PR to resolve the merge conflict if the changes can be merged.

To do this, you can run these commands to bring the content to your local computer:
```
git checkout -b ksasagit-patch-8 master
git pull https://github.com/ksasagit/azure-content.git patch-8
```
Then, create a PR from your fork to kasasagit's patch-8 branch. Kasasagit will then need to merge that PR, and then this one can be merged.

**Comment by jeffstokes72** [comment]
Hello,

This issue was raised by PMs internally a few days ago and it looks like our modification went live today.

Kasasagit can you validate you see the change in production?

Thanks,
Jeff

**Comment by ksasagit** [comment]
I've just confirmed that this issue has been corrected in production.
Thank you!

**Comment by tysonn** [comment]
Bases on conversation thread, I'm closing this :)

**Pull request closed without merging**
