### PR TITLE
Update Storage Replication Options

### PR DESCRIPTION
**Pull request by itzrahulsoni**
Geo Redundant Storage is default only in the Management Portal. This statement is not true for Preview portal.

When I created an storage account, I chose GRS and once the account was created... I tried changing it to LRS. This statement hence doesn't appear correct.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@itzrahulsoni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@itzrahulsoni Thanks for the contribution! I've sent this change to be reviewed by one of our team.

**Comment by itzrahulsoni** [comment]
I have changed On-Premise to On-Premises since the term On-Premise is incorrect. http://www.brianmadden.com/blogs/brianmadden/archive/2014/05/01/so-apparently-we-lost-the-grammar-war-and-on-premises-is-just-called-quot-on-premise-quot-now.aspx

**Comment by garyericson** [comment]
I'm fine with the changes to machine-learning-data-science-move-sql-server-virtual-machine.md

**Comment by tysonn** [comment]
Edits accepted, thank you for the updates. I had to pull the changes over to our private repo, but they should publish tomorrow. @deneha - this PR should close automatically when the private side is merged to the public side on Wed.

**Comment by itzrahulsoni** [comment]
Thanks bunch!

**Pull request merged**
