### PR TITLE
Clarity and emphasis added to step 5

### PR DESCRIPTION
**Pull request by undernewmanagement**
It was not entirely clear to me that you must add all those libraries in order to make things work. Just a small edit reiterating in text what is shown in the screenshot.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@undernewmanagement__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@piyushjo is it OK to accept and merge this contribution?

**Comment by piyushjo** [comment]
Yes, please merge.

**Comment by ggailey777** [comment]
@undernewmanagement thanks for your contribution. We appreciate your helping out with Azure docs.

**Comment by undernewmanagement** [comment]
@ggailey777 glad to help! Looking forward to helping out in the future :-)

**Pull request merged**
