### PR TITLE
Adds link to description of all reports

### PR DESCRIPTION
**Pull request by psignoret**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@psignoret__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (phsignor). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Adding @kenhoff and @yossibanai for awareness.  Not sure where the merge conflict would be happening, but LMK if you would like me to try merging again.

**Comment by psignoret** [comment]
Not sure how there's a conflict on a one-line change like this, but I'll just close this and submit another one.

**Comment by BryanLa** [comment]
Thanks Philippe.

FYI, there was a reorg of the “Articles” directory structure under azure-content/master recently, so that could be why.  Just make sure you do a “git pull upstream/master” to get the latest copy of the azure-content repo, before you make your changes.  You’ll find “active-directory-reporting-audit-events.md” in the Articles/Active-Directory directory now.

Btw, if you’ll be doing regular contributions, you will want to switch over to our private repo (azure-content-pr). You can find all of the info you need to get started in the Contributors’ Guide<https://github.com/Azure/azure-content/blob/master/contributor-guide/contributor-guide-index.md>.

Thanks,
Bryan

**Comment by psignoret** [comment]
Thanks. I did this directly form the Github web UI since it was (supposed to be) such a trivial change.

**Pull request closed without merging**
