### PR TITLE
Remove orphaned colon ':'

### PR DESCRIPTION
**Pull request by stuartleeks**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartleeks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stuartle). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@stuartleeks : Thanks for your contribution to the Azure documentation! The author, @dragon119, has been notified to review your proposed change.

**Comment by dragon119** [comment]
@stuartleeks , sorry for the late reply. Thank you for fixing the typo.

**Comment by dragon119** [comment]
#sign-off

**Pull request merged**
