### PR TITLE
Update active-directory-identityprotection.md

### PR DESCRIPTION
**Pull request by wasserja**
minor grammar fix

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@wasserja__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@wasserja : Thanks for your contribution to the Azure documentation! The author, @markusvi, has been notified to review your proposed change.

**Comment by MarkusVi** [comment]
Hi @wasserja, thanks a lot for catching this!
Cheers,
Markus:

**Comment by MarkusVi** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by BryanLa** [comment]
@KatieCumming, @jomolnar - this PR can be merged as @MarkusVi has done the appropriate sign-off.
@tysonn - I checked commit history and properties.authors has been set to "markusvi" for quite a while, so perhaps there is a PRMerger bug?

**Comment by tysonn** [comment]
The GitHub alias entered in the article must match exactly the actual GitHub account of the author, and it is case sensitive. Markus' account is MarkusVi, and the article lists it as markusvi. Markus should do a bulk update of his GitHub account for all his articles to ensure it matches exactly what the GitHub account is.

**Comment by BryanLa** [comment]
Ahh, thanks Tyson. Forgot about case sensitivity. @MarkusVi - please do this when you have a chance, drop another sign-off, and lets verify that this applies the ready-to-merge label correctly. 

@KatieCumming, @jomolnar - sorry for the false start. Please hold off on merging until Markus can update the authors metadata.

**Comment by tysonn** [comment]
Fix after this PR is merged. I have set the ready to merge label.

**Pull request merged**
