### PR TITLE
update freshness

### PR DESCRIPTION
**Pull request by ryancrawcour**
changed date to update freshness

### CODE REVIEW

**Comment by ryancrawcour** [comment]
@mimig1

**Comment by azurecla** [comment]
Hi __@ryancrawcour__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ryancraw). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mimig1** [comment]
@ryancrawcour - We can't postdate the date that far. Either make it 11/18 or 11/19. Thanks.

**Comment by ryancrawcour** [comment]
I originally picked that date b/c that's the date it expired. changed.

**Comment by mimig1** [comment]
#sign-off @rmca14 Please accept.

**Pull request merged**
