### PR TITLE
Made many updates to ASE creation document

### PR DESCRIPTION
**Pull request by ChrisCompy**
Simplified,
reflects new UI,
removed redundant information.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ChrisCompy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ccompy). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ChrisCompy** [comment]
#sign-off

**Comment by PRmerger** [comment]
@ChrisCompy : Thanks for your contribution to the Azure documentation! The author, @ccompy, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by ccompy** [comment]
#sign-off

**Comment by tysonn** [comment]
Hi Christina,

Please pull these changes over to the private repository and submit them there so the updates are validated, staged, and run through Acrolinx.

Also, please make sure you are working in the repo using the GitHub account you list in your articles. The automation is relying on the accounts to match exactly.

Thanks,
Tyson

**Comment by cephalin** [comment]
Hi Tyson. Christina said that in the past both @ChrisCompy and @ccompy had access to azure-content-pr but now @ChrisCompy doesn't anymore (@ccompy still does). Is it possible to still get that access for both accounts?

**Pull request closed without merging**
