### PR TITLE
Update search-import-data-portal.md Removed "classic" from the portal…

### PR DESCRIPTION
**Pull request by SychevIgor**
… name

As I know- this portal have no "classic" tag. It's just portal... we can naming it as new portal, but definitely not classic.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SychevIgor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@HeidiSteen 
Please approve/disapprove this pull request with a comment. Thanks.

**Comment by HeidiSteen** [comment]
Approved.  "Classic" portal was incorrectly added to all the Azure Search topics.

**Comment by HeidiSteen** [comment]
#sign-off

**Pull request merged**
