### PR TITLE
Modify New Relic store doc to simplify and direct users to the frequently updated New Relic hosted documentation

### PR DESCRIPTION
**Pull request by nickfloyd**
Simplifies page content so that all updates will be available through links to New Relic's documentation which is frequently updated.

This change modifies this [page](https://azure.microsoft.com/en-us/documentation/articles/store-new-relic-cloud-services-dotnet-application-performance-management/)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nickfloyd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@nickfloyd : Thanks for your contribution to the Azure documentation! The author, @nickfloyd, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.

It�s easy to access the private repo version of your articles in GitHub. Just add �pr to the URL, as follows: 

Public repo URL: https://github.com/Azure/azure-content/blob/master/articles/azure-portal-overview.md

Private repo URL: https://github.com/Azure/azure-content-pr/blob/master/articles/azure-portal-overview.md

We've closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, see the contributor guide instructions.

**Comment by cephalin** [comment]
@PRmerger He's not a Microsoft author. But he will take over as the main author of this article.

**Comment by cephalin** [comment]
@nickfloyd I think @PRmerger isn't seeing this because the PR is already closed. I can't reopen the PR. Can you reopen it?

**Comment by nickfloyd** [comment]
@cephalin I cannot.  I could always resubmit and sidekick you on the new PR? LMK.

**Comment by cephalin** [comment]
@nickfloyd Sounds good. Go for it.

**Comment by nickfloyd** [comment]
@cephalin - done - see related PR [here](https://github.com/Azure/azure-content/pull/7437)

**Pull request closed without merging**
