### PR TITLE
Clarification regarding verbose output added

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlekseiPolkovnikov : Thanks for your contribution to the Azure documentation! The author, @georgewallace, has been notified to review your proposed change.

**Comment by georgewallace** [comment]
@AlekseiPolkovnikov I submitted a PR to your fork.  I removed the verbose message from the output and left the text in the step alone, the verbose output should not have been there in the first place. Great catch.

**Comment by AlekseiPolkovnikov** [comment]
Agree, no need in verbose output in this place.

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by AlekseiPolkovnikov** [comment]
Re-opened, was closed by accident.

**Pull request merged**
