### PR TITLE
Update automation-scenario-start-stop-vm-wjson-tags.md

### PR DESCRIPTION
**Pull request by paulomarquesc**
Hi Matt,

This is the change, I added a space at the end of the paragraph you mentioned.

Regards

Paulo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@paulomarquesc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@paulomarquesc : Thanks for your contribution to the Azure documentation! The author, @MGoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@paulomarquesc thank you for your time to review and contribute to this article.  I've reviewed your suggestion and because we've already addressed that other concern in a different PR, this PR is not necessary so I'm going to kindly reject this PR.  @Jim-parker - ping me offline if you require specific details.

**Comment by Jim-Parker** [comment]
@paulomarquesc @MGoedtel  Paulo, are you okay with me closing this PR based on Matt's info?

**Pull request closed without merging**
