### PR TITLE
Clarify Folder Structure section

### PR DESCRIPTION
**Pull request by davidebbo**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@davidebbo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (davidebb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@davidebbo : Thanks for your contribution to the Azure documentation! The author, @christopheranderson, has been notified to review your proposed change.

**Comment by lindydonna** [comment]
@christopheranderson Ping to review the change and sign off :)

**Comment by davidebbo** [comment]
@christopheranderson can you please merge that in? If needed, let's add more authors on the document so we can short circuit the process of getting things merged in.

**Comment by christopheranderson** [comment]
sign_off

**Comment by christopheranderson** [comment]
#sign-off

**Comment by Ja-Dunn** [comment]
@christopheranderson - Hi Christopher, please change the note to use markdown, per the following guidance:
--Custom markdown elements are used where appropriate. Ex: Notes are coded using the AZURE.NOTE extension, not as plain text.
Thanks!  #hold-off

**Comment by lindydonna** [comment]
@davidebbo Please either allow editing of your pull request, or change your PR to use the following:

>[AZURE.NOTE]

Instead of **Note**

@Ja-Dunn Do we really need to block the merge on this?

**Comment by davidebbo** [comment]
@Ja-Dunn I made the change

**Comment by davidebbo** [comment]
Unbelievably, this is still not merged in :(

@Ja-Dunn @christopheranderson @lindydonna what need to happen?

**Comment by ggailey777** [comment]
@davidebbo @lindydonna  it needed to be signed-off again by @christopheranderson. 
I will go ahead and merge since it looks OK to me. Incidentally, the process is better/faster in the private azure-content-pr repo.

**Comment by lindydonna** [comment]
Thanks @ggailey777!

**Pull request merged**
