### PR TITLE
Re-read article and it's still valid

### PR DESCRIPTION
**Pull request by AndrewHoh**
In the middle of revamping the article completely to move off of REST Api calls to just the Ibiza Portal

### CODE REVIEW

**Comment by AndrewHoh** [comment]
@mimig1

**Comment by mimig1** [comment]
Andy, please review/address this verbatim bug: http://sqlbuvsts01:8080/Main/DocumentDB/_workitems#_a=edit&id=5453094&triage=true. Also, Andrew indicated there were changes to make to this topic - I can't remember what they were but can you ping him? They might not need to happen now, but I just want to make sure it's on your radar.

**Comment by AndrewHoh** [comment]
Ran through the article again and I'm unable to hit the user's bug. This could potentially be the result of a malformed REST Api call. 

Haven't spoken with Andrew, but he was probably thinking about moving the article to either the Ibiza Portal or the .NET SDK. I'll sync with him later today.

**Comment by mimig1** [comment]
@AndrewHoh Let me know the plan after you talk to Andrew.

**Comment by mimig1** [comment]
@AndrewHoh Any update?

**Comment by AndrewHoh** [comment]
Talked to Andrew and he doesn't have any strong preferences on it.

**Comment by mimig1** [comment]
Ok, thanks for following up. #sign-off @rmca14

**Pull request merged**
