### PR TITLE
Update expressroute-howto-linkvnet-arm.md

### PR DESCRIPTION
**Pull request by paulkel**
Removed duplicate text that linked to ASM guidance in this ARM article.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@paulkel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ganesr - Ganesh, could you review this suggested change?

**Comment by ganesr** [comment]
@tysonn Only a minor tweak is necessary. I will make the change in this PR.

@cherylmc

**Comment by ganesr** [comment]
@tysonn pls sign off on this. Once this goes to prod I will make the change. I don't have access to make a change to this pr

**Comment by tysonn** [comment]
@ganesr - merging. @paulkel Thanks for the updates!

**Pull request merged**
