### PR TITLE
Update sql-data-warehouse-reference-powershell-cmdlets.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@alexandair 
Thank you for your contribution and good fixes. I'll send to the author to verify, and get back to you. 

--Carolyn

**Comment by cjgronlund** [comment]
@barbkess 
Please check these fixes, and let me know whether I should accept this PR.

**Comment by barbkess** [comment]
He changed ResourceGroup11 to ResourceGroup1 in the commands. This is a good change.
#sign-off

**Comment by barbkess** [comment]
These changes are fine. Please accept the pull request.

**Pull request merged**
