### PR TITLE
Update limit of VMs per single vNet from 2048 to 4096

### PR DESCRIPTION
**Pull request by DevXE**
Update limit of VMs per single vNet from 2048 to 4096 as outlined in the Azure limits website - Private IP Addresses per virtual network.
 https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/

Mentions of 4096:
- “Plan for no more than 4096 VMs per VNET.” - https://azure.microsoft.com/en-us/documentation/articles/virtual-machine-scale-sets-overview/

- “Private IP Addresses per virtual network             4096” - https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#networking-limits

- Note, there is no mentioned of 2048 under the Azure Subscription Service limits aside from Job History and Request URL Size.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DevXE__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@DevXE : Thanks for your contribution to the Azure documentation! The author, @jimdial, has been notified to review your proposed change.

**Comment by jimdial** [comment]
Thanks for catching this inconsistency with the limits article @DevXE. I proposed a change to your change (with a comment explaining why). If you're OK with my change, please merge it and I can get your PR merged.  Thanks.

**Comment by DevXE** [comment]
Hi @jimdial - I'm seeing any changes you've proposed.

**Comment by jimdial** [comment]
@DevXE : Hmmm, don't know what happened, but I've proposed the changes to your PR [here](https://github.com/DevXE/azure-content/pull/1). If you're good with them, just merge the request and I'll merge yours.  --Thanks

**Comment by jimdial** [comment]
Thanks again for the feedback @DevXE. #sign-off

**Pull request merged**
