### PR TITLE
Added section about Windows 7 device registration

### PR DESCRIPTION
**Pull request by jurajsucik**
Windows 7 is listed in the supported devices but the instructions for it were missing.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jurajsucik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Adding @femila for review...

**Comment by BryanLa** [comment]
Hi @Femila - any thoughts?

**Comment by femila** [comment]
The changes look good. I realize I have some cross-referencing work to do in other topics. Please merge

**Pull request merged**
