### PR TITLE
Add: Deploying Your Own Private Docker Registry on Azure

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
cc: @squillace

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahmetalpbalkan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahmetb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
@deneha LGTM. Ship it!!!

**Comment by tysonn** [comment]
@squillace / @ahmetalpbalkan - Guys, can you please check this new article in through the private repository so it can run through content validation and be previewed prior to release? To me, it looks like the metadata section uses a bunch of tags we no longer use, the metadata items are in the wrong order, and validation may surface a few other things.

Thanks

**Comment by ahmetalpbalkan** [comment]
@tysonn this has gone through internal review? Why are not we discussing the problems with the Pull Request in public? If you have comments, let's reopen this and iterate here?

**Comment by tysonn** [comment]
@ahmetalpbalkan - we have automated article validation enabled only in the private repository so that we don't put a huge burden on customers who might be kind enough to offer us a contribution in the public repo on existing articles. A full new article from an employee needs to run through the validator and be staged first so the author can make any updates needed. Full new articles that haven't run through validation can block publishing for everyone.

**Comment by squillace** [comment]
I'll grab it and help out. @tysonn @ahmetalpbalkan

**Comment by azurecla** [comment]
Hi __@ahmetalpbalkan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahmetb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Pull request closed without merging**
