### PR TITLE
Update resiliency-service-guidance-index.md

### PR DESCRIPTION
**Pull request by kenrward**
Added link for FailSafe initiative for web apps built on Azure services.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kenrward__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
removing label to test repo automation

**Comment by PRmerger** [comment]
@kenrward : Thanks for your contribution to the Azure documentation! The author, @adamglick, has been notified to review your proposed change.

**Comment by adamglick** [comment]
Hi @kenrward thanks for the update!  In this case I think there may be some confusion as the "Cloud Services" listed here are for the actual service offering of Azure Cloud Services.  I'd be happy to link to a doc on designing for use of Cloud Services (PaaS) though the link included (the Failsafe content) is out of date, has a number of broken links and deals with the general design of cloud services. I do know that Khalid (the author of the DR doc) is looking into making one that will be more design focused and service specific. Do you feel the Failsafe content is Azure Cloud Services (PaaS) specific to designing for HA (in general the PaaS services don't need HA design ans that's what a PaaS is supposed to do for users though I'm not deep on Cloud Services so this may be an exception)..

**Comment by kenrward** [comment]
I think we need to link something or change the wording "not needed" is better than "not available".  Also, what about linking to Availability Set documentation for VM's?

**Comment by kenrward** [comment]
Sorry, meant to "close & comment"

**Pull request closed without merging**
