### PR TITLE
"Detect duration of a condition" query

### PR DESCRIPTION
**Pull request by omarpando**
The output table of  "Detect duration of a condition" query is showing **FaultDurationSeconds** but the solution query is only returning **StartFault** and **EndFault**.

Also, the query returns  only one record for the given dataset. Please, feel free to try with this json [https://gist.github.com/omarpando/c40b0fe27def4bc08612232b9d9c525d:](https://gist.github.com/omarpando/c40b0fe27def4bc08612232b9d9c525d)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omarpando__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jeffstokes72 - Please review this public repo pull request

**Comment by jeffstokes72** [comment]
Hello Omarpando, 

I am researching this with the team who owns this content and will circle back today. Thanks for your feedback and suggestion here.

Jeff

**Comment by omarpando** [comment]
Hello @jeffstokes72 ,
Here you have a screenshot of the test(it only returns one row and it has the **FaultDurationSeconds** 
column.
Also, I included a new [gist ](https://gist.github.com/omarpando/53037aeaddb06cb54167b550d187193a)with the changes/dataset that way you guys can test it.


## Screenshot
Query screenshot

**Comment by jeffstokes72** [comment]
@omarpando You are awesome. Thank you. I want to confirm this is the way we wanted our demo to go (did we mess up the query, or the intent of the lesson, or both) with the developer who had the idea. I should hear something shortly and follow up here. Thanks for these examples and the gist, this helps a lot!

jeff

**Comment by cjgronlund** [comment]
@jeffstokes72 
Please let me know if this should be accepted or not. Thansk!

**Comment by jeffstokes72** [comment]
@cjgronlund  
I think we addressed this. Checking.

**Comment by tysonn** [comment]
@jeffstokes72 - hey, any update on whether this was addressed?

**Comment by jeffstokes72** [comment]
Yes just checked it we published the solution to this on the 13th apologies for not following up earlier.

**Comment by jeffstokes72** [comment]
@tysonn @cjgronlund https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-stream-analytics-query-patterns/#query-example-detect-duration-of-a-condition is the solution update.

**Pull request closed without merging**
