### PR TITLE
Update multi-factor-authentication-whats-next.md

### PR DESCRIPTION
**Pull request by SunnyDeng**
Hi billmath, loc finds an incompleted sentence, could you please review: "Note that caching is not intended to be used for sign-ins to ."
Thanks
-sunny

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SunnyDeng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dengyun). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@SunnyDeng , @billmath - this PR has a merge conflict. Can either/both of you review and determine whether it should be closed or resolved? Thanks!

**Comment by billmath** [comment]
This has already been fixed and is live.  It should be:

Note that caching is not intended to be used for sign-ins to Azure AD.

**Comment by BryanLa** [comment]
Thanks @billmath. Given that it's already live and we have a merge conflict, I will close this PR.

@SunnyDeng - FYI, and thanks again.

**Pull request closed without merging**
