### PR TITLE
The anchor links weren't working

### PR DESCRIPTION
**Pull request by donkristo**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@donkristo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@donkristo : Thanks for your contribution to the Azure documentation! The author, @szarkos, has been notified to review your proposed change.

**Comment by szarkos** [comment]
Sorry, missed this.  This LGTM.

**Comment by szarkos** [comment]
#sign-off

**Pull request merged**
