### PR TITLE
Updating a few links where content has moved.

### PR DESCRIPTION
**Pull request by noopman**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@noopman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@billmath - can you please review when you have a chance? Thanks.

**Comment by billmath** [comment]
Yes, these look good, but we probably want to remove the en-us from the URLs.  Thanks @noopman!

**Comment by BryanLa** [comment]
Thanks @billmath. 

@noopman please remove the '/en-us' segments from the 2 new/replacement URLs. We do this to allow the reader to get correct localization. Once that's done I will merge.

**Comment by noopman** [comment]
Thanks and I'm sorry but how do I get back to my patch and make that change? I'm a little unaccustomed to this contribution model. Sorry.

**Comment by BryanLa** [comment]
Hi @noopman - you can just go to the "Files Changed" tab on the top of the PR page, then on the portion that has the file name (articles/active-directory/active-directory-aadconnect.md ), look to the far right and you will see a pencil-like icon. If you click that icon, it should drop you edit a web based editor on the file as it exists in your commit. From there you can make the change and save, which will show as another commit in your PR.

**Comment by noopman** [comment]
Thanks for the guidance!

**Comment by BryanLa** [comment]
You're welcome, and thanks for the contribution! Once other slight change I forgot to mention ...  :\
For any links to service-related articles hosted on azure.microsoft.com (like Azure AD, etc.), we don't express the full URL in the markdown; we only encode the filename portion, including the .md extension. So for instance, 
`[Azure AD Connect Health](https://azure.microsoft.com/documentation/articles/active-directory-aadconnect-health/)`

should be encoded as : 

`[Azure AD Connect Health](active-directory-aadconnect-health.md)`

If you wouldn't mind changing the one I mentioned above and the 2nd one, that would be great, and I promise I will merge after that. Thanks again!

**Comment by noopman** [comment]
No worries at all! It needs to be correct. I am learning here and you are being patient, sir! Hope it is correct now!

**Comment by BryanLa** [comment]
@noopman - just checking back,  as I don't see a new commit for the changes yet...

**Comment by noopman** [comment]
Really odd. I had to do this several times. For some reason my "Commit changes" didn't take. No I b3elieve they did?

**Comment by BryanLa** [comment]
Yes, I see the commit now. I will merge, and thanks again!

**Pull request merged**
