### PR TITLE
Search SDK: Adding migration guide for v1.0.0-preview of the .NET SDK

### PR DESCRIPTION
**Pull request by brjohnstmsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brjohnstmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brjohnst). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@brjohnstmsft 
Hello, Bruce. This is a new article and needs to be submitted for publication through the private repo azure-content-pr (which will put it though validation).

For guidance see the following:
https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md
https://github.com/Azure/azure-content/blob/master/contributor-guide/git-commands-for-master.md
https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Documentation%20training%20+%20best%20practices%20for%20partners.aspx

Thanks.

**Comment by rmca14** [comment]
@brjohnstmsft 
Hello, Bruce. This is a new article and needs to be submitted for publication through the private repo azure-content-pr (which will put it though validation).

Please close this pull request using the **Close and comment** button at the bottom of this page and submit a new pull request using the guidance below. Thanks for your contribution.    

For guidance see the following:
https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md
https://github.com/Azure/azure-content/blob/master/contributor-guide/git-commands-for-master.md
https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Documentation%20training%20+%20best%20practices%20for%20partners.aspx

**Comment by brjohnstmsft** [comment]
I'll re-submit using the private repo.

**Pull request closed without merging**
