### PR TITLE
Resources sub-heading missing a word: "that"

### PR DESCRIPTION
**Pull request by webframp**
Minor change I noticed while reading the docs

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@webframp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@webframp : Thanks for your contribution to the Azure documentation! The author, @tfitzmac, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@webframp - thanks for catching that mistake.

**Comment by tfitzmac** [comment]
#sign-off

**Pull request merged**
