### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by AlexZeitler**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlexZeitler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlexZeitler : Thanks for your contribution to the Azure documentation! The author, @msfussell, has been notified to review your proposed change.

**Comment by msfussell** [comment]
Alex - I looked at the commits and could not see the typo. What specifically did you update?
thanks

**Comment by AlexZeitler** [comment]
It is `contacts` vs. `contracts`
image

**Comment by AlexZeitler** [comment]
The GitHub "rich diff" display on that particular change:
https://github.com/Azure/azure-content/pull/7238/files?short_path=93a6e5c#diff-93a6e5cc80ebb92c3599fec550b1bac6

image

**Comment by msfussell** [comment]
This is a great catch. Thanks for seeing this. Yes, please approve.

**Comment by KatieCumming** [comment]
@msfussell - Hi Mark, merging. Please use #sign-off in the future when you've approved a change. Thanks, Katie

**Comment by msfussell** [comment]
#sign-off

**Pull request merged**
