### PR TITLE
Swap the Edit actions to reflect the text below it

### PR DESCRIPTION
**Pull request by MisinformedDNA**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MisinformedDNA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@mimig1

**Comment by mimig1** [comment]
Sent to PM for review.

**Comment by ryancrawcour** [comment]
@mimig1  ack

**Comment by mimig1** [comment]
#sign-off Please accept.

**Pull request merged**
