### PR TITLE
Updated SQL permission enumeration

### PR DESCRIPTION
**Pull request by DRediske**
Current to 8/17/16

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DRediske__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@DRediske : Thanks for your contribution to the Azure documentation! The author, @kgremban, has been notified to review your proposed change.

**Comment by kgremban** [comment]
@DRediske thanks for going through and making these edits. I've confirmed in PowerShell, and it all looks good.

**Comment by kgremban** [comment]
#sign-off

**Pull request merged**
