### PR TITLE
Update sql-database-powershell.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed minor typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alexandair - Looking at the diff, I don't see any changes. Do you see the changes you expected to see here?

**Comment by alexandair** [comment]
I can see it. :) A minor one. "ARM based" to "ARM-based". (twice)

**Comment by tysonn** [comment]
The terminology guidance around this would actually require us to say something like "the cmdlets for the Resource Manager deployment model" if I were following it literally, or "the Resource Manager cmdlets" if I were being a bit more flexible. We aren't supposed to use the acronym ARM, but its all over the place.

**Comment by alexandair** [comment]
As you said, the acronym ARM is everywhere. I just wanted to make it grammatically correct. I don't have access to internal style guide. (It would be nice to have it, if something like that exists. :))

**Comment by tysonn** [comment]
@alexandair - I submitted a PR to your fork :)

**Comment by alexandair** [comment]
I've merged your PR. :)

**Pull request merged**
