### PR TITLE
Update storsimple-update1-release-notes.md

### PR DESCRIPTION
**Pull request by vidarmsft**
The StorSimple Virtual Appliance image was refreshed on 10th July. This documentation change reflects the changes that came in with this update.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vidarmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@vidarmsft Thanks for the contribution! I've sent the change to the author for approval.

**Comment by SharS** [comment]
Reviewed - OK to merge.

**Comment by vidarmsft** [comment]
Hi, why am I not able to see the update to the page yet?

**Pull request merged**
