### PR TITLE
Update vpn-gateway-about-vpn-devices.md

### PR DESCRIPTION
**Pull request by samhodgkinson**
Further detail around Route Based VPN's  initiation process which is not currently clear

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@samhodgkinson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@samhodgkinson : Thanks for your contribution to the Azure documentation! The author, @yushwang, has been notified to review your proposed change.

**Comment by yushwang** [comment]
Hi, @samhodgkinson 

I looked at your suggestion, and it's not clear to me what the issue was. Could you clarify?

Thanks,
Yushun

**Comment by samhodgkinson** [comment]
Hi Yushun

From the documentation, it's not clear that the Azure route base VPN is only initiated on either the Azure gateway or the end VPN device. Although the configuration of the 2nd phase policy configuration does indicate this, it's not clearly stated. I have recently had to connect a customer into a new Azure environment, where the network team where looking for the connection to be established on either side. From my experience, this confusion has been caused by network engineers expecting the Azure VPN to conform to Cisco/Checkpoint. 

I was just looking to add a clarifying point to remove this possible confusion for anyone else.

Let me know if you need anything else 

Kind Regards

Sam Hodgkinson

**Comment by yushwang** [comment]
#please-close

@samhodgkinson - Sure. Technically speaking, based on the IPsec/IKE protocol definition, both sides can initiate the IKE handshakes. The proposed language is not completely accurate. I'll close this PR for now due to our internal migration schedule. If there's a specific issues on Check Point devices, which we have had a couple, please let me know. I wasn't aware of issues with Cisco devices.

Thanks,
Yushun

**Comment by samhodgkinson** [comment]
Thank you for your consideration 

 

This issues we had with the checkpoint was due to the checkpoint using the universal tunnel proposal. 

 

“When Azure negotiates the tunnel it sends to Check Point universal tunnel proposal which we do not expect. Check Point expect to receive as proposal *.*.*.*/26 network and in some reasons react with sync network IP”. With changing the IPsec configuration around connectivity from DC1 was possible but only when initiated from within DC1.

 

Kind Regards

 

Sam Hodgkinson

**Pull request closed without merging**
