### PR TITLE
Correction of the statement on premium circuits

### PR DESCRIPTION
**Pull request by omartin2010**
Same change as on the powershell ARM

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by cherylmc** [comment]
Hi @omartin2010, already fixed. :-) I put them both through at pretty much the same time, based on your earlier recommendation. Thanks for making sure, though!

**Comment by cherylmc** [comment]
#please-close

**Pull request closed without merging**
