### PR TITLE
Fixed typo in storage-table-design-guide.md

### PR DESCRIPTION
**Pull request by joelhulen**
Fixed a typo and made a slight grammatical modification within the designing Table service queries section.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@joelhulen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@joelhulen : Thanks for your contribution to the Azure documentation! The author, @jasonnewyork, has been notified to review your proposed change.

**Comment by tamram** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@tamram Hi Tamra
The listed author of this is authors="jasonnewyork". Tamra, please contact azdocprs to request this be merged. Only the listed author can use the sign off comment to get this merged. Thanks.

**Pull request merged**
