### PR TITLE
Fix example MD formatting

### PR DESCRIPTION
**Pull request by aarondandy**
All I did was change indentation so the content is formatted correctly. The diff looks way crazier than the actual change.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aarondandy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ChackDan - please review this public repo contribution.

**Comment by ChackDan** [comment]
ACK. the change looks good.

**Comment by tysonn** [comment]
@aarondandy  - Thank you for the update!

**Pull request merged**
