### PR TITLE
GS series related updates to be published after 8/31

### PR DESCRIPTION
**Pull request by ms-prkhad**
Added limits and verbiage related to GS-series VM support on Premium Storage. Since the official GS series Marketing content will be updated on 9/2, we want to publish this content in that week as well.

- Pradnya

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ms-prkhad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@ms-prkhad Thank you for these edits.  It appears you may be MSFT internal.  Would you please update your profile to meet the [guidelines](https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile) so pull request reviewers can recognize you?

**Comment by deneha** [comment]
@tamram Would you please review these edits and let me know if I have your approval to merge this request?  Thank you.

**Comment by deneha** [comment]
At MSFT as prkhad - CLA not required

**Pull request merged**
