### PR TITLE
Update active-directory-reporting-sign-ins-from-possibly-infected-dev…

### PR DESCRIPTION
**Pull request by SSalahAhmed**
…ices.md

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SSalahAhmed__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@SSalahAhmed We're trying to keep Markdown format as our primary format.  This change puts the format back into HTML.  Was there a reason why it needs to be in HTML?

**Comment by SSalahAhmed** [comment]
Sorry I wasn't aware of that. The link wasn't showing up properly, that's I made the change.

**Comment by BryanLa** [comment]
Thanks @SSalahAhmed. Adding @kenhoff ...  Ken: would you mind making the link update on the private repo (azure-content-pr), and removing the HTML? LMK if you're OK doing that and we can close this PR.

**Comment by BryanLa** [comment]
@kenhoff @yossibanai - any thoughts on this?

**Comment by kenhoff** [comment]
I can take a look at this now.

**Comment by kenhoff** [comment]
opened a pr: https://github.com/Azure/azure-content-pr/pull/15367

closing.

**Comment by BryanLa** [comment]
Closing per above

**Pull request closed without merging**
