### PR TITLE
Service Fabric Local Clusster Setup

### PR DESCRIPTION
**Pull request by jgardner04**
The getting started documentation "Create your first Azure Service Fabric application in Visual Studio" assumes that the local Service Fabric cluster is already created. Following the order of the Getting Started, it is not created until the following article. I recommend linking to this as I have done here. I can also add a section that will create the local cluster if this is not acceptable.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jgardner04__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@seanmck - Please review this public repo contribution. Thanks ---

**Comment by seanmck** [comment]
Thanks for the suggestions.

If you haven't set up a local cluster in advance, VS will spin one up for you so this step is not necessary. The cleanup step on the local cluster article is a good one to add but it would be better to include it inline rather than as a link to the long VS-focused article since these two are intended to be independent.

@tysonn: please close without merging.
@rwike77: consider adding an inline cleanup step in the local cluster article.

**Comment by tysonn** [comment]
@jgardner04 - Thanks for the suggestion - closing per the author's feedback.

**Comment by jgardner04** [comment]
@seanmck I ran it in VS as written and got an error until I setup the local cluster. I am running 2015 with the latest prod. updates.  Feel free to ping me on SfB (jogardn) if you want to discuss further as well.

**Pull request closed without merging**
