### PR TITLE
Update resource-group-authenticate-service-principal.md

### PR DESCRIPTION
**Pull request by notdev**
$azureAdApplication.ApplicationId used in the script is an object with Guid property.
-ServicePrincipalName expects string.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@notdev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@tfitzmac - Tom, could you review this proposed update from @notdev in the public repo?

**Comment by tysonn** [comment]
@tfitzmac - second notice, pls review

**Comment by tfitzmac** [comment]
@notdev - thanks for this fix. I double-checked your code and the original code, and it looks like both work. Perhaps this issue was resolved in the latest version of PowerShell. In the interest of clarity, let's merge this PR.

**Pull request merged**
