### PR TITLE
attempting to fix link

### PR DESCRIPTION
**Pull request by 4c74356b41**
this link gets constructed https://azure.microsoft.com/en-us/documentation/articles/azure-classic-rm/resource-group-overview.md/#template-deployment
and this SHOULD be constructed
https://azure.microsoft.com/en-us/documentation/articles/resource-group-overview/#template-deployment

I think I fixed it properly, but I'm not sure

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by 4c74356b41** [comment]
hello_

**Comment by 4c74356b41** [comment]
@telmosampaio friendly reminder

**Comment by jimdial** [comment]
@4c74356b41: Thanks for the suggestion.  There is no need to add "articles" to this link path because the article is in \articles, as-is the article it links to. In this case, only the article name being linked to is required, which is what the original link was.  The "/" that was between the "md" and "#" shouldn't have been there though, so I removed it.

I submitted a PR to your fork with this change.  If you agree with it, please accept and we can get this article updated with it.

Thanks again!

**Comment by 4c74356b41** [comment]
thanks, done!

**Comment by 4c74356b41** [comment]
hello? xD

**Comment by jomolnar** [comment]
@jimdial Hi Jim. This contribution looks ready to merge. If you agree, please sign off. Thanks.

**Comment by jimdial** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
