### PR TITLE
Noting that Windows clusters cannot be moved cross-subscription.

### PR DESCRIPTION
**Pull request by matt1883**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt1883__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mahi). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@tfitzmac - Can you please review this change from the public repo.

**Comment by tysonn** [comment]
@tfitzmac - Tom, can you review?

**Comment by matt1883** [comment]
Withdrawing this PR.

**Pull request closed without merging**
