### PR TITLE
Updating vpn-gateway verbiage around null encryption

### PR DESCRIPTION
**Pull request by CtrlDot**
Original verbiage is not clear if null encryption is a recommendation by the Azure network team, or simply an option that can be applied.  Further, it does not outline the inherent risks to using null encryption.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CtrlDot__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@cherylmc Cheryl, can you take a look at this contribution and let me and the author know if this should be merged? Thanks!

**Comment by cherylmc** [comment]
Hi! Thanks for taking the time to let us know how we can make this doc better. I've sent this over to the PM to verify. I always do that, just so the PM knows that there is a change and that he's on board with it. Once he validates, I'll comment and we can move forward.

**Comment by yushwang** [comment]
Hi, Looks good. Please go ahead and accept the PR.

Thanks,
Yushun

**Comment by cherylmc** [comment]
All good here as well. You can move forward to accept the PR.

**Pull request merged**
