### PR TITLE
Update for QuickStart

### PR DESCRIPTION
**Pull request by brandwe**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brandwe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@brandwe looks good.  The only additional suggestion I would have is to make your "For additional resources, check out:" statement at the end an H2 heading (ie: ##For additional resources, check out:).  Otherwise, just let me know when you are ready to merge.

**Comment by brandwe** [comment]
@BryanLa Done! Feel free to merge

**Comment by BryanLa** [comment]
Thanks Brandon.

Btw, I forgot to mention that the H2 headings are using a mix of italicized and non.  We normally go with non-italicized in all other Azure content.  LMK if you want to change one way or the other before I merge...

Thanks,
Bryan

**Comment by brandwe** [comment]
Go ahead and merge. I'll probably make more changes in the future.

**Comment by BryanLa** [comment]
Done.  

Btw, if you want to be more involved with content development (ie: on a more regular basis, or at a deeper level), using the private repo (azure-content-pr) would be a better experience for you.  The public repo is more for smaller, community updates.  We also monitor the private repo multiple times/day, and the recommended tools/process give you the ability to do deeper contributions.  We also provide CI which gives you continuous validation feedback, and staged deployment of articles so you can review them.  If you are interested, check out the contributors’ guide (https://github.com/Azure/azure-content/blob/master/contributor-guide/contributor-guide-index.md), and make sure to follow the “if you are a Microsoft employee…” steps along the way.  

Happy to help w/any of this.  LMK if you have any questions, and thanks again for this contribution.

**Pull request merged**
