### PR TITLE
remove blobs and files from managable objects of stored access policy

### PR DESCRIPTION
**Pull request by yijiem**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yijiem__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@yijiem Thank you for this contribution.  I'll have the owner of the article review.

@tamram Would you please review and let me know if I should merge this request?

**Comment by tamram** [comment]
This change isn't necessary, as stored access policies can be used to provide SAS parameters for blobs and files. 

However, stored access policies can be created only on containers, tables, queues, and file shares - they can't be created on blobs or files. I think this is why the contributor is offering this change. This text doesn't say that they can be created on blobs or files, but I can clarify the text to make that more obvious.

**Comment by yijiem** [comment]
Thank you @tamram for clarification!

**Comment by tysonn** [comment]
Closing per Tamra's feedback.

**Pull request closed without merging**
