### PR TITLE
Update sql-database-business-continuity-design.md

### PR DESCRIPTION
**Pull request by dstolts**
Add a note that if they do not already have a SQL Server in the destination location it can be created on the fly.  Instructions without this comment, if they do not already have a replica server (which is likely almost everyone) do not work.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dstolts__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@elfisher 
Please review this PR and approve/disapprove it here with a comment, thanks.

**Comment by elfisher** [comment]
This is a great add. I think we could be more explicit by saying "When creating enabling Geo-Replication in the portal, if you do not already have a server for your secondary, you can create a server on the fly."

**Comment by rmca14** [comment]
@dstolts 
Feel free to make the author's suggested change, thanks.

**Comment by rmca14** [comment]
@dstolts 
If you'd like to make the change as noted, please feel free to do so -- we can't make it for you in this pull request. Or feel free to close this pull request.
@elfisher 
If dstolts closes this pull request, and if you'd like this change made, feel free to open a new pull request (in the private repo) with the change.

Thanks.

**Comment by rmca14** [comment]
Closed due to inactivity.

**Comment by rmca14** [comment]
@elfisher 
Feel free to reopen this PR or open a new PR to make this change.

**Pull request closed without merging**
