### PR TITLE
Correction of the statement on premium circuits

### PR DESCRIPTION
**Pull request by omartin2010**
There was something that IMO isn't correct (all expressroute circuits must be in the same geopolitical region... it's vnets we're talking about and there's an exception if the circuit is a premium one).
Let me know if that makes sense!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @ganesr, has been notified to review your proposed change.

**Comment by ganesr** [comment]
#sign-off

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @ganesr, has been notified to review your proposed change.

**Comment by ganesr** [comment]
#sign-off

**Pull request merged**
