### PR TITLE
Update hdinsight-apache-spark-resource-manager.md

### PR DESCRIPTION
**Pull request by markgar**
Added some more description of how the math is done for allocating cores/ram for using only IPython.

Added text to explain IPython connection to Jupyter.  Folks new to Spark might not understand as Pupyter is the how we label things in the Azure Portal.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@markgar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
Please resolve the merge conflict. For guidance, see https://github.com/Azure/azure-content-pr/pull/12850

Thanks.

**Comment by rmca14** [comment]
Closed due to inactivity.

**Comment by markgar** [comment]
I tried to work on this but the link was broken that you sent me earlier.

[MSFT_logo]

Mark Garner
BI and Cloud Architect
Microsoft
North Central - Stu App Plat
Office: +1 (952) 832-8037
Mobile: +1 (515) 779-9877
mgarner@microsoft.com <mailto:mgarner@microsoft.com>

**Pull request closed without merging**
