### PR TITLE
Update azure-stack-webapps-deploy.md

### PR DESCRIPTION
**Pull request by JakobGSvendsen**
PS command for deploying the was a bit wrong
passwords needs to be securestring + extra spaces after ` breaks the line continuation. (dont know if they will still appear after edir in the final formatting) + i added verbose to be able to follow progress

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JakobGSvendsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@JakobGSvendsen - Thanks for the contribution.

@ccompy - Could you please review Jakob's contribution and let me know if we can go ahead and merge the updates?

**Comment by tysonn** [comment]
@ChrisCompy - please review this public repo contribution - second notice

**Comment by ChrisCompy** [comment]
There is another PR in works vis a vi one of the editors.  That PR has changes that make the contribution unneeded.  The change we made is slightly different but has the same effect.

**Comment by ChrisCompy** [comment]
@JakobGSvendsen  Just to be clear, I do thank you for the contribution.  You are correct in what was missing.  I had a few 'bumps' in the doc of which that was probably the most egregious.  We can go ahead and take your contribution which is helpful until the doc update comes out.

**Comment by tysonn** [comment]
@JakobGSvendsen - The code snippet has changed significantly:

```
New-AzureRmResourceGroupDeployment
-Name <name>
-ResourceGroupName <resource-group>
-TemplateFile <ArmTemplatePath>
-storageAccountNameParameter <storage-account>
-adminUsername <admin-username>
-adminPassword (ConvertTo-SecureString -force -AsPlaintext "myPassword1!")
-sqlservername <sql-server>
-sqlsysadmin 'sa'
-sqlsysadminpwd <sa-password>
-defaultSslPfxFilePassword <webapps-ssl-cert>
-resourceProviderSslPfxFilePassword <management-ssl-cert>
-environmentDnsSuffix 'webapps.azurestack.local'
-armEndpointUri 'https://api.azurestack.local'
-resourceProviderUri 'https://management.azurestack.local'   
```

And it sounds the overall article is going to change soon. There's a merge conflict due to the code snippet differences. I'm going to close at this time - I'm sorry we aren't able to merge.

**Pull request closed without merging**
