### PR TITLE
Duplicate grammar change

### PR DESCRIPTION
**Pull request by AndyHerb**
Removed duplicate phrase

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndyHerb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@AndyHerb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AndyHerb : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by Ja-Dunn** [comment]
@dlepow - Hi Dan, this is a public PR, and it looks like the content belongs to you or Ralph. Could one of you review? Thanks!

**Comment by dlepow** [comment]
@AndyHerb - Thanks very much for catching that and submitting the fix. Looks great. 
@cynthn - Just FYI, since this is a common file included in a couple of your articles.
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by cynthn** [comment]
#sign-off @AndyHerb - thanks again for catching this issue! @dlepow thanks for the help!

**Pull request merged**
