### PR TITLE
Update app-service-logic-what-are-logic-apps.md

### PR DESCRIPTION
**Pull request by kevinlam1**
These changes are for the Logic App preview refresh going out on 2/22/16.
Here's the new screen grab for the article:
logicappcapture2

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kevinlam1__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (klam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@kevinlam1 did this fix already get made in the private repo? If so, please close this PR.

**Comment by ggailey777** [comment]
@kevinlam1 Does the rest of this PR look OK to you?

**Comment by kevinlam1** [comment]
+Deon and Jeff
I thought these changes were already published?

-Kevin

**Comment by kevinlam1** [comment]
Yes, it looks like these are already published…no need to merge this pr…

From: Kevin Lam
Sent: Tuesday, March 8, 2016 5:08 PM
To: Azure/azure-content <reply@reply.github.com>; Azure/azure-content <azure-content@noreply.github.com>; Glenn Gailey <Glenn.Gailey@microsoft.com>; Deon Herbert <deonhe@microsoft.com>; Jeff Hollan <Jeff.Hollan@microsoft.com>
Subject: RE: [azure-content] Update app-service-logic-what-are-logic-apps.md (#5745)

+Deon and Jeff
I thought these changes were already published?

-Kevin

**Comment by MSFTMan** [comment]
These changes are already merged into the document, so no need to accept this pr

**Comment by ggailey777** [comment]
OK, I will close this PR for @kevinlam1.

**Pull request closed without merging**
