### PR TITLE
Update site-recovery-best-practices.md

### PR DESCRIPTION
**Pull request by adamglick**
Just some typo and grammar fixes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adamglick__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@adamglick : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
Changes are fine but they're not on the latest so merge needed. Please keep the new version where possible.

**Comment by Jim-Parker** [comment]
@adamglick Adam, I've submitted a PR to your fork to resolve the merge conflict. All I did was make sure your contributions showed up in the latest version. Can you please take a look and let me know if it's okay to merge?

**Comment by adamglick** [comment]
looks good.  I added one more the though it might make sense for the article owner to do a proofing pass on their content.

**Comment by Jim-Parker** [comment]
@adamglick  I can request an edit for this one. I'm still seeing a conflict on this PR though. You may need to merge my change into your fork. Can you take a look? And thanks for working with us on this article.

**Comment by rayne-wiselman** [comment]
Since these are light typos it might be quicker to close the pull request, get latest, and submit new one.

**Comment by adamglick** [comment]
I'm going to close.  I used the edit link on our website so if that isn't current then we might need to fix that.  The typos are small so perhaps you can put them into your latest version Rayne.

**Pull request closed without merging**
