### PR TITLE
added some extra info into threshold page

### PR DESCRIPTION
**Pull request by ashishmansukhani**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ashishmansukhani__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ashishmansukhani : Thanks for your contribution to the Azure documentation! The author, @masnider, has been notified to review your proposed change.

**Comment by masnider** [comment]
Hi @ashishmansukhani, , these changes look good. I #signoff, let me know if there is other steps I need to take.  Thanks!

**Comment by ashishmansukhani** [comment]
Hi @masnider , I don't have sufficient permissions to merge this. Will @azurecla do it automatically?

**Comment by masnider** [comment]
Well, I thought they would :) @tysonn - what do we need to do here?

**Comment by tysonn** [comment]
@masnider - Type #sign-off as the author, and the ready-to-merge label will be assigned. That lets us know it's ready to be merged.

**Comment by masnider** [comment]
@tysonn hm, I was told in a separate conversation with @rwike77 that didn't work (and I guess I thought I had when I did signoff all one word above). Whatever! Glad to do whatever is necessary. Will do in the future.

**Comment by rwike77** [comment]
@tysonn  Yes, I did tell @masnider that in a separate mail.  I must've misread the instructions, my mistake.

**Pull request merged**
