### PR TITLE
Fix double quotes around portalLink value

### PR DESCRIPTION
**Pull request by Gonkers**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Gonkers__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Gonkers : Thanks for your contribution to the Azure documentation! The author, @kamathashwin, has been notified to review your proposed change.

**Comment by rboucher** [comment]
Thanks for your contribution @Gonkers.  We are making this update.  Sorry for the bad smart quotes. CCing. @kamathashwin

**Comment by rboucher** [comment]
Adding myself @rboucher.

**Comment by kamathashwin** [comment]
#sign-off

**Comment by rboucher** [comment]
This change has been merged @Gonkers . Thanks!

**Comment by Gonkers** [comment]
Great! I'm just glad I can contribute. That was never possible before!

**Pull request merged**
