### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@YuriDio H Yuri. Please review this proposed change. Thanks.

**Comment by YuriDio** [comment]
@jomolnar changes are good. @BryanLa please merge it.

**Comment by jomolnar** [comment]
@YuriDio Hi Yuri. Can you please sign off? Thanks.

**Comment by YuriDio** [comment]
#signoff

**Pull request merged**
