### PR TITLE
Chages to AOI Article

### PR DESCRIPTION
**Pull request by alex-frankel**
Added images and edited a current AOI article to update it. This should resolve problems from previous pull requests; hence, they've been closed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alex-frankel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alex-frankel** [comment]
I've made the necessary changes required to the images.

**Comment by tysonn** [comment]
This pull request has a merge conflict now - can you run "git pull upstream master" from your local master branch, then resolve any merge conflicts that are listed.

**Comment by tysonn** [comment]
@alex-frankel Hey Alex - closing this PR since the source branch no longer exists, and because the merge conflicts are still present.  Please resubmit if you want these changes to be considered.

**Pull request closed without merging**
