### PR TITLE
Removed azure websites constraint

### PR DESCRIPTION
**Pull request by dabutvin**
Proved outbound rules for Access-Control-Allow-Origin worked on azure websites

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dabutvin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dabutvin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dragon119

**Comment by bennage** [comment]
@CamSoper do you handle the CDN docs?
Can you offer any input on this? //cc @atoakley +

**Comment by CamSoper** [comment]
I help with CDN, but I'm not the primary author at the moment, at least for the time being (due to being assigned other priority projects).  Please loop in CDN program manager @Lichard .

**Comment by dragon119** [comment]
Looks like now it works with Web site.

**Comment by dragon119** [comment]
# sign-off

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by dabutvin** [comment]
#sign-off

**Pull request merged**
