### PR TITLE
Recommendation to disable tables.

### PR DESCRIPTION
**Pull request by AnunayTiwari**
We are adding the recommendation to disable the HBase tables before deleting the cluster to avoid inconsistencies.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AnunayTiwari__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AnunayTiwari : Thanks for your contribution to the Azure documentation! The author, @mumian, has been notified to review your proposed change.

**Comment by mumian** [comment]
#sign-off

**Comment by tysonn** [comment]
I submitted a patch to the suggestion: https://github.com/AnunayTiwari/azure-content/pull/1

**Pull request merged**
