### PR TITLE
Update hdinsight-hadoop-create-linux-clusters-azure-powershell.md

### PR DESCRIPTION
**Pull request by oedenfield**
Changed "Value" on Line 84 to "Key1".  I had to make this change in my environment to get this to properly pull the key for the storage account into the $defaultStorageAccountKey variable.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@oedenfield__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@oedenfield : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@cjgronlund - Please merge this PR.

**Comment by nitinme** [comment]
@cjgronlund - Please merge this PR.

**Comment by nitinme** [comment]
#sign-off

**Comment by nitinme** [comment]
@tysonn - Please merge this PR

**Pull request merged**
