### PR TITLE
Correct grammar: "read *from* the regions specified"

### PR DESCRIPTION
**Pull request by mattscully**
Changed "read to the regions specified..." to "read from the regions specified..."

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mattscully__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mattscully : Thanks for your contribution to the Azure documentation! The author, @kiratp, has been notified to review your proposed change.

**Comment by kiratp** [comment]
@mattscully - thanks for catching this and filing a PR.

@mimig1 - ready to merge. Thanks!

**Comment by mimig1** [comment]
@tysonn - Please merge. Thank you!

**Pull request merged**
