### PR TITLE
Broken Link

### PR DESCRIPTION
**Pull request by punitganshani**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@punitganshani__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@wesmc7777 - Please review and let @ggailey777 know whether this proposed change from @punitganshani in the public repo can be merged.

**Comment by wesmc7777** [comment]
@ggailey777 we can merge this

**Comment by ggailey777** [comment]
@punitganshani thank you for finding and fixing this broken link. We appreciate your help improving the quality of Azure docs.

**Pull request merged**
