### PR TITLE
Update key-vault-developers-guide.md

### PR DESCRIPTION
**Pull request by BrucePerlerMS**
reorder some content and update a couple sections for clarity

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BrucePerlerMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bruceper). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Hey @BrucePerlerMS - I can't merge this one due to merge conflicts :-/  Likely caused by the other PR on this same file that was just merged. LMK if you'd like to close and resubmit, or open a PR against the private repo.

**Comment by BrucePerlerMS** [comment]
Hmmm. I’ll have a look and likely cancel and resubmit.
Thanks,
Bruce

**Comment by BrucePerlerMS** [comment]
I’d like to close and resubmit. ☺

**Comment by BrucePerlerMS** [comment]
merge conflict suggests I try again

**Pull request closed without merging**
