### PR TITLE
Update expressroute-howto-linkvnet-arm.md

### PR DESCRIPTION
**Pull request by EricAshton**
Add-AzureRmExpressRouteCircuitAuthorization and Set-AzureRmExpressRouteCircuit and Get-AzureRmExpressRouteCircuitAuthorization should be using the switch -ExpressRouteCircuit not -Circuit

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EricAshton__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by EricAshton** [comment]
Add-AzureRmExpressRouteCircuitAuthorization and Set-AzureRmExpressRouteCircuit and Get-AzureRmExpressRouteCircuitAuthorization should be using the switch -ExpressRouteCircuit not -Circuit

**Comment by PRmerger** [comment]
@EricAshton : Thanks for your contribution to the Azure documentation! The author, @ganesr, has been notified to review your proposed change.

**Comment by ganesr** [comment]
#sign-off

**Comment by ganesr** [comment]
@EricAshton thanks for the change.

**Pull request merged**
