### PR TITLE
Update automation-graphical-authoring-intro.md

### PR DESCRIPTION
**Pull request by JakobGSvendsen**
added how to use inputs

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JakobGSvendsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@JakobGSvendsen Thanks for the contribution!  I've sent the change to the author for approval.

**Comment by bwren** [comment]
Great addition, thanks.  Can we reword to something like the following to make it a bit more clear?

An input parameter can be accessed in an activity by using a PowerShell Expression data source for a parameter value.  Use the name of the input variable for the expression.  For example, if you specified StringParam for the name of the input variable, then specify $StringParam for the expression.

**Comment by JakobGSvendsen** [comment]
Yes please. Thanks!  :)

Sent from my Sony Xperia™ smartphone


---- Brian Wren wrote ----


Great addition, thanks. Can we reword to something like the following to make it a bit more clear?

An input parameter can be accessed in an activity by using a PowerShell Expression data source for a parameter value. Use the name of the input variable for the expression. For example, if you specified StringParam for the name of the input variable, then specify $StringParam for the expression.

**Comment by bwren** [comment]
I don't think I can make that change. Think you need to change the text and resubmit.

**Comment by JakobGSvendsen** [comment]
ok i think I got it now :D great feature this is!

**Comment by deneha** [comment]
Fixed merge conflict and incorporated edits into https://github.com/Azure/azure-content-pr/pull/12260

**Pull request closed without merging**
