### PR TITLE
ServiceFabricExplorer Requires Administor

### PR DESCRIPTION
**Pull request by lawrencegripper**
Added not to doc to show that the ServiceFabricExplorer tool needs to be run as administrator to allow connection to local cluster setup by DevClusterSetup.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lawrencegripper__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by seanmck** [comment]
@lawrencegripper: Did you run the DevClusterSetup script without any arguments as shown in the instructions? If so, you shouldn't need to run the explorer tool as an admin.

**Comment by lawrencegripper** [comment]
Hi, 

Strangely, straight after running the DevClusterSetup (no args) I needed to run the Service Fabric Explorer as Administrator otherwise it wouldn't allow me to expand any of items in the tree view (sorry didn't grab a screenshot of the exception, was something along the lines of cluster has changed refresh parent. Is there a log anywhere I can grab for you?). 

Now that I've restarted the box I can run the explorer without being admin and all works well.

**Comment by seanmck** [comment]
Did you run the tool multiple times as a standard user and see that error? If not, I suspect that the Admin aspect was a red herring. Based on the message that you saw, it is more likely that the tool was just catching up on the state of the cluster as you were expanding the treeview the first time, hence the suggestion to refresh the parent. Restarting the tool did that for you but you could have also clicked the refresh button in the toolbar or right-clicked on the top-level onebox cluster in the tree and performed a refresh from there.

We intend the UI for the tool more intuitive and automatic so that you don't have to decipher these messages.

**Comment by seanmck** [comment]
@lawrencegripper: Heads up that we're going to close this pull request. If you manage to repro this condition again, feel free to drop me an email (seanmck *at* microsoft.com) with the details and we'll try to get it sorted out.

**Pull request closed without merging**
