### PR TITLE
Update sql-database-business-continuity.md

### PR DESCRIPTION
**Pull request by anosov1960**
Added a note to clarify that ERT and RPO are not part of SQL DB SLA

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anosov1960__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sashan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
Please remove the "en-us" in the link. Thanks.

**Comment by jeffgoll** [comment]
@rmca14 @anosov1960 Ross, this is a pull from one of our PMs. Do you have guidance on how he can make the correction in web UI?

**Comment by rmca14** [comment]
Jeff, he should be able to go to this version of the doc https://github.com/Azure/azure-content/pull/4885/files , click the little editing pen in the upper right margin, make the needed changes, and then click (I believe) the "Propose file change" button in the lower left.

Guidance for link syntax is https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/create-links-markdown.md

**Comment by rmca14** [comment]
He should also edit his GitHub username/profile to indicate he's a Microsoft employee.

**Pull request merged**
