### PR TITLE
App Service VNET Integration is not supported in the coexist model

### PR DESCRIPTION
**Pull request by snobu**
@ChrisCompy (ref internal e-mail thread with subject "RE: P2S issue when a VNET which has both ExpressRoute and P2S gateway")

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@snobu : Thanks for your contribution to the Azure documentation! The author, @charwen, has been notified to review your proposed change.

**Comment by charwen** [comment]
@snobu thanks for the contribution. However I'll have to decline your edition mainly because App Service VNET integration is not a main scenario for ExpressRoute and VPN coexistence. We can't possibly enumerate all of the limitations.

**Comment by snobu** [comment]
What if we put a positive spin on it, like this:

>[AZURE.NOTE]
This document does not address App Service VNET Integration scenarios. Please refer to this page instead https://azure.microsoft.com/en-us/documentation/articles/web-sites-integrate-with-vnet/

And we drop an [AZURE.NOTE] in there explaining the limitation with P2S and ExpressRoute coexist  scenarios...

**Comment by charwen** [comment]
@snobu we won't add it. see the reason in my previous comment. please close the pull request.

**Comment by snobu** [comment]
@chriscompy did you get a chance to mention this limitation in the VNET integration docs? Could you please link to that page here if so? Thanks!

**Pull request closed without merging**
