### PR TITLE
Added link to usage fees

### PR DESCRIPTION
**Pull request by gopitk**
This is the PM from  IMML with a minor edit to content. Pl merge and publish the same.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gokuma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
The "en-us" must be removed from the URL before this pull request can be merged, so feel free to remove the "en-us". Thanks for your contribution.

**Comment by rmca14** [comment]
I'm unable to identify **gopitk** as a MS employee. There is no name, alias, or MS designation associated with the GitHub user name. Please update your GitHub profile to follow this guidance
https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

Thanks

**Comment by rmca14** [comment]
@bradsev  
 Can you please approve/disapprove this PR with a comment? Thanks.

**Comment by rmca14** [comment]
The link still needs the "en-us" to be removed before this PR can be merged. Thanks.

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gokuma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gokuma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by gopitk** [comment]
Thanks. I have this change propagated through another change. This pull request can be closed.

**Pull request closed without merging**
