### PR TITLE
removed tags from secret in example

### PR DESCRIPTION
**Pull request by eocrawford**
Key Vault RP does not support secret tags or other metadata at this time.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@eocrawford__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
@eocrawford - thanks for submitting this change. Looks good.

**Comment by tfitzmac** [comment]
@ggailey777 - this PR in azure-content is ready to be merged.

**Comment by ggailey777** [comment]
@eocrawford Thanks for your contribution to the Azure documentation. We appreciate your help improving the quality of our topics.

**Pull request merged**
