### PR TITLE
Updates on VM portal URL, PTVS setup

### PR DESCRIPTION
**Pull request by gopitk**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gokuma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@gopitk 
Hello, Gopi. As a Microsoft employee and with these substantial changes, in the future you should start submitting your pull requests through the private repo **azure-content-pr** (which will run the pull requests though validation). For guidance, see our contributor guide https://github.com/Azure/azure-content/tree/master/contributor-guide and the pull request submission procedure https://github.com/Azure/azure-content/blob/master/contributor-guide/git-commands-for-master.md. Thanks for your contribution.

I'll merge this pull request with Brad's approval.

@bradsev
Hello, Brad. Can you review and approve/disapprove this pull request with a comment here? Thanks

**Comment by rmca14** [comment]
Follow-up mail sent to Brad.

**Comment by bradsev** [comment]
These edits are fine. Publish it.

**Comment by bradsev** [comment]
#sign-off

**Pull request merged**
