### PR TITLE
Retrieval of connection string from web.config/app.config is wrong

### PR DESCRIPTION
**Pull request by mveenman**
The code for retrieving the storage accounts connection string was wrong. The connection string should either be created under configuration > connectionStrings or the retrieval should point to appSettings. As there are multiple documents already referring to the string being stored under appSettings I propose to change the retrieval code here.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mveenman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by mveenman** [comment]
Link to article: https://azure.microsoft.com/nl-nl/documentation/articles/storage-dotnet-how-to-use-blobs/

**Comment by tysonn** [comment]
@mveenman - Thanks for this update -

@tamram or @robinsh - Could you please review this contribution and enter #sign-off if we can merge?

**Comment by robinsh** [comment]
Looks good to me. 
#sign-off

**Comment by tysonn** [comment]
@mveenman - merging, thank you

**Pull request merged**
