### PR TITLE
Command runs if filename is enclosed by inverted commas

### PR DESCRIPTION
**Pull request by sjetha**
I'm not sure if this is a PowerShell 5.0 change or not, but the code doesn't run unless the splatting operation is enclosed with inverted commas. It may be worth testing this out on a PS4.0 machine (which I don't have access to) to see if it can be used in both environments.
Alternatively it could be a typo, but I wasn't able to get the command running without enclosing the splatting operation. Once I did this the command completed successfully.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sjetha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sjetha : Thanks for your contribution to the Azure documentation! The author, @naziml, has been notified to review your proposed change.

**Comment by naziml** [comment]
since there are no spaces in the filename in this example, the quotes are unnecessary here.

**Comment by sjetha** [comment]
I noticed this comment on the ARMClient readme file, maybe it should be included in this repo's readme file too:
Note: PowerShell users will need to escape the  @  symbol with a back tick  ` .

**Comment by naziml** [comment]
Your suggestion has been merged. Update app-service-web-configure-tls-mutual-auth.md #28502
Can you close this PR?

**Pull request closed without merging**
