### PR TITLE
New tutorial for using Azure Key Vault from a Web Application

### PR DESCRIPTION
**Pull request by adamhurwitz**
I noticed that there wasn't a tutorial for this use case and thought it will be a common one.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adamhurwitz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by adamhurwitz** [comment]
I work at Microsoft

**Comment by BryanLa** [comment]
Working with @adamhurwitz and @bruceper to redirect to private repo

**Comment by BrucePerlerMS** [comment]
Hi Bryan,
I'm totally new to this process, the PR receiving side. How do I know if I've permissions and what do the next steps look like.
Thanks,
Bruce

**Comment by BryanLa** [comment]
Merging per conversations with @BrucePerlerMS

**Comment by BrucePerlerMS** [comment]
Excellent.

**Pull request merged**
