### PR TITLE
remove import replace with var

### PR DESCRIPTION
**Pull request by jschluchter**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jschluchter__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jschluchter : Thanks for your contribution to the Azure documentation! The author, @alancameronwills, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
Thanks Joey!

#sign-off

**Comment by alancameronwills** [comment]
@ggailey777 please accept.

**Pull request merged**
