### PR TITLE
it doesn't work that way

### PR DESCRIPTION
**Pull request by 4c74356b41**
just tested and can confirm it doesn't work like that.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @davidmu1, has been notified to review your proposed change.

**Comment by davidmu1** [comment]
@4c74356b41: Thank you for providing feedback. Unfortunately, I am unable to reproduce the issue that you describe. You might check to make sure you are using the current version of PowerShell. I would be happy to work with you more on this, if you haven't resolved the issue.

**Comment by davidmu1** [comment]
@4c74356b41: Thank you again for caring about the quality of the documentation. @tysonn: The procedure in the article works as is. Please close the PR.

**Pull request closed without merging**
