### PR TITLE
Fix bad links to using custom scripts with ARM

### PR DESCRIPTION
**Pull request by ninlar**
Fixed two bad links in the docs.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ninlar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@kundanap - Kundana, could you review the proposed updates in this PR?

**Comment by tysonn** [comment]
@squillace & @cynthn - pull request for VMs in public repo

**Comment by tysonn** [comment]
@ninlar - We're refactoring the vm content in a private branch, this should be resolved there already. Thanks for the correction, though.

**Pull request closed without merging**
