### PR TITLE
Update backup-dpm-automation.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos and bugs in text and code.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@AnuragMehrotra - Please review this public repo pull request

**Comment by Jim-Parker** [comment]
@markgalioto - adding Mark, as he was also working on this article.

**Comment by markgalioto** [comment]
@alexandair - Thank you for your feedback. A recent update I made to this article has caused your feedback to appear as merge conflicts. Many of your update requests were incorporated in the previous pull request, but I will make sure all of your updates are added to the article.

**Comment by Jim-Parker** [comment]
@alexandair - do you have any concerns about us closing this PR per Mark's answer? Thanks.

**Comment by alexandair** [comment]
It's a shame when I invest time in a lots of changes and a PR is not merged, but that's how things work sometime. Close it, please.

**Comment by Jim-Parker** [comment]
Leave a comment

**Pull request closed without merging**
