### PR TITLE
frequencey spelled wrong

### PR DESCRIPTION
**Pull request by swigerb**
frequencey spelled wrong and corrected to frequency in SplitOn and Debatching section

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@swigerb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@swigerb : Thanks for your contribution to the Azure documentation! The author, @jeffhollan, has been notified to review your proposed change.

**Comment by jeffhollan** [comment]
Thanks @swigerb for the contribution. @KatieCummings can you approve/merge?

**Comment by jeffhollan** [comment]
#sign-off

**Pull request merged**
