### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by ErikCL**
There were several typos related to missing spaces in variable and method declarations.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ErikCL__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by sethmanheim** [comment]
Hi @ErikCL, thanks for catching these; they happened during the conversion from MSDN to Markdown. We appreciate the contribution! @tysonn, OK to merge.

**Comment by ErikCL** [comment]
@sethmanheim sure thing. I'm glad I could help. 

FYI: There were some other formatting problems with the code blocks on the lower half of that page that were probably due to another conversion glitch. I spent a little bit of time trying to fix them unsuccessfully as well. If they haven't been fixed by someone else you might want to try to fix them too. There is probably a hidden character or something breaking the markdown, but I couldn't figure it out.

**Comment by sethmanheim** [comment]
@ErikCL Thanks Erik, I definitely see the formatting issues you mentioned. I'll fix them ASAP, and thanks again!

**Comment by sethmanheim** [comment]
@tysonn You can close this pull request if you want, because I incorporated Erik's changes into a larger PR that also addressed his follow-up feedback. Thanks!

**Pull request merged**
