### PR TITLE
Resource groups are not what "we" call applications

### PR DESCRIPTION
**Pull request by RhysC**
Having spoken to a few other readers of this article we have all been confused by the same thing. Nowhere in here is an application deployed. We are PROVISIONING resources so they are ready to receive the resources implementation that make up and application.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RhysC__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
@RhysC - thanks for submitting this change.

**Comment by tfitzmac** [comment]
@ggailey777 - this PR in azure-content can be merged.

**Comment by ggailey777** [comment]
@RhysC  Thanks for your contribution to the Azure documentation. We appreciate your help improving the quality of our topics.

**Comment by RhysC** [comment]
No dramas. Thanks for allowing feedback!

**Pull request merged**
