### PR TITLE
Update machine-learning-what-is-machine-learning.md

### PR DESCRIPTION
**Pull request by jabhij**
machine learning explanation in the most simple world using real life reference examples like google search queries, social media interaction.
This definition will help beginners or even a person from non-computer science or related background in getting the theme of machine learning.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jabhij__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@jabhij 
Thank you for this contribution. I'll consider your recommendations and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@jabhij 
Thanks again. I'll incorporate your ideas into this article, but I'm unable to take this PR as is.

**Comment by jabhij** [comment]
Okay, no problem. Thanks for writing back.


On Thu, May 12, 2016 at 9:52 PM, C.J. Gronlund <notifications@github.com>
wrote:

> Closed #6499 <https://github.com/Azure/azure-content/pull/6499>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-content/pull/6499#event-658829631>
>



-- 



*Regards,Abhishek :) <https://twitter.com/@jabhij>*

*Twitter- @jabhij <https://twitter.com/@jabhij>*
*Let Us Tweak* <http://www.letustweak.com>

* C# Corner- Abhishek Jaiswal
<http://www.c-sharpcorner.com/authors/2072a9/abhishek-jaiswal.aspx>*

**Pull request closed without merging**
