### PR TITLE
Update data-factory-scheduling-and-execution.md

### PR DESCRIPTION
**Pull request by hirenshahms**
Update definition of activity window.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hirenshahms__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hirens). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@spelluru 
Please review and approve/disapprove with a comment here. Thanks.

**Comment by spelluru** [comment]
Yes. Please go ahead and approve. Hiren is an ADF PM. Thanks, Sreedhar

**Comment by rmca14** [comment]
@hirenshahms 
Hiren, can you insert your name into your GitHub profile so we can identify you in the future? Thanks, Profile guidance is https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

**Pull request merged**
