### PR TITLE
Update storage-concurrency.md

### PR DESCRIPTION
**Pull request by jasonnewyork**
Reviewed disqus comments (none) and wastore comments and guide is still up to date.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jasonnewyork__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jahogg). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@jasonnewyork Jason, please submit this update through the private repo

**Comment by jasonnewyork** [comment]
I thought I did? I added -pr to the name didn't I?

Sent from my Windows Phone
________________________________

**Comment by Jim-Parker** [comment]
@jasonnewyork Jason, at the top of the PR you can see that it's in azure-content (the public repo).

**Comment by tysonn** [comment]
Article updated in another PR. CLosing.

**Pull request closed without merging**
