### PR TITLE
Update active-directory-single-sign-on-protocol-reference.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed description.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@priyamohanram - Please review this pull request in the public repo

**Comment by priyamohanram** [comment]
@alexandair: Thank you for your contribution!

**Comment by priyamohanram** [comment]
@BryanLa: Can you please merge this PR?

**Pull request merged**
