### PR TITLE
Minor corrections to Step 9.20 and 9.22

### PR DESCRIPTION
**Pull request by venkatveeramanidaasan**
Corrected it to remove parameter selection to set the activity label.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@venkatveeramanidaasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@venkatveeramanidaasan : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@venkatveeramanidaasan thank you for your time and contribution to this article.  I have reviewed your edits and am fine with the proposed changes.

**Comment by MGoedtel** [comment]
#sign-off

**Pull request merged**
