### PR TITLE
Update application-gateway-create-url-route-arm-ps.md

### PR DESCRIPTION
**Pull request by ingmar79**
Videopathrule used the wong poolsettings

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ingmar79__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial Could you please review this proposed update in the public repo from @ingmar79?

**Comment by jimdial** [comment]
#sign-off

It's a good catch, please accept.

**Comment by tysonn** [comment]
@ingmar79 - Thanks!

**Pull request merged**
