### PR TITLE
[HackaDoc] Adding "Custom Activity Fails" to Data Factory Troubleshoot

### PR DESCRIPTION
**Pull request by JasonWHowell**
[HackADoc] Adding new section called "Problem: Custom Activity Fails" to Data Factory Troubleshooting page. ~Jason

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JasonWHowell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@JasonWHowell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by JasonWHowell** [comment]
[HackADoc] Adding new section called "Problem: Custom Activity Fails" to Data Factory Troubleshooting page. Fixing some formatting as well. ~Jason

**Comment by azurecla** [comment]
Hi __@JasonWHowell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by mollybostic** [comment]
@JasonWHowell, can you ping me on Lync? I need to get your Microsoft alias before accepting the pull request.

**Pull request merged**
