### PR TITLE
ASB TTL is incorrect

### PR DESCRIPTION
**Pull request by SeanFeldman**
It's not unlimited, but constrained to TimeSpan.Max.
Causes readers some confusion: http://stackoverflow.com/questions/38610392/how-to-set-message-time-to-live-unlimited-in-azure-service-bus-queue/38614239

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SeanFeldman : Thanks for your contribution to the Azure documentation! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@SeanFeldman Thanks for submitting the clarification Sean, we'll get this added right away. #sign-off

**Comment by v-anpasi** [comment]
@tysonn Please merge.

**Pull request merged**
