### PR TITLE
Update site-recovery-automate-mobility-service-install.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @krnese, has been notified to review your proposed change.

**Comment by krnese** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@krnese - Hi Kristian, please fix this merge conflict. Thanks, Katie
#hold-off

**Comment by ktoliver** [comment]
@alexandair - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/site-recovery/site-recovery-automate-mobility-service-install](https://docs.microsoft.com/en-us/azure/site-recovery/site-recovery-automate-mobility-service-install). Thanks for your understanding.  (FYI @krnese)

**Pull request closed without merging**
