### PR TITLE
Update virtual-machines-linux-classic-diagnostic-extension.md

### PR DESCRIPTION
**Pull request by hosungsmsft**
The way that configures Linux Azure Diagnostic extension has changed and all configuration properties except the customer credential (storageAccountName and storageAccountKey) must now be entered in the PublicConfig.json, so this change in documentation is necessary and urgent to minimize further confusion.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hosungsmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hoson). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hosungsmsft** [comment]
@tysonn @curtand Could you please help reviewing this PR, or redirect this to the right person? Sorry for a random request and thanks much in advance for your help.

**Comment by tysonn** [comment]
@NingKuang - Could you please review this update from @hosungsmsft in your article?

**Comment by hosungsmsft** [comment]
I resubmitted the same PR on the azure-content-pr repo, so closing this here.

**Pull request closed without merging**
