### PR TITLE
unlink missing

### PR DESCRIPTION
**Pull request by victorar**
Indicating that you must unlink the virtual network from the ER ckt (the word unlink is missing).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@victorar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (victorar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Could you review this public PR from @victorar?

**Comment by tysonn** [comment]
@cherylmc - Second notice, please review

**Comment by cherylmc** [comment]
Thanks @victorar. Good catch! @Tyson, can you please merge this in?

**Pull request merged**
