### PR TITLE
Updating yum.repos.d path that is wrong in the article

### PR DESCRIPTION
**Pull request by mabicca**
Correcting a small typo in the path for yum.repos.d folder in Oracle Linux 6 and 7.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mabicca__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@SuperScottz - Could you please review this public repo contribution?

**Comment by cynthn** [comment]
@tysonn I looked at this and the corrected path looks fine. I think it can be merged.

**Comment by tysonn** [comment]
@cynthn - Please resolve merge conflict to unblock...

**Comment by cynthn** [comment]
@tysonn I pulled this change into the private branch and fixed the merge conflicts #26787. @mabicca thank you for finding and fixing that bug!

**Pull request closed without merging**
