### PR TITLE
Update stream-analytics-use-reference-data.md

### PR DESCRIPTION
**Pull request by toddkitta**
Added reference data file size limit. Found metric here: https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-define-inputs/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@toddkitta__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@toddkitta 
Thank you for your contribution! I'm forwarding this to the author for review and will get back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@jeffstokes72 

Please review this contribution, and let me know whether to accept as is or whether you want to incorporate another way. Thanks!

**Comment by jeffstokes72** [comment]
This is a good find. We document this in our limits doc for Azure services and MSDN but not here. Worth the edit I think. Thanks @toddkitta !

**Comment by toddkitta** [comment]
👍🏻

**Comment by jeffstokes72** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@toddkitta @jeffstokes72 
Thanks, guys!

**Pull request closed without merging**
