### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by dvdsmpsn**
^ end_sesssion_endpoint^ end_session_endpoint

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dvdsmpsn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@dvdsmpsn : Thanks for your contribution to the Azure documentation! The author, @dstrockis, has been notified to review your proposed change.

**Comment by dstrockis** [comment]
Dup of https://github.com/Azure/azure-content/pull/6993

**Comment by BryanLa** [comment]
Closing, as this is resolved in #6993

**Pull request closed without merging**
