### PR TITLE
Only support latest Safari

### PR DESCRIPTION
**Pull request by flanakin**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@flanakin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (micflan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by davidwrede** [comment]
@flanakin, I just accepted a PR with some changes in supported browsers. Can you check the docs  later this afternoon to see if we still need this PR?

Thanks,
Dave

**Comment by ggailey777** [comment]
@flanakin this PR has been here for a while waiting for a response, and now there are conflicts. If you don't need this PR anymore please close it, otherwise please resolve the merge conflicts.

**Comment by tysonn** [comment]
@flanakin - Closing due to unresolved merge conflicts.

**Pull request closed without merging**
