### PR TITLE
Updated SSPK licensee list

### PR DESCRIPTION
**Pull request by xpouyat**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@xpouyat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (xpouyat). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@xpouyat : Thanks for your contribution to the Azure documentation! The author, @xpouyat,vsood, has been notified to review your proposed change.

**Comment by azurecla** [comment]
Hi __@xpouyat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by xpouyat** [comment]
#sign-off

**Pull request closed without merging**
