### PR TITLE
Move <variable> tag to be child of Environment

### PR DESCRIPTION
**Pull request by qwergram**
Fixing a quick typo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@qwergram__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Thraka** [comment]
#sign-off

**Comment by PRmerger** [comment]
@qwergram : Thanks for your contribution to the Azure documentation! The author, @thraka, has been notified to review your proposed change.

**Comment by Thraka** [comment]
@KatieCumming This is good.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by Thraka** [comment]
#sign-off

**Comment by Thraka** [comment]
@Ja-Dunn

**Pull request merged**
