### PR TITLE
Fixed typo in sql-database-point-in-time-restore-portal.md

### PR DESCRIPTION
**Pull request by nbeni**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nbeni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@nbeni : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
Hi @nbeni @stevestein was in the process of making additional updates to this article when your proposed changes came across. Thank you for the contribution though - we deeply appreciate it!

**Comment by cjgronlund** [comment]
@nbeni 
Thanks again for your contribution. I'll close this PR, as the article already has updates.

**Pull request closed without merging**
