### PR TITLE
Update cortana-analytics-technical-guide-demand-forecast.md

### PR DESCRIPTION
**Pull request by mq2004**
fix a typo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mq2004__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (inqiu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mq2004 : Thanks for your contribution to the Azure documentation! The author, @yijichen, has been notified to review your proposed change.

**Comment by yijichen** [comment]
#sign-off

**Comment by yijichen** [comment]
@mq2004 I have already signed off the changes. It will take few days for Azure Content team to merge this to the master branch. Once that is done, the changes will show up on the page.

**Comment by Ja-Dunn** [comment]
@yijichen - Hello, actually the original is correct. The subject, "messages," is plural, so the verb must be "appear" for correct subject-verb agreement.

@mq2004 - Min, thanks very much for your contribution, but we will close this request if it is alright with you. Please confirm.

**Comment by mq2004** [comment]
Thank James, but my name is still not showing up yet.

**Comment by yijichen** [comment]
@Ja-Dunn  Thanks for the correction. I think it's fine to close this request.

**Pull request closed without merging**
