### PR TITLE
Discourage NSGs on GatewaySubnet subnets

### PR DESCRIPTION
**Pull request by thenewwazoo**
Include a note from the NSG overview about inapplicability to GatewaySubnet subnets

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thenewwazoo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Could you please review this proposed update from @thenewwazoo in the public repo?

**Comment by tysonn** [comment]
@cherylmc - Second notice, please review

**Comment by cherylmc** [comment]
Hi! I made a small change to the wording and patched this. If that looks OK, it's fine to merge this in.

**Comment by thenewwazoo** [comment]
lgtm

**Comment by cherylmc** [comment]
Hi @thenewwazoo -I've pulled in the change from your branch and added it to a PR that was just merged in. So we're good to go! Thanks for brining this to our attention. @tysonn - the other PR was just merged in, so it's OK to close this one.

**Pull request closed without merging**
