### PR TITLE
This file doesn't exist any more - new version released.

### PR DESCRIPTION
**Pull request by Yonisha**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Yonisha__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@alancameronwills can you please verify? Thanks.

**Comment by alancameronwills** [comment]
This is fine, thanks. Please pull, Glenn.

**Comment by ggailey777** [comment]
@yonisha Thanks for your contribution to Azure docs. We appreciate it.

**Pull request merged**
