### PR TITLE
Update app-service-mobile-offline-data-sync.md

### PR DESCRIPTION
**Pull request by migig**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@migig__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@migig : Thanks for your contribution to the Azure documentation! The author, @wesmc7777, has been notified to review your proposed change.

**Comment by lindydonna** [comment]
Unfortunately, this edit can't be accepted for this article, because this query name restriction only applies on the .NET managed client. (For instance, on native iOS, any string length that is supported by Core Data is allowed.) To document query name in this article, we'd either have to enumerate all of the query ID restrictions for all clients, or better yet, include this content in the client how-to documentation. 

For the .NET client SDK, it doesn't look like there is a section that goes into the specifics of offline sync currently (https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-how-to-use-client-library/). You could either contribute some content there, or we will just make an note to add documentation on query names once there is specific offline sync content in that article.

**Comment by wesmc7777** [comment]
#please-close

**Comment by migig** [comment]
Okay makes sense!

**Pull request closed without merging**
