### PR TITLE
Fixing wording.

### PR DESCRIPTION
**Pull request by AndrejsAnt**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndrejsAnt__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anant). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AndrejsAnt : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by stevestein** [comment]
@AndrejsAnt - Andrey, you should use the private repo for updates.
@tysonn - this PR is ready to merge.
#sign-off

**Comment by Saisang** [comment]
@tysonn please merge this PR

**Pull request merged**
