### PR TITLE
Fix URL

### PR DESCRIPTION
**Pull request by yamatoya**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yamatoya__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@yamatoya Thank you very much for your contribution!  I have sent the change to the author for approval.

**Comment by telmosampaio** [comment]
I approve this PR.

**Comment by telmosampaio** [comment]
Thanks for spotting this! However, due to how our articles are [published there are a few things that we still need in the links, and we do not require the .md extension. I will close this PR and fix the links! Thanks again!

**Comment by telmosampaio** [comment]
Please close this PR.

**Pull request closed without merging**
