### PR TITLE
Update cloud-services-guestos-update-matrix.md

### PR DESCRIPTION
**Pull request by raiye**
Added entry for August

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@raiye__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (raiye). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@raiye__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (raiye). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@raiye : Thanks for your contribution to the Azure documentation! The author, @yuemlu, has been notified to review your proposed change.

**Comment by yuemlu** [comment]
@raiye 
Two things
1. The August Release would not start after Second Tuesday of the month. The release date would not start until Second Tuesday of the month plus 30 days.
2. The release date of July Guest OS and projected release date of August Guest OS in the tables need to be updated as well.

**Comment by raiye** [comment]
Hi Yuemin,
Here is the link for my changes:
https://github.com/raiye/azure-content/blob/38ce1750cfca5f7dcbf1a59abfac394b4cbfec69/articles/cloud-services/cloud-services-guestos-update-matrix.md
Please let me know if I need to change anything. Thanks for helping me get started!!
Best,
Rashmi Iyer

**Comment by raiye** [comment]
https://github.com/raiye/azure-content/blob/7df032f05d452ab42cb9cf1de5d33c465230fce2/articles/cloud-services/cloud-services-guestos-update-matrix.md
Updated link for this month.

**Comment by yuemlu** [comment]
#sign-off

**Comment by yuemlu** [comment]
@PRmerger  How could I transfer the ownership of this page to Rashmi so that she doesn't need my approval for merging the pull request?

**Comment by tysonn** [comment]
Update the author after this is merged, using the private repo. Also, please resolve the merge conflict - that is blocking the merge.

**Comment by tysonn** [comment]
#hold-off

**Pull request closed without merging**
