### PR TITLE
Updated the number of VM's

### PR DESCRIPTION
**Pull request by techmike2kx**
the doc stated that 1 to 20 VM's are supported in one Storage Account, it should be 40 (or did something happen with the IOPS). this should be in sync anyway with https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#storage-limits .

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@techmike2kx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@techmike2kx : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by Ja-Dunn** [comment]
@MikeWasson - Hi Mike, could you review this public PR please? Looks like the include file it refers to may be yours. Thanks!

**Comment by MikeWasson** [comment]
Thanks, @techmike2kx. The 40 limit is actually for Standard storage disks. We're recommending Premium. 

If I remember, 20 was an estimate based on the IOPS limit. I'm going to update the article to point to [this doc](https://azure.microsoft.com/en-us/documentation/articles/storage-premium-storage) and the Storage limits doc, which give more comprehensive information. I'll open a separate PR for that -- but thanks for pointing this out.

**Comment by techmike2kx** [comment]
ah, oops, didn't notice about the premium storage somehow, so we both were right in the end ;-). but maybe indeed it wouldn't be bad to mention it as you said. Thanks for looking at it!

**Comment by MikeWasson** [comment]
#please-close

**Pull request closed without merging**
