### PR TITLE
Update sql-database-faq.md

### PR DESCRIPTION
**Pull request by pehteh**
Update the frequency of change for performance tier and adjustment to pool (update SLO frequency).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pehteh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pehteh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jeffgoll** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@pehteh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pehteh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
#sign-off

**Pull request merged**
