### PR TITLE
Add math functions description.

### PR DESCRIPTION
**Pull request by chidmdxx**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
Just to maintain alphabetical order for the functions, I will re-submit these changes in my own PR.

**Comment by tfitzmac** [comment]
Thanks for providing this content. I have added it through another PR. It should go live during next publication.

**Comment by jimbe** [comment]
Closing per tfitzmac.

**Pull request closed without merging**
