### PR TITLE
Fixed broken link for Built-in-roles

### PR DESCRIPTION
**Pull request by rahulpnath**
The link to 'Built-in-roles' is broken as the identifier specified is missing '-'.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rahulpnath__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@rahulpnath__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Hi @rahulpnath - thanks for your contribution! Unfortunately, we have a merge conflict on this one. We can either close the PR, and you can apply to a new copy, or you can fix the merge conflict. Either way is fine, just let me know...  thanks!

**Comment by rahulpnath** [comment]
@BryanLa Looks like the broken link is fixed after the latest changes and we are good without this pull request.

**Comment by BryanLa** [comment]
Perfect, thanks @rahulpnath !

**Pull request closed without merging**
