### PR TITLE
Update backup-azure-vms-automation.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@markgalioto - Please review this proposed update from @alexandair in the public repo

**Comment by alexandair** [comment]
@tysonn any follow up on this PR?

**Comment by tysonn** [comment]
@markgalioto - Mark, can you please respond to @alexandair ?

**Comment by markgalioto** [comment]
@alexandair - Thank you for submitting the updates! I am almost finished with an extensive overhaul of this article. I have added your updates to the next version, which should be coming out very soon. Again thank you for taking the time to reply.

**Comment by Jim-Parker** [comment]
@alexandair - are you okay with me closing this PR based on Mark's reply? Thanks.

**Comment by alexandair** [comment]
Sure.

**Pull request closed without merging**
