### PR TITLE
Added clarity around same prefix advertising

### PR DESCRIPTION
**Pull request by omartin2010**
Added an example for clarity.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@yushwang Hi Yu-Shun Please review the updates to the include file in this pull request. The include file appears in some of your content. Thanks.

**Comment by yushwang** [comment]
#sign-off

Thanks!

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by yushwang** [comment]
@cherylmc - please approve the request (I am not the author :-))

**Comment by cherylmc** [comment]
Will do! #sign-off

**Pull request merged**
