### PR TITLE
Check if same or newer Framework is installed and update to net462

### PR DESCRIPTION
**Pull request by jnyrup**
If a newer Framework is already installed, I would guess the intended behaviour is not to run the installer.

Based on advice from https://msdn.microsoft.com/en-us/library/ee942965%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396#chaining_custom

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jnyrup__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jnyrup : Thanks for your contribution to the Azure documentation! The author, @thraka, has been notified to review your proposed change.

**Comment by Thraka** [comment]
Hi @jnyrup 

I didn't write this script originally and the person who did moved on to a different job.  Did you run into a specific problem which caused you to change the script? As I would understand it, none of these newer .NET frameworks would be installed by default anyway. Since you are the one putting the script into the startup tasks, you know what .NET you're installing right?

**Comment by jnyrup** [comment]
Hi @Thraka 

Initially I modified the script to support installation of .NET Framework 4.6.2.
I then found out that the release value in regedit differs from my local Windows 10 and Server 2012 on the Azure role. That's why I added the greater-than-or-equal check.

I have no idea how the upcoming Server 2016 will behave, but if it follows Windows 10 numbering for .NEt Frameworks, my changes should make it easier for the script to work on both server 2012 and 2016. (For some future release of .NET Framework that is not installed by default on any of them).

True, I know what .NET I'm trying to install, but it's easy to forget when e.g. upgrading to a newer osFamily ;)

**Comment by Thraka** [comment]
Gotcha :smile: 

Are you saying that you've discovered that the release value in the registry may differ from OS to OS even though it is the same framework?

**Comment by jnyrup** [comment]
Yes.

The release numbers are documented on 
 https://msdn.microsoft.com/en-us/library/ee942965%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396#chaining_custom

**Comment by Thraka** [comment]
Awesome! Validate the commands. Thanks a bunch for the contribution!

**Comment by Thraka** [comment]
#sign-off

**Comment by Thraka** [comment]
@Ja-Dunn

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
