### PR TITLE
Update iot-hub-gateway-sdk-physical-device.md

### PR DESCRIPTION
**Pull request by eissi**
Hi, in the sample of yours, it uses HTTP.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@eissi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@eissi : Thanks for your contribution to the Azure documentation! The author, @chipalost, has been notified to review your proposed change.

**Comment by dominicbetts** [comment]
#sign-off 

Hi @eissi, thanks for the update. Well spotted!

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
