### PR TITLE
Update backup-azure-backup-faq.md

### PR DESCRIPTION
**Pull request by aashishr**
corrections to the faq article.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aashishr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (aashishr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by aashishr** [comment]
I didn't quite get what I need to do to resolve the merge conflict.

**Comment by azurecla** [comment]
Hi __@aashishr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (aashishr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@aashishr You can either resolve the merge conflicts on this pull request or you can close this and open a new one with the changes.  Please feel free to message me if you need help.

**Pull request closed without merging**
