### PR TITLE
the $ServicePrincipalDisplayName does not exist - changing to $Applic…

### PR DESCRIPTION
**Pull request by SubZer0MS**
…ationDisplayName

the $ServicePrincipalDisplayName does not exist - changing to $ApplicationDisplayName

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SubZer0MS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@MGoedtel Matt, can you please review and let us know if this can be merged?

**Comment by MGoedtel** [comment]
Approving edit.  Thanks Mihai for bringing that to my attention.

**Comment by SubZer0MS** [comment]
with pleasure :D I used the script for a customer and noticed this. cool article btw!

**Pull request merged**
