### PR TITLE
Added max running time for free tier

### PR DESCRIPTION
**Pull request by ealsur**
Based on Eugene's answer at https://social.msdn.microsoft.com/Forums/en-US/2b2082d5-75a0-4033-b1b4-49b6092f5396/not-all-documents-being-indexed?forum=azuresearch

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ealsur__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@HeidiSteen 
Please review and approve/disapprove this PR with a comment. Thanks.

**Comment by HeidiSteen** [comment]
#sign-off

**Comment by HeidiSteen** [comment]
#sign-off

**Pull request merged**
