### PR TITLE
Update hdinsight-analyze-twitter-data.md

### PR DESCRIPTION
**Pull request by dem108**
Found some obvious errors in the PowerShell code, for example, the ones not using the right parameters.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dem108__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@dem108 
Thanks again for corrections. I'll pass these by the author. 
--Carolyn

**Comment by cjgronlund** [comment]
@mumian 
Jonathan, please check these corrections. Thanks!

**Comment by mumian** [comment]
@cjgronlund 

Please change "-ClusterCredential" to "-HttpCredential" in the following line:
Get-AzureRmHDInsightJobOutput -ClusterName $clusterName -JobId $jobID -DefaultContainer $defaultBlobContainerName -DefaultStorageAccountName $defaultStorageAccountName -DefaultStorageAccountKey $defaultStorageAccountKey -ClusterCredential $httpCredential 

I don't have the push access.

**Comment by mumian** [comment]
@dem108 

Please change "-ClusterCredential" to "-HttpCredential" in the following line, and submit the PR again:
 Get-AzureRmHDInsightJobOutput -ClusterName $clusterName -JobId $jobID -DefaultContainer $defaultBlobContainerName -DefaultStorageAccountName $defaultStorageAccountName -DefaultStorageAccountKey $defaultStorageAccountKey -ClusterCredential $httpCredential

**Pull request merged**
