### PR TITLE
Update automation-schedules.md

### PR DESCRIPTION
**Pull request by kelillus**
Reference to weekly and monthly recurring options

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kelillus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@kelillus : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@kelillus thank you for your contribution to the article.  I have reviewed proposed change and accept.

**Comment by MGoedtel** [comment]
#sign-off

**Pull request merged**
