### PR TITLE
Updated service-bus-brokered-tutorial-rest.md

### PR DESCRIPTION
**Pull request by Davesmall28**
Updated formatting of some of the code snippets to move the method definition out of the comment line onto its own line.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Davesmall28__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sethmanheim - Seth, could you please review this contribution?

**Comment by sethmanheim** [comment]
@Davesmall28 Thank you for catching that! We'll get it fixed right away. 

@tysonn OK to merge.

**Comment by Davesmall28** [comment]
No problem.

**Pull request merged**
