### PR TITLE
refresh.

### PR DESCRIPTION
**Pull request by h0n**
@mimig1

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@h0n__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hawong). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@h0n : Thanks for your contribution to the Azure documentation! The author, @h0n, has been notified to review your proposed change.

**Comment by mimig1** [comment]
@h0n - you made this in the public repo, so I think it'll get auto closed. Please resubmit in the private repo.

**Comment by JennieHubbard** [comment]
@mimig1 @h0n Han can we close this?

**Comment by mimig1** [comment]
@jenniehubbard Yes, I will port it to private tomorrow.

**Comment by ktoliver** [comment]
@h0n - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/documentdb/documentdb-use-cases](https://docs.microsoft.com/en-us/azure/documentdb/documentdb-use-cases). Thanks for your understanding.

**Comment by mimig1** [comment]
#please-close The doc has been updated in the new site - @h0n is fine with this.

**Pull request closed without merging**
