### PR TITLE
Update instructions for cloning from GitHub

### PR DESCRIPTION
**Pull request by pshelton-skype**
Attempting to clone ADAL for Android doesn't work, so update to the HTTPS URL:

```
C:\src\go>git clone git@github.com:AzureAD/azure-activedirectory-library-for-android.git

  Cloning into 'azure-activedirectory-library-for-android'...
  The authenticity of host 'github.com (192.30.252.131)' can't be established.
  RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
  Are you sure you want to continue connecting (yes/no)? yes
  Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights and the repository exists.
```
```
C:\src\go>git clone git@github.com:AzureAD/azure-activedirectory-library-for-android.git

  Cloning into 'azure-activedirectory-library-for-android'...
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights and the repository exists.
```
```
C:\src\go>git clone https://github.com/AzureAD/azure-activedirectory-library-for-android.git

  Cloning into 'azure-activedirectory-library-for-android'...
  remote: Counting objects: 12268, done.
  remote: Total 12268 (delta 0), reused 0 (delta 0), pack-reused 12268
  Receiving objects: 100% (12268/12268), 8.61 MiB | 2.32 MiB/s, done.
  Resolving deltas: 100% (5693/5693), done.
  Checking connectivity... done.
```

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pshelton-skype__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by brandwe** [comment]
Actually, can I ask you to fix this? Agree with https:// is fine but you are linking to the actual repo instead of the sample. Sample should be: 

`https://github.com/Azure-Samples/active-directory-android.git` correct?

**Comment by BryanLa** [comment]
Hi @pshelton-skype - your PR correction is for the step on cloning the ["Integrating an android app with Azure AD" sample repo](https://github.com/AzureADSamples/NativeClient-Android), ie:

`$ git clone git@github.com:AzureADSamples/NativeClient-Android.git`

The article is actually correct, as the "org" segment of the URL must be **AzureADSamples** (not AzureAD). 

Looking at your error messages though, it looks like they are specific to cloning the [SDK source](https://github.com/AzureAD/azure-activedirectory-library-for-android), which *is* in the Azure AD org. I believe the problem is that you were attempting to clone the SDK source from a URL that had AzureADSamples as the org instead of AzureAD:

`git clone git@github.com:AzureADSamples/azure-activedirectory-library-for-android.git`

so you just need to modify, removing the "Samples" portion, ie: 

`git clone git@github.com:AzureAD/azure-activedirectory-library-for-android.git`

Let me know if that's the case and we can decide if the PR needs to be close, or we're misunderstanding each other. Also, per @brandwe's comment, we have migrated the samples to an entirely new org as well (GitHub.com/azure-samples); for now the old URLs will redirect, but we will be revising the articles over time to indicate this as well. Also note that you can use the [HTTPS form of the repo remote](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended) for cloning as well, if you prefer.

Thanks!

**Comment by BryanLa** [comment]
Closing for now, but we can reopen later after you have a chance to review.

**Pull request closed without merging**
