### PR TITLE
github personal access token URL has changed

### PR DESCRIPTION
**Pull request by johnkemnetz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@johnkemnetz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johnkem). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@johnkemnetz : Thanks for your contribution to the Azure documentation! The author, @tysonn, has been notified to review your proposed change.

**Comment by curtand** [comment]
@johnkemnetz Thank you for your contribution!

When I paste your link URL into a browser, it takes me to the OAuth Applications page. It LOOKS like what you wanted was https://github.com/settings/tokens, which lands you on the Personal Access Tokens page. Please retest and confirm.

@tysonn

**Comment by tysonn** [comment]
@johnkemnetz - Thanks for the fix!

**Pull request merged**
