### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**
actually I'm not sure if it should be like this.
at first I thought it should be "a N-tier"? but after some googling it seems that everyone uses "an N-tier". I'm confused ;)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @mikewasson, has been notified to review your proposed change.

**Comment by MikeWasson** [comment]
"An N" sounds OK to me. (Or is it NaN? :smile_cat: )

#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by 4c74356b41** [comment]
how this is weird, aren't you the author ;)

**Comment by MikeWasson** [comment]
@tysonn  thanks!

**Pull request merged**
