### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @TomArcher, has been notified to review your proposed change.

**Comment by rboucher** [comment]
Thanks for taking the time to fix these typos @4c74356b41.  I'm accepting your changes. - Rob

**Comment by rboucher** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by TomArcher** [comment]
#sign-off

**Pull request merged**
