### PR TITLE
Update virtual-machines-linux-azure-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix various typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @vlivech, has been notified to review your proposed change.

**Comment by vlivech** [comment]
#hold-off under review

**Comment by vlivech** [comment]
hey @alexandair - thank you so much! fantastic work! this doc was pushed out the door far too fast and you have fixed it up nicely.  thanks again!

**Comment by vlivech** [comment]
#sign-off

**Comment by squillace** [comment]
@tysonn can we merge this? Not sure how this should work.

**Comment by tysonn** [comment]
Thanks for pulling me in, it appears the comment automation is cancelling itself out - I suspect there is a bug in how the logic handles a PR that contains both hold off and sign off comments. I manually assigned the ready-to-merge tag and have reported the potential bug.

**Pull request merged**
