### PR TITLE
Added VNET/gateway configuration to the prereqs

### PR DESCRIPTION
**Pull request by jboeshart**
The document references the requirement of having a VNET with a gateway configured, but doesn't list this in the prerequisites nor point to the documentation to do so. Adding this in with a link to the documentation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Cheryl, could you review this proposed update in the public repo from @jboeshart?

**Comment by tysonn** [comment]
@cherylmc - Second notice, please review

**Comment by cherylmc** [comment]
Looks like a good addition to me. Thanks @jboeshart for suggesting it! @tysonn- can you go ahead and merge this in?

**Pull request merged**
