### PR TITLE
New Load with PolyBase document.

### PR DESCRIPTION
**Pull request by sahaj08**
Creating new Polybase document for the Hero scenario.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sahaj08__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sahajs). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by sahaj08** [comment]
#sign-off

**Comment by sahaj08** [comment]
#sign-off

**Comment by rmca14** [comment]
@sahaj08 
Please correct the filename by inserting a hyphen where it's needed. Thanks.

@barbkess

**Comment by sahaj08** [comment]
@rmca14 I have corrected the filename.

**Comment by sahaj08** [comment]
#sign-off

**Comment by sahaj08** [comment]
Closing this pull request and creating one in the new azure-content-pr branch

**Pull request closed without merging**
