### PR TITLE
Update active-directory-b2c-devquickstarts-api-node.md

### PR DESCRIPTION
**Pull request by Jtango18**
Fixed inconsistent port naming in curl example
Fixed heading numbering 18-19-18 -> 18-19-20
Fixed typo causing BearerStrategy issue
Added fs and path requirements per final app
Updated 'Microsoft Azure' to 'Windows Azure'
Added missing comma to config.js section - this was causing an error if copy and pasted

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Jtango18__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by brandwe** [comment]
eep. Unfortunately @Jtango18 the name is now Microsoft Azure and not Windows Azure. Can you make that change back and resubmit? Otherwise it looks great!

**Comment by Jtango18** [comment]
Doh! It must be the code that has it wrong and the tutorial had it right. I'll take a look at that, but I've reversed those changes so it should be good for you to merge now.

**Comment by BryanLa** [comment]
Thanks @Jtango18 and @brandwe !

**Pull request merged**
