### PR TITLE
AzureAutomation RunAs Documentation Updates (jogardn@msft)

### PR DESCRIPTION
**Pull request by jgardner04**
I as working on a project and reviewing the documentation and found these two items I have made changes to.

1. The execution and verification PowerShell scripts contain line breaks without the correct ` character to make copy and paste work correctly.  I added these.
2. To run the Get-AutomationConnecton command the AzureAutomationAuthoringToolkit needs to be installed.  I added this note.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jgardner04__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by MGoedtel** [comment]
Jim and Jonathan,

These changes are accepted and thank you Jonathan for bringing these items to my attention and helping to address them.

**Comment by Jim-Parker** [comment]
Signing off for Matt per his comment above.
#sign-off

**Comment by jgardner04** [comment]
Thank you gentlemen for letting me do so.

**Pull request merged**
