### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
seems reasonable

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by KatieCumming** [comment]
@NarayanAnnamalai - Hi Narayan, please review this change. If it's okay, please update this note format to Markdown. Thanks! Katie
#hold-off

**Comment by carmonmills** [comment]
I reviewed the change and it looks good.  

#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@NarayanAnnamalai Hi Narayan. Please resolve the conflicts to enable a merge. Usually, authors of the files are able to fix merge conflicts using the process here on the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve a local merge conflict yourself.aspx). Thanks.

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by jimdial** [comment]
@4c74356b41 thanks for your contribution. Due to the merge conflict, the changes have been incorporated in this [PR](https://github.com/Azure/azure-content-pr/pull/32589/).

**Comment by jimdial** [comment]
#please-close

**Pull request closed without merging**
