### PR TITLE
Update machine-learning-linear-regression-in-azure.md

### PR DESCRIPTION
**Pull request by KBaroni**
Modified ms.date from 7/14/2015 to 10/14/2015

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@KBaroni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by KBaroni** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@KBaroni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by KBaroni** [comment]
#sign-off

**Pull request closed without merging**
