### PR TITLE
Added clarity around potential UDR routing loops

### PR DESCRIPTION
**Pull request by omartin2010**
Added clarity in form of an Azure.TIP.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @tracsman, has been notified to review your proposed change.

**Comment by tracsman** [comment]
#sign-off

**Comment by tracsman** [comment]
@tysonn  Approved for merge
@omartin2010 Thanks for the update!
 #sign-off

**Comment by Ja-Dunn** [comment]
@tracsman - Hi Jon, just noticed a couple of small things to clean up if it makes sense to you:

--"pointing to VNETLocal is a critical as otherwise"
Delete the word "a"?

--"will fail as they will sent over to the NVA"
Add the word "be"? "...will be sent..."

--"traditional, on-premise, appliances"
Change to "on-premises"?

Thanks!  #hold-off

**Comment by Ja-Dunn** [comment]
@omartin2010 - Hi Olivier, it may be quicker to have you implement the following minor changes to your PR (it's a bit of an involved process to have Jon make changes in your PR). Would you mind? Thanks!
--"pointing to VNETLocal is a critical as otherwise"
Delete the word "a"?
--"will fail as they will sent over to the NVA"
Add the word "be"? "...will be sent..."
--"traditional, on-premise, appliances"
Change to "on-premises"?

**Comment by omartin2010** [comment]
@Ja-Dunn : So James, that should be ok now! Sorry about that!

**Comment by omartin2010** [comment]
@Ja-Dunn : corrected one more thing - so we might want to wait for @tracsman to check it out before since he owns the article.

**Comment by Ja-Dunn** [comment]
@omartin2010 - Excellent, thanks so much, looks good now.
@tracsman - Jon, if you could provide one final review? If it looks good to you, I will merge.

**Comment by tracsman** [comment]
@Ja-Dunn I'm fine with the changes. Please merge.
#sign-off

**Comment by KatieCumming** [comment]
@tracsman - Hi Jon, please make the edits James suggests above. Thanks! Katie

**Pull request merged**
