### PR TITLE
Updating freshness

### PR DESCRIPTION
**Pull request by ryancrawcour**
Updating freshness

### CODE REVIEW

**Comment by ryancrawcour** [comment]
@mimig1

**Comment by mimig1** [comment]
Please address/resolve verbatim bug 5604335.The new feedback (from 9/8) is: "not enough details provided", but I need to track that you've seen it and it's up to you to decide what to do with it. http://sqlbuvsts01:8080/Main/DocumentDB/_workitems#_a=edit&id=5604335&triage=true

**Comment by ryancrawcour** [comment]
Resolved. Not enough details provided to action anything.

**Comment by mimig1** [comment]
#sign-off

**Comment by mimig1** [comment]
@rmca14

**Pull request merged**
