### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**
Gosh, that's a lot ot typos for an article of such importance!

https://msdn.microsoft.com/en-us/library/hh510230.aspx - Always On

You should also check "its" and "it's" in this article, it seems misused a couple of times to me, but I'm not sure, as English is not my native language

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @Rboucher, has been notified to review your proposed change.

**Comment by rboucher** [comment]
Thanks for removing these typos @4c74356b41.  I do appreciate the time you took to do that.  I'll take a look at the use of its and it's.  "Its" is the possessive pronoun and should be used in the same context as "the car's tire ".  "It's" is a contraction and short for "it is".

**Comment by rboucher** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
@rboucher - Rob, can you please resolve the merge conflict? And, update the metadata to match your actual account. The automation is case sensitive (authors="Rboucher" in article)

**Comment by 4c74356b41** [comment]
Hello?

**Comment by rboucher** [comment]
Hi. Still here.  Just need to solve that merge conflict on my side.  Will do that soon.

**Comment by 4c74356b41** [comment]
Thanks!

**Comment by rboucher** [comment]
Hi 4c74356b41.
Because of the size of the article, I'm having a heck of a time with github actually trying to update literally a single character in this pull request. That's blocking me from incorporating your changes.  I think I'm going to have to pull your changes into another pull request of my own and submit them, then report back when it's done.  Is that okay with you?

**Comment by rboucher** [comment]
Hi 4c74356b41.
Because of the size of the article, I'm having a heck of a time with github actually trying to update literally a single character in this pull request. That's blocking me from incorporating your changes.  I think I'm going to have to pull your changes into another pull request of my own and submit them, then report back when it's done.  Is that okay with you?

**Comment by 4c74356b41** [comment]
I'm okay with whatever way you are doing this ;)

**Comment by rboucher** [comment]
Now at https://github.com/Azure/azure-content-pr/pull/28602. That is a private repository so you probably can't view it. I'll follow up when the changes are live.

**Comment by rboucher** [comment]
I was on vacation.  These changes were incorporated 12 days ago and are live now.  Thanks!

**Comment by 4c74356b41** [comment]
if you say so

**Pull request closed without merging**
