### PR TITLE
Remove hardcoded endpoint names in CreateServiceInstanceListeners()

### PR DESCRIPTION
**Pull request by MattKotsenas**
`StatelessService::CreateServiceInstanceListeners()` hardcodes the endpoint name when creating an `OwinCommunicationListener`. This approach has two drawbacks

  1. Implicit coupling between the service and the `ServiceManifest.xml` that can be difficult to detect
  2. Doesn't automatically add new `ServiceInstanceListner`s when new endpoints are added to `ServiceManifest.xml`

This change addresses both issues by querying the `CodePackageActivationContext` for the list of HTTP and HTTPS endpoints and creates a listener for each.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MattKotsenas__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by MattKotsenas** [comment]
Note that the LINQ query looks for both HTTP and HTTPS, and HTTPS endpoints won't work until after #6415.

**Comment by MattKotsenas** [comment]
Also note that this code is also in the new service template that comes as part of the Service Fabric SDK and tools. I can update that code as well, but I don't know where it lives. Any help there is greatly appreciated. Thanks!

**Comment by MattKotsenas** [comment]
I'm proposing this changed based on [this blog post](https://matt.kotsenas.com/posts/https-in-service-fabric-web-api) that walks through adding HTTPS to a Service Fabric Web API.

**Comment by tysonn** [comment]
@vturecek / @seanmck - Could you review this proposed change by @MattKotsenas in the public repository?

**Comment by vturecek** [comment]
@MattKotsenas Great change, I like this. I'll update our sample code as well.
@tysonn Please merge.

**Pull request merged**
