### PR TITLE
Update sql-data-warehouse-get-started-provision.md

### PR DESCRIPTION
**Pull request by lodipalm**
Adding link to sample data loading

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lodipalm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@JennieHubbard 
 Jennie, please review this PR and let me know if I should merge. Thanks.

**Comment by rmca14** [comment]
@barbkess 
FYI

**Comment by JennieHubbard** [comment]
Approved!

**Pull request merged**
