### PR TITLE
node.js developer link not working

### PR DESCRIPTION
**Pull request by seanlarge**
line 196 is a link to a 404...please update =)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seanlarge__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by seanlarge** [comment]
correct link
https://azure.microsoft.com/en-us/develop/nodejs/

**Comment by tysonn** [comment]
@rmcmurray - Robert, could you look at this PR and handle the update?

**Comment by rmcmurray** [comment]
That change looks fine, but I do not have write access to this branch to update the link.

**Comment by rmcmurray** [comment]
I was not able to update the article based on this PR, so I submitted  #6494 to fix the broken link and make a few additional (minor) tweaks.

**Comment by tysonn** [comment]
@seanlarge - Thanks for calling this out! Closing now.

**Pull request closed without merging**
