### PR TITLE
Update virtual-machines-linux-azure-overview.md

### PR DESCRIPTION
**Pull request by jluk**
Updated missing "to", rewording, and a link to SLA.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jluk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (juluk). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@RicksterCDN - Could you please review this update from @jluk and let me know if it can be merged?

**Comment by tysonn** [comment]
@RicksterCDN - Rick, please review public repo contribution (second notice)

**Comment by tysonn** [comment]
@RicksterCDN - Third notice - please review.

**Comment by RicksterCDN** [comment]
Didn't even notice this one. All good here. #Sign-Off

**Pull request merged**
