### PR TITLE
Update vs-storage-aspnet5-getting-started-blobs.md

### PR DESCRIPTION
**Pull request by eerhardt**
Fixing the configuration code so it compiles.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@eerhardt__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by eerhardt** [comment]
I needed to fix the code in the other 2 places it was copied - Queues and Tables.  We will need all 3 commits for this issue to be fixed.

**Comment by azurecla** [comment]
Hi __@eerhardt__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Contributor is a MSFT employee.

**Pull request merged**
