### PR TITLE
Updating to actual Resource Manager cmdlets

### PR DESCRIPTION
**Pull request by kevinhillinger**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kevinhillinger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by kevinhillinger** [comment]
These commands are severely out of date. I'm having to send something to my customer, and we need this updated ASAP

**Comment by BryanLa** [comment]
@kevinhillinger - thanks very much for your contribution! 
@kgremban - can you have a look at this PR? Kevin is a MSFT employee. The PR is currently in merge conflict, so it's probably best if you can review these and decide if they should be rolled into a different/internal PR. LMK and I can close this one after you have a chance to review. Thanks!

**Comment by kevinhillinger** [comment]
@kgremban is there a faster/fast track way  to get these type of changes into the documentation as an MSFT employee? 

...and I don't mind updating my PR if there are conflicts.

**Comment by curtand** [comment]
@kevinhillinger I sent an email pinging @kgremban . Hope this helps!
@bryanla

**Comment by kgremban** [comment]
@BryanLa I reached out to Kevin offline about this. The article he wants to update has been retired. Please close this PR.

**Comment by BryanLa** [comment]
@kgremban Done. Thanks!

**Pull request closed without merging**
