### PR TITLE
Corrected Sample web.config for caching

### PR DESCRIPTION
**Pull request by enterprisebug**
Corrected some whitespaces that have been missing

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@enterprisebug__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@enterprisebug : Thanks for your contribution to the Azure documentation! The author, @steved0x, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@enterprisebug Thank you for your contribution and for catching this. 

@PRMerger these changes are good and are ready to be merged.

**Comment by steved0x** [comment]
#sign-off

**Comment by steved0x** [comment]
@ggailey777 these customer changes are good and are ready to be merged. Thank you.

**Pull request merged**
