### PR TITLE
Changed linus to Linux

### PR DESCRIPTION
**Pull request by microsoftman**
I changed Linus to Linux in the Azure Disk Encryption .md documentation

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@microsoftman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@microsoftman : Thanks for your contribution to the Azure documentation! The author, @YuriDio, has been notified to review your proposed change.

**Comment by YuriDio** [comment]
@microsoftman thanks for your contribution. @PRMerger please merge this change.

**Comment by YuriDio** [comment]
@BryanLa pls merge

**Pull request merged**
