### PR TITLE
A string data is not closed

### PR DESCRIPTION
**Pull request by iwate**
The code highlight is wrong due to a string data is not closed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iwate__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by aliuy** [comment]
ack

**Comment by MonicaRush** [comment]
Merged

**Comment by MonicaRush** [comment]
Thank you very much for your contribution!

**Pull request merged**
