### PR TITLE
Update prerequisites for deploy logic app from VS

### PR DESCRIPTION
**Pull request by derek1ee**
Add Azure PowerShell to prerequisites

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@derek1ee__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@derek1ee : Thanks for your contribution to the Azure documentation! The author, @jeffhollan, has been notified to review your proposed change.

**Comment by jeffhollan** [comment]
Thanks @derek1ee  this looks ready to merge. @PRmerger

**Comment by jeffhollan** [comment]
@KatieCumming can you help merge this?

**Pull request merged**
