### PR TITLE
Adding article to describe how customers can get support from AppInsights development team

### PR DESCRIPTION
**Pull request by AlexBulankou**
We are introducing a new support option for our customers - now they can submit Feedback form on Azure portal, explain their specific scenario and provide contact email address. We are setting a goal to triage and send the first response within 2 business days. @alancameronwills @tommo-ms @jltgit can you please review.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlexBulankou__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (albulank). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by alancameronwills** [comment]
Hi Alex - Please make a couple of changes:

When you have a technical issue that  --> When you have a technical issue with [Visual Studio Application Insights](app-insights-overview.md) that 

AppInsights --> Application Insights

**Comment by AlexBulankou** [comment]
Addressed more offline comments:
* Added indication that we are introducing this new channel as part of preparing for GA
* Removed mention of 2 business days. While our internal SLO will be to respond within 1 business day, we are not offering this with any obligations from us to customers.

**Comment by AlexBulankou** [comment]
@alancameronwills can you please help with referencing this article from the navigation menu? Thanks!

**Comment by alancameronwills** [comment]
#sign-off

**Comment by tysonn** [comment]
Hi - This work needs to happen in the private repository because it needs to pass staging and validation on the private side. You can use the following commands to move it to a private repo branch:

```
git checkout -b AlexBulankou-patch-3 master
git pull https://github.com/AlexBulankou/azure-content.git patch-3
```
Then add, commit, push, and create a PR to master.

Thanks!

**Comment by AlexBulankou** [comment]
Done: https://github.com/AlexBulankou/azure-content/pull/1

**Pull request closed without merging**
