### PR TITLE
Update sql-data-warehouse-overview-workload.md

### PR DESCRIPTION
**Pull request by slaven-s**
Hi,

I added section "Books" and a link to the Big Data Warehousing written by Karthik Ramachandran, Istvan Szededi, and Richard L. Saltzer for Manning Publications. We believe this book is a great resource and all members of community will benefit from this information. If you find this inappropriate, please let me know where I can publish it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@slaven-s__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by slaven-s** [comment]
Thank you very much!Slaven
 


     Datuma 21:45 Utorak, 1. Rujan 2015., Azure Contribution License Agreements <notifications@github.com> je napisao:
   

 Hi @slaven-s, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
 
 This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
 TTYL, AZPRBOT;—

**Comment by rmca14** [comment]
@JennieHubbard 
Please review and approve/disapprove, thanks.
@barbkess 
FYI

**Comment by JennieHubbard** [comment]
#sign-off

**Pull request merged**
