### PR TITLE
Fix wrong variable name in code example

### PR DESCRIPTION
**Pull request by YoungjaeKim**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@YoungjaeKim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@mimig1 
Please verify this PR, and let me know whether to accept it.

**Comment by cjgronlund** [comment]
@YoungjaeKim 
Thank you for your contribution. I've notified the writer for verification, and I'll get right back to you.

**Comment by mimig1** [comment]
@YoungjaeKim Thank you for your contribution. We refactored the code in the sample last week, and at the same time we made the change you suggested. So this PR can be closed, as the sample was fixed in a different PR.

**Comment by YoungjaeKim** [comment]
got it.

**Pull request closed without merging**
