### PR TITLE
Updated Scopes to work with MSA accounts

### PR DESCRIPTION
**Pull request by danieldobalian**
Changed scopes to match what will work with AAD and MSA accounts.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@danieldobalian__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by danieldobalian** [comment]
@brandwe

**Comment by PRmerger** [comment]
@danieldobalian : Thanks for your contribution to the Azure documentation! The author, @brandwe, has been notified to review your proposed change.

**Comment by brandwe** [comment]
#sign-off

**Pull request merged**
