### PR TITLE
Add step for manual build of WA Linux Agent RPM file

### PR DESCRIPTION
**Pull request by animetauren**
At times it is necessary to manually build the RPM file due to security constraints on the clients environment and having an alternative is nice and handy.

### CODE REVIEW

**Comment by tysonn** [comment]
@cynthn  & @squillace - VM pull request

**Comment by azurecla** [comment]
Hi __@animetauren__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Close/reopen to prompt CLA automation

**Comment by tysonn** [comment]
Closing due to refactoring work.

**Pull request closed without merging**
