### PR TITLE
Update media-services-manage-content.md

### PR DESCRIPTION
**Pull request by muttech**
Fixing typo of the word Azure

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@muttech__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@Juliako - Here's a public repo pull request for you to review

**Comment by Juliako** [comment]
#sign-off

**Comment by tysonn** [comment]
@muttech - Thanks for the fix!

**Pull request merged**
