### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by AlexZeitler**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlexZeitler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlexZeitler : Thanks for your contribution to the Azure documentation! The author, @rwike77, has been notified to review your proposed change.

**Comment by rwike77** [comment]
Hi @AlexZeitler, I'm looking through the diff in Files Changed and I'm not seeing any updates.  What changes did you want to make?  Thanks.

**Comment by AlexZeitler** [comment]
@rwike77 This is the proposed change: https://github.com/Azure/azure-content/pull/7239/files?short_path=e8ccc77#diff-e8ccc77f3ff76ed403c0317c6de97355

**Comment by rwike77** [comment]
Thanks, @AlexZeitler, I missed your change earlier.  Update looks good to me.  @tysonn, please go ahead and merge the change.

**Comment by tysonn** [comment]
@rwike77 - Remember to use #sign-off to sign off on public PRs :)

**Pull request merged**
