### PR TITLE
update response_type value for Token Aquisition

### PR DESCRIPTION
**Pull request by benkroeger**
this documentation used "id_token+code", which is not one of the supported values for response_type.
Updated to "id_token%20code" and "id_token code" accordingly

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@benkroeger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@benkroeger - thanks very much for your contribution!
@dstrockis - can you review and LMK your thoughts?

**Comment by BryanLa** [comment]
@dstrockis - any thoughts? Seems reasonable.

**Comment by dstrockis** [comment]
+ should be a fine separator as opposed to space, no? 

There is a bug in this article though, the `response_mode` is incorrect.

**Comment by BryanLa** [comment]
Yes, '+' works, and I believe ADAL injects a '+' ? Looks like [the spec](http://openid.net/specs/openid-connect-core-1_0.html#Authentication) uses a space but this is apparently not mandated?

Looks like we have a merge conflict now, so LMK if you want to make the changes/fix on the internal repo and we can close this one.

**Comment by benkroeger** [comment]
since both work, and space ` ` is in the spec, why not put both in the documentation? Or even better, only document according to the spec while keeping the `+` intact (to not break any existing implementations)

**Comment by dstrockis** [comment]
I like Ben's suggestion to adhere to the spec.  Bryan I'll let you decide if you want to close out this PR b/c of the merge conflicts and open a new one, or fix the conflicts yourself.

**Comment by BryanLa** [comment]
@benkroeger - I've dropped a [PR](https://github.com/benkroeger/azure-content/pull/1) in your fork that will hopefully resolve the merge conflict. Please review/merge when you have a chance, and assuming it fixes this merge conflict we can get this PR merged for you. Thanks again, and thanks for your patience.

**Comment by azurecla** [comment]
Hi __@benkroeger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
