### PR TITLE
Update log-analytics-windows-agents.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed some typos and DSC configuration.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@bandersmsft Bill, can you take a look Aleksandar's suggestions and let us know if the changes can be merged?.

**Comment by bandersmsft** [comment]
Yes, the changes Alexsandar made are fine.

**Comment by Jim-Parker** [comment]
@alexandair Alexandar, thanks for the review and for making those changes. I'll merge them now.

**Pull request merged**
