### PR TITLE
Update resource-group-move-resources.md

### PR DESCRIPTION
**Pull request by alexandair**
Update PowerShell code.

### CODE REVIEW

**Comment by tfitzmac** [comment]
@alexandair - thanks for making this change.

**Comment by tfitzmac** [comment]
@ggailey777 - this PR on azure-content can be merged. I have verified the syntax.

**Comment by ggailey777** [comment]
@alexandair Thanks for your contribution to the Azure documentation. We appreciate your help improving the quality of our topics.

**Comment by alexandair** [comment]
You're welcome. I'm glad you find my contribution helpful.

**Pull request merged**
