### PR TITLE
Update documentdb-create-dbaccount.md

### PR DESCRIPTION
**Pull request by oedenfield**
Updated link for [Consistency levels in DocumentDB]. - I tried to use the ../ path, I believe I got it correct but I might have an error there.  Trying to link to https://azure.microsoft.com/en-us/documentation/articles/documentdb-consistency-levels/.

It was linking to ../articles/azure-portal/resource-group-portal.md (https://azure.microsoft.com/en-us/documentation/articles/resource-group-portal/).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@oedenfield__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@oedenfield : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@AndrewHoh Hi Andrew. Please review the proposed changes. Thanks.

**Comment by mimig1** [comment]
Hi @oedenfield, Thank you for finding and fixing this! Your change is almost correct, you just need to include the documentdb folder in the relative link, so it should look like this(../articles/documentdb/documentdb-consistency-levels.md). Can you make that change and we'll accept the PR? Thanks!

**Comment by oedenfield** [comment]
@mimig1 Thank you for your help.  I believe I've updated the change in the PR.  Please let me know if I've made an error here.  Cheers!

**Comment by mimig1** [comment]
@oedenfield Looks good, thank you! 
@jomolnar I #sign-off, but this will likely cause an error as @andrewhoh is listed as the author, but he is OOF this week. Please merge. Thanks!

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
