### PR TITLE
fix md syntax of configuration quote on ExpressRoute NAT configuration example

### PR DESCRIPTION
**Pull request by kazubu**
Hi,

I've fixed a markdown syntax of configuration quote to offer more readability.
Could you please merge it?

Thanks,
Kazuki

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kazubu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Cheryl, could you please review this update from @kazubu? Thx.

**Comment by cherylmc** [comment]
@ganesr , can you please review this? Thanks!

**Comment by tysonn** [comment]
@cherylmc & @ ganesr - second notice  on public PR

**Comment by ganesr** [comment]
Please accept PR

**Comment by ganesr** [comment]
#sign-off

**Comment by kazubu** [comment]
Thanks!

**Comment by cherylmc** [comment]
@kazubu - Thanks for letting us know!

**Pull request merged**
