### PR TITLE
Update active-directory-devquickstarts-cordova.md

### PR DESCRIPTION
**Pull request by kunalbabre**
Minor Typo fixed

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kunalbabre__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@kunalbabre : Thanks for your contribution to the Azure documentation! The author, @vibronet, has been notified to review your proposed change.

**Comment by vibronet** [comment]
#signoff

**Comment by mike16546** [comment]
Hi sorry. For that

**Comment by mike16546** [comment]
Let's  will

**Comment by mike16546** [comment]
Let  pull

**Comment by mike16546** [comment]
I'm. Your. Friend.  To

**Comment by mike16546** [comment]
Mike16546@gmail.com

Sorry

**Pull request merged**
