### PR TITLE
Missing -EnableBgp $true flag on New-AzureRmVirtualNetworkGateway com…

### PR DESCRIPTION
**Pull request by sevelho**
Without that feature enable the BGP won't work properly

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sevelho__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sevelho : Thanks for your contribution to the Azure documentation! The author, @yushwang, has been notified to review your proposed change.

**Comment by yushwang** [comment]
Hi,

The EnableBGP parameter is actually no-op. There are some backend interactions that make setting this parameter on EXISTING gateways seemingly "enable" BGP. But it actually is not the value, but the update that made it work. I'll need to provide an update on the doc to explain why that's the case, but setting this value for creating gateways is not needed and have no effect.

Thanks,
Yushun

**Comment by yushwang** [comment]
@tysonn Please close this PR. It's not needed.

**Pull request closed without merging**
