### PR TITLE
fixing markdown

### PR DESCRIPTION
**Pull request by 4c74356b41**
that's the best I could get to work in all the markdown editors I've tested with. Not a single one of them would reproduce ordered sublist...

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by 4c74356b41** [comment]
actually, the same article has got a ordered sublist, but when I look at it - it makes no sense. it's like ordered list, than next line 4 spaces another ordered list, than several lines with tabs instead of spaces and it renders properly. I have no idea how this thing works. Every markdown article states that ordered sublist is just 2 spaces indented from the ordered list but it doesn't work that way.
1. test
  1.testo

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @ruturaj, has been notified to review your proposed change.

**Comment by ruturaj** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@ruturaj - Hi Ruturaj, please resolve this conflict. Thank you, Katie
#hold-off

**Comment by ruturaj** [comment]
How can I resolve the markdown for a pull I have not created? Please let me know how to close the request.

**Comment by 4c74356b41** [comment]
you could tell me what to fix or you could submit a PR to my fix

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by ruturaj** [comment]
#sign-off

**Comment by ruturaj** [comment]
then please close this pull request as the fixes are old.

**Comment by 4c74356b41** [comment]
well, they were not old when i submitted them 3 months ago, you know

**Pull request closed without merging**
