### PR TITLE
DocumentDB Social Apps article refresh

### PR DESCRIPTION
**Pull request by ealsur**
Refreshing article by request of @mimig1 . Adding new scenarios and Azure services.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ealsur__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ealsur : Thanks for your contribution to the Azure documentation! The author, @ealsur, has been notified to review your proposed change.

**Comment by aliuy** [comment]
Awesome, looks good to me :)

:shipit: :shipit: :shipit:

**Comment by mimig1** [comment]
@ealsur Thanks again for doing your freshness review and updating the article! @tysonn Please merge this change, the author is an external contributor & MVP. I've reviewed the changes and privately verified that the changes passed validation.

**Pull request merged**
