### PR TITLE
Changes to the Oracle Linux repositories to make it easier for custom…

### PR DESCRIPTION
**Pull request by mabicca**
…ers that are using YUM.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mabicca__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@SuperScottz - Could you please review this suggested update?

**Comment by SuperScottz** [comment]
@tysonn I'm OK with the update proposed. Thank you for reminder.

@mabicca Thank you for your decent contribution :)..

**Comment by tysonn** [comment]
@squillace and @cynthn  - VM update in public repo.

**Comment by tysonn** [comment]
@mabicca - Sorry this sat. I've pulled the commit over to our private repo and merged it to the article there. I expect the update to go live later this week. Thank you for the contribution.

**Pull request closed without merging**
