### PR TITLE
Fix example in app-insights-analytics-reference.md

### PR DESCRIPTION
**Pull request by anishpatel**
Fix let clause example

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anishpatel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@anishpatel : Thanks for your contribution to the Azure documentation! The author, @alancameronwills, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
@ggailey777 - this is fine, please pull.

**Comment by alancameronwills** [comment]
@anishpatel - thanks, Anish

**Comment by alancameronwills** [comment]
@sign-off

**Comment by alancameronwills** [comment]
#sign-off

**Pull request merged**
