### PR TITLE
No longer asking customers to include their email address

### PR DESCRIPTION
**Pull request by AlexBulankou**
No longer asking customers to include their email address, as we can obtain this info from telemetry. @alancameronwills Can you please take a look.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlexBulankou__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (albulank). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlexBulankou : Thanks for your contribution to the Azure documentation! The author, @alexbulankou, has been notified to review your proposed change.

**Comment by AlexBulankou** [comment]
@PRmerger not sure why you say I was notified to review the proposed changed, I authored the change. Clearing the label.

**Comment by alancameronwills** [comment]
Hi Alex,
The change has been copied to azure-content-pr and is now on the stage:

http://acom-sandbox.azurewebsites.net/en-us/documentation/articles/app-insights-get-dev-support/

It should go live today.

Please close this PR.
Thanks
Alan

**Comment by tysonn** [comment]
Alex, see https://microsoft.sharepoint.com/teams/azurecontentguidance/article-author-working-in-the-public-repo for info about why you need to be working in the private repo.

**Pull request closed without merging**
