### PR TITLE
Added: Using io.js with Azure Websites

### PR DESCRIPTION
**Pull request by felixrieseberg**
io.js is the new hot thing in the Node.js community - and luckily for us, it runs right out of the box on Azure. Using it with a website doesn't require a lot of work, but it's a tiny bit obscure, hence the tutorial.

As discussed with Ralph Squillace, this is a short tutorial, explaining both automated as well as manual io.js deployment.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@felixrieseberg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
Hey Felix -- we're in a day-long hold pattern with content PRs right now; I'll have a read and send feedback, but this looks great. Likely merging on Wednesday or Thursday. I'll also track down the right person to own (it'll be me at least initially....)

**Comment by cephalin** [comment]
Hi Felix. Thanks for your contribution. I think this one is almost ready to go:
- in the metadata "authors" and "ms.service", change it to your GitHub username "felixrieseberg".
- At the end of line 13, change a to an.

**Comment by felixrieseberg** [comment]
@cephalin Thanks for taking a look! I included your changes.

**Pull request merged**
