### PR TITLE
Correct typos

### PR DESCRIPTION
**Pull request by SvenAelterman**
"memboer" to "member"
"failback" to "fallback"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SvenAelterman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SvenAelterman : Thanks for your contribution to the Azure documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@SvenAelterman thx Sven - I am going to accept your first change related to the typo - but not the second change. There is not industry standard for failback versus fallback. From a google search, it appears that failback is the preferred term in Microsoft content whereas Cisco uses fallback.

**Comment by CarlRabeler** [comment]
@SvenAelterman I will make the change in another branch, so you can close this PR.

**Comment by SvenAelterman** [comment]
Closing per comment

**Pull request closed without merging**
