### PR TITLE
Update site-recovery-vmware-to-azure-classic.md

### PR DESCRIPTION
**Pull request by DileepaKariyawasam**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DileepaKariyawasam__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@DileepaKariyawasam : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
@tysonn 
merge-as-is

Hi @DileepaKariyawasam, thanks for your fix, We'll get this merged.

Rayne

**Comment by DileepaKariyawasam** [comment]
Hi Rayne,

No problems at all. Happy to help!

Dileepa

**Pull request merged**
