### PR TITLE
uniqueString description fix

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by PRmerger** [comment]
@AlekseiPolkovnikov : Thanks for your contribution to the Azure documentation! The author, @tfitzmac, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@AlekseiPolkovnikov - thanks for making these changes. I like the suggestions, and I agree it clarifies how the function works . I submitted a PR to your branch with a few changes. I fixed one typo. I changed "down to" to "scoped to" - I think either one works so if you want to keep "down to", that is fine. Finally, I removed "limitedly" because I was concerned it might be confusing.

**Comment by tfitzmac** [comment]
Looks great.

**Comment by tfitzmac** [comment]
#sign-off

**Pull request merged**
