### PR TITLE
Updated app-insights-java-get-started.md with dynamic Instrumentation…

### PR DESCRIPTION
**Pull request by infosatheesh2020**
…Key setting

Updated app-insights-java-get-started.md with dynamic InstrumentationKey setting. Reference: https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@infosatheesh2020__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@infosatheesh2020 : Thanks for your contribution to the Azure documentation! The author, @alancameronwills, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
#sign-off

**Comment by alancameronwills** [comment]
@ggailey777 please pull - thanks!

**Comment by alancameronwills** [comment]
@sign-off

**Comment by alancameronwills** [comment]
#sign-off

**Comment by ggailey777** [comment]
@infosatheesh2020 thanks for helping with Azure docs.

**Pull request merged**
