### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by jurajsucik**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jurajsucik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jurajsucik : Thanks for your contribution to the Azure documentation! The author, @ChackDan, has been notified to review your proposed change.

**Comment by ChackDan** [comment]
#sign-off

**Comment by ChackDan** [comment]
@tysonn  @jamarw the changes look good, please merge

**Pull request merged**
