### PR TITLE
Fixed parameter type of $DataDiskOnly

### PR DESCRIPTION
**Pull request by rfcdejong**
Passing as string would require a different check, thus the code didn't work

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rfcdejong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rfcdejong : Thanks for your contribution to the Azure documentation! The author, @ms-prkhad, has been notified to review your proposed change.

**Comment by yuemlu** [comment]
#sign-off

**Comment by tysonn** [comment]
@tamram - Tamra, could you confirm this is mergeable? This is one of Pradnya's articles, we need a storage team sign off :)

**Comment by tamram** [comment]
@tysonn - yes, I approve. Yuemin is on the storage team, and was assigned to handle this at my request.

**Comment by azurecla** [comment]
Hi __@rfcdejong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
