### PR TITLE
Update virtual-machines-windows-ps-common-ref.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by davidmu1** [comment]
@alexandair: Thank you for your feedback. I agree with the correction of the casing in PowerShell, but not with the casing change of fromImage. I would like to stay consistent with the cmdlet help, which states "[-CreateOption] {empty | attach | fromImage}". Can you revert that part of the commit and we can go ahead and merge the PowerShell change?

**Comment by alexandair** [comment]
@davidmu1 My help says "FromImage". Also, what do you get for IntelliSense in PowerShell ISE? I get "FromImage". The same if I do Set-AzureRmVMOSDisk -CreateOption <tab>. What version of Azure PowerShell do you use?

**Comment by davidmu1** [comment]
@alexandair: I am running the latest version. It works no matter which is case is used. @tysonn: please go ahead and merge the change, the PowerShell cmdlet help is not consistent, so it won't hurt to publish the change.

**Pull request merged**
