### PR TITLE
Fix typo, consistency

### PR DESCRIPTION
**Pull request by stuartleeks**
Correct 'Vet' to 'VNet'
Standardise casing of 'VNet'
Expand ER to Express Route as it hadn't been referenced previously

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartleeks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stuartle). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@stuartleeks : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
#Hold-off , lot of typos are being corrected in a current PR that is under review

**Comment by NarayanAnnamalai** [comment]
Hi @staurtleeks thanks for your contribution to improving the documentation, the original content has been modified and hence this change is no longer required.

Please close this PR.

**Comment by NarayanAnnamalai** [comment]
#please-close

**Comment by stuartleeks** [comment]
Closing as per request. New article is much improved. Have submitted a minor change from this PR that wasn't carried forwards: #7560

**Pull request closed without merging**
