### PR TITLE
Update app-insights-sample-mscrm.md

### PR DESCRIPTION
**Pull request by arunvinoth**
some cosmetic changes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arunvinoth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@arunvinoth Thanks for the contribution.  I'll have the author review.

**Comment by arunvinoth** [comment]
FYI - am the developer of this project

**Comment by alancameronwills** [comment]
@arunvinoth Thanks for this, Arun. One small improvement - could we change line 154 to 
[Here is the sample solution implemented in Dynamics CRM](https://dynamicsandappinsights.codeplex.com/).

Thanks!

**Comment by arunvinoth** [comment]
yeah Alan. Am fine with this.

**Pull request merged**
