### PR TITLE
Missing "--blob-url" argument in CLI command

### PR DESCRIPTION
**Pull request by EgoAleSum**
A customer of mine reported that the sample command for uploading the VHD using the Azure CLI (ASM mode) fails. After some investigation, it seems that the reference is missing the required "--blob-url" argument.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EgoAleSum__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dsk-2015 - Dhanashri, could you review this and let me know if it can be merged?

**Comment by dsk-2015** [comment]
@tysonn I am incorporating this change during my freshness updates to this article. Please do not merge this PR, just close it to avoid conflicts. Thanks! 

Also, many thanks to @EgoAleSum for pointing out the missing tag!

**Comment by tysonn** [comment]
@EgoAleSum - Thanks for the update. @dsk-2015 - We should merge this contribution.

**Pull request merged**
