### PR TITLE
Update timeout value

### PR DESCRIPTION
**Pull request by derek1ee**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@derek1ee__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (deli). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@derek1ee : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@rothja Hi Jason. Please review these proposed changes. Thanks.

**Comment by rothja** [comment]
#sign-off

**Comment by rothja** [comment]
@jomolnar , I did a #sign-off comment. Is that all that is needed to get this change accepted? Thanks.

**Comment by jomolnar** [comment]
@rothja Yes, your comment is all that's needed. Thanks.

**Pull request merged**
