### PR TITLE
Updating the example of the cluster DNS

### PR DESCRIPTION
**Pull request by TheBeardedLlama**
Current example didn't match actual format for service fabric cluster DNS

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheBeardedLlama__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cawams - Could you review this additional proposed change from @TheBeardedLlama in the public repository?

**Comment by tysonn** [comment]
@mthalman-msft - Hey Matt, could you review this public repo pull request from @TheBeardedLlama now that you've taken the article over from @CawaMS? Thanks!

**Comment by mthalman-msft** [comment]
@tysonn: Looks good

**Pull request merged**
