### PR TITLE
Update nodejs-use-node-modules-azure-apps.md

### PR DESCRIPTION
**Pull request by seanlarge**
Hi,
the following link returns a 404: https://npmjs.org/doc/install.html
and I think this is the link we want:   https://docs.npmjs.com/cli/shrinkwrap

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seanlarge__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by seanlarge** [comment]
also, anywhere it says 'see npm-install' the link is wrong, this is the correct link: https://docs.npmjs.com/cli/install

**Comment by tysonn** [comment]
@rmcmurray - Could you review this PR in the public repo from @seanlarge?

**Comment by cephalin** [comment]
@seanlarge Thanks for improving the Azure documentation!
@tysonn @ggailey777 Please go ahead and merge.

**Pull request merged**
