### PR TITLE
Update insights-alerts-powershell.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix casing.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @rboucher, has been notified to review your proposed change.

**Comment by alexandair** [comment]
@rboucher Could you please review the changes?

**Comment by rboucher** [comment]
Hi @alexandair. Thanks for the corrections.  Looks good.  I'm sorry for late reply.  Last week was Ignite, so I was overly busy.   #sign-off

**Comment by rboucher** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@rboucher @Erikre - please address the merge conflict. If you need assistance, please see the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve a local merge conflict yourself.aspx). Thanks, Katie

**Comment by Erikre** [comment]
Checking with Glenn on this one.

**Comment by ggailey777** [comment]
@alexandair thanks for your contribution, but this topic has been removed from the repo (or perhaps renamed).

**Comment by rboucher** [comment]
@alexandair It was moved. I moved it just recently. I will make the change in the moved source.

**Pull request closed without merging**
