### PR TITLE
Version 4.5 release notes are missing

### PR DESCRIPTION
**Pull request by SeanFeldman**
Latest installer available is for 4.5

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SeanFeldman : Thanks for your contribution to the Azure documentation! The author, @tamram, has been notified to review your proposed change.

**Comment by tamram** [comment]
Looks good.

#sign-off

**Comment by KatieCumming** [comment]
@tamram - Hi Tamra, are you able to add any text under this added release notes heading for 4.5? Thanks, Katie
#hold-off

**Comment by Saisang** [comment]
@tysonn please merge this PR.

**Comment by tamram** [comment]
@tysonn, can we please merge this? I will update afterwards to add the new text, which I have ready. I don't seem to be able to edit off of this patch.

**Comment by tamram** [comment]
@tysonn, Please see PR #30240 (now merged). I have duplicated the change made here (which was to add the header with no content), and also added the necessary text under the header.

@SeanFeldman, thanks for your contribution. You caught our inadvertent omission.

**Comment by SeanFeldman** [comment]
@tamram all good :)

**Comment by KatieCumming** [comment]
@tamram - closing as discussed as a duplicate. 
@SeanFeldman - the change is live at https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/.

**Comment by SeanFeldman** [comment]
Great! Thanks @KatieCumming

**Pull request closed without merging**
