### PR TITLE
'Connect to Azure' wrong reference

### PR DESCRIPTION
**Pull request by DexterPOSH**
Under Step 7, it says to add the activity below 'Connect to Azure', however the previous activity is 'Specify Subscription Id'.

2. Add **Start-AzureRmVM** to the canvas and then click and drag it underneath **Connect to Azure**.

Fixing the typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DexterPOSH__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@DexterPOSH__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@DexterPOSH : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@DexterPOSH thank you for taking the time to submit a request to make corrections/updates to this article.  I have reviewed them and approve them to be merged.

**Comment by DexterPOSH** [comment]
Thanks @MGoedtel , I have few more changes coming your way for review.

**Comment by MGoedtel** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@Matt Goedtel Hi Matt
Your sign off did not work with the comment automation because your GitHub account is listed incorrectly in the article metadata: authors="mgoedtel"
It needs to match your GitHub account EXACTLY, including capitalization. Please fix your GitHub account in all your articles after this is merged.

**Pull request merged**
