### PR TITLE
Update virtual-machine-scale-sets-portal-create.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@gatneil 
"From the portal, you can easily deploy a scale set with CentOS, CoreOS, Debian, Open Suse, Red Hat Enterprise Linux, SUSE Linux Enterprise Server, or Ubuntu Server images."

We can use Windows images as well, right?

**Comment by gatneil** [comment]
Yes, good point, we can use Windows images as well :)

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @gatneil, has been notified to review your proposed change.

**Comment by gatneil** [comment]
#sign-off

**Comment by alexandair** [comment]
@tysonn Could you merge it, please?

**Pull request merged**
