### PR TITLE
Fixed typo in step to set context and restore JSON file

### PR DESCRIPTION
**Pull request by jboeshart**
There were a couple typos in the steps where you set the storage context and restore the JSON config file. I also don't think the -context parameter was needed on the Get-AzureStorageBlobContent command as we set the current context previously, and it doesn't look like that variable was actually ever set in the first place.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jboeshart : Thanks for your contribution to the Azure documentation! The author, @markgalioto, has been notified to review your proposed change.

**Comment by markgalioto** [comment]
@jboeshart : thank you for finding the errors. I'll add them immediately.

**Comment by markgalioto** [comment]
@Jim-Parker ; please merge as-is.

**Pull request merged**
