### PR TITLE
Update service-fabric-concepts-partitioning.md

### PR DESCRIPTION
**Pull request by noopman**
The code on this page has not been updated when the code in the linked repository got updated. The code on the page is out of date.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@noopman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@bmscholl - Please review this public repo pull request

**Comment by bmscholl** [comment]
@noopman, thanks so much for taking the time to review and update. We had to update the article anyways as we needed to reflect the latest changes in the Visual Studio Screenshots, so we have updated all in one batch. 
@tysonn: You can close the PR as the changes have already been applied by the PR we submitted couple days ago.

**Comment by noopman** [comment]
My pleasure - no problem - good luck!

**Pull request closed without merging**
