### PR TITLE
Fixing up sample request with id_token & query

### PR DESCRIPTION
**Pull request by gsacavdm**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gsacavdm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by gsacavdm** [comment]
@dstrockis, @skwan - Can either of you guys take a look?
Our sample request has id_token & query which we don't support.

**Comment by PRmerger** [comment]
@gsacavdm : Thanks for your contribution to the Azure documentation! The author, @dstrockis, has been notified to review your proposed change.

**Comment by dstrockis** [comment]
@gsacavdm good catch. Can we keep the AZURE.TIP though? Right now it would just be a floating link.

**Comment by dstrockis** [comment]
#hold-off

**Comment by dstrockis** [comment]
@gsacavdm

**Comment by dstrockis** [comment]
Please close this out if Saca's not going to respond.

**Comment by ktoliver** [comment]
@gsacavdm - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-protocols-oidc](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-protocols-oidc). Thanks for your understanding.

**Pull request closed without merging**
