### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by arjancornelissen**
Adjusted the URL, it was correct in the image but not in the text.
Birst also has 2 datacenters for witch the URL is different. I had a call with Paul Gale from Birst who told me this.
Also found out that the Reply URL is by default www.birst.com and that needs to be configured as well (step b)
And updated the image.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arjancornelissen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@arjancornelissen__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@arjancornelissen : Thanks for your contribution to the Azure documentation! The author, @jeevansd, has been notified to review your proposed change.

**Comment by jeevansd** [comment]
**@arjancornelissen** I have added the support for the Eu datacenter in the Reply URL. So Customers dont have to configure this. As we receive any one of the value Azure AD will use that. 
So please remove that comment and keep the orginal screenshot. Also I have added the example URL now, so Europe customer understand that the EU datacenter is not supported by us.

**Comment by jeevansd** [comment]
@arjancornelissen: Quick reminder! Can you please make these changes?
Thanks.

**Comment by arjancornelissen** [comment]
I removed the comment and reset the image back to the original

**Comment by jeevansd** [comment]
#sign-off

**Pull request merged**
