### PR TITLE
Few nits and adding Windows 10 support

### PR DESCRIPTION
**Pull request by sachincsheth**
I am the PM on Azure Data Lake team.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sachincsheth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sachincsheth : Thanks for your contribution to the Azure documentation! The author, @spelluru, has been notified to review your proposed change.

**Comment by spelluru** [comment]
@sachincsheth - Thanks for the update. 
@cjgronlund  - Looks good. Please merge. Thanks.

**Comment by tysonn** [comment]
@spelluru - Please resolve merge conflict so the PR can be merged

**Comment by spelluru** [comment]
@sachinsheth - I have resolved the merge conflict as part of another PR: https://github.com/Azure/azure-content-pr/pull/26676 as mentioned in the comment above. Thanks.

**Pull request merged**
