### PR TITLE
Update sql-database-cloud-migrate-compatible-using-transactional-repl…

### PR DESCRIPTION
**Pull request by gwalters69**
…ication.md

SQL 2013 -> SQL 2012 in last line of list.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gwalters69__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by gwalters69** [comment]
SQL 2013 -> SQL 2012 in last line of list.

**Comment by azurecla** [comment]
Hi __@gwalters69__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by gwalters69** [comment]
#sign-off

**Pull request closed without merging**
