### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by LazarusX**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@LazarusX__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (fangzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@LazarusX : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
Merge as-is

**Comment by mike16546** [comment]
ok  then  is it

**Comment by billmath** [comment]
Changes look good please merge

**Pull request merged**
