### PR TITLE
Updated SQL Database vs SQL Server on VMs artcile

### PR DESCRIPTION
**Pull request by sjwaight**
Simplified some text, removing statements that add little value. Ensured links and service names were up-to-date where they have changed since the last time this article was updated.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sjwaight__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@jeffgoll 
Can you review and approve/disapprove this PR with a comment? Thanks.

**Comment by rmca14** [comment]
@sjwaight 
If you are a Microsoft employee, can you complete your GitHub profile per our guidance (unable to determine if you are)? https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

If you're not a Microsoft employee, then there is no further action. Thanks for your contribution.

**Comment by jeffgoll** [comment]
@sjwaight. By and large love your edits. Thank you so much. There are some other opportunistic updates (like bad links to outdated pages) we should make to this article. Jumping in on your branch was getting messy, so I'm just going to submit a new PR. I'll do it in the public branch and send you a link. Thank you again. Ping me in person at my work mail jeffreyg at Microsoft dot com if you want to chat.

@rmca14 can you close this PR and I'll send you a link when I have the new one.

**Comment by rmca14** [comment]
@jeffgoll 
Will do and thanks.

**Pull request closed without merging**
