### PR TITLE
PT-BR initial translation

### PR DESCRIPTION
**Pull request by thdotnet**
First version of the PT-BR version of this documentation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thdotnet__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@thdotnet - Hi Thiago - I'm not able to merge it into our English source repo, but I'm checking with our localization team on how to proceed with this. 

cc/ @SunnyDeng

**Comment by thdotnet** [comment]
Yeah, I've noticed that it was the main branch. But I didn't know how to submit the pull request for this case. Let me know once you get any update from the team. 

Cheers,

**Comment by tysonn** [comment]
@thdotnet - You can resubmit to the **azure-content-ptbr** repository.

**Comment by tysonn** [comment]
You can resubmit to the **azure-content-ptbr** repository.

**Comment by SunnyDeng** [comment]
@thdotnet - please go to http://azure.microsoft.com/**pt-br**/documentation/articles/container-service-intro, click the 'Editar no GitHub' button to submit the feedback PR. /Thanks

**Comment by SunnyDeng** [comment]
@thdotnet - The link should be http://azure.microsoft.com/pt-br/documentation/articles/container-service-intro.

**Pull request closed without merging**
