### PR TITLE
Scottworking

### PR DESCRIPTION
**Pull request by SuperScottz**
Create an arcticle regarding how to install MySQL into a LInux VM in Azure.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SuperScottz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mingzhan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by SuperScottz** [comment]
Hello
I ‘m a full time employee in Microsoft,  and will contribute content for Azure as Program Manager from Open Source Technology Center.
So I don’t need sign the agreement, could you please help me to move on the content publish process?


Best Regards
Scott Zhang

**Comment by SuperScottz** [comment]
Hello
Here is a request to add a new article about how to update Azure Linux Agent from Github, by Scott Zhang, PM from Microsoft Open Source Technology Center.

**Comment by azurecla** [comment]
Hi __@SuperScottz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mingzhan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Sent info in email

**Comment by SuperScottz** [comment]
tysonn
I will cancel this pull request and create a new one based on your commen in email.

Thanks.

**Pull request closed without merging**
