### PR TITLE
Fixed link to Ethereum Consortium Blockchain Network

### PR DESCRIPTION
**Pull request by sidkri**
The link was pointing to an older revision.  Changed it to the latest on the master branch.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sidkri__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sidkri). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by sidkri** [comment]
Please expedite as users will be directed to a page that does not work for Azure Govt.

**Comment by zakramer** [comment]
#sign-off

**Comment by sidkri** [comment]
@Ryansoc @zakramer to review and approve

**Comment by Ryansoc** [comment]
#sign-off

**Pull request merged**
