### PR TITLE
Add trim and uri function to template builtin functions.

### PR DESCRIPTION
**Pull request by sezheng**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sezheng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sezheng). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by sezheng** [comment]
Add trim and uri function to template builtin functions.

**Comment by tfitzmac** [comment]
I have made some changes and submitted through another pull request. @davidwrede - this can be closed.

**Comment by ggailey777** [comment]
@sezheng thank you for your contribution. It looks like your suggestion was incorporated into another PR, so I will be closing this PR. Please feel free to submit additional content in the future, and we will try harder to accept your PR into the public repo.

**Pull request closed without merging**
