### PR TITLE
Typo in anchor

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@snobu : Thanks for your contribution to the Azure documentation! The author, @jtuliani, has been notified to review your proposed change.

**Comment by jtuliani** [comment]
Looks good, thanks for the fix!

**Comment by jtuliani** [comment]
#sign-off

**Comment by tysonn** [comment]
#sign-off

**Pull request merged**
