### PR TITLE
Update insights-advanced-autoscale-virtual-machine-scale-sets.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@kamathashwin Hi Ashwin Please review the proposed changes. Thanks.

**Comment by rboucher** [comment]
@kamathashwin cleared the changes. @sign-off

**Comment by Erikre** [comment]
This has been reviewed by the author. Please ship it! Better yet to have author's sign off directly as a comment if possible.

**Pull request merged**
