### PR TITLE
Adding in DSC troubleshooting tips

### PR DESCRIPTION
**Pull request by elcooper**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@elcooper__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (elcooper). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@SnehaGunda Sneha, can you please review these updates and let me and the contributor know if they can/will be merged? Thanks!

**Comment by SnehaGunda** [comment]
@elcooper thanks for the PR. There are some minor wording changes to be made, which I can make locally after the changes are merged.
@Jim-Parker please merge the changes.

**Comment by SnehaGunda** [comment]
#sign-off

**Pull request merged**
