### PR TITLE
Update machine-learning-recommendation-api-sample-application.md

### PR DESCRIPTION
**Pull request by LuisCabrer**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@LuisCabrer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (luisca). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@LuisCabrer 
Merge conflict must be resolved before this PR can merged. Thanks.

**Comment by rmca14** [comment]
@LuisCabrer 
If you need help with this merge conflict, let me know. If this PR has been superseded by other work, feel free to close this PR unmerged. Thanks.

**Comment by LuisCabrer** [comment]
I just changed the date... so closing this one... Will edit again later.

**Pull request closed without merging**
