### PR TITLE
Added note re: partitioned queues and AMQP

### PR DESCRIPTION
**Pull request by tonymitchell**
Since queues are created with partitioning enabled by default now and partitioned queues are not supported with AMQP, this is a common source of errors for people following this tutorial.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tonymitchell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Hi Tony, the SME reviewed and approved the update. Could you update the msdn URL to use http only, and to not include the en-us part of the link? Then I'll be able to accept. The change should just get added to this pending pull request.

**Comment by tonymitchell** [comment]
That's great. I have updated the URL as requested.

**Comment by tysonn** [comment]
Thank you for the contribution!

**Pull request merged**
