### PR TITLE
Two small changes to the instructions

### PR DESCRIPTION
**Pull request by TheBeardedLlama**
Changed the order of the variables of the `CreateAndUpload-Certificate.ps1` script to match the order the script expects them when entering the values.

Changed the name of the image to be used for the build agent to match the latest one as shown in Azure

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheBeardedLlama__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cawams - Could you please review this proposed change in the public repo, submitted by @TheBeardedLlama?

**Comment by CawaMS** [comment]
Thanks @TheBeardedLlama for proposing the change! I see it reflects the latest Azure VM images. However Universal Windows Tools is not a required dependency for using Service Fabric tools. So I suggest that we say something like: pick up an image with Visual Studio 2015 update 2 and Azure SDK 2.9. @tysonn how do I make such a change?

**Comment by tysonn** [comment]
@CawaMS - You can submit your suggested revision to @TheBeardedLlama's fork, patch-1 branch [here](https://github.com/TheBeardedLlama/azure-content/blob/patch-1/articles/service-fabric/service-fabric-set-up-continuous-integration.md). He would then review and merge to his fork, updating this PR.

**Comment by TheBeardedLlama** [comment]
Hey @CawaMS, I appreciate UWP is not required, but that's all that was available with VS and Azure SDK on the ready made images.
I was just trying to be as explicit as the instructions by using the actual name of the image.

**Comment by CawaMS** [comment]
#sign-off

**Comment by tysonn** [comment]
@TheBeardedLlama - merged! Thanks.

**Pull request merged**
