### PR TITLE
Clarifying GW upgrade options

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (alpolko). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlekseiPolkovnikov : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by cherylmc** [comment]
@charwen

**Comment by charwen** [comment]
#sign-off

**Comment by cherylmc** [comment]
#sign-off

**Comment by cherylmc** [comment]
Yes, it's true that this was just added. I'll update the doc after this is merged in. no need to put another update through.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by cherylmc** [comment]
#sign-off

**Pull request merged**
