### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
@4c74356b41 thanks for catching this.
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@NarayanAnnamalai Hi Narayan. Please resolve the conflicts to enable a merge. Usually, authors of the files are able to fix merge conflicts using the process here on the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve a local merge conflict yourself.aspx).

Your sign off did not work with the comment automation because your GitHub account is listed incorrectly in the article metadata: authors="narayanannamalai"
It needs to match your GitHub account EXACTLY, including capitalization. Please fix your GitHub account in all your articles after this is merged.

Thanks.

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by jimdial** [comment]
@4c74356b41  Thank you for the contribution. Your edits were incorporated into the article outside of this PR so I'm closing it. If you disagree, feel free to open a new PR against the updated article.  Thanks!

#please-close

**Pull request closed without merging**
