### PR TITLE
Update dotnet-sdk.md

### PR DESCRIPTION
**Pull request by keithpleas**
Fixed style for "Microsoft Azure Mobile App SDK 1.0" heading, and removed duplicate jump to #hdinsight (causing anchor to jump to top of page)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@keithpleas__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@tysonn 
"dotnet" not in our pillar list.

**Comment by Jim-Parker** [comment]
@tdykstra Tom, can you please review this contribution and sign off if it should be incorporated? Thanks

**Comment by tdykstra** [comment]
@Jim-Parker This looks fine, thanks.

**Comment by Jim-Parker** [comment]
@keithpleas Keith, thanks for the contribution. I'll merge this today.

**Comment by keithpleas** [comment]
Thanks @Jim-Parker & @tdykstra!

**Pull request merged**
