### PR TITLE
Update sql-data-warehouse-get-started-load-with-polybase.md

### PR DESCRIPTION
**Pull request by kuniteru**
1. Picture of created External table,TextFile, and AzureStorage moved to the appropriate position.
2. Fixed Step numbers. (Step 4 -> Step 3, Step 5 -> Step 4)
3. Fixed create statistics table name in comment.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kuniteru__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@kuniteru 
Thank you for your contribution. I'll send this to the author for verification. 
--Carolyn

**Comment by cjgronlund** [comment]
@sahaj08 @barbkess 
Please review these recommended changes. Let me know whether to accept as is, or whether you'd like to incorporate just part. 
--Carolyn

**Comment by sahaj08** [comment]
These changes are okay, please accept as is.

**Comment by barbkess** [comment]
Good to go
#sign-off

**Pull request merged**
