### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by mburleigh**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mburleigh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mburleigh : Thanks for your contribution to the Azure documentation! The author, @spelluru, has been notified to review your proposed change.

**Comment by spelluru** [comment]
@mburleigh - Thanks for updating the article. 

@cjgronlund - please merge the PR when you get a chance. Thanks. 

#sign-off

**Comment by tysonn** [comment]
@spelluru - Sreedhar, you need to resolve the merge conflicts. See https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx for instructions.

**Comment by spelluru** [comment]
@mburleigh - looks like I had resolved the issue at the same time as you did. I have verified that the article renders correctly. Please let me know if you still see the issue. 

@tysonn - please close this pull request as I had resolved the issue while working on the article recently.

**Pull request closed without merging**
