### PR TITLE
Broken links fixed

### PR DESCRIPTION
**Pull request by arambarri**
4 links against elastic search site were broken. 
I've fixed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arambarri__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dragon119 - Please review these proposed updates in the public repo from @arambarri 

cc// @bennage

**Comment by dragon119** [comment]
@tysonn, I have confirmed those fix are all correct.

**Comment by tysonn** [comment]
@arambarri  - Thanks!

**Pull request merged**
