### PR TITLE
Update virtual-machines-extensions-customscript-with-template.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alexandair - Unfortunately, I'm not able to merge at this time - see https://github.com/Azure/azure-content/issues/5959.

**Comment by alexandair** [comment]
@tysonn Does that apply to other VM-related 5 PRs that I submitted in the last month?

**Comment by tysonn** [comment]
@alexandair - I'm working with them on how to handle the outstanding items. @squillace or I will update you.

**Pull request closed without merging**
