### PR TITLE
Added link to video on acs from build 2016

### PR DESCRIPTION
**Pull request by rbinrais**
Added link to a video on acs [building applications using azure container service] session from build 2016.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rbinrais__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rbinrais). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@rgardler - Can you review this update from @rbinrais in the public repo? If you want to add the link, the video should be uploaded to ACOM and the video markdown extension added - you can pull Razi's updates over to your private repo using this command and update as needed:

```
git pull https://github.com/rbinrais/azure-content.git patch-2
```

**Comment by tysonn** [comment]
@rgardler - Please review, second notice

**Comment by rgardler** [comment]
#sign-off

@rbinrais My apologies for not reviewing this simple patch earlier.

**Comment by svick** [comment]
This doesn't seem to work, the rendered page just displays the URL, it's not even a link.

**Pull request merged**
