### PR TITLE
Update virtual-machines-windows-portal-sql-alwayson-int-listener.md

### PR DESCRIPTION
**Pull request by MikeBazMSFT**
Correct "other" model; currently reads "Resource Manager instead of Resource Manager"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MikeBazMSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@MikeRayMSFT 
Please check this PR, and let me know whether to accept it. 
Thanks!
--Carolyn

**Comment by cjgronlund** [comment]
@MikeBazMSFT 
Thank you for this contribution! I'll verify with the author and get back to you.
--Carolyn

**Comment by MikeRayMSFT** [comment]
@MikeBazMSFT, thank you for this contribution. Appreciate your help!

**Comment by MikeRayMSFT** [comment]
#sign-off

**Pull request merged**
