### PR TITLE
adding hero article for azure devops

### PR DESCRIPTION
**Pull request by mlearned**
this should go under Get started here https://azure.microsoft.com/en-us/documentation/articles/azure-portal-keyboard-shortcuts/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mlearned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mlearned : Thanks for your contribution to the Azure documentation! The author, @mlearned, has been notified to review your proposed change.

**Comment by curtand** [comment]
@mlearned 
Thanks for your contribution! It looks like you're a Microsoft employee, and a writer. You should be contributing to our private repository, Azure/azure-content-pr. Our guidance wiki has the instructions for getting permissions, etc. The advantages for you are much more validation and error checking before publishing, and content staging so that you can see your changes just by opening a pull request.

Guidance: https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github 

also @Flanakin, Please review and approve this article as well. Michael is asking that this be added to the left-nav for the Azure Portal documentation (open "Azure portal keyboard shortcuts" and that's the left-nav I mean) under Getting Started. If you approve of the article and the navigation request, I (Curtis Love) can help you with the mechanical part of that if you need me to.

**Comment by mlearned** [comment]
Yea sorry about that, I'm submitting to private repo. I'm making some updates and will do that this weekend.

**Pull request closed without merging**
