### PR TITLE
Create azure-stack-kv-deploy-vm-with-secret.md

### PR DESCRIPTION
**Pull request by rlfmendes**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rlfmendes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ricardom). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rlfmendes : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by rlfmendes** [comment]
#Sign-Off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request closed without merging**
