### PR TITLE
Add Python example to AAD API getting started page

### PR DESCRIPTION
**Pull request by mmcla**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mmcla__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (michmcla). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@mmcla - thanks very much for the contribution!

@dhanyahk - can you please review when you have a few minutes, and let me know if we can proceed with the merge?

**Comment by mmcla** [comment]
Dhanyah, could you take a look at this?

**Comment by dhanyahk** [comment]
Yes. We can merge. Looks good

**Pull request merged**
