### PR TITLE
Remove extra dot in Microsoft..CDN/profiles

### PR DESCRIPTION
**Pull request by jangelfdez**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jangelfdez__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jangelfdez : Thanks for your contribution to the Azure documentation! The author, @ravbhatnagar, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@jangelfdez - thanks for catching and fixing this mistake.

**Comment by tfitzmac** [comment]
@Ja-Dunn or @KatieCumming - can one of you merge this PR? I have verified the fix, but I am not listed as the author so I can't sign off. The author is out right now.

**Comment by KatieCumming** [comment]
@tfitzmac - thanks Tom. Merging.

**Pull request merged**
