### PR TITLE
Update sql-database-disaster-recovery.md

### PR DESCRIPTION
**Pull request by elfisher**
Added a note for what to do if you run into server DTU quota issues.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@elfisher__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by elfisher** [comment]
Added a note for what to do if you run into server DTU quota issues.

**Comment by rmca14** [comment]
@elfisher 
Please remove the locale indicator "en-us" from links. For guidance, see https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/create-links-markdown.md

Thanks.

**Comment by elfisher** [comment]
removed the en-us

**Pull request merged**
