### PR TITLE
Update virtual-machines-linux-mac-create-ssh-keys.md by adding steps …

### PR DESCRIPTION
**Pull request by jierong**
…to generate X509 cert files.

Previously in https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-ssh-from-linux, there are steps to introduce steps to generate X509 cert files, and customers like to see that, but that article redirects to this article, and the steps are missing, I've just copied the steps from that article to this article, hope we can merge them to this article.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jierong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jierong). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jierong : Thanks for your contribution to the Azure documentation! The author, @vlivech, has been notified to review your proposed change.

**Comment by vlivech** [comment]
@jierong - we fixed the x509 section to make sure its covered.

[Using PEM keys](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-mac-create-ssh-keys/#using-ssh-keygen)

**Comment by ktoliver** [comment]
@jierong - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-mac-create-ssh-keys](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-mac-create-ssh-keys). Thanks for your understanding.

**Pull request closed without merging**
