### PR TITLE
Correcting the updated method name

### PR DESCRIPTION
**Pull request by Esperteyu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Esperteyu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Esperteyu : Thanks for your contribution to the Azure documentation! The author, @vgorbenko, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
@vgorbenko You need to look at the change and type '#sign-off' here

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by vgorbenko** [comment]
#sign-off, this looks good

**Pull request merged**
