### PR TITLE
Add import for SecurityContext

### PR DESCRIPTION
**Pull request by eliotstock**
This doesn't compile without this.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@eliotstock__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@bradygaster @tdykstra I assume this is correct, but can you please just verify?

**Comment by bradygaster** [comment]
@tdykstra @ggailey777 LGTM

**Comment by ggailey777** [comment]
@eliotstock  thank you for finding and fixing this bug. We appreciate your help improving the quality of Azure docs.

**Pull request merged**
