### PR TITLE
Update virtual-machines-size-specs.md

### PR DESCRIPTION
**Pull request by coreysa**
Some tweaks...

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@coreysa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (coreysa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by coreysa** [comment]
look good?

**Comment by squillace** [comment]
Sorry, Corey -- swamped figuring out the mass move of windows/linux. @tysonn, can you pull in this addition from Corey? I'll submit one fix to it now....

**Comment by coreysa** [comment]
Thanks, Ralph. Let me know if you need anything more...

**Comment by squillace** [comment]
@rmca14 @Jim-Parker can one of you merge this INSTANTLY please? it's actually more important than we know.

**Pull request merged**
