### PR TITLE
Update virtual-machines-windows-guidance-compute-single-vm.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @mikewasson, has been notified to review your proposed change.

**Comment by MikeWasson** [comment]
The text in square brackets doesn't appear in the rendered topic.

#please-close

**Comment by alexandair** [comment]
That's true. But, why should have a typo in a Markdown text if it can be easily fixed. :)

**Pull request closed without merging**
