### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by vitorfariatomaz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vitorfariatomaz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@vitorfariatomaz : Thanks for your contribution to the Azure documentation! The author, @ddove, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@ddove

**Comment by ddove** [comment]
#sign-off

**Comment by ddove** [comment]
#sign-off
@JennieHubbard 
@CarlRabeler

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRmerger** [comment]
The ready-to-merge label could not be added to this pull request. Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
@cjgronlund ready to merge

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by v-anpasi** [comment]
@tysonn Please Merge

**Pull request merged**
