### PR TITLE
Update storage-nodejs-use-table-storage-web-site.md

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Missing semicolon added to code sample. The missing semicolon is not wrong in JS,
but some editors (like VS Code) just mark such line invalid.

Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@peterblazejewicz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@rmcmurray - Could you please review the suggested update?

**Comment by rmcmurray** [comment]
Yup – I’ll take a look. Thanks!

**Comment by azurecla** [comment]
__@peterblazejewicz__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by rmcmurray** [comment]
I checked this change (and several other minor changes) into the private repo for this article. This PR can be closed.

**Comment by tysonn** [comment]
@peterblazejewicz - Thanks for your contribution; I'll merge.

@rmcmurray - We should accept this contribution.

**Pull request merged**
