### PR TITLE
Update security-center-install-endpoint-protection.md

### PR DESCRIPTION
**Pull request by jboeshart**
Added details to specify the specific products that this recommendation is looking for (Microsoft Antimalware & TrendMicro).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jboeshart : Thanks for your contribution to the Azure documentation! The author, @TerryLanfear, has been notified to review your proposed change.

**Comment by TerryLanfear** [comment]
@jboeshart - Thank you for your contribution! I'm reviewing with dev team to see if anything new will be added in the next few days.  If yes, we'll incorporate that too.  I'll get back to you soon with the results.  Thanks, Terry

**Comment by TerryLanfear** [comment]
@jboeshart - Thank you, again, for your contribution. I am signing off on this change.  Your PR will be merged soon.
#sign-off

**Comment by TerryLanfear** [comment]
#sign-off

**Comment by jboeshart** [comment]
Sounds good, thanks @TerryLanfear!

**Comment by ktoliver** [comment]
@jboeshart - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/security-center/security-center-install-endpoint-protection](https://docs.microsoft.com/en-us/azure/security-center/security-center-install-endpoint-protection). Thanks for your understanding.

**Comment by TerryLanfear** [comment]
@jboeshart - Hi, I can make the change for you so you don't have to resubmit again.  I'll follow-up when the change is published.  Thanks!

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaboes). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jboeshart** [comment]
@TerryLanfear I had some other doc updates that I needed to resubmit so I went ahead and submitted this one as well. 
https://github.com/Microsoft/azure-docs/pull/71

**Pull request closed without merging**
