### PR TITLE
Update api-management-get-started.md

### PR DESCRIPTION
**Pull request by justinyoo**
Hi, Team.

I've added a note for API Management when importing Swagger 2.0 document, which users should be aware of. Until it is resolved, I would suggest this note should be on the page.

It would be great, if you have a review and accept it.

Cheers,

Justin

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@justinyoo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@steved0x Can you please verify this note Justin wants to add?

**Comment by steved0x** [comment]
@ggailey777 Please merge in this change, I reviewed it with the team and it is correct.

@justinyoo Thank you for the contribution!

**Comment by ggailey777** [comment]
@justinyoo Thanks for your contribution to the Azure documentation. We appreciate your help improving the quality of our topics. @steved0x thanks for the quick review too.

**Pull request merged**
