### PR TITLE
Update app-service-mobile-html-how-to-use-client-library.md

### PR DESCRIPTION
**Pull request by jorgifumi**
Added "Configure your Mobile App Service for External Redirect URLs" section.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jorgifumi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@jorgifumi__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@jorgifumi : Thanks for your contribution to the Azure documentation! The author, @adrianhall, has been notified to review your proposed change.

**Comment by ggailey777** [comment]
Thanks @jorgifumi. For you contribution.

**Pull request merged**
