### PR TITLE
An error on code

### PR DESCRIPTION
**Pull request by ciani**
This call has an incorrect characters 
CreateTemplateDeployment(
          credential,
          groupName",
          storageName,
          deploymentName **}"**,
          subscriptionId **}"**);

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ciani__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ciani : Thanks for your contribution to the Azure documentation! The author, @davidmu1, has been notified to review your proposed change.

**Comment by davidmu1** [comment]
@ciani : Good catch. I appreciate you taking the time to correct the example.

**Comment by davidmu1** [comment]
#sign-off

**Pull request merged**
