### PR TITLE
fixed typo - repeated word

### PR DESCRIPTION
**Pull request by Lexman42**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Lexman42__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Lexman42 : Thanks for your contribution to the Azure documentation! The author, @tamram, has been notified to review your proposed change.

**Comment by tamram** [comment]
Looks good. Thanks for your contribution, @Lexman42.

#sign-off

**Comment by azurecla** [comment]
__@Lexman42__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Pull request merged**
