### PR TITLE
Syntax error in date time string.

### PR DESCRIPTION
**Pull request by betamaxed**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@betamaxed__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@spelluru - Public pull request for you to review!

**Comment by spelluru** [comment]
@betamaxed - Thank you very much for your contribution to Data Factory content. 
@tysonn / @cjgronlund - please merge when you get a chance. Thanks.

**Comment by spelluru** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@betamaxed 
Thank you for contribution to Azure documentation!
-Carolyn

**Pull request merged**
