### PR TITLE
Update service-fabric-get-started-with-a-local-cluster.md

### PR DESCRIPTION
**Pull request by PiDiBi**
missing parametr for upgrade cmdlet

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@PiDiBi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@seanmck Sean, can you please review this contribution? merge conflicts will need to be resolved.

**Comment by seanmck** [comment]
Thanks for the submission. This has already been fixed.

**Comment by tysonn** [comment]
Closing

**Pull request closed without merging**
