### PR TITLE
Fix various typos in the Overview of Azure Service Fabric.

### PR DESCRIPTION
**Pull request by adarce**
This change corrects various discovered typos, including:
- Capitalizing node.js -> Node.js.
- Adding bullets, and replacing tabs with spaces.
- Resolving various subject-verb agreement issues.
- Splitting a paragraph into two separate paragraphs.
- Correcting typos like "programmming" and "capabilites".
- Removing redundant words and adding missing words.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adarce__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by adarce** [comment]
Hi @azurecla. I'm actually an employee at Microsoft (my alias is adarce). Are you sure that a CLA is required?

**Comment by tysonn** [comment]
@msfussel - Could you review this public repo contribution to your article?

**Comment by azurecla** [comment]
__@adarce__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by msfussell** [comment]
@tysonn . I reviewed these changes and they are good. Please merge these into the docs.
@adarce. Thanks for meticulously going over these docs to make them better. Much appreciated.

**Pull request merged**
