### PR TITLE
Update sql-database-resource-limits.md

### PR DESCRIPTION
**Pull request by yiruxue**
Update the description of Database per Server in the server limit table. Based on the discussion with engineering team, log-in and connectivity is no longer an issue of preventing the customers from creating 5,000 databases on one server.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yiruxue__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by PRmerger** [comment]
@yiruxue : Thanks for your contribution to the Azure documentation! The author, @carlrabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
sign-off
@yiruxue

**Comment by CarlRabeler** [comment]
@Ja-Dunn 
please merge

**Comment by tysonn** [comment]
Carl, Carolyn is your FTE pull request reviewer. The vendor team does not currently work in the public repo.

**Comment by CarlRabeler** [comment]
@cjgronlund 
please merge this PR

**Pull request merged**
