### PR TITLE
Update sql-database-general-limitations.md

### PR DESCRIPTION
**Pull request by andyjballgit**
Added details about AAD Authentication

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@andyjballgit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by andyjballgit** [comment]
I work for the firm :-) Alias Anball

**Comment by azurecla** [comment]
Hi __@andyjballgit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by andyjballgit** [comment]
(closed in error)

**Comment by rmca14** [comment]
@andyjballgit 
Please correct the typos/extra spaces in the sentence that you added. Thanks for your contribution.

**Comment by cjgronlund** [comment]
@andyjballgit 
Please fix the link format. Should be [Article title](sql-database-aad-authentication.md)

**Comment by cjgronlund** [comment]
@andyjballgit 
OK, git didn't show the raw link -- see the link above the one you added for format.

**Comment by azurecla** [comment]
Hi __@andyjballgit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by JennieHubbard** [comment]
@cjgronlund I accept.

**Comment by cjgronlund** [comment]
@JennieHubbard @andyjballgit 
We can't use the link as shown. At minimum, please remove the locale part of the path: en-gb

**Comment by cjgronlund** [comment]
@JennieHubbard @andyjballgit 
Thank you for your contribution! I've updated the file with this change. See https://github.com/Azure/azure-content/pull/6203

**Pull request closed without merging**
