### PR TITLE
Fix code that generates SAS URL

### PR DESCRIPTION
**Pull request by alexvy86**
The New-AzureStorageContainerSASToken cmdlet already returns an URL that includes the account endpoint and container name.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexvy86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexvy86 : Thanks for your contribution to the Azure documentation! The author, @NKing92, has been notified to review your proposed change.

**Comment by Nking92** [comment]
Hi @alexvy86 
For me, New-AzureStorageContainerSASToken is returning only the SAS Token itself, for example something like "?sv=2015-04-05&sr=c&sig=d9ocZT5RCUvd69yGf%2BCe3XFF10CLGhSXke86t%2FUb0Y6%3D&se=2016-10-13T13%3B57%3A15Z&sp=rwdl"
Can you use Get-Module and tell us which version of Azure.Storage you're using?

**Comment by alexvy86** [comment]
@Nking92 my apologies, you are correct, I just noticed that in my code I'm using the -FullUri switch parameter and that's why I got the full URL. That said, I think it makes it easier to use (over having to then build the URL manually) so maybe you want to consider that and include it in your article.

For completeness, in response to your question, I'm using version 2.0.1 of the AzureRm.Storage module (and of Azure.Storage as well).

**Comment by Nking92** [comment]
I agree that using the -FullUri switch is the best way to write the code. If you want, you can make a new with that change and we will merge it in.

**Comment by alexvy86** [comment]
@Nking92 there you go. Let me know if anything else is needed in order to merge the pull request.

**Comment by Nking92** [comment]
Thanks, it looks good!
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
