### PR TITLE
Update solution-dev-test-environments.md

### PR DESCRIPTION
**Pull request by sryabkov**
Update the article to match the ARM template, which was updated in March

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sryabkov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by sryabkov** [comment]
I suggest that this PR be used instead of #7259. 
I have tested the changes.

**Comment by sryabkov** [comment]
I don't know if I can get the CLA signed. If you can't waive the CLA requirement, feel free to copy/paste the changes and close this PR w/o merge. Or use #7259, it does not require a CLA.

**Comment by tfitzmac** [comment]
@sryabkov - thanks for suggesting this change. Unfortunately, we can't waive the CLA. I will make sure your suggestions are addressed when updating the topic.

I am not able to close the PR. Can you close it?

**Comment by sryabkov** [comment]
@tfitzmac Thank you.

**Pull request closed without merging**
