### PR TITLE
Update virtual-network-peering-overview.md

### PR DESCRIPTION
**Pull request by jourdant**
Made one small spelling correction (Vets to VNets).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jourdant__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jourdant : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
Thanks for your contribution. This can be merged as-is.

**Comment by NarayanAnnamalai** [comment]
#merge as-is

**Comment by jimdial** [comment]
Thanks @jourdant. This issue was apparently resolved outside this PR and should be closed. #please-close.

**Pull request closed without merging**
