### PR TITLE
Update app-insights-release-notes-dotnet.md

### PR DESCRIPTION
**Pull request by sadjadbp**
There are some nuget package name errors.

This line wrong
Microsoft.Web.TelemetryChannel nuget was renamed on Microsoft.WindowsServer.TelemetryChannel
 it should be
Microsoft.ApplicationInsights.Web.TelemetryChannel nuget was renamed on Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sadjadbp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by sadjadbp** [comment]
Also one more thing regarding this change. I've just update my AI from 1.1 to 1.2 and now my projects both have dependency/reference to Microsoft.ApplicationInsights.Web.TelemetryChannel (old package 1.1) and Microsoft.AI.ServerTelemetryChannel (new package 1.2). So either there is something wrong with the update process or my VS did something wrong.

Am I right? I should be able to uninstall Microsoft.ApplicationInsights.Web.TelemetryChannel package from my Web Application (ASP.NET)

**Comment by azurecla** [comment]
Hi __@sadjadbp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@sadjadbp Thanks for this contribution.  I've forwarded this to the author for review.

**Comment by alancameronwills** [comment]
Thanks! Dene, please pull.

@abaranch Any comment on the version update question above?

**Pull request merged**
