### PR TITLE
Update billing-use-existing-office-365-account-azure-subscription.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @jiangchen79, has been notified to review your proposed change.

**Comment by JiangChen79** [comment]
@alexandair: Thanks for raising this. I have already noticed this and submitted [pull request 26202](https://github.com/Azure/azure-content-pr/pull/26202) to fix this, which has been merged. You can close your pull request.

**Comment by alexandair** [comment]
Leave a comment

**Pull request closed without merging**
