### PR TITLE
Clarity on NVA based VPN devices

### PR DESCRIPTION
**Pull request by omartin2010**
These devices should make sure to be not leveraging ESP or AH or GRE... won't work otherwise.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @yushwang, has been notified to review your proposed change.

**Comment by yushwang** [comment]
@please-close

@omartin2010 - Thanks for the note - ESP and AH actually work as long as the Public IP does not have a load balancer. GRE is something we called out separately, but will consider adding it here.

**Comment by omartin2010** [comment]
Ok, didn't know that. Are all IP protocols supported, then (if they're not fronted by a load balancer)? and GRE is not supported, correct? So GRE over IPsec would work, then...

**Comment by yushwang** [comment]
#please-close

**Pull request closed without merging**
