### PR TITLE
'azure' instead of 'Azure' in CLI examples

### PR DESCRIPTION
**Pull request by sfilatov**
Consider using lowercase first letter instead of Uppercase. This is common style for bash/cmd command. 
Uppercase first letter make this command look like usual sentence.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sfilatov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stepan.filatov@skype.net). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sfilatov : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by sdwheeler** [comment]
@sfilatov @cherylmc 
This was fixed in another PR.

#please-close

**Comment by cherylmc** [comment]
#please-close

**Comment by cherylmc** [comment]
Thanks @sfilatov and @sdwheeler!

**Pull request closed without merging**
