### PR TITLE
Change flags for creating storage accounts in version 0.9.20

### PR DESCRIPTION
**Pull request by briglx**
The flags are wrong for version 0.9.20 of the api

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@briglx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@Blackmist - Please review this public repo pull request from @briglx

**Comment by Blackmist** [comment]
Hi @briglx, the document is current with the latest version of Azure CLI (0.10.0). Help for this the azure storage account create command for this version shows the following:

C:\Users\larryfr\Documents\GitHub> azure storage account create -h
help:    Create a storage account
help:
help:    Usage: storage account create [options] <name>
help:
help:    Options:
help:      -h, --help                                             output usage information
help:      -v, --verbose                                          use verbose output
help:      -vv                                                    more verbose with debug output
help:      --json                                                 use json output
help:      --sku-name <skuName>                                   the SKU name (LRS/ZRS/GRS/RAGRS/PLRS)
help:      --kind <kind>                                          the account kind
help:      --access-tier <accessTier>                             the access tier (Hot/Cool)
help:      --enable-encryption-service <enableEncryptionService>  specifies the service which needs to enable encryption settings
help:      --custom-domain <customDomain>                         the custom domain
help:      --subdomain                                            whether uses the 'asverify' subdomain to preregister the custom domain
help:      --tags <tags>                                          the account tags. Tags are key=value pairs and separated with semicolon(;)
help:      -l, --location <location>                              the location
help:      -g, --resource-group <resourceGroup>                   the resource group name
help:      -s, --subscription <id>                                the subscription id
help:
help:    Current Mode: arm (Azure Resource Management)

Trying to use the parameters from 0.9.20 gives you errors:
C:\Users\larryfr\Documents\GitHub> azure storage account create -g larrytest0520 --type RAGRS -l northcentralus larrytes
tstore0525

  error: unknown option `--type'

We try to keep documentation up to date for the latest version of the Azure CLI and PowerShell, so I cannot approve this PR since the information is for an older version. I would recommend updating the version of Azure CLI on your development environment to the latest version.

Thanks,
Larry

**Comment by cjgronlund** [comment]
@briglx 
Thank you for your contribution. I'll close this PR now.
--Carolyn

**Pull request merged**
