### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
i think its correct this way, but I might be wrong

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by Ja-Dunn** [comment]
@NarayanAnnamalai - Please review these changes. Also, if the changes are okay, please change the formatting of the note to markdown. Thanks!

**Comment by Ja-Dunn** [comment]
#hold-off

**Comment by carmonmills** [comment]
@NarayanAnnamalai  spelling change "trafic" to "traffic" in addition to the changes submitted by  @4c74356b41.

thank you for your updates.

**Comment by 4c74356b41** [comment]
fixed

**Comment by NarayanAnnamalai** [comment]
Hi @4c74356b41 ,
Thanks for your contribution to improving Azure documentation. Due to an issue with merge conflict, I am requesting you to please close this PR, the changes have been made to the repository already. Thanks again.

**Comment by NarayanAnnamalai** [comment]
#please-close

**Pull request closed without merging**
