### PR TITLE
Update storage-disaster-recovery-guidance.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @robinsh, has been notified to review your proposed change.

**Comment by robinsh** [comment]
Hi @alexandair Thanks very much for fixing my typo in the DR article! 

@tysonn This PR is ready to be merged.

**Comment by alexandair** [comment]
@robinsh Your articles are fantastic. It's a pleasure to read them.

**Comment by robinsh** [comment]
@alexandair Thanks! I'm glad they are helpful to you.

**Pull request merged**
