### PR TITLE
Fix typo: trafficmanager,net --> .net

### PR DESCRIPTION
**Pull request by davidni**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@davidni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (davidni). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@davidni : Thanks for your contribution to the Azure documentation! The author, @jtuliani, has been notified to review your proposed change.

**Comment by jtuliani** [comment]
#sign-off

**Comment by jtuliani** [comment]
Thank you @davidni for the fix!

@tysonn this is good to merge

**Pull request merged**
