### PR TITLE
Update machine-learning-r-csharp-cluster-model.md

### PR DESCRIPTION
**Pull request by charislove**
Updating date to ensure KPI for freshness

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@charislove__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@charislove 
I can't confirm if you're a Microsoft employee. Can you please edit your profile per this guidance? https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

Thanks.

**Comment by charislove** [comment]
Hi, I've updated my profile. Thanks for the instructions!

**Comment by azurecla** [comment]
Hi __@charislove__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
