### PR TITLE
Several typos fixed in sql-database-cloud-migrate.md

### PR DESCRIPTION
**Pull request by vitorfariatomaz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vitorfariatomaz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@vitorfariatomaz : Thanks for your contribution to the Azure documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off
@cjgronlund OK to merge

**Comment by CarlRabeler** [comment]
@tysonn I have signed off and notified @cjgronlund what else do I need to do to have this PR merged? @JennieHubbard

**Pull request merged**
