### PR TITLE
Update azure-stack-key-features.md - wordsmithing

### PR DESCRIPTION
**Pull request by jpsnover**
Internal use is going to be more prevalent than service providers amongst the readers so change the emphasis.

Portal and PowerShell are co-equal paths for interacting with AS.

"consistent with Azure Portal" implies "different".  It isn't different, it is an instance of the Azure Portal running on your servers.

Services and applications - the examples are services => applications so the setup words should follow the same order.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jpsnover__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jpsnover : Thanks for your contribution to the Azure documentation! The author, @Heathl17, has been notified to review your proposed change.

**Comment by HeathL17** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
