### PR TITLE
Example for user/pass combo for MQTT

### PR DESCRIPTION
**Pull request by snobu**
Let's help the next reader not waste 30 minutes trying to form the password.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dominicbetts - Please review contribution and let me know if it can be merged. Thanks -

**Comment by dominicbetts** [comment]
@tysonn  That's fine to go ahead and merge.

**Comment by tysonn** [comment]
@snobu - Thanks for the improvement to the article!

**Pull request merged**
