### PR TITLE
Tenant id in URL is incorrect

### PR DESCRIPTION
**Pull request by helaili**
The post sample shows the tenant id, but whith `.onmicrosoft.com` appended. 
The Bash and PowerShell sample don't even show the tenant ID

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@helaili__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@helaili : Thanks for your contribution to the Azure documentation! The author, @navalev, has been notified to review your proposed change.

**Comment by navalev** [comment]
@helaili thank you for the comment. I will accept your edits.

Merge as-is

**Comment by tfitzmac** [comment]
@navalev - for these changes to get merged, use #sign-off. Only the author can sign off on the changes.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by navalev** [comment]
#sign-off

**Pull request merged**
