### PR TITLE
Clarification that SqlReaderQuery can reference multiple tables

### PR DESCRIPTION
**Pull request by lpillar**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lpillar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@lpillar 
Thank you for your contribution. I'll verify this with the author and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@spelluru 
Hi, Sreedhar, please check this PR and let me know whether to accept it. Thanks!

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
