### PR TITLE
Update virtual-machine-scale-sets-design-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @gatneil, has been notified to review your proposed change.

**Comment by cynthn** [comment]
@tysson this is fine to merge. @alexandair thank you for finding and fixing these typos!

**Comment by alexandair** [comment]
@tysson Could you merge this one, please? It was approved 2 weeks ago.

**Comment by gatneil** [comment]
If it helps, I #sign-off :)

**Comment by tysonn** [comment]
@cynthn - remember to @ mention me using my actual account - tysonn :)

**Pull request merged**
