### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by lorenpaulsen**
This article keeps mentioning the Azure Classic Portal, when in fact ADF is managed using the new portal and the screenshots are of the new portal

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lorenpaulsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@spelluru 
Sreedhar, please review these changes and let me know whether to accept the PR.

**Comment by cjgronlund** [comment]
@lorenpaulsen 
Thank you for these fixes. The author will validate, and I'll get right back to you.

**Comment by spelluru** [comment]
Azure Classic Portal is the wrong name. 
@lorenpaulsen  - Thanks for the fixes.

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
