### PR TITLE
Update automation-scheduling-a-runbook.md

### PR DESCRIPTION
**Pull request by elcooper**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@elcooper__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (elcooper). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@elcooper : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@elcooper thank you for taking the time to submit a request to make corrections/updates to this article.  I have reviewed them and approve them to be merged.  I also identified a couple of other minor mistakes during my review, so I am going to be submitting a PR after yours with additional updates.  #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
