### PR TITLE
Link term VNet

### PR DESCRIPTION
**Pull request by stuartleeks**
Create connection between "virtual network" and "VNet"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartleeks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stuartle). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@stuartleeks : Thanks for your contribution to the Azure documentation! The author, @NarayanAnnamalai, has been notified to review your proposed change.

**Comment by jimdial** [comment]
@stuartleeks : Thanks for the edit. #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
The listed author of this is   authors="NarayanAnnamalai". Jim, please contact azdocprs to request this be merged. Only the listed author can use the sign off comment to get this merged.

**Comment by NarayanAnnamalai** [comment]
#sign-off

**Pull request merged**
