### PR TITLE
Azure AD Connect: fix broken link

### PR DESCRIPTION
**Pull request by AndKjell**
Fix a broken link regressed by:
https://github.com/Azure/azure-content-pr/pull/31706

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndKjell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (andkjell). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by AndKjell** [comment]
I've left Microsoft and I'm now external. I've already signed the CLA earlier today.

**Comment by PRmerger** [comment]
@AndKjell : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
