### PR TITLE
changing code snippets for better color doing

### PR DESCRIPTION
**Pull request by ryancrawcour**
changing code snippets for better color doing

### CODE REVIEW

**Comment by ryancrawcour** [comment]
@bursteg

**Comment by rmca14** [comment]
@mimig1

**Comment by mimig1** [comment]
@ryancrawcour Sorry I missed this yesterday. I can push this live but we won't know what it looks like until it's live as changes made to this repo don't get staged. If you want to see it staged before publishing, move it to azure-content-pr. Let me know what you want to do.

**Comment by mimig1** [comment]
@rmca14 #sign-off We're pushing this from this repo.

**Pull request merged**
