### PR TITLE
Update hdinsight-analyze-twitter-data.md

### PR DESCRIPTION
**Pull request by dem108**
Found another typo. Parameter not properly set, so fixed it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dem108__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@dem108 
Thank you for the correction! I'll send this to the author for verification, before I accept this PR.

**Comment by cjgronlund** [comment]
@mumian 
Jonathan, please check this correction.

**Comment by mumian** [comment]
#sign-off

**Pull request merged**
