### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
Trying to make article more clear

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@gatneil - Neil, please review this proposed update from @4c74356b41 to your article in the public repository. I'll forward additional details via email.

**Comment by tysonn** [comment]
@madhana - This is the pull request that needs review by you or your team. Thanks

**Comment by gatneil** [comment]
I like the idea behind the change, but I dislike that the link to the custom image at scale template is in a paragraph about platform images. I'd prefer that we make that sentence its own paragraph (something like "to deploy more VMs than the above limits, you will need to use multiple scale sets. For an example, please see...).

**Comment by tysonn** [comment]
@gatneil - Go ahead and submit a fix to the contributor's patch-20 branch: https://github.com/4c74356b41/azure-content/blob/patch-20/articles/virtual-machine-scale-sets/virtual-machine-scale-sets-design-overview.md. That way, @4c74356b41 can see the suggested update and merge it to his branch and fork, which will update this PR.

**Comment by gatneil** [comment]
done

**Comment by gatneil** [comment]
#sign-off

**Comment by 4c74356b41** [comment]
Hello?

**Pull request merged**
