### PR TITLE
Package was renamed in openSUSE and SUSE Linux Enterprise

### PR DESCRIPTION
**Pull request by rjschwei**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rjschwei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rjschwei : Thanks for your contribution to the Azure documentation! The author, @szarkos, has been notified to review your proposed change.

**Comment by szarkos** [comment]
LGTM, thanks!

**Comment by szarkos** [comment]
#sign-off

**Pull request merged**
