### PR TITLE
Refreshed article virtual-machines-dotnet-run-compute-intensive-task to include current portal screenshots

### PR DESCRIPTION
**Pull request by Drewm3**
Updated article to be correct for the current portal behavior for Service Bus now that Service Bus is no longer in preview.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Drewm3__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Drew is an employee.

**Comment by tysonn** [comment]
Drew, can you please run "git pull upstream master" from your local master branch and resolve the merge conflict? After you resolve the changes, run the add & commit commands, then push to master on your fork. The changes will be added to this open pull request.

**Comment by Drewm3** [comment]
Thanks Tyson. I was not able to figure out how to resolve the conflict so I killed the previous fork, created another fork and was able to submit the PR without any merge conflict issues.

**Pull request closed without merging**
