### PR TITLE
Some Minor Editing to: vs-azure-tools-resource-groups-deployment-projects-create-deploy.md

### PR DESCRIPTION
**Pull request by kbdavis07**
Changed: By adding a reference, you link the web app project to the resource group project, and set three key properties. 

To:

By adding a reference, you link the web app project to the resource group project, and _**you need to**_ set three key properties. 

Then added spaces between the three properties.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kbdavis07__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@tfitzmac can you please verify the customer's additions?

**Comment by tfitzmac** [comment]
@kbdavis07 - thanks for suggesting this change. I need to double-check the work flow, but in my set up those properties were set automatically. Did you have to set those manually? Let me try it again, and then we can come up with wording that works for both scenarios.

**Comment by kbdavis07** [comment]
> but in my set up those properties were set automatically.

What properties ?   :smile:

By adding a reference, you link the web app project to the resource group project, and **you need to** set three key properties. 

All I changed was adding the words, "_you need to_"   and then some spacing to make it easier to read.

**Comment by kbdavis07** [comment]
Screen shot:
creating and deploying azure resource group visual studio projects - microsoft azure 2016-04-15 16-18-56


Hopefully this makes more sense in context of the actual article :smile:

**Comment by tfitzmac** [comment]
@kbdavis07 - I double-checked the process, and those values were automatically set by Visual Studio. I think adding "you need to" will be confusing, especially since the values are not intuitive. Could you change your pull request to something like ", and Visual Studio automatically sets three key properties."

I like the extra spacing, and I think a bullet list might be the best option.

**Comment by tfitzmac** [comment]
I submitted PR to kbdavis07:patch-1 with small changes.

**Comment by tysonn** [comment]
@tfitzmac - Tom, @kbdavis07 merged the PR you submitted. Are we ready to merge now?

**Comment by tfitzmac** [comment]
Yes, please merge.

**Comment by kbdavis07** [comment]
So everything good to go?

:smile:

Thanks,

Brian Davis

**Comment by tysonn** [comment]
Merged! Thank you, guys

**Pull request merged**
