### PR TITLE
Update solution-dev-test-environments.md

### PR DESCRIPTION
**Pull request by sryabkov**
Add a warning saying a new version of the ARM template is available. Because the new version doesn't match the article, update the links in the article to point to the version of the template that was current at the time the article was written.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sryabkov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sryabkov : Thanks for your contribution to the Azure documentation! The author, @jimdial, has been notified to review your proposed change.

**Comment by sryabkov** [comment]
@jimdial You might prefer to update the article vs. change links to the older version of the template. I just wanted to point out the mismatch.

**Comment by tfitzmac** [comment]
@sryabkov - thanks for letting us know about the version change. Yes, we are planning to update this topic soon. I am going to review how much needs to be updated, and then we will either accept your pull request as a short-term fix, or just go ahead and update the whole topic.

**Comment by sryabkov** [comment]
@tfitzmac @jimdial I think it is better to bring up the article to the new version of the template rather than fit the article to the old version of the template. I did this over here: https://github.com/Azure/azure-content/pull/7260. I suggest you use #7260 and close this PR without merging.

**Comment by tfitzmac** [comment]
@sryabkov - thanks again for making this change. Let's merge this one as a short-term fix until the topic is updated.
@jimdial or @tysonn - can you sign off on this PR? We are transferring this topic from Jim to me but I am not currently listed as the author so I can't sign off.

**Pull request merged**
