### PR TITLE
Added D_V2 NIC sizes

### PR DESCRIPTION
**Pull request by magaal**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@magaal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Thanks for the update, mike. @telmosampaio - pls review :)

**Comment by telmosampaio** [comment]
All good. I had a thread going on with Mike and others on this as well.

**Comment by telmosampaio** [comment]
#sig-off

**Pull request merged**
