### PR TITLE
Fix indentation issue in app-service-mobile-ios-how-to-use-client-library.md

### PR DESCRIPTION
**Pull request by dhei**
Objective-C code in Custom API section has indentation issue

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dhei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@dhei : Thanks for your contribution to the Azure documentation! The author, @krisragh, has been notified to review your proposed change.

**Comment by krisragh** [comment]
@dhei  thanks for fixing this! Looks good to me! #sign-off

**Comment by PRmerger** [comment]
@dhei : Thanks for your contribution to the Azure documentation! The author, @krisragh, has been notified to review your proposed change.

**Comment by dhei** [comment]
@krisragh Would you merge this PR if you have write permission?

**Pull request merged**
