### PR TITLE
Update sql-data-warehouse-reference-powershell-cmdlets.md

### PR DESCRIPTION
**Pull request by TwoUnder**
Fixing a broken link and removing a duplicate number (2. vs. 2. 2. )

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TwoUnder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mausher). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@JennieHubbard 
Please review/approve here, thanks.

**Comment by rmca14** [comment]
@JennieHubbard 
This is updating date and author, so I'll approve it.
@barbkess 
FYI

**Comment by JennieHubbard** [comment]
#Sign-off and thank you Ross!

**Pull request merged**
