### PR TITLE
Updating freshness

### PR DESCRIPTION
**Pull request by ryancrawcour**
Updating freshness

### CODE REVIEW

**Comment by ryancrawcour** [comment]
@mimig1

**Comment by mimig1** [comment]
@ryancrawcour Please address/resolve verbatim bug 5452989. http://sqlbuvsts01:8080/Main/DocumentDB/_workitems#_a=edit&id=5452989&triage=true

**Comment by ryancrawcour** [comment]
This issue has been resolved as “Cannot reproduce”. The CreateDocumentCollectionQuery method most definitely exists.

**Comment by mimig1** [comment]
#sign-off

**Comment by mimig1** [comment]
@rmca14

**Pull request merged**
