### PR TITLE
Update data-factory-azure-sql-data-warehouse-connector.md

### PR DESCRIPTION
**Pull request by ahkim**
Remove the last comma in SqlDWSink example to prevent error.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@ahkim 
Thank you for your contribution. I'll verify the changes with the author and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@spelluru 
Hi, Sreedhar, Please confirm whether I should accept this PR. Thanks!

**Comment by spelluru** [comment]
Yes. The command (,) was not needed. Thanks.

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
