### PR TITLE
Update machine-learning-competition-faq.md

### PR DESCRIPTION
**Pull request by charislove**
Reviewed for freshness and changed date to 8/23

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@charislove__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by charislove** [comment]
#sign-off

**Comment by PRmerger** [comment]
@charislove : Thanks for your contribution to the Azure documentation! The author, @hning86, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by garyericson** [comment]
@charislove @hning86- Updates by Microsoft employees should only be made in the azure-content-pr repo. If Hai can sign this off, this update will go through okay. But in the future use the azure-content-pr repo (replace "azure-content" with "azure-content-pr" in the GitHub URL for the article).

**Pull request closed without merging**
