### PR TITLE
Update stream-analytics-introduction.md

### PR DESCRIPTION
**Pull request by stuartswift**
Aligned outputs as defined in programming sections

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartswift__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@stuartswift 
Thank you for your contribution. I'll verify this with the writer and get right back to you.
Thanks,
Carolyn

**Comment by cjgronlund** [comment]
@jeffstokes72 
Hi, Jeff, Please check this PR and let me know whether to accept. Thanks!
Carolyn

**Comment by jeffstokes72** [comment]
This looks like a good change to me. Please move forward.

**Comment by jeffstokes72** [comment]
These two PRs he submits are good but both modify the same paragraph in different ways so conflict. I'll make a new PR to address.

**Comment by cjgronlund** [comment]
@stuartswift @jeffstokes72 
Oops! Merge conflict. 
@stuartswift I can work with Jeff to resolve the conflict. Or, you can resubmit your changes to the new paragraph you edited in your other PR.

**Comment by cjgronlund** [comment]
@jeffstokes72 
Based on your comment about resubmitting the changes in another PR, I'm going to close this.
Thanks!
--Carolyn

**Pull request closed without merging**
