### PR TITLE
Update sql-database-cloud-migrate.md

### PR DESCRIPTION
**Pull request by CarlRabeler**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CarlRabeler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@CarlRabeler 
It'll best to use the Markdown syntax for that Important note. See guidance at https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/custom-markdown-extensions.md

Thanks

**Comment by CarlRabeler** [comment]
Thanks – I was trying to find this note.
Carl

**Comment by rmca14** [comment]
@CarlRabeler 
Following up, thanks.

**Comment by rmca14** [comment]
@CarlRabeler 
Per our conversation, I'm closing this.

**Pull request closed without merging**
