### PR TITLE
Update devtest-lab-faq.md

### PR DESCRIPTION
**Pull request by alexandair**
Remove unnecessary parenthesis.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @tomarcher, has been notified to review your proposed change.

**Comment by TomArcher** [comment]
@alexandair Thanks for your contribution. As you mention, the parens are completely necessary. However, they are there more for readability than function.

**Comment by alexandair** [comment]
@TomArcher I don't understand how they increase the readability. Quite the opposite. They are not used in that way in any other article. If that's a good practice, everyone will use it. Please, remove them.

**Comment by TomArcher** [comment]
@tysonn #sign-off

**Pull request merged**
