### PR TITLE
Missing adding initialize method to Global.asax.cs

### PR DESCRIPTION
**Pull request by joescars**
Missing adding initialize method to Global.asax.cs. The site will give you errors without this line of code as it has not created the default DocumentDB

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@joescars__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@mimig1 
Please verify this change, and let me know whether to accept the PR. Thank you!
--Carolyn

**Comment by cjgronlund** [comment]
@joescars 
Thank you for your contribution. I'll verify it with the author and get right back to you.
--Carolyn

**Comment by mimig1** [comment]
@joescars @cjgronlund Will confirm on Monday. Thanks!

**Comment by mimig1** [comment]
Have not forgotten - but delayed until Tues.

**Comment by mimig1** [comment]
@joescars - Thank you for the update, I have confirmed the fix and we will merge it in. @cjgronlund - Please merge. Thanks!

**Comment by joescars** [comment]
Thank you!

Thank you,
Joe Raio

**Pull request merged**
