### PR TITLE
fix note per user comment

### PR DESCRIPTION
**Pull request by adhurwit**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adhurwit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (adhurwit). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@adhurwit : Thanks for your contribution to the Azure documentation! The author, @adhurwit, has been notified to review your proposed change.

**Comment by curtand** [comment]
@adhurwit 
thanks for your contribution! It looks like you're a Microsoft employee, and the author of the article. You should be contributing to our private repository, Azure/azure-content-pr. Our guidance wiki has the instructions for getting permissions, etc. The advantages for you are much more validation and error checking before publishing, and content staging so that you can see your changes just by opening a pull request.

Guidance: https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github

**Comment by tysonn** [comment]
@adhurwit - I'm closing this PR - please see https://microsoft.sharepoint.com/teams/azurecontentguidance/article-author-working-in-the-public-repo for more info.

**Pull request closed without merging**
