### PR TITLE
Update active-directory-accessmanagement-groups-with-advanced-rules.md

### PR DESCRIPTION
**Pull request by RobdeJong**
Updates to support for custom attributes and extension attributes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RobdeJong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rodejo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@RobdeJong - LGTM. Btw, you might want to consider following the Contributors' Guiide and setup for internal/employee contributions (see https://github.com/Azure/azure-content/) if you haven't already.

Adding @curtand for his review ...

**Comment by RobdeJong** [comment]
Hi, I still have two outstanding pull requests:
2 Pull Requests

  1.  Open #5422 Update active-directory-accessmanagement-groups-with-advanced-rules.md<https://github.com/Azure/azure-content/pull/5422> Jan 20 Azure/azure-content<https://github.com/Azure/azure-content>
  2.  Open #5412 Update active-directory-accessmanagement-groups-with-advanced-rules.md<https://github.com/Azure/azure-content/pull/5412> Jan 19 Azure/azure-content<https://github.com/Azure/azure-content>

Can you please look at these?

/Rob

**Comment by RobdeJong** [comment]
From: Rob de Jong
Sent: Tuesday, January 26, 2016 11:30 PM
To: 'Azure/azure-content' <reply@reply.github.com>; Azure/azure-content <azure-content@noreply.github.com>
Subject: RE: [azure-content] Update active-directory-accessmanagement-groups-with-advanced-rules.md (#5406)

Hi, I still have two outstanding pull requests:
2 Pull Requests

  1.  Open #5422 Update active-directory-accessmanagement-groups-with-advanced-rules.md<https://github.com/Azure/azure-content/pull/5422> Jan 20 Azure/azure-content<https://github.com/Azure/azure-content>
  2.  Open #5412 Update active-directory-accessmanagement-groups-with-advanced-rules.md<https://github.com/Azure/azure-content/pull/5412> Jan 19 Azure/azure-content<https://github.com/Azure/azure-content>

Can you please look at these?

/Rob

**Pull request merged**
