### PR TITLE
Minor formatting change to PowerShell and claim rule

### PR DESCRIPTION
**Pull request by RyanSizemore**
Fixing a few formatting issues.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RyanSizemore__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@RyanSizemore : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
Thanks Ryan!  
#sign-off

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
