### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @fsautomata, has been notified to review your proposed change.

**Comment by fsautomata** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@fsautomata - Hi Elio, please fix the merge conflict. If you need guidance, see the instructions on the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx).
Thanks, Katie

https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Pull request merged**
