### PR TITLE
Removing additional instances per request note.

### PR DESCRIPTION
**Pull request by cristhianu**
In an internal discussion with Product group, we decided to remove this part: "Additional instances are available by opening a support request."

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cristhianu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@cristhianu : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by KatieCumming** [comment]
@rothja - Hi Jason, please review this proposed change. Thanks! Katie

**Comment by rothja** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by rothja** [comment]
@KatieCumming Hi, I tried to sign off, but it won't let me. Can you help me merge this. I approve.

**Comment by cristhianu** [comment]
Hello, 
Just checking on this as it has been approved.
Thank you,

**Pull request merged**
