### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
Since the release of Premium tier for redis this information is outdated, proposing this change.
Also proposing second little change to emphazise the note section

https://azure.microsoft.com/en-us/documentation/articles/cache-configure/#cluster-size
you can check the size, and sharding

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @dragon119, has been notified to review your proposed change.

**Comment by dragon119** [comment]
The first part of PR is not correct. It has to be reverted back to the original statement. The second part looks good.

**Comment by 4c74356b41** [comment]
Ok, I've removed the first part, but why is it not correct, I mean premium tier of redis supports clustering and databases up to 530gb (the documentation says you can even request more)

**Comment by dragon119** [comment]
@4c74356b41,  The size limit of a single node is 53GB, and clustering is still in preview. Our guidance should focus on the GA features.  Thank you for checking this anyway. I really appreciate it.

**Comment by 4c74356b41** [comment]
Ah, ok. I see now. Thanks!

**Comment by 4c74356b41** [comment]
Care to approve it? xD

**Comment by dragon119** [comment]
Sorry I thought I did. Yes, this PR should be merged. Thanks!

**Comment by dragon119** [comment]
#sign-off

**Comment by 4c74356b41** [comment]
thanks!

**Comment by tysonn** [comment]
@dragon119 - Masashi, can you please convert this into a markdown note now that the formatting has changed? See the [custom markdown extension info](https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/custom-markdown-extensions.md#notes-and-tips). Also, here's a [link to the internal wiki with instructions about the ways you can integrate this change](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Make%20changes%20to%20another%20person%27s%20pending%20pull%20request.aspx).

**Comment by tysonn** [comment]
#hold-off

**Comment by 4c74356b41** [comment]
folks?

**Comment by dragon119** [comment]
Can you change **Note** to [AZURE.NOTE] ?

**Comment by 4c74356b41** [comment]
like so?

**Comment by dragon119** [comment]
#sign-off

**Comment by dragon119** [comment]
#sign-off

**Pull request merged**
