### PR TITLE
Update vs-storage-aspnet5-getting-started-blobs.md

### PR DESCRIPTION
**Pull request by edrohler**
The documentation was referencing asp.net 5 beta 8 and 'Microsoft.Framework' namespaces were changed to 'Microsoft.Extensions'

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@edrohler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@TomArcher can you please review and verify this contribution so that I can merge it?

**Comment by tysonn** [comment]
@TomArcher - Can you review?

**Comment by TomArcher** [comment]
:shipit:

**Pull request merged**
