### PR TITLE
Make it clear that static public IP is the new way

### PR DESCRIPTION
**Pull request by dacap**
It isn't clear what concept has replaced reserved IPs. So we can make it explicit.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dacap__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@dacap : Thanks for your contribution to the Azure documentation! The author, @jimdial, has been notified to review your proposed change.

**Comment by jimdial** [comment]
@dacap:  Thanks for the suggestion.  I issued a PR to your suggestion with a slight change.  If you're OK with it, please accept.  --Thanks

**Comment by dacap** [comment]
The modification looks good, we can close this PR and merge the other one.

**Comment by jimdial** [comment]
@dacap: I think you have to accept the PR I made to your branch (for your PR).  Once you do, I think that will update this PR, then I can accept it.  Can you accept the PR I made to your branch?

Thanks

**Comment by dacap** [comment]
Oh sorry about that! I did not realize that your PR was a PR for my PR 😅

**Comment by jimdial** [comment]
It's quite the daisy chain :).  Thanks again! #sign-off

**Pull request merged**
