### PR TITLE
Fixing string equivalence bug

### PR DESCRIPTION
**Pull request by paulpv**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@paulpv__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@ggailey777 
I labeled this mobile-android PR with Modern Apps as that looked like the best fit in our pillar list. Let me know if it should be another pillar. Thanks.

**Comment by ggailey777** [comment]
@ricksal can you verify this customer-provided fix? Thanks.

**Comment by ggailey777** [comment]
@RickSaling can you verify this customer-provided fix? Thanks.

**Comment by ggailey777** [comment]
@RickSaling please verify this fix that the customer has provided.

**Comment by paulpv** [comment]
FYI, I stopped using Azure because of issues similar to this.
In 2.5 months Microsoft has done nothing with this simple Pull Request that is definitely correct and that fixes a definitive string equivalence bug.
Same with many of the other Azure half baked offerings that are full of half promises.
So much for the new Microsoft. (FYI, I used to work at Microsoft [1998-2005]).

**Comment by ggailey777** [comment]
Sincere apologies that it has taken us this long to review your submission. Not to make excuses, but we are still working on automation to make these PRs more discoverable to the topic owners. I've verified your fix and will go ahead and merge it. We do appreciate your help improving our Android code samples. Please do not let this deter you from contributing to Azure docs in the future.

**Pull request merged**
