### PR TITLE
Adding [assembly: OwinStartup(typeof(Startup))].

### PR DESCRIPTION
**Pull request by noopman**
This won't work without the OwinStartupAttribute!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@noopman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@dstrockis - can you review when you have a chance?  Thanks.

**Comment by dstrockis** [comment]
@BryanLa please don't merge yet, I would need to update the quick start code and test it.

**Comment by BryanLa** [comment]
@dstrockis - sounds good

**Comment by BryanLa** [comment]
@dstrockis  - just checking back on this one ...

**Comment by BryanLa** [comment]
@dstrockis - another ping ...

**Comment by BryanLa** [comment]
@dstrockis - ping

**Comment by dstrockis** [comment]
Good to go @BryanLa sorry for the delay

**Comment by BryanLa** [comment]
@dstrockis - thanks! 
@noopman - thanks for the contribution!

**Pull request merged**
