### PR TITLE
Adding Note to File Share Limitation

### PR DESCRIPTION
**Pull request by animetauren**
Azure Files can only be mounted on VMs in the same region, adding this note to prevent mounting errors.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@animetauren__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@animetauren Thanks for the update animetauren.

**Comment by Jim-Parker** [comment]
@Jasontang501 hey Jason, could you please review this contribution?

**Comment by Jasontang501** [comment]
Hi @animetauren

Thanks for the comment, actually the restriction you described has been removed since Azure File Storage GA at 9/29/2015. Right now with the support for encryption in SMB 3.0 customers can mount from anywhere in the world (e.g. from on-premises servers)

For more details please refer to our post below

https://azure.microsoft.com/en-us/documentation/videos/azurecon-2015-azure-files-storage-a-frictionless-cloud-smb-file-system-for-windows-and-linux/ 

https://azure.microsoft.com/en-us/blog/azure-file-storage-now-generally-available/

Let me know if there is more questions.

- Jason Tang | Microsoft Azure Storage team

**Pull request closed without merging**
