### PR TITLE
Update sql-database-elastic-query-overview.md

### PR DESCRIPTION
**Pull request by torsteng**
CSS asked to clarify the relationship to SQL DW. I added a note to the discussion of the scenario to position properly with a reference to SQL DW.

### CODE REVIEW

**Comment by rmca14** [comment]
Please update the "Note" content with the proper syntax. For guidance, see https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/custom-markdown-extensions.md

Please update with the proper link syntax. For guidance, see https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/create-links-markdown.md

Thank you

**Comment by torsteng** [comment]
Since the link in the "Note" content does not refer to a documentation page, I applied the guidance copied below. Let me know if this is not correct. 

I committed the corresponding change to this pull request.

Thanks,
Torsten

To link to a page on ACOM (such as a pricing page, SLA page or anything else that is not a documentation article), use an absolute URL, but omit the locale. The goal here is that links work in GitHub and on the rendered site:
[link text](http://azure.microsoft.com/pricing/details/virtual-machines/)

**Comment by rmca14** [comment]
Also insert the proper "Note" syntax, which is to insert the following in front of the Note text:

> [AZURE.NOTE]

Guidance here, https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/custom-markdown-extensions.md

Thank you

**Comment by torsteng** [comment]
Done. I also adjusted another 'note' paragraph to be consistent across the doc.

**Comment by rmca14** [comment]
Thank you

**Pull request merged**
