### PR TITLE
Convergence

### PR DESCRIPTION
**Pull request by brandwe**
node.js Convergence articles

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brandwe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Hey @brandwe - given that you are a trusted source (ie: from an Azure engineering team), we encourage you to submit your PRs directly against the master branch in the main/private repo: azure-content-pr/master. Please let me know if you are able, or need assistance, and we can close this PR and work w/you there. Thanks!

**Comment by brandwe** [comment]
Don't have access to *-pr. Can you add me?

**Comment by BryanLa** [comment]
Unfortunately, we can't anymore. All repos in the Azure org have to follow the standard access procedures now. You'll find this in the [Tools and Setup section](https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md) of the [azure-content-pr Contributors' Guide](https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md), under [Permissions in GitHub](https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github).  See the paragraph that refers to Microsoft employees. Once you navigate to the site, you'll need to sign in with your GitHub credentials and it will create a connection to your MSFT credentials to set up the right permissions.

There is a ton of additional info in here as well, so please let me know if you need help w/any of this or have any problems.

**Comment by brandwe** [comment]
@BryanLa I've set up this linking and those links give me 404.

**Comment by BryanLa** [comment]
@brandwe - can you access https://azureopensource.azurewebsites.net/account? If you've joined your accounts, you should be able to access this page, assuming you've authenticated with both GitHub and your MSFT credentials on the main page of this site. If you can get that far, you can join the Azure-Content-Read team in the Azure Organization. If you can get that far, LMK and I will work with you internally to resolve.

**Comment by brandwe** [comment]
In -pr now. Thanks for your help @BryanLa. Turns out that I was previously in /Azure org from back in the day and so my permissions were messing up with the automation. I unjoined and rejoined the org. I'm all better :-)

**Comment by BryanLa** [comment]
@brandwe Excellent, and happy to help. I'll work w/you through the azure-content-pr one.

**Pull request closed without merging**
