### PR TITLE
Update key-vault-manage-with-cli.md

### PR DESCRIPTION
**Pull request by BrucePerlerMS**
Remove double dashes (--) from all parameter names

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BrucePerlerMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bruceper). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by BrucePerlerMS** [comment]
ERROR ... this was not done with consensus of the DEV team.

**Comment by BrucePerlerMS** [comment]
ERROR - this change needs to be reviewed by Dev team before I update the topic. And the Dev team needs to be in consensus about what's needed. :)

**Comment by BrucePerlerMS** [comment]
sorry for the spam PR

**Pull request closed without merging**
