### PR TITLE
Update sql-database-copy.md

### PR DESCRIPTION
**Pull request by PatrickAlexander**
I purpose adding few lines to "To copy a SQL database you need the following:"
The document doesn't talk and the user permission required to be able to perform the DB copy task.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@PatrickAlexander__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@PatrickAlexander 
Thank you for your contribution! I'm sending this to the author for validation.
--Carolyn

**Comment by cjgronlund** [comment]
@stevestein
Please check with PR and let me know whether to accept it.

**Comment by stevestein** [comment]
@PatrickAlexander 
Thanks for pointing this out. I'm incorporating your suggestion of required permissions into each of the 'Copy SQL Database' articles. The updated versions should appear online by the end of the week.

**Comment by cjgronlund** [comment]
@PatrickAlexander 
Thank you again for contributing. I'm closing this PR now.

**Pull request closed without merging**
