### PR TITLE
Updating the troubleshooting docker errors document to align with our latest release

### PR DESCRIPTION
**Pull request by dbreshears**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dbreshears__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (devinb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@dbreshears : Thanks for your contribution to the Azure documentation! The author, @allclark, has been notified to review your proposed change.

**Comment by mlearned** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by mlearned** [comment]
ok I'm not assigned as of yet (but will be), can we get it approved and pushed out or do I need to wait to be assigned?

**Comment by mlearned** [comment]
#sign-off

**Comment by allclark** [comment]
#sign-off

**Pull request merged**
