### PR TITLE
Update automation-scenario-aws-deployment.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@MGoedtel Matt, can you take a look at Aleksandar's contribution and let me know if we're good to merge? If so, please sign off. thanks.

**Comment by MGoedtel** [comment]
I just released an update to the article that will be merged today, so I am not going to sign-off on this and I'll make the changes to the updated article this evening and submit a new PR.

**Comment by MGoedtel** [comment]
Alexandair, thanks for taking the time to review and contribute. I had already identified a couple of those items earlier and because I'm preparing to make additional updates to the article, I politely declined your PR and I'll incorporate your changes.

**Comment by alexandair** [comment]
OK.

**Pull request closed without merging**
