### PR TITLE
Removed circular link from Architecture Overview

### PR DESCRIPTION
**Pull request by SidneyAndrewsOpsgility**
http://aka.ms/CnESymbols is a circular link back to this article on azure.com.  Replaced it with the link to the icon set from the download center: http://www.microsoft.com/en-us/download/details.aspx?id=41937

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SidneyAndrewsOpsgility__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@SidneyAndrewsOpsgility Thanks for the contribution!  I've forwarded the change to the author.

**Comment by rboucher** [comment]
Yes. Good catch. 

Actually, I fixed it in another way now so you can close this pull request as fixed without merging it. The aka.ms link was pointing in a circle. I pointed it to the download link now. I wanted to track how many people use that link so I prefer that.

**Comment by seesharprun** [comment]
Thanks @rboucher!

**Comment by rboucher** [comment]
Thanks for reporting it. @SidneyAndrewsOpsgility. I appreciate it.

**Pull request closed without merging**
