### PR TITLE
include config command in ALL 'Learn about deployment...

### PR DESCRIPTION
**Pull request by seanlarge**
Hi,
Following azure documentation can be tricky sometimes and I have been finding myself looping through the rabbit hole of blogs to accomplish one task. Just knowing whether you are in ASM or ARM was a struggle for myself and I am assuming others now that this message is at the beginning of a lot of blog posts. Whichever deployment model the blog is covering, the `azure config mode` asm or arm needs to be included in this message, IMO. It's beyond frustrating to start going through the blog to find out you are in the wrong deployment model and to find out whatever resource was spun up is basically wrong. Better to start the average developer off on the right step. It would be a huge help!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seanlarge__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@seanlarge : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by Ja-Dunn** [comment]
@dlepow - Hi Dan, this contribution affects content that a number of authors on your team use. Would you be willing to review, or identify a more appropriate author here? Thanks!

**Comment by dlepow** [comment]
(cc Cynthia) Hi James, I can review the contribution and will recommend (politely) rejecting it. The contributor has a valid point but I think we’d want to approach the solution case by case in articles and not through the include, which will touch lots of articles with perhaps unintended consequences.

Thanks,

--Dan

**Comment by dlepow** [comment]
@seanlarge - Sean, thanks for the good feedback here. As you note, with CLI content especially customers can find that they need to set the CLI mode explicitly, and we're not consistently providing this guidance. Recent versions of the CLI have changed the default mode, however, so we need to update a number of articles soon. We'll probably find a solution other than modifying the text you pointed out, but we'll try to achieve the same goal.
#please-close

**Comment by seanlarge** [comment]
@dlepow I would like to respectfully push back. Can you explain how there will be unintended consequences?

**Comment by seanlarge** [comment]
for the time being the user should explicitly set whether they are in asm or arm right at the beginning of whatever blog this message show on

**Comment by dlepow** [comment]
@seanlarge - No problem (and I apologize for the terseness of my first comment). I agree entirely with the spirit of your feedback. There's no way for you to know, but the particular text file that you suggest modifying gets included directly in several dozen articles. Some of those articles are about using the CLI, but many are about using Azure PowerShell or the Azure portals, or even other environments. So the CLI-specific instruction in many contexts could be confusing, so that's why I recommend not making the change there. On the positive side, note we're following your suggestion in some of our more recently updated articles - check out https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-quick-create-cli/. We just need to do more of that, right?

**Comment by seanlarge** [comment]
the thing is that command works in powershell on my machine at work and on my mac at home.

**Comment by seanlarge** [comment]
but yes I see that article, it should be noted at the beginning of each article just like that. I would also put it in bold.  Thanks for the quick response.

**Comment by seanlarge** [comment]
if the article says 'this blog follows the classic deployment model' why is it confusing the the reader to make sure they are pointing to that?

**Pull request closed without merging**
