### PR TITLE
table can't be parsed well

### PR DESCRIPTION
**Pull request by SunnyDeng**
@ddove one of the tables in this article has format issue. Even GITHUB can't parse well.  I made a <!-- Loc comment in the .md text. Could you please check further? Thanks!

@v-jacard for tracking.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SunnyDeng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SunnyDeng : Thanks for your contribution to the Azure documentation! The author, @ddove, has been notified to review your proposed change.

**Comment by ddove** [comment]
Hi @SunnyDeng , please merge with your fix. #Merge-as-is #sign-off

**Comment by cjgronlund** [comment]
@SunnyDeng @ddove 
The edit is a loc comment, and shouldn't be published. Please provide a fix that is appropriate to merge.
Thanks!
--Carolyn

**Pull request closed without merging**
