### PR TITLE
Update virtual-machine-scale-sets-windows-create.md

### PR DESCRIPTION
**Pull request by tsubasaxZZZ**
Update a bit miss command parameters

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tsubasaxZZZ__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@davidmu1 - Could you review this proposed update from @tsubasaxZZZ in the public repository?

**Comment by davidmu1** [comment]
@tysonn - The changes look appropriate to me after updating my Azure PowerShell installation to the latest version.

**Comment by tysonn** [comment]
@tsubasaxZZZ - Thank you for the update - merging :)

**Pull request merged**
