### PR TITLE
Make the two types clearer by separating them.

### PR DESCRIPTION
**Pull request by noopman**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@noopman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@msmbaldwin - this seems reasonable to me. Can you review when you have a chance and LMK if you want to merge, or include in any changes you might be making?

**Comment by BryanLa** [comment]
@msmbaldwin - any thoughts on this one?

**Comment by BryanLa** [comment]
@msmbaldwin - just another ping...

**Comment by msmbaldwin** [comment]
I think this is a fine idea.  I'll do the merge ...

**Comment by BryanLa** [comment]
@msmbaldwin - did you want me to merge this, or just incorporate into the next revision of `active-directory-authentication-scenarios`?

**Pull request merged**
