### PR TITLE
Update storage-python-how-to-use-queue-storage.md

### PR DESCRIPTION
**Pull request by ajithps**
QueueMessage class has been refactored. 'message_id' attribute is now 'id'.
https://github.com/Azure/azure-storage-python/blob/master/azure/storage/queue/models.py#L47

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ajithps__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ajithps : Thanks for your contribution to the Azure documentation! The author, @emgerner-msft, has been notified to review your proposed change.

**Comment by emgerner-msft** [comment]
Looks good to me!

**Comment by ajithps** [comment]
@emgerner-msft I think you need to say #sign-off as a comment without which the PRmerger bot doesn't move further :)

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by emgerner-msft** [comment]
#sign-off

**Pull request merged**
