### PR TITLE
Update best-practices-availability-paired-regions.md

### PR DESCRIPTION
**Pull request by adamglick**
Adding the Canada regions

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adamglick__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (aglick). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@adamglick : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
@Jim-Parker 
Change is fine but Adam will need to resolve conflict.
#sign-off

**Comment by adamglick** [comment]
What merge conflict?  If it's easier Rayne can do the update. I was just trying to help out.

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, let me know if you can make the update, per Adam's response. Otherwise, we will need to sync so I can help.

**Comment by rayne-wiselman** [comment]
Hi Adam, I wasn't exactly sure what change you wanted to make since the article actually looked fine. 
I've updated a few other things in the article and submitted a new pull request so you can close this one. 

If you still see any other issues after it republishes fix directly or let me know.

**Pull request closed without merging**
