### PR TITLE
Update to the code for Microsoft Monitoring Agent for Azure Operation…

### PR DESCRIPTION
**Pull request by neumanndaniel**
…al Insights

If you don't use the protectedSettings for the Workspace Key it will be get exposed to the deployment logs etc. You don't want that!

Example: http://www.danielstechblog.de/azure-azure-stack-iaas-vm-arm-mma-operational-insights-template-integration/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@neumanndaniel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@neumanndaniel Thank you for this contribution.  I'll have the author review.

@KundanaP  Would you please review this contribution and let me know if I should merge it?  Thank you.

**Comment by neumanndaniel** [comment]
@deneha @KundanaP It is a bit disappointing to see that nothing has happened the last 18 days on that topic.

**Comment by KundanaP** [comment]
@neumanndaniel @deneha  -  I'm very sorry that I missed this notification. The article looks great! Thanks for writing. There seems to be a minor typo in this sentence " I assume that you have a ready to use IaaS VM ARM template". Rest looks great.

**Comment by deneha** [comment]
@neumanndaniel If you can make that one change @KundanaP suggested and fix the merge conflict on this request, I'll get this merged for you right away.

**Comment by neumanndaniel** [comment]
@deneha @KundanaP My article was only for explaining why I have done the code change for the setting workspaceKey. It is enough for me when you merge my code change.

**Comment by neumanndaniel** [comment]
Ok. I just checked the documentation website. The code change has been done already.
capture1

**Comment by neumanndaniel** [comment]
And you are using the wrong settings:

It is "workspaceId" instead of "workspace_name".

It is "workspaceKey" instead of "workspace_key".

**Comment by deneha** [comment]
@KundanaP Additional feedback here - please check

**Comment by richrundmsft** [comment]
Thanks for pointing out that the field names are incorrect. You are totally right - it should be workspaceId and workspaceKey.

BTW, thanks for writing your blog post - I know it helped to resolve at least one customer issue.

**Pull request merged**
