### PR TITLE
Update date

### PR DESCRIPTION
**Pull request by gbowerman**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gbowerman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (guybo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@gbowerman - Use two-digit date format in the month space.

**Comment by tysonn** [comment]
@gbowerman - Actually, I need you to reach out to @squillace & @cynthn for this update.

**Comment by gbowerman** [comment]
This is a waste of everyone's time just to mark a document as current.

**Comment by squillace** [comment]
@gbowerman Guy, we're in the middle of ripping the entire doc set apart, over 250 topic and thousands of links, so there's a "master" branch freeze at the moment, that is the delay. You can either wait until next week, in which case this will work fine, or you can make the changes in a different branch -- ping me offline and I'll be happy to show you where.

**Pull request closed without merging**
