### PR TITLE
Fix code formatting

### PR DESCRIPTION
**Pull request by dabutvin**
need a newline to get proper formatting

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dabutvin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dabutvin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@dabutvin : Thanks for your contribution to the Azure documentation! The author, @stepsic-microsoft-com, has been notified to review your proposed change.

**Comment by stepsic-microsoft-com** [comment]
#sign-off

**Comment by stepsic-microsoft-com** [comment]
#signoff

**Pull request merged**
