### PR TITLE
modifying articles based on customer feedback

### PR DESCRIPTION
**Pull request by jeffhollan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jeffhollan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jehollan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jeffhollan** [comment]
#signoff

**Comment by jeffhollan** [comment]
#sign-off

**Comment by jeffhollan** [comment]
@ggailey777 sorry didn't add the #sign-off previously but would be great if we could get this merged today.  Thanks

**Comment by ggailey777** [comment]
@jeffhollan I've cherry-picked these commits into the private repo for validation and sign-off there. Closing this PR as no longer needed.

**Pull request closed without merging**
