### PR TITLE
GetAccessTokenAsync() code fix

### PR DESCRIPTION
**Pull request by illeszsolt**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@illeszsolt__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@illeszsolt : Thanks for your contribution to the Azure documentation! The author, @davidmu1, has been notified to review your proposed change.

**Comment by davidmu1** [comment]
@illeszsolt: Thank you for your feedback. @Tyson: Please merge the change.

**Comment by davidmu1** [comment]
This change has already been incorporated into the article.

**Comment by davidmu1** [comment]
@tysonn : Please merge this change.

**Pull request merged**
