### PR TITLE
Outdated code snippet fix

### PR DESCRIPTION
**Pull request by SeanFeldman**
Please review

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@vturecek - Please review this public repo PR

**Comment by SeanFeldman** [comment]
Thank you @tysonn I even forgot about this one :laughing:

**Comment by vturecek** [comment]
Thanks @SeanFeldman, I ended up rolling this fix into a larger documentation update, so it did make it in just in a different PR.

**Comment by SeanFeldman** [comment]
Fantastic. Thank you @vturecek

**Pull request closed without merging**
