### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by carmonmills** [comment]
Narayan is the author of the article.

**Comment by jomolnar** [comment]
@NarayanAnnamalai Hi Narayan. Please resolve the conflicts to enable a merge. Usually, authors of the files are able to fix merge conflicts using the process here on the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve a local merge conflict yourself.aspx). Thanks.

**Comment by NarayanAnnamalai** [comment]
Hi @4c74356b41 ,

Thanks for your contribution to improving Azure documentation. Due to an issue with merge conflict, I am requesting you to please close this PR, the change have been made to the repository already. Thanks again.

**Comment by NarayanAnnamalai** [comment]
#please-close

**Pull request closed without merging**
