### PR TITLE
Update sql-server-stretch-database-predicate-function.md

### PR DESCRIPTION
**Pull request by Antvgski**
updated ownership

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Antvgski__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anvang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Antvgski : Thanks for your contribution to the Azure documentation! The author, @douglaslMS, has been notified to review your proposed change.

**Comment by Antvgski** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by jomolnar** [comment]
@Antvgski This change should be made in the private repo. For information about accessing the private repository, see https://github.com/Azure/azure-content#use-github-git-and-this-repository.

I'm closing this pull request. Thanks.

**Pull request closed without merging**
