### PR TITLE
Note LaunchWorker.ps1 is not required to Web role project

### PR DESCRIPTION
**Pull request by YoungjaeKim**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@YoungjaeKim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@YoungjaeKim : Thanks for your contribution to the Azure documentation! The author, @thraka, has been notified to review your proposed change.

**Comment by Thraka** [comment]
@YoungjaeKim Thanks for the contribution! This is a great note to add. I've updated the wording slightly to match Azure.com styling suggestions. Please [accept a pull request I created](https://github.com/YoungjaeKim/azure-content/pull/2) in your repository. When you do, this PR will automatically be updated.

Thanks again!

**Comment by Thraka** [comment]
#sign-off @KatieCumming

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
