### PR TITLE
feature-parity-between-sbmp-and-amqp

### PR DESCRIPTION
**Pull request by SeanFeldman**
@sethmanheim  please have a look at this. According to my understanding, there's a feature parity between SBMP and AMQP protocols.
/cc @jtaubensee

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SeanFeldman : Thanks for your contribution to the Azure documentation! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by jtaubensee** [comment]
looks good to me. Thanks for catching this Sean.

**Comment by SeanFeldman** [comment]
For a second you got me scared with the issues with this this stale document :smiley:

**Comment by sethmanheim** [comment]
@SeanFeldman Thanks for the contribution Sean! 

#sign-off

**Pull request merged**
