### PR TITLE
A few more typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@mahthi - please review this public repo PR

**Comment by 4c74356b41** [comment]
Sorry, are you talking to me or not?

**Comment by tysonn** [comment]
Nope, @mahthi is the author of this article - he needs to review the updates you submitted :)

**Comment by 4c74356b41** [comment]
Oh, thanks, https://github.com/Azure/azure-content/pull/6532 also this one, I wasn't aware I could just continue editing this one

**Pull request closed without merging**
