### PR TITLE
Update app-service-logic-enterprise-integration-agreements.md

### PR DESCRIPTION
**Pull request by padmavc**
Removed coming soon next to EDIFACT

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@padmavc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@padmavc : Thanks for your contribution to the Azure documentation! The author, @msftman, has been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by padmavc** [comment]
#sign-off

**Pull request merged**
