### PR TITLE
Updated to reflect no support for encrypted VMs

### PR DESCRIPTION
**Pull request by jboeshart**
Backup of encrypted Azure VMs is currently not supported with the Azure Backup VM extension. Updated the document to reflect this.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jboeshart : Thanks for your contribution to the Azure documentation! The author, @Jim-Parker, has been notified to review your proposed change.

**Comment by trinadhk** [comment]
Hi jboeshart
We now support backup for encrypted VMs using PowerShell. We are working on updating documentation for relevant cmdlets. I thank you for your time to improve the documentation for Azure Backup and look forward to seeing more contributions from you.

**Comment by jboeshart** [comment]
Thanks @trinadhk, will go ahead and close this PR.

**Pull request closed without merging**
