### PR TITLE
Incorrect parameter for ServerVersion in the example

### PR DESCRIPTION
**Pull request by nshampur**
The example for 'Starting the upgrade' had an incorrect parameter name (Version should be ServerVersion)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nshampur__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@stevestein - Here's a public repo contribution to review

**Comment by stevestein** [comment]
@nshampur - thanks for pointing this out and submitting the fix!
@cjgronlund - this is good to merge and publish.
#sign-off

**Comment by cjgronlund** [comment]
@nshampur 
Thank you for your contribution!
--Carolyn

**Comment by nshampur** [comment]
Welcome!

**Pull request merged**
