### PR TITLE
Deleting duplicate video references

### PR DESCRIPTION
**Pull request by odvoskin**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@odvoskin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@odvoskin : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@SyntaxC4 - Cory, can you review this pull request in the public repo?

**Comment by SyntaxC4** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
