### PR TITLE
Corrected the description for AKV Principal Secret

### PR DESCRIPTION
**Pull request by AndyHerb**
@tysonn - Replication of #5843 into new repository

Corrected the description of the AKV Principal Secret parameter in the Key Vault Integration section

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndyHerb__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@MikeRayMSFT - Could you please review this update from @AndyHerb pls?

**Comment by tysonn** [comment]
@MikeRayMSFT - second notice on review of public PR

**Comment by MikeRayMSFT** [comment]
Thanks Tyson. I’m trying to remember how to merge the changes.

**Comment by tysonn** [comment]
I'll take that as sign off. Merging.

**Comment by MikeRayMSFT** [comment]
Thank you and please merge

**Pull request merged**
