### PR TITLE
Update sql-data-warehouse-overview-load.md

### PR DESCRIPTION
**Pull request by TwoUnder**
Link update and the addition of the SqlBulkCopy class.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TwoUnder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mausher). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@barbkess 
Please review and approve, thanks.

**Comment by rmca14** [comment]
@JennieHubbard 
Hi, Jennie. Can you please review and let me know if I should merge this PR? Barb is apparently OOF. Thanks.

**Comment by JennieHubbard** [comment]
Approved!

**Comment by rmca14** [comment]
Separate mail sent to author re merge conflict.

**Pull request closed without merging**
