### PR TITLE
Update Azure AD B2B Limitations documentation

### PR DESCRIPTION
**Pull request by egbill3eagle**
Added additional clarity for distribution lists not being supported instead of assuming reader knows what DL's stands for.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@egbill3eagle__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@egbill3eagle : Thanks for your contribution to the Azure documentation! The author, @viv-liu, has been notified to review your proposed change.

**Comment by viv-liu** [comment]
Thanks for the added clarity and keen eye! #sign-off

**Comment by viv-liu** [comment]
#sign-off

**Pull request merged**
