### PR TITLE
Update app-service-api-java-api-app.md

### PR DESCRIPTION
**Pull request by miyohide**
update the path of Contact.java and ContactsApiServiceImpl.java.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@miyohide__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@bradygaster can you verify the path fix provided by the customer?

**Comment by bradygaster** [comment]
Looks good.

**Comment by ggailey777** [comment]
@miyohide thanks for you contribution to this topic. We appreciate your help with Azure documentation.

**Pull request merged**
