### PR TITLE
Updated lots of SQL VM aspects that have either changed over the past…

### PR DESCRIPTION
**Pull request by luisherring**
… year or were incorrect.

Updated lots of SQL VM aspects that have either changed over the past year or were incorrect.

Please apply ASAP. Contact me with any questions.

Luis Vargas (Principal PM leading SQL VM)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@luisherring__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lvargas). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@luisherring : Thanks for your contribution to the Azure documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
@cjgronlund @tysonn  can you help expedite this merger?

**Comment by CarlRabeler** [comment]
@KatieCumming can you help expedite this merger?

**Comment by luisherring** [comment]
Thanks Carl.

When do you think this will  be updated in production.

Thanks!,
Luis

**Comment by CarlRabeler** [comment]
Investigating – assuming it will be live by 11 PM today. Will follow up in a few hours.
Carl

**Pull request merged**
