### PR TITLE
s/sush/such

### PR DESCRIPTION
**Pull request by davidbetz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@davidbetz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@davidbetz : Thanks for your contribution to the Azure documentation! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by MikeWasson** [comment]
Good catch, thanks! #sign-off

**Comment by MikeWasson** [comment]
@davidbetz I'll fix the typo on my end, no need to resolve the merge conflict. 😺 Thanks again for the fix.

#please-close

**Pull request closed without merging**
