### PR TITLE
Update virtual-machines-windows-extensions-dsc-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @zjalexander, has been notified to review your proposed change.

**Comment by zjalexander** [comment]
@alexandair looks good, thanks so much! ready to merge

**Comment by zjalexander** [comment]
@alexandair sorry, i didn't use the right keywords, and in the meantime I had to update the article content with my own stuff. Can you take a look at it again? #hold-off

**Comment by cynthn** [comment]
@alexandair thank you for the contributions! Since this file has been changed quite a bit since you submitted your fixes, there are now merge conflicts. I believe the original writer incorporated your changes in his updates, so we will probably close out this PR. Thanks again for helping to make the documentation better!

**Pull request closed without merging**
