### PR TITLE
Update sql-database-implementation-umbraco.md

### PR DESCRIPTION
**Pull request by mcollier**
Fix a minor typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mcollier__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mcollier). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mcollier : Thanks for your contribution to the Azure documentation! The author, @carlrabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

@mcollier thanks for the catch. PR approved.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by CarlRabeler** [comment]
I am the author
#sign-off

**Comment by CarlRabeler** [comment]
looks like issue with case sensitivity - fixing

**Pull request merged**
