### PR TITLE
Update iot-hub-mqtt-support.md

### PR DESCRIPTION
**Pull request by kdotchkoff**
Updates of MQTT implementation details

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kdotchkoff__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kdotchko). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@kdotchkoff : Thanks for your contribution to the Azure documentation! The author, @kdotchkoff, has been notified to review your proposed change.

**Comment by kdotchkoff** [comment]
#sign-off

**Comment by kdotchkoff** [comment]
#sign-off

**Comment by dominicbetts** [comment]
@kdotchkoff - Hi Konstantin, you can submit your changes more easily through the azure-content-pr repo rather than this public repo.

**Comment by dominicbetts** [comment]
#sign-off 
Please accept this PR

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
