### PR TITLE
Update backup-azure-vms-automation.md

### PR DESCRIPTION
**Pull request by bgener**
Corrected syntax of New-AzureResourceGroup powershell cmdlet and its parameters

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bgener__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@bgener Thanks for the contribution.  I'll have the article owner review.

@aashishr @Jim-Parker Would you please comment in this request to let me know if I should merge it?

**Comment by deneha** [comment]
@bgener This request has merge conflicts.  Would you please resolve the merge conflict so I can merge the request?

**Comment by deneha** [comment]
Closing this request due to inactivity.  @bgener Please comment if you would like this request reopened so you may fix the merge conflict.

**Pull request closed without merging**
