### PR TITLE
Moved the section that explains how to create the HDI cluster up

### PR DESCRIPTION
**Pull request by arkulkarni**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arkulkarni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@Blackmist 
Please check this PR, and let me know whether to accept.

**Comment by cjgronlund** [comment]
@arkulkarni 
Thank you for your contribution. I've sent this PR to the author for verification, and I'll get back shortly.
--Carolyn

**Comment by tysonn** [comment]
@Blackmist - second notice on public PR

**Comment by Blackmist** [comment]
Duplicate of https://github.com/Azure/azure-content/pull/6091, which has already been merged.

**Comment by cjgronlund** [comment]
@arkulkarni @Blackmist 
Thanks for the information. I'll close this PR.

**Pull request closed without merging**
