### PR TITLE
Update biztalk-backup-restore.md

### PR DESCRIPTION
**Pull request by MandiOhlinger**
Content Freshness: updated date.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MandiOhlinger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by MandiOhlinger** [comment]
#sign-off

**Comment by davidwrede** [comment]
@MandiOhlinger, seems like this is out-of-date. Can I close this PR?

**Comment by MandiOhlinger** [comment]
Yes. Closing PR.

**Pull request closed without merging**
