### PR TITLE
Update app-insights-java-get-started.md

### PR DESCRIPTION
**Pull request by OriYosefiMSFT**
Created a [URL redirector](https://aka.ms/aijavasdk) to point to the download site holding the most recent download files. This site has changed but may change again in the future.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@OriYosefiMSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (oriy). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by alancameronwills** [comment]
#sign-off

**Comment by alancameronwills** [comment]
#sign-off

**Comment by PRmerger** [comment]
@OriYosefiMSFT : Thanks for your contribution to the Azure documentation! The author, @alancameronwills, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
#sign-off

**Comment by alancameronwills** [comment]
#sign-off

**Pull request merged**
