### PR TITLE
Updated owners list

### PR DESCRIPTION
**Pull request by roopalik**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@roopalik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
Please resolve the merge conflict. Thanks.

**Comment by rmca14** [comment]
If you need guidance about how to resolve a local merge conflict, see http://sharepoint/sites/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx

**Comment by rmca14** [comment]
Closed due to inactivity.

**Pull request closed without merging**
