### PR TITLE
Add string/int 2 more functions documentation

### PR DESCRIPTION
**Pull request by linweigao**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@linweigao__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by linweigao** [comment]
I have just joined Microsoft Azure organization on GitHub. Shall I still go through this license agreement?

**Comment by tfitzmac** [comment]
@jimbe This pull request can be closed. We need to wait before publishing these additions and I will re-submit through a new pull request when ready.

**Comment by jimbe** [comment]
Closing per tfitzmac.

**Pull request closed without merging**
