### PR TITLE
Fix link to cmdlet

### PR DESCRIPTION
**Pull request by lukos**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lukos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@lukos : Thanks for your contribution to the Azure documentation! The author, @tfitzmac, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@lukos - thanks for catching this broken link. I changed the URL to the Azure PowerShell 2.0 version of the cmdlet. Because that URL includes parenthesis for the version number, I had to move it to a referenced link. If you accept the PR in your branch, we can merge this.

**Comment by tfitzmac** [comment]
#sign-off

**Pull request merged**
