### PR TITLE
Update automation-troubleshooting-automation-errors.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed some typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@SnehaGunda Sneha, can you take a look at Aleksandar's contributions to this article and sign-off if they are correct? Thanks,

**Comment by SnehaGunda** [comment]
@alexandair thanks for your contribution. We'll merge the changes.

**Comment by SnehaGunda** [comment]
#sign-off

**Pull request merged**
