### PR TITLE
Azure AD's graph API can't send mail... yet.

### PR DESCRIPTION
**Pull request by rhencke**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rhencke__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rhencke** [comment]
@azurecla You're always such a friendly chap.

**Comment by dstrockis** [comment]
Haha, well played @rhencke.  Thanks for the catch.  @BryanLa should be merging this fix shortly.

**Comment by rhencke** [comment]
Thanks, @dstrockis @BryanLa ! :)

**Comment by BryanLa** [comment]
@rhencke  - You're welcome, and thanks a ton for your contribution!

**Pull request merged**
