### PR TITLE
Fix link to iOS SDK to reference

### PR DESCRIPTION
**Pull request by vt-cezary**
The link referenced the old version (Azure Mobile Services iOS SDK) which is discontinued in favor of Azure Mobile App iOS SDK

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vt-cezary__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@vt-cezary : Thanks for your contribution to the Azure documentation! The author, @krisragh, has been notified to review your proposed change.

**Comment by krisragh** [comment]
@vt-cezary thanks for your contribution, and good catch on the updated link. I appreciate your update! I notice that the new link you have (changelog.md) doesn't actually have a download link on that page. 

How about updating that link to https://github.com/Azure/azure-mobile-apps-ios-client/blob/master/README.md#ios-client-sdk instead? (I don't have permissions to do this since you opened this PR.)

**Comment by krisragh** [comment]
@vt-cezary looks good, thanks for the update. @ggailey777 and @tysonn it's OK to go ahead and merge this.

**Comment by ggailey777** [comment]
@vt-cezary Thanks for helping to improve the quality of Azure docs.

**Pull request merged**
