### PR TITLE
Azure Search: Removing deprecated useJsonParser

### PR DESCRIPTION
**Pull request by seansaleh**
The deprecated configuration value  "parameters" : { "configuration" : { "useJsonParser" : true } },  was referenced in the docs. Instead you should use  "parameters" : { "configuration" : { "parsingMode" : "json" | "jsonArray" } }

### CODE REVIEW

**Comment by seansaleh** [comment]
@chaosrealm @brjohnstmsft

**Comment by azurecla** [comment]
Hi __@seansaleh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (seasa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by brjohnstmsft** [comment]
@seansaleh I have a big PR pending in azure-content-pr. I'll incorporate these changes into my PR to avoid merge issues later. Please close this PR.

**Comment by seansaleh** [comment]
Closing as per @brjohnstmsft's request

**Pull request closed without merging**
