### PR TITLE
Tweak language and usage (on-premises instead of on-premise, etc.) in virtual-networks-name-resolution-for-vms-and-role-instances.md

### PR DESCRIPTION
**Pull request by timothywarner**
Besides the on-premise bit (an admitted pet peeve of mine; I feel it reduces Microsoft's credibility when its cloud service documentation uses incorrect terminology), I also made some simply formatting tweaks to make the article easier to digest. That's what I hope, anyway. :) Thanks, Tim

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@timothywarner__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@timothywarner : Thanks for your contribution to the Azure documentation! The author, @GarethBradshawMSFT, has been notified to review your proposed change.

**Comment by timothywarner** [comment]
Hello? :) -Tim

**Comment by telmosampaio** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by Ja-Dunn** [comment]
@telmosampaio @GarethBradshawMSFT - The changes look good for the most part, but the markdown for the notes is actually correct in the original version. Making these changes would result in incorrect formatting of the notes. Please revert. Thanks!

**Comment by jimdial** [comment]
@timothywarner Thank you for the edits. The change you made for the note formatting is incorrect, so I'm going to close this PR.  Separately, we will incorporate the on-premise to on-premises change you submitted. @GarethBradshawMSFT 

Thanks

#please-close

**Pull request closed without merging**
