### PR TITLE
update links (one broken, the others just outdated syntax)

### PR DESCRIPTION
**Pull request by conceptdev**
Fixing links (customer reported a broken link via DISQUS)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@conceptdev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by jimbe** [comment]
Hi Craig. Thanks for fixing these links. But the first link ("Get started with data") is missing (see View on Files changed tab). Can you add it back in? Thanks - Jim

**Comment by conceptdev** [comment]
hey @jimbe - not sure what you mean. I *think* I just updated the link formats... the diff shows 4 lines changed but none completed removed:

screen shot 2015-07-09 at 4 26 53 pm

**Comment by jimbe** [comment]
If you go into the Files changed tab, and then View/Raw data, near the bottom of the file the list of links is missing the Get started with data link:
capture

**Comment by conceptdev** [comment]
Ah, I was confused by your comment
> Can you add it back in?

because it is not currently displayed on the live site, so it was not something I "removed". Here is the currently 'live' link list:

next-steps

Looking closely at the doc [get started with data](https://azure.microsoft.com/en-us/documentation/articles/partner-xamarin-mobile-services-ios-get-started-data/) it looks like it's mostly a repeat of this page, except that it includes the steps for "Add a new table to the mobile service" section. I've added a new link to this page, as you requested.

**Comment by jimbe** [comment]
Thanks Craig.

**Pull request merged**
