### PR TITLE
Add in note: dependency on C# extension in VSCode

### PR DESCRIPTION
**Pull request by snlacks**
Without the C# extension in Visual Studio Code, the DNX extension won't be available.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snlacks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@Erikre I don't know if you still own this topic, but I'm fairly sure that this PR will break the [AZURE.NOTE] rendering after I merge it.

**Comment by Erikre** [comment]
Based on Glenn's feedback, it looks like we should close this PR (not publish).

**Comment by tysonn** [comment]
@Erikre - Can you review the actual techical content of the update and make the decision based on that? Any potential fomatting issue is easily fixed and shouldn't play into whether this is merged or not :)

**Comment by Erikre** [comment]
@tysonn - Yes, the content is okay. If a formatting issue occurs, your fix would be appreciated. Please merge.

**Comment by Erikre** [comment]
@tysonn - Got it. Because I can't edit the existing PR, let's close this and I'll create a new PR with my changes. Thanks you.

**Comment by ggailey777** [comment]
@snlacks I cherry-picked your commit into the private repo so that I could test-out the formatting of the note. @Erikre  Please check [this topic](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-app-using-vscode/#run-the-web-app-locally) on the site tomorrow after noon to verify that my updates are correct.  
Thanks for your contribution to improving the quality of Azure docs.

**Comment by Erikre** [comment]
@ggailey777 - Looks good. Thanks!

**Pull request closed without merging**
