### PR TITLE
Rule entity name max length

### PR DESCRIPTION
**Pull request by SeanFeldman**
should be documented

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by SeanFeldman** [comment]
@sethmanheim please review

**Comment by tysonn** [comment]
@sethmanheim - Could you review this proposed change from @SeanFeldman in the public repo?

**Comment by sethmanheim** [comment]
@SeanFeldman Hi Sean, and thanks again for the submission. I have to ask though, whether anyone from the engineering team confirmed this limit?

**Comment by sethmanheim** [comment]
@SeanFeldman Thanks again, this looks good! @tysonn OK to merge.

**Pull request merged**
