### PR TITLE
Fixed StorageAccount key command

### PR DESCRIPTION
**Pull request by mahedley**
The script used the classic get-azurestorageaccountkey command when referencing an ARM object. Replaced with get-AzureRMStorageAccountKey

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mahedley__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@nitinme 
Please check the content change here, and let me know whether I should accept the PR.

**Comment by nitinme** [comment]
@mumian 
Passing this on to Jonathan because he has been looking more into the HDI docs lately.

**Comment by mumian** [comment]
The article has been updated long time back.  You can close this request.

**Comment by cjgronlund** [comment]
@mahedley 
Thank you for this suggestion. The updated article included these ideas.
--Carolyn

**Pull request closed without merging**
