### PR TITLE
Load balancer docs spelling error (ned to need)

### PR DESCRIPTION
**Pull request by microsoftman**
Changed ned to need for a spelling error: fixed "where the NICs ned to be created" to "where the NICs need to be created"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@microsoftman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@microsoftman : Thanks for your contribution to the Azure documentation! The author, @joaoma, has been notified to review your proposed change.

**Comment by joaoma** [comment]
#sign-off

**Comment by joaoma** [comment]
Thank you for your contribution! I appreciate the input!

**Comment by PRmerger** [comment]
@microsoftman : Thanks for your contribution to the Azure documentation! The author, @joaoma, has been notified to review your proposed change.

**Pull request merged**
