### PR TITLE
Fixed minor formatting issue

### PR DESCRIPTION
**Pull request by jboeshart**
Fixed a minor formatting issue where a couple of images weren't showing up.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jboeshart : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by cjgronlund** [comment]
@MikeRayMSFT @JennieHubbard 
Please let me know what I should do with this PR. Thanks!

**Comment by MikeRayMSFT** [comment]
@cjgronlund @JennieHubbard 
I'm looking over the changes now. Thanks for raising it to my attention.

**Comment by MikeRayMSFT** [comment]
@jboeshart, thank you very much for submitting this change. Your submission was spot on. I have been working on an update for the document in a different pull request so I manually integrated your change. Thanks again for helping us make Azure docs better.

**Comment by MikeRayMSFT** [comment]
@cjgronlund,

Can we please close this pull request? I already had a PR open for other changes in this same space. I have incorporated the changes proposed by @jboeshart and signed off on the other request in the private repo.

**Comment by JennieHubbard** [comment]
@jboeshart per @MikeRayMSFT request please close this PR

**Comment by jboeshart** [comment]
Closing since @MikeRayMSFT already included these changes in his PR. Thanks all!

**Pull request closed without merging**
