### PR TITLE
Guide users to not install R versions of PowerCLI

### PR DESCRIPTION
**Pull request by RudiGroenewald**
I had an issue at a customer where we installed the latest R version of PowerCLI on our processing server which caused a significant amount of troubleshooting for a week.  We lost a lot of time.  We couldn't uninstall the R3 version and just install "RTM" as when R3 is installed, the code is stuck in there even when installed 6.0.  We had to rebuild our processing server from scratch.  When you look at the download page, I believe you are compelled to want to get the latest version, which is the issue we got stuck on.  The edit is to try and avoid other pros from making this mistake.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RudiGroenewald__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@RudiGroenewald : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
correct but language needs changes

Please change from : "Ensure to install Version 6.0 and not the R versions"
To: "Currently other versions of PowerCLI aren't supported, including R releases of version 6.0."
@azurecla

**Comment by RudiGroenewald** [comment]
Changes done!  Thanks @rayne-wiselman

**Comment by rayne-wiselman** [comment]
Thank you for  your contribution Rudi. Great to see folks participating in our documentation!

**Pull request merged**
