### PR TITLE
Update resource-group-rbac.md

### PR DESCRIPTION
**Pull request by pcgeek86**
Added details about RBAC "actions" to documentation.

/cc @tfitzmac @cabailey 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
@pcgeek86 thanks for submitting this change. It looks good. The PowerShell command needs to be changed to Get-AzureRmProviderOperation (without Resource)

**Comment by pcgeek86** [comment]
@tfitzmac Tom, sorry about that oversight. I've fixed it.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by tfitzmac** [comment]
@davidwrede this pull request can be merged.
Thanks Trevor!

**Pull request merged**
