### PR TITLE
Update service-fabric-reliable-services-communication-webapi.md

### PR DESCRIPTION
**Pull request by CJM81**
Changed public to internal

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CJM81__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@CJM81 : Thanks for your contribution to the Azure documentation! The author, @vturecek, has been notified to review your proposed change.

**Comment by vturecek** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@vturecek - Hi Vaclav, please fix this merge conflict. If you need guidance, please see the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx) for instructions on fixing it. Thanks, Katie

**Comment by vturecek** [comment]
@KatieCumming can you close this out? I had to issue another PR to resolve merge conflicts (#32373)

**Pull request closed without merging**
