### PR TITLE
Added SAS token usage at AMQP level

### PR DESCRIPTION
**Pull request by ppatierno**
Added how to use and send the SAS token to the Service Bus at AMQP level with an example in C#.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ppatierno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@ppatierno__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by djrosanova** [comment]
Approved. Great addition!

**Comment by ppatierno** [comment]
Great ! Thanks ;-)

**Pull request merged**
