### PR TITLE
Update virtual-machines-linux-create-upload-centos.md

### PR DESCRIPTION
**Pull request by maxirus**
Steps for CentOS 7+ are incorrect and will not lead to a successful VM launch. The kernel will go into Crash Recovery mode and the VM will ultimately fail to launch. The following additions correct these issues. Note: These additional steps will most likely be required in RHEL 7+ as well though I have not tested it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@maxirus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@szarkos / @RicksterCDN - Could you review this proposed update from @maxirus and let me know if it's good to merge?

**Comment by szarkos** [comment]
Some of these look fine, but I think the root of the problems is due to prepping the image on Virtualbox.  This document presumes you are prepping the image on Hyper-V.  That's also why you're seeing the "[Errno 5] Input/output error" - for some reason we can't log to /dev/console under vbox.

It may be better to add some of those notes to the following document since they are not all specific to CentOS: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-generic/#linuxinstall

You also shouldn't have to reboot after changing the kernel, except maybe to test the changes.  The net.ifnames=0 is a good change. It's not necessary in this case, but it's actually part of some of the Openlogic images already.

**Comment by szarkos** [comment]
@tysonn if there's no desire to modify the PR then I can just take this feedback and integrate the changes into the appropriate docs, ok?

**Comment by szarkos** [comment]
OK, I've taken the feedback and integrated it into multiple docs.  I think we can close this for now.  Thanks!

**Comment by tysonn** [comment]
@maxirus - Thanks for the contributions...the author incorporated via other PRs to multiple articles.

**Pull request closed without merging**
