### PR TITLE
[Azure Stack] Increas concurrent VPN connections

### PR DESCRIPTION
**Pull request by ostrich75**
Concurrent VPN connections is limited to the number of ports instead of # of local user. In order to increase concurrent VPN connection, Our customer doesn't need to create additional local users but use the command "netsh ras set wanports device="WAN Miniport (L2TP)" maxports=10" and modify the maxports.

Also fix some typo and format issue.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ostrich75__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (larryzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ostrich75** [comment]
#sign-off

**Comment by ostrich75** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@ostrich75__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (larryzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ostrich75** [comment]
#sign-off

**Pull request closed without merging**
