### PR TITLE
Update app-service-api-dotnet-swashbuckle-customize.md

### PR DESCRIPTION
**Pull request by rachelappel**
Freshness update

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rachelappel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rachelap). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bradygaster** [comment]
LGTM

**Comment by rachelappel** [comment]
#sign-off then

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by bradygaster** [comment]
#sign-off

**Pull request merged**
