### PR TITLE
Update hdinsight-apache-spark-zeppelin-notebook-jupyter-spark-sql.md

### PR DESCRIPTION
**Pull request by aniedea**
typo -- select "SPARK" not "Hadoop" for cluster type

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aniedea__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (aniedea). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by aniedea** [comment]
typo -- select "SPARK" not "Hadoop" for cluster type

**Comment by azurecla** [comment]
Hi __@aniedea__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (aniedea). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@nitinme 
fyi

**Pull request merged**
