### PR TITLE
Update virtual-machines-linux-remote-desktop.md

### PR DESCRIPTION
**Pull request by jinmiaoms**
Made some grammatical changes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jinmiaoms__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@SuperScottz 
Please review and approve or disapprove this pull request with a comment here. Thanks.

**Comment by rmca14** [comment]
@superscottz 
Please review this pull request and approve or disapprove with a comment here. Thanks.

**Comment by deneha** [comment]
@jinmiaoms This request has merge conflicts.  Would you please fix the merge conflict?

**Comment by SuperScottz** [comment]
I have created another pull request to merge the change from this one, let's close this.
https://github.com/Azure/azure-content-pr/pull/15636

@jinmiaoms Thank you for decent feedback!

**Pull request closed without merging**
