### PR TITLE
Update data-lake-analytics-documentation-backlog.md

### PR DESCRIPTION
**Pull request by saveenr**
Request for range-based join doc

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saveenr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (saveenr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@mumian 
Please review and approve/disapprove this PR with a comment. Thanks.

**Comment by rmca14** [comment]
@mumian 
Following up, thanks.

**Comment by mumian** [comment]
#sign-off

**Pull request merged**
