### PR TITLE
Update app-insights-proactive-detection.md

### PR DESCRIPTION
**Pull request by antonfrMSFT**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@antonfrMSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by alancameronwills** [comment]
Editors, please accept.

**Comment by ggailey777** [comment]
@alancameronwills can you work with @antonfrMSFT to fix the merge conflicts in the PR, or if you don't need it anymore please close it.

**Comment by ggailey777** [comment]
Closing this due to unresolved merge conflict. If you still need this fix in the public repo, please reopen the PR and fix the conflict.

**Pull request closed without merging**
