### PR TITLE
Update automation-variables.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed some typos in code snippets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@bwren Brian, can you please review this change?

**Comment by bwren** [comment]
@alexandair Appreciate those corrections.  Thanks!

**Comment by bwren** [comment]
#sign-off

**Pull request merged**
