### PR TITLE
Update virtual-machines-linux-how-to-attach-disk.md

### PR DESCRIPTION
**Pull request by ksasagit**
Fix wrong mount point for systems based on SUSE Linux.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ksasagit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@ksasagit Thank you for this contribution.  I'll have the author review.

@dsk-2015 Would you please review this change and let me know if I should merge?  Thank you.

**Comment by ksasagit** [comment]
How about this?
Mounting data disk to / (root directory) is not appropriate...
Please fix it to appropriate mount point "/datadrive".
Thanks,

**Comment by deneha** [comment]
@dsk-2015 Please review this request when you have a moment and signoff

**Comment by dsk-2015** [comment]
#sign-off . Thanks for fixing this @ksasagit

**Comment by deneha** [comment]
@ksasagit Could you please fix the merge conflict so I may merge this for you?

**Comment by tysonn** [comment]
Resolved merge conflict. Thank you for the update!

**Pull request merged**
