### PR TITLE
simple rename, typos

### PR DESCRIPTION
**Pull request by mlearned**
renaming title, taking ownership of article, fixing typos

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mlearned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mlearned : Thanks for your contribution to the Azure documentation! The author, @mlearned, has been notified to review your proposed change.

**Comment by azurecla** [comment]
Hi __@mlearned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@mlearned  - Hey, please work in the private repo - see https://microsoft.sharepoint.com/teams/azurecontentguidance/article-author-working-in-the-public-repo

**Comment by mlearned** [comment]
Ok yea sorry, I clicked on edit in git hub on my nav there ☹

**Pull request closed without merging**
