### PR TITLE
Update virtual-machines-windows-classic-create-powershell.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos in text and code. (Shortcut to Azure PowerShell command prompt is removed in the latest 2 versions of Azure PowerShell modules.) Also, consider removing copy/pasting to a text file. PowerShell ISE should be used as an editor.

### CODE REVIEW

**Comment by alexandair** [comment]
@tysonn New PR.

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cynthn - @alexandair has proposed some changes in this article, could you please review and let me know if I can merge?

**Comment by cynthn** [comment]
#sign-off @tysonn these changes look fine.

**Pull request merged**
