### PR TITLE
fix typo: device -> devise

### PR DESCRIPTION
**Pull request by srehorn**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@srehorn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@srehorn : Thanks for your contribution to the Azure documentation! The author, @btardif, has been notified to review your proposed change.

**Comment by btardif** [comment]
Looks good, thanks for the correction! #sign-off

**Comment by btardif** [comment]
#sign-off

**Comment by btardif** [comment]
@tysonn this can be merged as is.

**Pull request merged**
