### PR TITLE
Fix the grammar issues of sample code

### PR DESCRIPTION
**Pull request by metacpp**
There're 2 issues in the sample code of the documentation:

1. static keyword should be put before async keyword.
2. Missing "using System.Threading.Tasks;".

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@metacpp__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@metacpp : Thanks for your contribution to the Azure documentation! The author, @adhurwit, has been notified to review your proposed change.

**Comment by metacpp** [comment]
The original source code of the document contains lots of mixed use of spaces and tabs as indention, which should be consistent across the whole code base.

**Comment by metacpp** [comment]
@adhurwit can you take a look at my PR ?

**Comment by adhurwit** [comment]
thanks for the pr
#sign-off

**Pull request merged**
