### PR TITLE
Fix Get-AzureRmLocation sample

### PR DESCRIPTION
**Pull request by SvenAelterman**
Fix property to compare from **Name** to **Providers**
Fix value from **Microsoft.Sql/servers** to **Microsoft.Sql**
Fix property name from **Locations** to **Location**
Fix capitalization and spacing

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SvenAelterman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@stevestein - Please review this proposed change from @SvenAelterman in the public repository.

**Comment by stevestein** [comment]
#sign-off 
@SvenAelterman - Good catch! 

FYI - this cmdlet has been churning a bit (https://github.com/Azure/azure-powershell/issues/1299) and was removed and just added back into the module for the May release. Looks like it's tagged to possibly change again in the future.

Thanks for the edit/update!

**Comment by stevestein** [comment]
@cjgronlund  - this update is good to push live. Thanks.

**Pull request merged**
