### PR TITLE
Specify details for start menu applications

### PR DESCRIPTION
**Pull request by cdavid**
When the user creates the template image for RemoteApp, they should specify a particular shortcut file (.lnk) in a particular location (Start menu folder for all users). This was not previously specified and this patch addresses that issue.

Please contact elizapo for signoff.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cdavid__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@cdavid__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by lizap** [comment]
I talked with Catalin and added these changes to an open PR in the private repo. Closing this PR in favor of this one: https://github.com/Azure/azure-content-pr/pull/15020

**Comment by BryanLa** [comment]
@lizap - I noticed this is still open; LMK if you would like me to close.

**Comment by BryanLa** [comment]
@lizap - went ahead and closed this one, per your recommendation (in addition to the fact that it's in a merge conflict state now as well)

**Pull request closed without merging**
