### PR TITLE
Update data-factory-use-custom-activities.md

### PR DESCRIPTION
**Pull request by ahkim**
Considering that this is a sample for .Net custom activity, "osType": "Linux" wouldn't be relevant. I propose changing this to either "Windows" or remove the line itself.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@spelluru - Could you review this proposed update from @ahkim in the public repo?

**Comment by spelluru** [comment]
Yes. Makes sense.

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
