### PR TITLE
Corrected Selecting Azure Resource Manager Subscription

### PR DESCRIPTION
**Pull request by RezaMahmood**
Corrected syntax to use Select-AzureRMSubscription otherwise the subscription does not get picked up in the context of Resource Manager and will default to whatever subscription is selected when using Select-AzureSubscription.  Problematic when you have multiple subscriptions.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RezaMahmood__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cynthn - Could you please review this public repo update from @RezaMahmood?

**Comment by cynthn** [comment]
@tysonn I don't think this change applies anymore. The topic was recently updated and the change has already been made in the text. I think this is why there is also a merge conflict for this change?

**Comment by tysonn** [comment]
OK. That is likely why there are merge conflicts. @RezaMahmood - thanks for the update, I apologize for the delay in review. It sounds like this was fixed already, so I'm closing the PR.

**Pull request closed without merging**
