### PR TITLE
Update service-bus-resource-manager-namespace-event-hub.md

### PR DESCRIPTION
**Pull request by ShubhaVijayasarathy**
Changes added to reflect the service changes and separating Service Bus Messaging from Event Hub

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ShubhaVijayasarathy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ShubhaVijayasarathy : Thanks for your contribution to the Azure documentation! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by ShubhaVijayasarathy** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by ShubhaVijayasarathy** [comment]
Closing as the updates are no more required

**Comment by azurecla** [comment]
Hi __@ShubhaVijayasarathy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (shvija). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Pull request closed without merging**
