### PR TITLE
Update machine-learning-faq.md

### PR DESCRIPTION
**Pull request by ahgyger**
Clarifying how many modules can execute in parallel.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahgyger__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@ahgyger 
Thank you for your contribution. I'm sending this to the author for verification.

**Comment by cjgronlund** [comment]
@pablissima @garyericson 
Please verify this change. Thanks!

**Comment by cjgronlund** [comment]
@garyericson 
#sign-off

**Pull request merged**
