### PR TITLE
Corrected upload blob example to match library

### PR DESCRIPTION
**Pull request by dazfuller**
The methods in the Azure Storage SDK no longer contain the "block" part of the name, removed from the Upload example

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dazfuller__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@emgerner-msft - Please review this pull request from @dazfuller  in the public repository and let me know if the changes should be merged.

**Comment by emgerner-msft** [comment]
@tysonn JC fixed this in the internal content repo 4 days ago and it was merged and published. The [python blob article](https://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-blob-storage/) looks correct. The change for some reason isn't in the public repo though. Merging this could cause some nasty merge issues depending on the process you use...

**Comment by dazfuller** [comment]
@tysonn Just caught up on this, the public repo and the article look fine now, I'm guessing I must have submitted a change around the same time as the article was being updated.  I'll close this pull request by tomorrow morning unless anyone wants to hang on to it.

**Comment by tysonn** [comment]
@dazfuller - Thanks, I've closed.

**Pull request closed without merging**
