### PR TITLE
Please add reference for HDInsight properties

### PR DESCRIPTION
**Pull request by ahkim**
> For the clusterSize property, specify the size of the HDInsight cluster.

Please give a reference to mapping document which shows what each integer value means which spec of cluster size. The sample code shows following

> "clusterSize": 4

But, how do we know what 4 means here? Is this a number of worker nodes? Where can I check exact spec for this? The closest information I've found is [here](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-provision-clusters/#basic-configuration-options). This will help us determine what size we should choose.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@spelluru - Could you review this pull request from @ahkim in the public repo?

**Comment by spelluru** [comment]
@ahkim 

Thanks for the feedback. I have added the following information after confirming with the dev team: 

**clusterSize:** Number of worker/data nodes in the cluster. The HDInsight cluster is created with 2 head nodes along with the number of worker nodes you specify for this property. The nodes are of size Standard_D3 that has 4 cores, so a 4 worker node cluster will take 24 cores (4*4 for worker nodes + 2*4 for head nodes). See [Create Linux-based Hadoop clusters in HDInsight](https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-provision-linux-clusters/) for details about the Standard_D3 tier.

https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-provision-linux-clusters/

Thanks & Regards,
Sreedhar

**Comment by cjgronlund** [comment]
@ahkim @spelluru 
It looks like this issue is resolved. Thank you @ahkim for your contribution. 
Closing this PR.
--Carolyn

**Pull request closed without merging**
