### PR TITLE
Refresh instructions to work with latest cordova

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
- Update requirements - add VS 2015 and upgrade to Xcode 6 as it's nor is required to build for iOS
- Update create app section - `--copy-from` flag is broken and is replaced with manual template copying 
- Minor formatting fixes

### CODE REVIEW

**Comment by BryanLa** [comment]
@KatieCumming - the writer for this one (@vibronet) is OOF and the contributor would like to get this merged. If we can get someone else to approve/sign-off, can you merge for us?

Btw, any idea why the PRMerger bot didn't route this to @vibronet ?

**Comment by BryanLa** [comment]
Also, I guess merging would be frozen anyway, due to the ACOM->OPS migration?

**Comment by ktoliver** [comment]
@vladimir-kotikov - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/active-directory/active-directory-devquickstarts-cordova](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-devquickstarts-cordova). Thanks for your understanding.

**Comment by vladimir-kotikov** [comment]
@ktoliver, thanks for the information! I've re-sent the PR to new repo

**Pull request closed without merging**
