### PR TITLE
path/name and message maximum size update

### PR DESCRIPTION
**Pull request by SeanFeldman**
* queues and topics have a path of 260 (was omitted)
* rule is not listed in entities 
* namespace, subs, rules, or eventhubs names have a limit of 50 char only. Queues and topics can be up to 260 since name could be the whole path.
* Max message size to reflect the Premium tier (it's ok to mention that you can do up to a meg!)
* Update to the max message size note to be tier agnostic

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sethmanheim - Could you review this proposed update from @SeanFeldman in the public repo?

**Comment by sethmanheim** [comment]
@SeanFeldman Hi Sean, and thank you for your contribution! Can you show me where you obtained this information? If the engineering team confirmed these limits, that's great -- otherwise I will need to verify with them. Many thanks again.

**Comment by SeanFeldman** [comment]
@sethmanheim [here](https://github.com/Particular/docs.particular.net/pull/1470/files#diff-5c2eaa64b40ca8f30994900b772dde13R23) :grinning: 

I'm compiling doco for our product which is based on ASB, so all those items are based on the work I've done and things have seen (the things I have seen... :laughing:). If you'd like a quick confirmation, [ServiceBus explorer](https://github.com/paolosalvatori/ServiceBusExplorer) could do the trick as well.

**Comment by SeanFeldman** [comment]
@djrosanova could you please verify the change?

**Comment by sethmanheim** [comment]
@SeanFeldman Wow, great info and thorough research you've done -- thanks again! @tysonn OK to merge.

**Comment by SeanFeldman** [comment]
@sethmanheim thank you.
Glad to be of help.

**Pull request merged**
