### PR TITLE
Update data-lake-analytics-u-sql-get-started.md

### PR DESCRIPTION
**Pull request by spiharsh**
Updated Visual Studio blog post link.
Updated output file name in the first example  to SearchLog-first-u-sql.csv which is used in the query.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@spiharsh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@spiharsh 
Thank you for your contribution. These look like good changes. I'll verify with the author, and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@edmacauley @mumian 
Please verify these changes. Thanks!

**Comment by cjgronlund** [comment]
@edmacauley @mumian 
Hey, guys, please let me know about this PR.

**Comment by edmacauley** [comment]
#sign-off

I swear I set myself to receive emails

**Comment by cjgronlund** [comment]
@edmacauley 
Thanks, Ed! :>)

**Comment by cjgronlund** [comment]
@spiharsh 
Thank you for your contribution. 
--Carolyn

**Pull request merged**
