### PR TITLE
Update active-directory-assign-admin-roles.md

### PR DESCRIPTION
**Pull request by VinceSmith**
Changed all instances of "Office 365 Protection Center" to "Office 365 Security & Compliance Center" per updated product name.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@VinceSmith__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vincesm@ntdev.microsoft.com). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@VinceSmith__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vincesm@ntdev.microsoft.com). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@VinceSmith : Thanks for your contribution to the Azure documentation! The author, @curtand, has been notified to review your proposed change.

**Comment by curtand** [comment]
#sign-off

**Comment by PRmerger** [comment]
@VinceSmith : Thanks for your contribution to the Azure documentation! The author, @curtand, has been notified to review your proposed change.

**Pull request merged**
