### PR TITLE
typo with file

### PR DESCRIPTION
**Pull request by viresh-arm**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@viresh-arm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@viresh-arm : Thanks for your contribution to the Azure documentation! The author, @kundanap, has been notified to review your proposed change.

**Comment by cynthn** [comment]
#sign-off @viresh-arm thank you for fixing that issue!

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
