### PR TITLE
Remove the Express Route Circuit FAQ

### PR DESCRIPTION
**Pull request by mahthi**
Remove the Express Route Circuit FAQ since its not relevant anymore.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mahthi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mahthi). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by mahthi** [comment]
#sign-off

**Comment by PRmerger** [comment]
@mahthi : Thanks for your contribution to the Azure documentation! The author, @carlrabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
@rothja Hey Jason - this is your article now :)

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
@Ja-Dunn can you see why this has not merged yet?

**Comment by CarlRabeler** [comment]
@cjgronlund can you look into why this PR is still open?

**Pull request merged**
