### PR TITLE
Changed HTTP to HTTPS on line 4

### PR DESCRIPTION
**Pull request by rwwilden**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rwwilden__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@rwwilden__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by davidwrede** [comment]
Hey @tdykstra, can you take a look at this change?

Thanks,
Dave

**Comment by tdykstra** [comment]
@davidwrede It looks good.

**Comment by ggailey777** [comment]
@rwwilden thanks for helping out with the Azure content. Sorry it took so long to get your contribution merged.

**Pull request merged**
