### PR TITLE
Updating date

### PR DESCRIPTION
**Pull request by AndrewHoh**
Still too early to move to Azure Preview Portal for HDInsight. User workflow is not complete.

### CODE REVIEW

**Comment by rmca14** [comment]
@mimig1

**Comment by mimig1** [comment]
@AndrewHoh please remove the keywords. I'm only adding those to articles after I've done the related SEO work on them.

**Comment by AndrewHoh** [comment]
@mimig1  done

**Comment by mimig1** [comment]
Also, resolve/address this bug. http://sqlbuvsts01:8080/Main/DocumentDB/_workitems#_a=edit&id=5818039&triage=true

**Comment by AndrewHoh** [comment]
Merge conflicts resolved in other PR.

**Pull request closed without merging**
