### PR TITLE
Create Network Access Control Lists

### PR DESCRIPTION
**Pull request by MAYAKARYA**
https://github.com/Azure/azure-content/blob/master/articles/virtual-network/virtual-networks-acl-powershell.md

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MAYAKARYA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MAYAKARYA : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by ShawnJackson** [comment]
@jimdial - Looks like you're the author for this article. Please review the proposed change. Thanks!

**Comment by jimdial** [comment]
@MAYAKARYA : I haven't done a side-by-side comparison of what you're proposing versus the original, but I see that what you're proposing has 46 lines less than the original.  It appears maybe you pasted text over the original, because the proposal appears as though all the text is new, rather than showing changes.  Can you provide a brief description of what you're proposing and why?  --Thanks

**Comment by jimdial** [comment]
@MAYAKARYA: If I don't hear back from you over the next few days I will close this request, but you're of course, welcome to open another one at a later time too.  Please let me know what you're wanting to change and why so I can evaluate.  --Thanks

**Comment by jimdial** [comment]
#please-close.  Closing this request since I haven't heard back from the proposer.  They're welcome to propose it again though with additional information.

**Pull request closed without merging**
