### PR TITLE
Update docker cli port 4243→2376

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
As of azure cli 0.9.5, the default Docker port opened up on the VM is 2376.

cc: @squillace

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahmetalpbalkan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahmetb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
@ahmetalpbalkan ack. This is because we're installing the new dockerextension?

**Comment by squillace** [comment]
LGTM. Ship it. :+1: Thanks, @ahmetalpbalkan.

**Comment by ahmetalpbalkan** [comment]
Not "because", the port change is because Docker has registered an IANA port officially (it used to be 4243, which is used by some other product) and since docker 1.0 2375(http)/2376(https) are the defaults.

Extension doesn't know about what is the default, it uses whatever the CLI provides to it and it's 2376 for now.

**Comment by squillace** [comment]
@ahmetalpbalkan Perfect; thanks for the clarification.

**Comment by squillace** [comment]
@deneha Thanks, Dene.

**Pull request merged**
