### PR TITLE
Update marketplace links for New Relic

### PR DESCRIPTION
**Pull request by nickfloyd**
Updates the marketplace links to correctly point to azure.microsoft.com so that users can view product info and details on New Relic.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nickfloyd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@nickfloyd__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tysonn** [comment]
Nick, could you remove the /en-us/ parts from the updated URLs please? These paths cause the localized content experience to break by forcing users from a localized article back to an English one. Push the updates to this pending pull request. Also, if you reviewed the content of the full articles and the content is still accurate and up to date, change the ms.date value in the metadata to reflect that review. Thanks ----

**Comment by nickfloyd** [comment]
Hey @tysonn All done.  Thanks for the review. Please let me know if there is anything else.

**Pull request merged**
