### PR TITLE
Update active-directory-view-access-usage-reports.md

### PR DESCRIPTION
**Pull request by yossibanai**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yossibanai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@yossibanai__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by BryanLa** [comment]
Working with @yossibanai and @curtand to get the changes redirected to the private repo.

**Comment by BryanLa** [comment]
Closing for now, as there have been several updates to article since submitting. We will continue to work with Yossi (and the entire AAD engineering team) to redirect changes via private repo.  We can reopen if necessary.

**Pull request closed without merging**
