### PR TITLE
Updating ADLA & ADLS Java "getting started" article

### PR DESCRIPTION
**Pull request by matt1883**
Updating ADLA & ADLS Java "getting started" article to replace SNAPSHOT versions with explicit version numbers, to avoid unexpected breaking changes.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt1883__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mahi). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@matt1883 : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@matt1883, thanks for the edits. I hope you have already tested the code in the article after these edits.

**Comment by nitinme** [comment]
@cjgronlund Please merge this PR.

**Comment by nitinme** [comment]
@cjgronlund Please merge this PR.

**Pull request merged**
