### PR TITLE
Update machine-learning-apps-frequently-bought-together-api.md

### PR DESCRIPTION
**Pull request by charislove**
Updating THIS SERVICE HAS BEEN DEPRECATED

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@charislove__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@charislove 
2 options: 
* Resolve this merge conflict
* Easier: Close this PR, and make the change again in another PR.

**Comment by cjgronlund** [comment]
@charislove 
Thanks! :>)

**Comment by charislove** [comment]
Closing this PR and opening another

**Pull request closed without merging**
