### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
seems reasonable

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by Ja-Dunn** [comment]
@NarayanAnnamalai - Please review this change. Also, if the change is okay, change the note formatting to markdown please. Thanks.

**Comment by carmonmills** [comment]
@NarayanAnnamalai 
In addition to the requested change to the note there is also a typo that needs to be corrected in this PR. 
Trafic to Traffic

**Comment by 4c74356b41** [comment]
fixed, thanks

**Comment by NarayanAnnamalai** [comment]
Hi @4c74356b41, thanks for your contribution to improving Azure documentation. Due to an issue with merge conflict, I am requesting you to please close this PR, the changes have been made to the repository already. Thanks again.

**Comment by NarayanAnnamalai** [comment]
#please-close

**Pull request closed without merging**
