### PR TITLE
Update power-bi-embedded-what-is-power-bi-embedded.md

### PR DESCRIPTION
**Pull request by oedenfield**
Updated from render billing to session billing.  Billing changed as of Sept 1, 2016 from render to session.  https://azure.microsoft.com/en-us/pricing/details/power-bi-embedded/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@oedenfield__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (orrin.edenfield). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@oedenfield : Thanks for your contribution to the Azure documentation! The author, @mgblythe, has been notified to review your proposed change.

**Comment by mgblythe** [comment]
Hey Adam (@guyinacube) can you take this one?

**Comment by Erikre** [comment]
Sent an email to Adam for review.

**Comment by guyinacube** [comment]
#sign-off

**Pull request merged**
