### PR TITLE
Revert "Update remoteapp-hybridtrouble.md"

### PR DESCRIPTION
**Pull request by MAYAKARYA**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MAYAKARYA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MAYAKARYA : Thanks for your contribution to the Azure documentation! The author, @vkbucha, has been notified to review your proposed change.

**Comment by lizap** [comment]
@MAYAKARYA - Hi, there - I took a look at your proposed change. Why do you want to remove the link to the DNS article? Does it not have what you would have expected there?

Thanks, Liza

**Comment by MAYAKARYA** [comment]
@lizap what's link...

**Comment by lizap** [comment]
Per conversations with the author and contributor, please close this PR. The content is associated with a service that is being discontinued; minimal updates will be accepted.

**Pull request closed without merging**
