### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
making this similar to other topics on azure

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@charwen - Please review this contribution to your article in the public repo.

**Comment by charwen** [comment]
#sign-off

**Comment by tysonn** [comment]
@4c74356b41  - I ran this change through staging on our private side. It turns out this include file is used in 26 different articles. Updating the format to make it an Azure note causes problems in some of the articles, so I'm going to close this. Thanks for the suggestion.

**Comment by 4c74356b41** [comment]
Ok, no worries!

**Pull request closed without merging**
