### PR TITLE
Update media-services-face-and-emotion-detection.md

### PR DESCRIPTION
**Pull request by DarinShapiroMS**
example formula was off..
Old -
Seconds x (Framerate/Timescale) = 63 frames
2.1 X (29.97 / 2997)  = 0.021

New-
Seconds x Framerate = 63 frames 
2.1 X 29.97 = 62.937

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DarinShapiroMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@DarinShapiroMS : Thanks for your contribution to the Azure documentation! The author, @juliako, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@DarinShapiroMS - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/media-services/media-services-face-and-emotion-detection](https://docs.microsoft.com/en-us/azure/media-services/media-services-face-and-emotion-detection). Thanks for your understanding.

**Comment by Juliako** [comment]
@DarinShapiroMS - I am going to update the formula ( based on your feedback) in our new doc repo. Thank you!

**Pull request closed without merging**
