### PR TITLE
Update remoteapp-officesubscription.md

### PR DESCRIPTION
**Pull request by jobende**
updating per eric's request to state specifically that office 2016 is not officially supported in ARA.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jobende__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jobende). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jobende : Thanks for your contribution to the Azure documentation! The author, @piotrci, has been notified to review your proposed change.

**Comment by lizap** [comment]
@jobende - Hey, Josh - just a minor typo fix:
You can use **your** Office 365 subscription to activate and share Office 2013 **in** Azure RemoteApp deployments.

**Comment by lizap** [comment]
#sign-off - This is ready to go live.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by BryanLa** [comment]
Merging per conversation w/@lizap, as the author is no longer in org/role.

**Pull request merged**
