### PR TITLE
Update Application Insights documentation for 1.0 release of .NET SDK

### PR DESCRIPTION
**Pull request by olegsych**
This pull request contains changes in Application Insights documentation for the 1.0 release of the Application Insights .NET SDK.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@olegsych__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@olegsych__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by alancameronwills** [comment]
I created a new PR for these changes. Please close this one.

**Comment by olegsych** [comment]
Could you reference the new PR here? 
Did I do something wrong with this one?

**Comment by alancameronwills** [comment]
https://github.com/Azure/azure-content-pr/pull/12087

Just that it seemed to be taking a long time for this to go through. I just copied all your changes, apart from a spare "."

**Pull request closed without merging**
