### PR TITLE
Made Premium tier scale out limits clear without reading fine print

### PR DESCRIPTION
**Pull request by snobu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@yochay can you please verify that this tweak is correct (it probably is, but I am very careful with pricing stuff).

**Comment by ggailey777** [comment]
Signed-off on by @Yochay.

**Comment by ggailey777** [comment]
@snobu thank you for your contribution to this topic. We do appreciate your help improving the quality of Azure docs.

**Pull request merged**
