### PR TITLE
use async versions of Send and Receive

### PR DESCRIPTION
**Pull request by omidkrad**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omidkrad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sethmanheim - Please review this pull request in the public repo

**Comment by sethmanheim** [comment]
@omidkrad Hi Omid, many thanks for your contribution. Unfortunately, when I incorporate your changes to the code, I get a build error on the **Task.WaitAll(Queue())** call, stating "Error CS1503 Argument 1: cannot convert from 'void' to 'System.Threading.Tasks.Task'."

**Comment by sethmanheim** [comment]
@omidkrad OK, I've identified some other code changes that need to be made in order to get your changes to work. I'll submit the changes ASAP.

**Comment by sethmanheim** [comment]
@tysonn OK to merge, I will make the fixes after the merge.

**Pull request merged**
