### PR TITLE
Add important note that only Git is supported in VSTS.

### PR DESCRIPTION
**Pull request by lukos**
TFVC is not supported for these instructions but that fact is not specified anywhere which led me (and presumably others) down a dead end when trying to set this up with TFVC.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lukos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@lukos : Thanks for your contribution to the Azure documentation! The author, @dariagrigoriu, has been notified to review your proposed change.

**Comment by Erikre** [comment]
Sent an email to @cephalin for review.

**Comment by cephalin** [comment]
@lukos Thank you for the change! Looks great! #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by cephalin** [comment]
@lukos, could you please address the merge conflict? I know, it's our fault because we jumped to this PR too late, and I apologize for that.

**Comment by azurecla** [comment]
Hi __@lukos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@lukos__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Hi all - I attempted to resolve the merge conflict, but was unable. The [original commit](https://github.com/lukos/azure-content/commit/e697334e266c00c45defcc6f2572ffcda918e372) used to open the PR thoroughly confused GitHub.

The merge conflict was caused by `articles/app-service-web/app-service-continuous-deployment.md` getting deleted/recreated (or renamed) in `lukos/azure-content:master`, and replaced with `articles/app-service-web/app-service-continous-deployment.md` (note the typo in the file name). So the PR was trying to delete app-service-continuous-deployment.md, and update app-service-continous-deployment.md (which doesn't exist in azure/azure-content:master).

I didn't catch this until later though, AFTER the process of pulling `lukos/azure-content:master` down, correcting what I thought was the conflict in the file (but doing it to the renamed/recreated file), then pushing it back up to `lukos/azure-content:master`. At that point it brought thousands of commits into the PR from `azure/azure-content:master`, as the fork was at least a couple of months out of date.

Anyway, at this point, it would be easier to start with a new PR; @lucas, if you would like to update or recreate your fork, and resubmit the changes to `app-service-continuous-deployment.md` in a new PR, we would be happy to get this merged asap for you. Your fork is probably up to date after the push I did tonight, so you may not need to refresh it, but you will need to delete `app-service-continous-deployment.md` before you open a new PR. We just want to make sure you get the commit credit for this, but if you prefer one of us do it, that works too.  I've saved the change for your convenience :

` > [AZURE.NOTE] Only git repositories are supported when using VSTS. If you wish to use Team Foundation Version Control (TFVC), then you must push a deployment using a Deploy step in your VSTS build as detailed [here](https://www.visualstudio.com/en-us/docs/release/examples/azure/azure-web-apps-from-build-and-release-hubs).`

Apologies that this PR had to be closed, but hope this helps and is workable for everyone.

**Pull request closed without merging**
