### PR TITLE
Update vpn-gateway-bpg-faq-include.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed IP addresses.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @AndrewHoh, has been notified to review your proposed change.

**Comment by yushwang** [comment]
#sign-off

**Comment by cherylmc** [comment]
@tysonn  Good to go! Can you please merge this in? @alexandair - Thanks for bringing this to our attention. Much appreciated!

**Pull request merged**
