### PR TITLE
Update azure-stack-webapps-deploy.md

### PR DESCRIPTION
**Pull request by CharbelNemnom**
New-AzureRmResourceGroupDeployment 
We should enter a new storage account name that does not matches the storage account that you created earlier.
Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CharbelNemnom__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by CharbelNemnom** [comment]
Thank You!

**Comment by tysonn** [comment]
@ccompy - Please review this public repo update from @CharbelNemnom - thx!

**Comment by ChrisCompy** [comment]
#sign-off

**Pull request merged**
