### PR TITLE
Added "Create Internet facing Load Balancer from current Azure Portal" article

### PR DESCRIPTION
**Pull request by crpietschmann**
Added an "Create an Internet facing load balancer in Resource Manager using the Azure Portal" article. There seemed to be a bit of a hole in the documentation coverage for configuring Load Balancers from the Azure Portal. There's a few steps involved and they aren't necessarily straight forward to create.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crpietschmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@crpietschmann : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@carmonmills Hi Carmon. Please direct this new content to an appropriate contact on your team for review. Thanks.

**Comment by sdwheeler** [comment]
@crpietschmann - thanks for your contribution. This version article was published recently. See https://azure.microsoft.com/en-us/documentation/articles/load-balancer-get-started-internet-portal/

#please-close

**Comment by crpietschmann** [comment]
Hmm... That's nice. My PR was submitted 2 weeks before that other article was... Oh well, I guess we'll see if I can get a new article published next time... :(

**Comment by sdwheeler** [comment]
@crpietschmann - Sorry about that. This PR got lost in some personnel transition. Also, the article was actually being developed internally before that date. 

I do appreciate your effort. It was a gap in the documentation that needed to be filled. Keep submitting contents and edits. We do appreciate your contribution.

**Comment by crpietschmann** [comment]
@sdwheeler no problem. I'll definitely keep contributing! :)

**Pull request closed without merging**
