### PR TITLE
New-AzureRmADApplication parameter replacement

### PR DESCRIPTION
**Pull request by Desmopowerrr**
The latest version of the CmdLet New-AzureRmADApplication does not support the parameters KeyValue and KeyType, these have been replaced by CertValue

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Desmopowerrr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Desmopowerrr : Thanks for your contribution to the Azure documentation! The author, @tfitzmac, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@Desmopowerrr - thanks for making this change.

**Comment by tfitzmac** [comment]
#sign-off

**Pull request merged**
