### PR TITLE
Correcting typo in code comment

### PR DESCRIPTION
**Pull request by lorenpaulsen**
Correcting a minor typo in the a code sample

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lorenpaulsen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@tamram - Could you review this update from @lorenpaulsen and let me know if it can be merged?

**Comment by tamram** [comment]
Looks great. Thank you @lorenpaulsen for your contribution.

**Comment by tamram** [comment]
@tysonn, please merge.

**Pull request merged**
