### PR TITLE
Update site-recovery-deploy-with-powershell.md

### PR DESCRIPTION
**Pull request by vijaynar**
1) Updated Monitor activity code
2) Corrected step 7.5
3) Corrected indentation across article
4) Some cmdlets were written as plain text, corrected those.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vijaynar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vijaynar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, can you please take a look at these updates and let me know if they can be merged?

**Comment by rayne-wiselman** [comment]
Look good to me ☺

**Comment by Jim-Parker** [comment]
#sign-off

**Pull request merged**
