### PR TITLE
Update iot-hub-manage-through-portal.md

### PR DESCRIPTION
**Pull request by BeatriceOltean**
Propose change for the regions and add description for the service connect and device connect in the "Create a new policy" section

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BeatriceOltean__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@BeatriceOltean : Thanks for your contribution to the Azure documentation! The author, @nasing, has been notified to review your proposed change.

**Comment by dominicbetts** [comment]
Hi @BeatriceOltean and @naysing - I've already made this change using the document you sent me.
I'll close this PR.
In future, you can submit changes directly using the private azure-content-pr repository instead of this public one.
Dominic

**Comment by dominicbetts** [comment]
It looks like I can't close this PR - please go ahead and close it.

**Pull request closed without merging**
