### PR TITLE
changed flow and added a link.

### PR DESCRIPTION
**Pull request by TomShinder**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TomShinder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tomsh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@TomShinder : Thanks for your contribution to the Azure documentation! The author, @TomShinder, has been notified to review your proposed change.

**Comment by YuriDio** [comment]
Thanks @TomShinder your request will be merged

**Comment by TerryLanfear** [comment]
@BryanLa - This PR has been reviewed and can now be merged.
#sign-off

**Comment by BryanLa** [comment]
Hi all - the *"Implementing a Secure Hybrid Network Architecture in Azure"* link in the proposed changes should have the "/en-us/" segment removed, otherwise when someone using a computer with different culture settings clicks on it, they will get the English-US version of the article. Can someone revise before we merge? Then just drop another @ comment for me and I can merge ASAP.

@TomShinder : the team that manages the ACOM repo asks that internal contributors use a GitHub fork and local repo to do contributions via the private repo, esp. if you are an ACOM author or are part of an engineering team that regularly contributes to ACOM. Smaller/typo changes are fine to do via the GitHub UI on the public repo, but larger ones, or changes that need to run through validation (ie: ones with links like this) should run through the private repo, as it gives you validation and staging. Any of us can help you if you have questions on this; there is also a comprehensive Contributor Guide here that will help get you started: https://github.com/Azure/azure-content/.

**Comment by tysonn** [comment]
@TomShinder - Please see [Authors contributing through the public repo](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Article%20authors%20working%20in%20the%20public%20repo.aspx) on the wiki. Closing this PR.

**Pull request closed without merging**
