### PR TITLE
Update resource-groups-vm-searching.md

### PR DESCRIPTION
**Pull request by Sergmis**
Powershell 1.0 commands above are listed in ISE as Get-AzureRMVMImagePublisher, etc...

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Sergmis__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
@Sergmis Thanks, Sergio -- I apologize for the delay. Right now, we have a note that says that for 1.0+ you remplace "Azure*" with "AzureRm*". Otherwise, if you're on PS <1.0, the commands are the same. We're getting ready to reverse that statement, but we have more people on <1.0 than on >1.0 at the moment. :-|

To wit:

>
[AZURE.NOTE] With Azure PowerShell modules above 1.0, the Switch-AzureMode cmdlet was removed. With that version and more recent, please replace the commands below with the Azure portion replaced with AzureRm. If you are using Azure PowerShell modules below 1.0, you will use the below commands but you must first Switch-AzureMode AzureResourceManager.
>

Perhaps we'll take your submission and rework this topic completely! I'll report back shortly.

**Comment by tysonn** [comment]
@squillace - Ralph - can you follow up on this?

**Comment by squillace** [comment]
@tysonn sure will. Sorry; I've been distracted.

**Comment by tysonn** [comment]
@Sergmis / @squillace - At this point, I'm going to close this PR. Author comments indicate change was not mergeable initially, and the VM content is being refactored.

**Pull request closed without merging**
