### PR TITLE
API link correction in power-bi-embedded-get-started-sample.md

### PR DESCRIPTION
**Pull request by pavlinap**
Putting in the right link to the Power BI Embedded API reference

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pavlinap__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@dvana 
Please let me know whether to accept this PR. Thanks!

**Comment by cjgronlund** [comment]
@pavlinap 
Thank you for this contribution. I'll verify the change with the writer, and get right back to you.

**Comment by dvana** [comment]
#sign-off

**Pull request merged**
