### PR TITLE
homophone correction: discreet -> discrete

### PR DESCRIPTION
**Pull request by buzzcola**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@buzzcola__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@buzzcola : Thanks for your contribution to the Azure documentation! The author, @stephbaron, has been notified to review your proposed change.

**Comment by mimig1** [comment]
@stephbaron - can you add the #sign-off tag to get this incorporated.

**Comment by stephbaron** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
