### PR TITLE
Use Get-AzureDnsZone as it already exists

### PR DESCRIPTION
**Pull request by OliverMartini**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@OliverMartini__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@OliverMartini Thanks for this contribution! I've sent this to the author for review.

**Comment by joaoma** [comment]
approved . sign off to merge.

**Comment by joaoma** [comment]
thanks @OliverMartini for the feedback!

**Pull request merged**
