### PR TITLE
Update vpn-gateway-about-vpn-devices.md

### PR DESCRIPTION
**Pull request by stegag**
Corrected lifetime values for Dynamic gateways as validated by Steve and Ashok in ICM 16890452

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stegag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stegag). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cherylmc** [comment]
@Tyson This change is good. Please accept.

**Comment by tysonn** [comment]
@cherylmc - Cheryl, could you please review these updates from @stegag and let me know if they can be merged?

**Comment by tysonn** [comment]
@cherylmc - Comments just updated, I see you signed off.  @stegag - Thanks for the update!

**Pull request merged**
