### PR TITLE
Fix Azure CLI command for VM shutdown

### PR DESCRIPTION
**Pull request by dondizon**
Use "vm deallocate" instead of "vm shutdown"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dondizon__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@squillace & @cynthn - VM pull request

**Comment by tysonn** [comment]
@dsk-2015 - Please review; since the file name is staying the same in the refactor this is mergeable to the release branch. Let me know.

**Comment by dsk-2015** [comment]
@tysonn This is not mergeable until we lift the freeze on the master VMs articles, which should be mid next week. This is V1 file and it's renamed to virtual-machines-linux-classic-capture-image.md in the release branch.

**Comment by tysonn** [comment]
@dondizon - Thanks for this update. Could you see #6002 for details on why I am closing this PR?

**Comment by dsk-2015** [comment]
@tysonn thanks for addressing this. @dondizon thanks for suggesting this change, we will be able to work on this as soon as the file renaming work is completed.

**Pull request closed without merging**
