### PR TITLE
Changes -> Charges

### PR DESCRIPTION
**Pull request by dbrust**
Changed "Changes only accruing when you are actually running code." to "charges only when you are actually running code."

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dbrust__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@eduardolaureano - Please review this proposed change from @dbrust in the public repo.

**Comment by ggailey777** [comment]
This fix is correct.

**Comment by ggailey777** [comment]
@dbrust thanks for taking the time to find and fix this typo. We appreciate your help improving the quality of Azure docs.

**Pull request merged**
