### PR TITLE
Renaming preview portal to Azure Portal

### PR DESCRIPTION
**Pull request by singhkay**
Renaming preview portal to Azure Portal since it's GA now.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@singhkay__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kasing). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
@tysonn Looks like we missed one. Thanks, Kay! #sign-off.

**Comment by singhkay** [comment]
@squillace Found a few more occurences

**Comment by squillace** [comment]
So did i. @singhkay can you close this? I'll submit complete fixes for our world.

**Comment by singhkay** [comment]
Done

**Pull request closed without merging**
