### PR TITLE
Update stream-analytics-twitter-sentiment-analysis-trends.md

### PR DESCRIPTION
**Pull request by olgamatoula**
Clarification for the connection strings; it took me a whole hour to figure out what I was doing wrong because the guide does not say that I have to separate the strings to put each to the according field.
Please review this, because there were a lot of comments on the article that I think they have faced the same issue.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@olgamatoula__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@olgamatoula 
Thank you for this contribution! I'll send to the author to verify, and get right back to you.

**Comment by cjgronlund** [comment]
@jeffstokes72 
Please let me know whether to accept this PR.
Thanks!

**Comment by jeffstokes72** [comment]
yes please move forward with this one. thanks!

**Comment by cjgronlund** [comment]
@olgamatoula 
PR accepted. Thanks again!

**Comment by olgamatoula** [comment]
Any time @cjgronlund

**Pull request merged**
