### PR TITLE
Link for CLOUDS in VMM is bad...

### PR DESCRIPTION
**Pull request by johnwildes**
Replacing the www.server-log.com link...which redirects to spam / ad home page...all links should redirect somewhere to Microsoft.com...anything is better than a third party blog...

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@johnwildes__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@johnwildes : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
Link update is ok

**Comment by rayne-wiselman** [comment]
@PRmerger

**Comment by rayne-wiselman** [comment]
Hi John, please close this PR and I'll make the change in a new one. Since the PR is old trying to resolve the merge conflict will involve too many files that have changed in the interim

**Comment by rayne-wiselman** [comment]
Here's the PR that's been opened instead - https://github.com/Azure/azure-content-pr/pull/32919. Please close.

**Pull request closed without merging**
