### PR TITLE
Update automation-dsc-cd-chocolatey.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sebastus - Please review this proposed change in the public repository to your article.

**Comment by sebastus** [comment]
@alexandair Thank you very much for the contributions.  They look good.
@tysonn #sign-off

**Comment by alexandair** [comment]
@sebastus You're welcome. Thank you for an excellent article.

**Pull request merged**
