### PR TITLE
Update service-fabric-reliable-services-communication-webapi.md

### PR DESCRIPTION
**Pull request by CJM81**
Changed OwinCommunicationListener from public to internal.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CJM81__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@CJM81 : Thanks for your contribution to the Azure documentation! The author, @vturecek, has been notified to review your proposed change.

**Comment by vturecek** [comment]
@CJM81 Thanks! If you can make the same change on line 232, then I can sign off on this one and get it published.

**Comment by vturecek** [comment]
#sign-off

**Pull request merged**
