### PR TITLE
Monitor with Dynatrace (DC/OS)

### PR DESCRIPTION
**Pull request by MartinGoodwell**
Could you please add this content to https://azure.microsoft.com/en-us/documentation/articles/container-service-mesos-marathon-ui/ in parallel to the other two entries on DC/OS monitoring?

If in doubt, please get in touch with eduardoe@microsoft.com.

For any other questions, please don't hesitate to contact me.

Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MartinGoodwell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@MartinGoodwell__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@MartinGoodwell : Thanks for your contribution to the Azure documentation! The author, @rbitia, has been notified to review your proposed change.

**Comment by MartinGoodwell** [comment]
Hi @rbitia, I just wanted to check whether there's any issues left?

**Comment by ktoliver** [comment]
@MartinGoodwell - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/container-service/container-service-mesos-marathon-ui](https://docs.microsoft.com/en-us/azure/container-service/container-service-mesos-marathon-ui). Thanks for your understanding.

**Pull request closed without merging**
