### PR TITLE
Update virtual-networks-create-vnetpeering-scenario-crosssub-include.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@NarayanAnnamalai Hi Narayan Please review the proposed change. Thanks.

**Comment by alexandair** [comment]
@NarayanAnnamalai Hi Narayan Please review the proposed change. Thanks.

**Comment by jimdial** [comment]
@alexandair : Thanks for the edit. #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
