### PR TITLE
Fix manual process about restore a deleted database

### PR DESCRIPTION
**Pull request by buchizo**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@buchizo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@elfisher 
Please review approve/disapprove with a comment. Thanks.

**Comment by rmca14** [comment]
Follow-up mail sent for review request.

**Comment by elfisher** [comment]
Hi buchizo,

The proposed change is not the correct workflow for restoring a deleted database. The current documentation is correct. I think there is a misunderstanding though. The proposed change will restore a database, however it is the workflow for restoring using Geo-Restore as illustrated in the documentation here: https://azure.microsoft.com/en-us/documentation/articles/sql-database-disaster-recovery/#recover-using-geo-restore

If you have more questions let me know.

Thanks,
-Eli

**Comment by rmca14** [comment]
Thank you, both. I'll close this PR unmerged.

**Comment by buchizo** [comment]
Hi Eli,

If I am not mistaken, I can't do that operation on portal.azure.com, because I can't look 'deleted database' on server's blade.

https://azure.microsoft.com/en-us/documentation/articles/sql-database-user-error-recovery/

**Comment by elfisher** [comment]
Are you able to access your server blade? If so try to scroll down for a trash bin labelled "deleted database". If you are unable to access your server blade, do you have any role based access control permissions set?

Regards,
-Eli

**Comment by buchizo** [comment]
Hi @elfisher ,

I found it! Sorry, I had a mistake. I'd like to close this PR.

* Suggestion:

Now: Under **Operations** on you server's blade, select **Deleted Databases**.
My Suggestion: Under **Operations** on you server's blade, click **Deleted Databases** tile.

**Comment by elfisher** [comment]
Great suggestion!

Thanks!

**Pull request closed without merging**
