### PR TITLE
fixed spacing

### PR DESCRIPTION
**Pull request by TomShinder**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TomShinder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by TomShinder** [comment]
What happened to my previous changes? Is the system down? Do you know what it will come back up?

**Comment by PRmerger** [comment]
@TomShinder : Thanks for your contribution to the Azure documentation! The author, @TomShinder, has been notified to review your proposed change.

**Comment by TerryLanfear** [comment]
@TomShinder - Thank you for your contribution! It can be merged.
@BryanLa - I reviewed this PR and it can be merged.
#sign-off

**Comment by TerryLanfear** [comment]
@BryanLa - Hi Bryan, I reviewed this PR and it can be merged.
#sign-off

**Pull request merged**
