### PR TITLE
Misspelling in Sentence

### PR DESCRIPTION
**Pull request by mikhailalmeida**
Changed "Additonally" to "Additionally,".

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mikhailalmeida__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mikhailalmeida : Thanks for your contribution to the Azure documentation! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by cjgronlund** [comment]
@telmosampaio 
Simple typo fix. I confirmed nothing else was done. I'm accepting this.

**Comment by cjgronlund** [comment]
@mikhailalmeida 
Good catch! Thank you for your contribution to Azure documentation.
--Carolyn

**Comment by telmosampaio** [comment]
@sign-off

**Pull request merged**
