### PR TITLE
Update virtual-machines-scale-sets-dsc.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix casing in a section title and DSC extension version to 2.20. (Version 2.9 is removed.)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @zjalexander, has been notified to review your proposed change.

**Comment by zjalexander** [comment]
@alexandair looks great, thanks so much! this can be merged.

**Comment by zjalexander** [comment]
@alexandair sorry, i didn't use the right keywords, and in the meantime I had to update the article content with my own stuff. Can you take a look at it again? #hold-off

**Pull request closed without merging**
