### PR TITLE
typo

### PR DESCRIPTION
**Pull request by davidbetz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@davidbetz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@davidbetz : Thanks for your contribution to the Azure documentation! The author, @christopheranderson, has been notified to review your proposed change.

**Comment by christopheranderson** [comment]
sign_off

**Comment by christopheranderson** [comment]
Terribly sorry @davidbetz, but I used our automation tool wrong and it looks like there is a merge conflict now. Could you potentially update your PR? I'll sign off properly and quickly after you've sent it. :)

#hold-off

**Pull request closed without merging**
