### PR TITLE
replacing old commandlets with the new ones

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by 4c74356b41** [comment]
also you would want to replace automation cmdlets link on the right with the proper one
https://msdn.microsoft.com/en-us/library/mt244122.aspx

untitled

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@4c74356b41 Thank you for your suggested changes to this article.  Upon review of your proposed changes, they are incomplete where the example PowerShell script would not complete successfully.  Additionally, the links to the ARM cmdlets were not included with your suggested change.  I've updated the article accordingly and updated/validated the script logic.  I'll submit a PR now and will also submit another PR to update the TOC to reference the Automation ARM cmdlets.   I cannot approve this PR.

**Comment by 4c74356b41** [comment]
how can i update the navigation menu on the left? i mean where do i supply the pr? also yeah, i forgot the resourcegroup in there, sorry

**Comment by MGoedtel** [comment]
@4c74356b41 - You can't, its not a task that can be performed from the public repo.  I identified another section in the article that needs re-working, so I'm addressing that now (specifically - Viewing job status from the portal.  It's referencing the old portal not the new portal...)

**Comment by 4c74356b41** [comment]
what did you mean with the link to arm commadlets then? I've updated the links in my pr...

**Comment by MGoedtel** [comment]
@4c74356b41 - I was referring to the link on MSDN for each of the cmdlets.  Originally you had updated the reference to the ARM cmdlet, but not the link to the MSDN topic.  It was addressed in my PR and today/tomorrow I am releasing another update to this article to address outdated details/information in other sections of the article.

**Comment by ktoliver** [comment]
@4c74356b41 - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/automation/automation-runbook-execution](https://docs.microsoft.com/en-us/azure/automation/automation-runbook-execution). Thanks for your understanding.

**Pull request closed without merging**
