### PR TITLE
Update configure-ssl-web-site.md

### PR DESCRIPTION
**Pull request by cristhianu**
I changed the &gt; to > at the beginning of the paragraphs so that it looks like an AZURE.NOTE

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cristhianu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cristhianu - Thanks!

**Comment by cristhianu** [comment]
Hello,
It still looks wrong. Could somebody look at line 458 and tell me why the [Azure.Note] doesn't show as a Note as the previous note? I added > at the beginning of each paragraph but instead it shows them as >. I already tried adding them as a &lt; but it resulted on the same.
Thank you,

**Comment by tysonn** [comment]
@cristhianu - I will look into it. I have a PR filed in the private repo to try and solve this. Thanks for calling it out. The reason it's not working is the blockquoting from the prior note is causing this following note to be interpreted as part of the first note.

**Comment by cristhianu** [comment]
Excellent. Thank you, Tysonn.

**Pull request merged**
