### PR TITLE
Update storsimple-virtual-device-u1.md

### PR DESCRIPTION
**Pull request by vidarmsft**
Typos corrected and minor accuracy changes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vidarmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alkohli - Alpa, could you please review?

**Comment by alkohli** [comment]
Hi Vivek, I reviewed the changes. I am recommending a couple of changes: 
1. In this sentence - "item level retrieval from backups, on-premise disaster recovery and cloud dev/test scenarios. " - can we use on-premises instead of on-premise.

2. Also, in this same doc in the Create and configure virtual device section, as we discussed offline, could we please  mention that whether is update 1, 1.1 or 1.2, the dropdown always says update 1. I think this should be added as a note. If you encounter any issues creating a note with proper format, please let me know and I will make this change in a separate PR. 

Thanks a lot!

**Comment by tysonn** [comment]
@vidarmsft - Could you reply to Alpa's feedback?

**Comment by azurecla** [comment]
Hi __@vidarmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by vidarmsft** [comment]
Hey Sorry, I’m not sure what to do here. I’m ok with the changes, how do I close this?

**Comment by vidarmsft** [comment]
Hey Vivek,
Could you please incorporate the suggested change? After the validation goes through, if you enter "#sign-off", the PR approver can approve your PR.
Thanks!

-Alpa

On Oct 19, 2015, at 11:52 PM, Vivek N Darera <vidar@microsoft.com<mailto:vidar@microsoft.com>> wrote:

Hey Sorry, I'm not sure what to do here. I'm ok with the changes, how do I close this?

**Pull request closed without merging**
