### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
attempting to fix link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
The referred article is in a different sub-directory, so the reference should be 
../vpn-gateway/vpn-gateway-vnet-vnet-rm-ps.md

Please make this change before merge

**Comment by 4c74356b41** [comment]
yeah, sorry, I wasn't sure how to look that up, hence I was guessing where it is. thanks!

**Comment by NarayanAnnamalai** [comment]
Hi @4c74356b41 thanks for your contribution to improving the documentation, the original content has been modified and hence this change is no longer required.
Please close this PR.
#please-close

**Pull request closed without merging**
