### PR TITLE
Update power-bi-embedded-get-started-sample.md

### PR DESCRIPTION
**Pull request by oedenfield**
Added information about Update-Package command after opening the solution in VS.  First time I ran this without updating packages I received a number of errors and warnings.  After running Update-Package in NuGET console errors and warnings went away.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@oedenfield__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@oedenfield : Thanks for your contribution to the Azure documentation! The author, @minewiskan, has been notified to review your proposed change.

**Comment by Minewiskan** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by Minewiskan** [comment]
#sign-off

**Pull request merged**
