### PR TITLE
Adding Cognitive Services reference

### PR DESCRIPTION
**Pull request by ealsur**
Updating article by request from @mimig1

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ealsur__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ealsur : Thanks for your contribution to the Azure documentation! The author, @ealsur, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.

It�s easy to access the private repo version of your articles in GitHub. Just add �pr to the URL, as follows: 

Public repo URL: https://github.com/Azure/azure-content/blob/master/articles/azure-portal-overview.md

Private repo URL: https://github.com/Azure/azure-content-pr/blob/master/articles/azure-portal-overview.md

We've closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, see the contributor guide instructions.

**Comment by mimig1** [comment]
@ealsur - Because both our names are on this article, our bot is confused and closed this PR. I'll need you to reopen this sometime, but let me get the bot issue figured out first.

**Pull request closed without merging**
