### PR TITLE
Update release notes for Application Insights .Net SDK

### PR DESCRIPTION
**Pull request by upendras**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@upendras__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (upendras). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by upendras** [comment]
@SergeyKanzhelev, @alancameronwills please have a look.

**Comment by SergeyKanzhelev** [comment]
Looks good.

**Comment by abaranch** [comment]
Looks good

**Comment by alancameronwills** [comment]
Fine by me.

**Comment by alancameronwills** [comment]
#sign-off

**Pull request merged**
