### PR TITLE
Update sql-data-warehouse-load-with-polybase.md

### PR DESCRIPTION
**Pull request by sahaj08**
Adding a workaround for UTF8 encoding issue and minor corrections in the code.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sahaj08__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sahajs). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@barbkess 
Please review and approve here, thanks.

**Comment by rmca14** [comment]
Please resolve the merge conflict. For guidance, see https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx

Thanks.

**Comment by sahaj08** [comment]
Withdrawing the pull request. Communicated with JRJ, we should let his pull request go through.

**Pull request closed without merging**
