### PR TITLE
fixed minor typo

### PR DESCRIPTION
**Pull request by victorar**
fixed minor typo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@victorar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (victorar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@victorar : Thanks for your contribution to the Azure documentation! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by cjgronlund** [comment]
@telmosampaio 
Easy typo. I'm accepting this PR. Thanks!
--Carolyn

**Comment by cjgronlund** [comment]
@victorar 
Nice catch! I'll accept this PR. Thank you!
--Carolyn

**Pull request merged**
