### PR TITLE
Improving sctipting brevity

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlekseiPolkovnikov : Thanks for your contribution to the Azure documentation! The author, @mahthi, has been notified to review your proposed change.

**Comment by dlepow** [comment]
@AlekseiPolkovnikov - Thanks for the suggestion to simplify the script! I've taken ownership of the article so will attempt to merge. 
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by dlepow** [comment]
@KatieCumming - Hello Katie, I took ownership of this article after @AlekseiPolkovnikov made the PR. I approve the change. Can you please merge? Thanks!

**Comment by KatieCumming** [comment]
@dlepow - thanks Dan. Merging.

**Pull request merged**
