### PR TITLE
Fixed the issue related to the name of Layer 4

### PR DESCRIPTION
**Pull request by olegchorny**
Layer 4 is Transport and not Network layer within the OSI model

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@olegchorny__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@olegchorny : Thanks for your contribution to the Azure documentation! The author, @azdocpr, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@joaoma & @carmonmills - Could you review, please?

**Comment by joaoma** [comment]
#sign-off . It’s a valid change.

Joao

**Pull request merged**
