### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@chipalost Hi Chipalo Please review this proposed change. Thanks.

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by dominicbetts** [comment]
@4c74356b41 - it looks like there's now a merge conflict on this PR - can you fix the merge conflict and then we can accept your change?
Thanks, Dominic

**Comment by dominicbetts** [comment]
#please-close
@4c74356b41 @chipalost - rather than you fixing the merge conflict - I've made the change directly.

**Pull request closed without merging**
