### PR TITLE
Minor fixes to native client setup of AAD quickstart webapi dotnet

### PR DESCRIPTION
**Pull request by gsacavdm**
Fixing ClientID details and permission drop down value for Native client piece of .Net Web API tutorial

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gsacavdm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dstrockis - Please review this proposed change from @gsacavdm to your article in the public repository.

**Comment by dstrockis** [comment]
@tysonn this is fine, thanks.

**Comment by dstrockis** [comment]
#sign-off?

**Comment by gsacavdm** [comment]
Ping :)

**Pull request merged**
