### PR TITLE
Include Azure CLI support for Resource Policies

### PR DESCRIPTION
**Pull request by jangelfdez**
Adds details about how to work with Resource Policies from the Azure CLI.

The following sections are included:

- Create Policy Definition using Azure CLI
- Policy Assignment using Azure CLI
- Policy Audit Events using Azure CLI

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jangelfdez__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by jangelfdez** [comment]
I'm a FTE, no CLA should be required as https://cla.azure.com shows.

**Comment by jangelfdez** [comment]
@tfitzmac Is it possible to remove the cla-required tag due to my previous message?

**Comment by azurecla** [comment]
Hi __@jangelfdez__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (josefern). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@jangelfdez__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (josefern). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jangelfdez** [comment]
Closing and re-opening the PR in order to update my employee status

**Comment by PRmerger** [comment]
@jangelfdez : Thanks for your contribution to the Azure documentation! The author, @ravbhatnagar, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@jangelfdez - thanks for this important addition to the topic.

**Comment by tfitzmac** [comment]
@KatieCumming - are you able to merge this PR? The author is out. I have reviewed it.

**Comment by KatieCumming** [comment]
@tfitzmac - thanks Tom. Merging.

**Pull request merged**
