### PR TITLE
Don't use bad practices in a sample

### PR DESCRIPTION
**Pull request by mstaessen**
throw de breaks the call stack. Instead, use throw

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mstaessen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mstaessen : Thanks for your contribution to the Azure documentation! The author, @AndrewHoh, has been notified to review your proposed change.

**Comment by cjgronlund** [comment]
@mimig1 @AndrewHoh 
Please check this PR and let me know what I should do with it. 
Thanks!

**Comment by mimig1** [comment]
I will defer to @AndrewHoh on this.

**Comment by AndrewHoh** [comment]
This looks good! Please merge.

**Comment by JennieHubbard** [comment]
#sign-off

**Comment by mimig1** [comment]
@cjgronlund

**Pull request merged**
