### PR TITLE
Update data-lake-analytics-documentation-backlog.md

### PR DESCRIPTION
**Pull request by saveenr**
Added a doc backlog item

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saveenr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (saveenr). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@saveenr 
If you are a Microsoft employee, please update your GitHub profile to indicate that. Thanks.

https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

**Comment by rmca14** [comment]
@mumian 
I don't know if this contributor is a Microsoft employee, so can you please approve/disapprove this update? Thanks.

**Comment by mumian** [comment]
#sign-off

**Pull request merged**
