### PR TITLE
Update virtual-machines-linux-create-upload-vhd.md

### PR DESCRIPTION
**Pull request by JasonMAnderson**
Changed CLI command from "azure change mode asm" to the correct "azure config mode asm"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JasonMAnderson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (janders). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@dsk-2015 hey Dhanashri, , could you please review this contribution?

**Comment by dsk-2015** [comment]
Thanks for catching this error!

**Comment by dsk-2015** [comment]
#sign-off

**Pull request merged**
