### PR TITLE
Update app-insights-asp-net-exceptions.md

### PR DESCRIPTION
**Pull request by ChrisMissal**
corrects casing on the JavaScript method to track exceptions

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ChrisMissal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alancameronwills - Please review this contribution in the public repo from @ChrisMissal and let @ggailey777 know if he can merge it. Thanks!

**Comment by alancameronwills** [comment]
#sign-off

**Comment by alancameronwills** [comment]
@ggailey777: fine, please accept

@ChrisMissal : Thanks, Chris!

**Comment by ggailey777** [comment]
@ChrisMissal thank you for finding and fixing this bug. We appreciate your help improving the quality of Azure docs.

**Pull request merged**
