### PR TITLE
Correct bookmark links to "Premium Storage Scalability and Performance Targets"

### PR DESCRIPTION
**Pull request by kszabelski**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kszabelski__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ms-prkhad - Please review this public repo pull request from @kszabelski

**Comment by carmonmills** [comment]
@robinsh Would you please review this PR and confirm the changes being requested.

**Comment by robinsh** [comment]
Hi @kszabelski . Thanks so much for fixing those bookmark links in this document. I really appreciate it! 

@tysonn -- This change can be merged.

**Comment by kszabelski** [comment]
I've fixed conflicts. It should be good to go now.

**Comment by robinsh** [comment]
@kszabelski This has been merged, and should be published today. Thanks again!

**Pull request merged**
