### PR TITLE
update Powershell script

### PR DESCRIPTION
**Pull request by tnjyothi**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tnjyothi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dhanyahk - Please review this public repository pull request from @tnjyothi and let @BryanLa and @curtand know if it can be merged.

**Comment by BryanLa** [comment]
@tnjyothi - thanks for your contribution!
@dhanyahk - I can work w/you on this. Just let me know if you want to merge.

**Comment by dhanyahk** [comment]
I need more input into what was changed. Will get back

**Comment by azurecla** [comment]
Hi __@tnjyothi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request closed without merging**
