### PR TITLE
Changed ip address for backend servers

### PR DESCRIPTION
**Pull request by opentodonet**
Changed the ip address for the backend servers and the description for Back-end server pool, since the ip addresses must be in a different subnet for application gateway resource.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@opentodonet__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@joaoma & @cherylmc - Could you review this app gateway update in the public repo and let me know if I can merge?

**Comment by cherylmc** [comment]
@joaoma, please take a look.

**Comment by joaoma** [comment]
#sign-off

**Comment by tysonn** [comment]
@opentodonet - Thanks for the update!

**Pull request merged**
