### PR TITLE
Minor corrections: Fix typos and punctuation

### PR DESCRIPTION
**Pull request by chustedde**
This is just a handful of minor corrections I made after coming across some typos while reading the article.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chustedde__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
Hi @shoatman, @billmath - these look OK to me, but I'd like to get your approval before merging. Thanks!

**Comment by BryanLa** [comment]
Hi @chustedde - these look really helpful, so thanks very much for your contribution! Unfortunately, this article has also changed in the interim (between the time you made your edits and now), to the point where we can't merge this PR due to merge conflicts. Would you mind closing this PR and resubmitting with a new/fresh copy of active-directory-aadconnect-dirsync-upgrade-get-started.md ?

**Comment by BryanLa** [comment]
FYI for @shoatman

**Comment by BryanLa** [comment]
@chustedde @shoatman @billmath  - please let me know if one of you would like to resolve the merge conflict, or close and reapply these fixes to a new copy of active-directory-aadconnect-dirsync-upgrade-get-started.md.

**Comment by chustedde** [comment]
@BryanLa Sorry, I haven't had time to take a look at this again. I'll close this PR and reapply the changes to a new copy.

**Comment by BryanLa** [comment]
@chustedde - Sounds great, and thank you for the contribution!

**Pull request closed without merging**
