### PR TITLE
Update mobile-services-apns-configure-push.md

### PR DESCRIPTION
**Pull request by izikl**
Fix a broken link to apple's documentation. 
On safari, the new link doesn't scroll correctly, but it is better then the PageNotFound in the existing docs.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@izikl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (izikl). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@krisragh can you just verify real quick that this the link you want? Thanks.

**Comment by krisragh** [comment]
@ggailey777  looks good!

**Comment by ggailey777** [comment]
@izikl Thanks for your contribution. We appreciate your helping to improve the quality of the Azure docs.

**Pull request merged**
