### PR TITLE
Minor spacing fixes

### PR DESCRIPTION
**Pull request by ShaneCastle**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ShaneCastle__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
at @ShaneCastle Shane, thank you for making the updates to the Service Bus brokered messaging .NET tutorial.

**Comment by Jim-Parker** [comment]
@sethmanheim Seth, could you please review this contribution?

**Comment by sethmanheim** [comment]
@ShaneCastle Thanks for catching that, we lost some spaces when we converted from MSDN to Azure.com. :-) We'll get your contribution published right away. #sign-off

**Pull request merged**
