### PR TITLE
Updated Portal View screenshot

### PR DESCRIPTION
**Pull request by crpietschmann**
Updated Portal View screenshot for current Azure Portal

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crpietschmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@crpietschmann : Thanks for your contribution to the Azure documentation! The author, @mmccrory, has been notified to review your proposed change.

**Comment by crpietschmann** [comment]
I updated the create-database.png screenshot as well.

**Comment by crpietschmann** [comment]
Ping... could someone please review this one soon?

**Comment by crpietschmann** [comment]
Bueller... Bueller... Bueller...

**Comment by crpietschmann** [comment]
If @mmccrory is on to other things, could someone else pick this one up?

**Comment by tysonn** [comment]
@crpietschmann - Sorry, you hit a bug in our notification automation. I will redirect to the author of the article these images are used in.

**Comment by tysonn** [comment]
@barbkess - Hi Barb, could you please review this proposed update to sql-data-warehouse-get-started-provision.md?

**Comment by crpietschmann** [comment]
thanks @tysonn I figured it may have been something like that. :)

**Comment by barbkess** [comment]
@crpietschmann thank you for fixing these images. They look good and we can accept your pull request.

**Comment by barbkess** [comment]
@crpietschmann sorry about the delay in responding, I was on vacation last week.

**Comment by barbkess** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
