### PR TITLE
Update machine-learning-retrain-models-programmatically.md

### PR DESCRIPTION
**Pull request by hning86**
I updated the doc and replaced Scoring with Predicative, and fixed some typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hning86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@raymondlaghaeian
Please review this pull request and approve/disapprove with a comment here. Thanks.

**Comment by rmca14** [comment]
Mail sent.

**Comment by raymondlaghaeian** [comment]
Approved

**Comment by raymondlaghaeian** [comment]
#sign-off

**Pull request merged**
