### PR TITLE
Update cloud-services-continuous-delivery-use-vso.md

### PR DESCRIPTION
**Pull request by UberNewf**
Hi. Trevor Hancock (trevorh@microsoft.com) here from the Microsoft VSO CSS support team. We get quite a few customers trying to deploy VS Web Site  projects from VSO to Azure who get frustrated trying to figure out what's wrong. VSO only supports deployment of VS Web *Application* projects to Azure at this time and I'd like to make that clear in this document. I hope my edit does just that.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@UberNewf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Thraka** [comment]
@kempb Can you confirm the change please?

**Comment by UberNewf** [comment]
Actually, while we're at it we might want to make a comment about Azure Web Jobs. The current VSO CI system does not support deployment of those either, and we've had quite a few customers come in who are trying to make that work, not knowing that it's not even possible (yet). You can verify this with ChrisPat (Microsoft FTE) and then I can add another note about that (or someone else can - doesn't matter to me <g>). I just want to save our customers some frustration. 

Finally, is anyone working on documenting the CI process using the VSO BUILD.NEXT system? It's completely different from this current process.

**Comment by kempb** [comment]
Responded to Trevor's questions via email.

**Pull request merged**
