### PR TITLE
Update backup-dpm-automation.md

### PR DESCRIPTION
**Pull request by AnuragMehrotra**
Corrected an error in the cmdlet flow

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AnuragMehrotra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anuragm). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@AnuragMehrotra Thank you for this contribution.  I'll ask the author to review.

@Jim-Parker Would you please review this change and let me know if I should merge it?

**Comment by Jim-Parker** [comment]
@AnuragMehrotra  In the paragraph just above the change, it mentions that the "step is to specify the protection method using the Set-DPMProtectionType cmdlet." Should there be additional info to support the addition of the Add-DPMChildDatasource cmdlet?

**Comment by AnuragMehrotra** [comment]
I have added some details to explain the new cmdlet.

**Comment by Jim-Parker** [comment]
@AnuragMehrotra added content looks good. Thanks.

**Pull request merged**
