### PR TITLE
Invalid path'ing on CDN backed by Storage Account

### PR DESCRIPTION
**Pull request by jeffpatton1971**
We just went through setting up a CDN endpoint per this article. It turns out that the files just need to be in a public container on the storage account, that container has no impact on the final URL. This was revealed to us after banging away for about an hour against a file we could see in the storage account, but CDN was returning a 404. Someone typo'd the URL excluding the public container and the file began to download to their machine. I only edited the portion related to Storage Accounts, as that's all we are doing.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jeffpatton1971__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@camsoper can you please verify the customer's proposed changes?

**Comment by CamSoper** [comment]
@jeffpatton1971 Hey, Jeff, thanks for the edit!  I'm the maintainer of that article (though not the original author) and it seems like that fell through the cracks when I took over.  I sincerely apologize for your trouble with it.

I'll step through it today and verify your edits (I'm sure they're good) and we'll get it merged in. 

@ggailey777 I'll let you know today when you can approve the PR.

**Comment by CamSoper** [comment]
Okay, so based on the experiment I ran yesterday, there are some discrepancies with how CDN and storage accounts work together.  I have escalated to the engineering team to get some clarification.  I'll keep you posted.

**Comment by ggailey777** [comment]
OK, thanks @camsoper.

**Comment by CamSoper** [comment]
I heard back from engineering.  The documentation was technically correct *as is*, but it omitted an important clarification regarding the **Origin Path** parameter, which is what led to the confusion @jeffpatton1971 experienced (along with longer-than-normal edge node propagation, we think).

I've made the required clarification to the doc on the private repository.  This PR can be closed without merge.

@jeffpatton1971 Thank you for bringing this to my attention.

**Comment by ggailey777** [comment]
@jeffpatton1971 Thanks for your contribution to fixing Azure documentation. We normally like to accept public PRs from customers so that you can get credit for the fix, but in this case it sounds like a fix was already made by @CamSoper in our internal repo. Please don't hesitate to contribute to Azure docs in the future; we will try our best to use your submission next time. 

At this point, I will close this PR.

**Pull request closed without merging**
