### PR TITLE
Updates to the release notes for known issue.

### PR DESCRIPTION
**Pull request by manuaery**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@manuaery__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (manuaery). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@SharS - Sharon, can you review this submission through the public repo?

**Comment by SharS** [comment]
Yes. Thanks.

**Comment by SharS** [comment]
Tyson, please reverse this. It will overwrite some changes that I made to the file. Manu is aware of this and was supposed to close this PR and resubmit this.

**Pull request merged**
