### PR TITLE
change portal url to production

### PR DESCRIPTION
**Pull request by buchizo**
The ms.portal.azure.com is preview UI portal. NOT production.

I would like to change portal url to production url.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@buchizo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@buchizo : Thanks for your contribution to the Azure documentation! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
@tysonn Need to find the correct author.

**Comment by tysonn** [comment]
@buchizo - Thanks for the fix!

**Pull request merged**
