### PR TITLE
Fix PowerShell steps numbering

### PR DESCRIPTION
**Pull request by Zaid-Safadi**
fix PS commands numbering and references in notes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Zaid-Safadi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Cheryl, could you review this update proposed by @Zaid-Safadi in the public repo?

**Comment by tysonn** [comment]
@cherylmc - second notice, please review

**Comment by cherylmc** [comment]
@Zaid-Safadi, thanks for letting us know! @tysonn, could you please merge this in?

**Pull request merged**
