### PR TITLE
Update hdinsight-hadoop-use-pig-powershell.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@Blackmist - Could you please review this public repo update from @alexandair ? Note that it has merge conflicts with the current version. If you decide to merge these, the best path forward is probably for you to run these commands to pull the changes to your local fork, then submit a new PR:

```
git checkout -b alexandair-patch-29 master
git pull https://github.com/alexandair/azure-content.git patch-29
```

You can run these commands from your local private clone.

**Comment by Blackmist** [comment]
Thanks, will fix the merge conflict and publish this morning.

@alexandair, thanks for the contributions! Also, just a heads up that the latest version of Azure PowerShell changes how you retrieve the key. That's why there's a merge conflict; we changed the code to match usage for the new Get-AzureRmStorageAccountKey cmdlet behavior last week. So if you're using an older version of Azure PowerShell, your existing scripts might break when you upgrade. The new method of retrieving a key is:

`$defaultStorageAccountKey = (Get-AzureRmStorageAccountKey -ResourceGroupName $resourceGroupName  -Name $defaultStorageAccountName)[0].Value`

Thanks,
Larry

**Comment by Blackmist** [comment]
Merge conflict resolved in #6658.

**Comment by alexandair** [comment]
@Blackmist, I'm aware of that change. :) Thank you.

**Pull request merged**
