### PR TITLE
Updating the Linux hero page. 

### PR DESCRIPTION
**Pull request by coreysa**
These are some minor updates to the Linux hero page. We will need additional updates over the next few weeks but this is a small revision to update to latest images and remove some of the putty (windows) focus.

### CODE REVIEW

**Comment by squillace** [comment]
Please: DO NOT MERGE.  Hi @coreysa; this document is being completely rewritten -- I'll be checking a complete overhaul into the tree in an hour or so, and will ping you.

**Comment by coreysa** [comment]
Ohhhh, sweet. I didn't know it would be this fast to do a complete over-haul. Thanks, Ralph.

**Comment by squillace** [comment]
@coreysa The complete rewrite is available. I'll send the link.

**Comment by deneha** [comment]
@squillace Should I leave this pull request open?  Looks like you've moved to a different pull request.

**Comment by squillace** [comment]
Go ahead and close as the rewrite has already pushed.

**Pull request closed without merging**
