### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
looks cleaner

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @krnese, has been notified to review your proposed change.

**Comment by krnese** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@krnese - Hi Kristian, please convert these two notes to [Markdown format](https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/custom-markdown-extensions.md#notes-and-tips). Thanks! Katie

**Comment by 4c74356b41** [comment]
Ok, I've fixed that "an" vs "a"

**Comment by 4c74356b41** [comment]
Could you. please clarify what means converting to markdown, since it is using markdown and your link return 404. And I can easily do that, so save Kristian some valuable time.

**Comment by KatieCumming** [comment]
@4c74356b41 - Hi, thank you for offering this, and thanks for your contributions! A markdown note looks like this (on a separate line):
`> [AZURE.NOTE] Your text` where the `>` is at very left margin.

**Comment by 4c74356b41** [comment]
I think I got it.

**Comment by KatieCumming** [comment]
@4c74356b41 - thanks, very close! And I see that there is an extra space in the example I gave you. 
It should like this - the notes need to be on their own line. The `>` is needed too.
`>[AZURE.NOTE] <Your note text>'

**Comment by 4c74356b41** [comment]
ok, i think preview shows what you were asking for now, if not, please let me know!

**Comment by KatieCumming** [comment]
@4c74356b41 - looks good. Thanks again!

**Pull request merged**
