### PR TITLE
Missing EnableBGP flag when creating GW

### PR DESCRIPTION
**Pull request by PedroPerezMSFT**
EnableBGP flag is missing (thus defaulted to $false) when creating the gateway.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@PedroPerezMSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pepere). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@PedroPerezMSFT : Thanks for your contribution to the Azure documentation! The author, @yushwang, has been notified to review your proposed change.

**Comment by yushwang** [comment]
Hi Pedro,

This flag is not needed, but it does trigger the update of a VPN gateway created before BGP was released to "backfill" the BGP parameters. Therefore created a misconception that this flag is needed. I will need to figure out how to explain this in the doc.

Thanks,
Yushun

**Comment by PedroPerezMSFT** [comment]
Hey Yushun,

Good to know ☺

Thanks!
Pedro

**Comment by carmonmills** [comment]
@tysonn Please close this PR per the comments from above.

**Pull request closed without merging**
