### PR TITLE
Update storage-powershell-guide-full.md

### PR DESCRIPTION
**Pull request by pcgeek86**
1. Updates to code formatting
2. Add named parameters
3. Added command to dynamically retrieve Storage Account Key, instead of statically specifying it

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@pcgeek86 Thanks for the contribution!  I have forwarded this change to the author for review.

**Comment by tamram** [comment]
Approved. This is very helpful, thanks.

**Comment by pcgeek86** [comment]
@deneha @tamram Thanks for the feedback!! Small improvements to an already great article!! 

Cheers,
Trevor Sullivan

**Pull request merged**
