### PR TITLE
Updating date and ownership

### PR DESCRIPTION
**Pull request by Antvgski**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Antvgski__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anvang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Antvgski : Thanks for your contribution to the Azure documentation! The author, @AntvgSki, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by ggailey777** [comment]
@Antvgski if you are taking ownership of this topic, you need to be working in the private repo (azure-content-pr). Please resubmit this change in the private repo. Thanks.

**Pull request closed without merging**
