### PR TITLE
From private repo

### PR DESCRIPTION
**Pull request by MAYAKARYA**
The Azure deployment

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MAYAKARYA__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by MAYAKARYA** [comment]
CLA

**Comment by azurecla** [comment]
__@MAYAKARYA__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@MAYAKARYA : Thanks for your contribution to the Azure documentation! The author, @bandersmsft, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@MAYAKARYA - Thanks for your contribution. This pull request contains 404 changed files - it appears that you may be working from an outdated copy of the repository. I am closing this PR for now - please resubmit changes through the public repo one file at a time or reply to this comment with more information about what you are trying to do. Thanks!

**Comment by v-anpasi** [comment]
@MAYAKARYA - Additionally the FromPrivateRepo branch is used internally to keep the public repo in sync with an internal repo. Please use a different branch name moving forward.

**Comment by MAYAKARYA** [comment]
@v-anpasi @tysonn @PRmerger ;
thanks for yours support. now i will learn firts about yours mesage coment.
@azurecla ;
I just get this from docu in my email ;
3D1B65741E7B455398C8DB8596627F531

**Pull request closed without merging**
