### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by keyur32**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@keyur32__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@keyur32 : Thanks for your contribution to the Azure documentation! The author, @dstrockis, has been notified to review your proposed change.

**Comment by dstrockis** [comment]
This doesn't have any changes in it? Please close.

**Comment by BryanLa** [comment]
@dstrockis - this one is a typo correction (ie: Authentcation). Please sign-off when you get a chance and we will get it merged.

**Comment by dstrockis** [comment]
Oh I see, the github syntax didn't highlight it.  #sign-off

**Pull request merged**
