### PR TITLE
Change in last update date, authors

### PR DESCRIPTION
**Pull request by AdiGanMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AdiGanMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (adigan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AdiGanMsft : Thanks for your contribution to the Azure documentation! The author, @Nkolli1, has been notified to review your proposed change.

**Comment by markgalioto** [comment]
Merge as-is, this is just an update to the date.

**Comment by markgalioto** [comment]
@Jim-Parker, This PR can be merged as-is.

**Comment by markgalioto** [comment]
@AdiGanMsft , I'll accept this for Neela. When making these types of updates, if you submit a PR through the private repo, then you can sign off for your own updates, even if you aren't the owner of the article.

**Pull request merged**
