### PR TITLE
Update storsimple-virtual-device-u2.md

### PR DESCRIPTION
**Pull request by vidarmsft**
Removed the version selector and some other minor changes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vidarmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vidar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alkohli - Can you please review these changes in the public repo.

**Comment by alkohli** [comment]
Hi Vivek, I just reviewed the changes. Minor nits: replace 1TB with 1 TB. Also why is the optional tag required? If you see the title of step 3, the entire step is marked as optional. Do you think we still need to add an optional tag to individual steps there? Thanks!

**Comment by tysonn** [comment]
@vidarmsft / @alkohli - I'm closing this for now. If you want to continue, I'd recommend making these updates in the private repository.

**Pull request closed without merging**
