### PR TITLE
Update images now that Service Bus is out of preview

### PR DESCRIPTION
**Pull request by Drewm3**
Refresh images now that Service Bus is not in preview and update code
sample to match the current UI behavior.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Drewm3__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Drew's an employee.

**Comment by tysonn** [comment]
The metadata section is a regression. Can you please run "git pull upstream master" to update your local master. You might have merge conflicts to resolve. See https://github.com/Azure/azure-content/blob/master/contributor-guide/article-metadata.md

**Comment by Drewm3** [comment]
I reverted the first commit and then redid the updates. For some reason there are areas of the article that GitHub us showing as changed which I cannot see what changed. Is this possibly a problem with using Atom as the editor, or this something that is ignorable?

**Pull request merged**
