### PR TITLE
Add urls for 3 pages that are referenced

### PR DESCRIPTION
**Pull request by bethz**
There were 3 pages referenced in the article and I added the relevant url for each of them. This is a minor change.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bethz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bezeran). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@bethz : Thanks for your contribution to the Azure documentation! The author, @HannibalSII, has been notified to review your proposed change.

**Comment by HannibalSII** [comment]
I've reviewed and verified the suggested changes.
#sign-off @PRmerger

**Comment by Saisang** [comment]
@tysonn please merge this PR.

**Pull request merged**
