### PR TITLE
Use the unused variable

### PR DESCRIPTION
**Pull request by mstaessen**
The collectionInfo variable is created twice.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mstaessen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mstaessen : Thanks for your contribution to the Azure documentation! The author, @AndrewHoh, has been notified to review your proposed change.

**Comment by AndrewHoh** [comment]
Great catch mstaessen! Thank you for the PR. @mimig1, can we merge this?

**Comment by mimig1** [comment]
@cjgronlund Please merge. @mstaessen Thank you for the contribution!

**Pull request merged**
