### PR TITLE
Update security-center-troubleshooting-guide.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @YuriDio, has been notified to review your proposed change.

**Comment by YuriDio** [comment]
@alexandair thanks for your contribution. @PRmerger  please merge this change.

**Comment by YuriDio** [comment]
@BryanLa pls merge

**Comment by BryanLa** [comment]
@YuriDio - this one will need to be closed due to a merge conflict. The change can be rolled into your next update to security-center-troubleshooting-guide.md:

Change FROM: ##Troubleshooting Monitoring Agent Installation in Windows  
Change TO: ## Troubleshooting Monitoring Agent Installation in Linux

LMK if you're OK with that and I will close.

**Comment by alexandair** [comment]
@BryanLa Sure, you can close it.

**Comment by BryanLa** [comment]
Thanks @alexandair , will do. And thanks for your contributions!

**Pull request closed without merging**
