### PR TITLE
Updated script with Makecert

### PR DESCRIPTION
**Pull request by crshnbrn66**
Added support for the name of the subscription as creation of the Automation connection fails if you don't set your context first. 
Also added support for using MakeCert.  As the cmdlets first published with this only work if you are on windows 10 and server 2016.  Set the variable for pathToMakeCert to 'C:\Program Files (x86)\Fiddler2\makecert.exe'  Also added logic to see if the certificate is already in the Localhost certificate store.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crshnbrn66__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@crshnbrn66__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tysonn** [comment]
@MGoedtel

**Comment by crshnbrn66** [comment]
I think I missed a ` in this portion of my pull request right after subscription name.

     .\New-AzureServicePrincipal.ps1 -ResourceGroup <ResourceGroupName> `
       -AutomationAccountName <NameofAutomationAccount> `
       -ApplicationDisplayName <DisplayNameofAutomationAccount> `
 -     -CertPlainPassword "<StrongPassword>"
 +     -CertPlainPassword "<StrongPassword>" `
 +     -SubscriptionName <SubscriptionName>  `
 +     -pathToMakeCert <Location where Makecert.exe is>

**Comment by MGoedtel** [comment]
Thanks for your contribution.  I have already updated this article to include updated logic for the POSH script to support referencing a specific subscription with some other changes as well to the overall article.  While it does not include your addition for supporting MakeCert, that can be included after the article is released.  This update is going to be released next week.  I'm going to ask that this request is not processed because of that.

**Comment by crshnbrn66** [comment]
One question when using this script what are the requirements for the permissions of the application in AD?  Does this script setup the permissions for the Application and I missed it?

What permissions to other applications does it need.  REason I ask is because of this article: 
https://github.com/Azure/azure-powershell/issues/2179

**Comment by MGoedtel** [comment]
Hi Thom - just to clarify, I didn't update the article based on your PR, we had already identified that gap in the script for supporting multiple subscriptions a couple of weeks ago.  I didn't want my response to come across the wrong way as trivializing it or disregarding your efforts.  Regarding your other question, it is assigned the Contributor role in the script (and through the UI).  I see that Joe Levy is already looped in with your other article and he is the right person to help you work through your issue.

**Comment by crshnbrn66** [comment]
No problem  I was in no way bothered by your comments. Glad you have a fix in hand

**Pull request closed without merging**
