### PR TITLE
wordsmithing

### PR DESCRIPTION
**Pull request by jpsnover**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jpsnover__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jpsnover : Thanks for your contribution to the Azure documentation! The author, @heathl17, has been notified to review your proposed change.

**Comment by HeathL17** [comment]
Thanks for the PR @jpsnover.  The Azure Style Guide requires the use of sentence casing for titles.  Can you commit with "architecture" in lower case and I'll get the PR merged?  Thanks!

+@ByronR

**Comment by jpsnover** [comment]
I updated the PR.

**Comment by HeathL17** [comment]
Thanks @jpsnover!

#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
