### PR TITLE
Update virtual-machine-scale-sets-overview.md

### PR DESCRIPTION
**Pull request by jluk**
fix "teamplate" typo, minor grammar issues, and swapped backticks for underscores in command line inputs for readability

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jluk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (juluk). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@gbowerman - Can you please review this update and let me know if it can be merged?

@jluk - for future updates, change "azure-content" in the URL of the article you want to update to "azure-content-pr", that will take you to the private repo where PMs and writers work. If you need perms, see https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github.

**Comment by jluk** [comment]
@tysonn yep! thanks for the heads up, will do :smiley:

**Comment by gbowerman** [comment]
Reviewed. Please go ahead and merge.

**Pull request merged**
