### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
as per this article https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-reserved-private-ip/ this change sound logical to me. I'm aware that the "Static Internal Private IP" was referred to as DIP earlier, but I think that now its not supposed to be called DIP. And in this context it also makes no sense:
"static dynamic IP".

Feel free to reject it if you find that its not a sufficient reason for a change, thanks!
ps. also all those PIP,DIP,VIP are really confusing in a whitepaper, I always forget whats the right one, so i have to bing it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial - Could you please review this public repo PR?

**Comment by jimdial** [comment]
#sign-off

**Comment by 4c74356b41** [comment]
Hello?

**Pull request merged**
