### PR TITLE
Added Azure warning for generalized machines for azure-content/articles/virtual-machines/virtual-machines-windows-capture-image.md

### PR DESCRIPTION
**Pull request by olgamatoula**
It has been asked a lot (and I has the question myself) whether you can start the original VM after it has been generalized and after a lot of reading and PowerShell efforts, I have come to the conclusion that you cannot. I think there should this warning on the guide, to inform users that the stopped VM is in an irreversible state, to take proactive action.

@tysonn How do you feel about this? I think it is very important because this search to confirm took a well 4 hours!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@olgamatoula__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dsk-2015 - Dhanashri, could you review this update from @olgamatoula (make sure to read her comments in the pull request thread) and let me know if we can merge?

**Comment by dsk-2015** [comment]
Thanks @olgamatoula. I will test this again later today and sign off.

**Comment by dsk-2015** [comment]
@olgamatoula Hi Olga, I just generalized a RM based Win VM again and I can certainly Stop/Start/Restart it after generalization. The only thing I cannot do is Connect via RDP, since generalization removes all user accounts among other things. In a sense, the generalized VM is in a not so useful state. However the "Status" on the portal does not change to Stopped (deallocated) automatically after Sysprep. We can put a warning saying make a backup copy of your VM since you won't be able to use it after Sysprep.
@tysonn How would you like to proceed on this? The wordings will need to be changed. Let me know.

**Comment by olgamatoula** [comment]
@dsk-2015 Hi Dhanashri, I see what you are saying and yes after the sysprep only it is as you described. BUT when you start the "Capture the VM" procedure at step 4 the PowerShell command
`Set-AzureRmVm -ResourceGroupName YourResourceGroup -Name YourWindowsVM -Generalized` <br>(although super needed to conclude the capturing) is the one that produces this issue i.e. causing the **VM to stay eternally in the stopped (deallocated) state** and the user cannot start it again no matter what I have tried. 
Please, if you could try that also and we can discuss again. :) 
Thanks for reviewing it so far.

**Comment by dsk-2015** [comment]
#sign-off

**Comment by dsk-2015** [comment]
@olgamatoula copying response from the other PR: About your concern about the generalized. I agree, since the Azure commands for generalization are just setting the state of the VM to a "generalized" state manually. We mention that in the steps, and eventually Azure will remove the need to manually set this state, i.e. they will infer the state once SysPrep is over. We could add a line there if that seems confusing.

**Comment by dsk-2015** [comment]
@olgamatoula  For now, we can go ahead and merge this little warning and revisit this later. Or I can make the change in those sections as you wanted as I understand your point now. This PR is showing merge conflicts; you can resolve them by doing a "git pull upstream master" and then "git push origin yourbranchname" in that order. It should most likely resolve everything, since this file is not being touched by anyone else. Let me know if you face any issues.

**Comment by olgamatoula** [comment]
@dsk-2015 To be completely honest I do not think that this line is particularly helpful "_To avoid this affecting your setup, we highly recommend to create a backup copy of your virtual machine before generalizing it._" This tutorial is about making a copy, so suggesting to make a copy has the same result. Shall we rethink how to explain this better and then I'll fix the conflicting issues.

**Comment by dsk-2015** [comment]
@olgamatoula you are right, I'll create another PR on your branch to remove this line. Appreciate your diligence :+1:

**Comment by olgamatoula** [comment]
hi @dsk-2015 I merged your PR and I think that should be fine. Now I am confused about what I should do with this conflict. Can you guide me or even better is it something you can take over?

**Comment by dsk-2015** [comment]
@olgamatoula are you working locally? If yes, then just do a "git pull upstream master" followed by "git push origin yourbranch" and this should get resolved.

**Comment by dsk-2015** [comment]
@tysonn Not sure if she is working locally, but if it's through the web UI, do you have any suggestions about the merge conflicts? Thanks!

**Comment by olgamatoula** [comment]
@dsk-2015 No, since it was a small improvement I used the web UI. I created a remote repository and followed your instructions but there still are conflicts. If you could guide me better since it is my first time having such a conflict or should I open a new PR with a new branch? Thank you again for helping me in this!

**Comment by dsk-2015** [comment]
@olgamatoula Hi Olga, I consulted with an expert in our team; there doesn't seem to be any way to resolve the merge conflicts on the web ui.  So a new PR with a new branch might be the best option for this small change.

**Comment by tysonn** [comment]
@dsk-2015 - This should not be a problem, it's easy enough to figure out. Please come by my office and I will show you.

**Comment by dsk-2015** [comment]
@tysonn Thanks for fixing the conflict and merging this change!

@olgamatoula your change has been merged and should show up on the article when it gets published today.

**Comment by olgamatoula** [comment]
Thanks @tysonn and @dsk-2015 for resolving this!

**Pull request merged**
