### PR TITLE
Update active-directory-accessmanagement-groups-with-advanced-rules.md

### PR DESCRIPTION
**Pull request by RobdeJong**
Removed unused attribute enrollmentType

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@RobdeJong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rodejo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@RobdeJong : Thanks for your contribution to the Azure documentation! The author, @curtand, has been notified to review your proposed change.

**Comment by BryanLa** [comment]
@KatieCumming, @Ja-Dunn - this PR needs to be signed off, but the author (@curtand) is out of sick leave this month. Engineering needs this merged, so is it possible Curtis' manager ( @Femila) can sign off in his absence? Thanks!

**Comment by femila** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@BryanLa - thanks for letting us know! @femila - thanks!

**Comment by BryanLa** [comment]
Thanks @KatieCumming !

**Pull request merged**
