### PR TITLE
Update site-recovery-best-practices.md

### PR DESCRIPTION
**Pull request by jurajsucik**
fixed typo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jurajsucik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@rayne-wiselman Hey Rayne, could you please review this contribution? If it should be added there is a merge conflict that will need to be resolved.

**Comment by rayne-wiselman** [comment]
He’s fixing a typo that as far as I can see no longer exists in the latest version of the doc. You can just tell him he made changes on a non-current version and the doc has recently gone thru a major overhaul. If he still sees anything to fix on the new version - https://azure.microsoft.com/en-us/documentation/articles/site-recovery-best-practices/ he should make a new request.

**Comment by tysonn** [comment]
Thanks for the update, Juraj. It looks like it's been handled in a rewrite of the article, so closing this PR.

**Pull request closed without merging**
