### PR TITLE
Typos and invocation fix

### PR DESCRIPTION
**Pull request by bgelens**
Fixed some markdown typo's. Fixed Url. People probably will browse to and open script using UI so don't use ISE. If you hit f5 / run after opening, PSScriptRoot will be c:\windows\system32 and certificate logic is flawed in this case.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bgelens__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ErikjeMS - Eric, can you review and let me know if we should merge? Note comment from @Dumagar. Thanks -

**Comment by ErikjeMS** [comment]
Yes, please merge.

**Comment by tysonn** [comment]
@bgelens - Thanks for the fix - merged.

**Pull request merged**
