### PR TITLE
Update hdinsight-hadoop-create-linux-clusters-azure-cli.md

### PR DESCRIPTION
**Pull request by oedenfield**
Changed this:
  azure storage account create -g groupname --sku-name RAGRS -l location --kind Storage storagename
to this:
  azure storage account create -g groupname --type RAGRS -l location storagename

I had to use this syntax to get the azure storage account create command to work as expected.

### CODE REVIEW

**Comment by oedenfield** [comment]
Upon further inspection, I had to use a different command for Azure CLI on Linux.  

On Windows I had to use:
azure storage account create -g $hdirg --type RAGRS -l $hdilocation $location $hdistore

On Ubuntu I had to use:
azure storage account create -g $hdirg --kind Storage --sku-name RAGRS -l $hdilocation $location $hdistore

I'm guessing this should be addressed in the documentation (as well as Azure CLI itself)?

**Comment by Blackmist** [comment]
Hi @oedenfield, thanks for reporting this. Can you check the version of the Azure CLI on the Windows and Ubuntu machines? The command would be `azure -v`. 
Also, can you check the mode that the Azure CLI is in? This would be just the `azure` command, and the last line should say the current mode (ARM or ASM).

Trying the latest (0.10.3,) on a Windows system, the command is of the -g, --kind, --sku-name RAGRS variety, which is already in the document. You may be seeing a different set of parameters due to older binaries, or if the cli is in ASM mode. We keep the docs updated to the current version, which unfortunately causes confusion when there's a decision to change the parameters.

Thanks,
Larry

**Comment by oedenfield** [comment]
Hi Larry - You are correct.  I upgraded my Azure CLI on Windows and can now use the same command.  I'm now at 0.10.3.  Sorry for the mis-report.

**Comment by Blackmist** [comment]
Thanks for verifying @oedenfield!

Thanks,
Larry
#please-close

**Pull request closed without merging**
