### PR TITLE
Update sql-data-warehouse-overview-load.md

### PR DESCRIPTION
**Pull request by lodipalm**
Replacing the old article with a new one giving some baseline prescriptive guidance, this will be expanded over the next few days.

### CODE REVIEW

**Comment by deneha** [comment]
Contributor is MSFT employee - remove CLA required

**Comment by rmca14** [comment]
@barbkess 
Please review and approve, thanks.

**Comment by rmca14** [comment]
Hi, Jennie. Can you please review and let me know if I should merge this PR? Barb is apparently OOF. Thanks.

**Comment by JennieHubbard** [comment]
Approved!

**Pull request merged**
