### PR TITLE
Content not relevant to the article

### PR DESCRIPTION
**Pull request by warnov**
The section about "Viewing function output" shows how to see the function invocations of a given function on Azure. I don't find how this is related with the execution of Functions locally using Visual Studio. This confuses the reader too much. So I eliminated that paragraph.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@warnov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@warnov__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@warnov : Thanks for your contribution to the Azure documentation! The author, @tdykstra, has been notified to review your proposed change.

**Comment by tdykstra** [comment]
@warnov, thank you for your suggestion. I've reviewed the article content, and while there may be some readers for whom this section is unnecessary, for many of them it provides helpful information that is relevant to learning how to run functions locally.

**Comment by warnov** [comment]
I do totally agree with you. Actually I learnt to execute functions locally, thanks to the article. It is a great content. But the paragraph I talk about, it seems like it is out of context. And it confused me for a couple of minutes trying to figure it out why it was there.
Just my humble opinion.
T
Get Outlook for iOS




On Mon, Oct 10, 2016 at 2:52 PM -0500, "Tom Dykstra" <notifications@github.com> wrote:












@warnov, thank you for your suggestion. I've reviewed the article content, and while there may be some readers for whom this section is unnecessary, for many of them it provides helpful information that is relevant to learning how to run functions locally.

**Comment by tdykstra** [comment]
@warnov - The "viewing" section might make more sense located at the end just before "troubleshooting" -- If you want to change your PR to move instead of delete the section, we can merge it, otherwise I'm inclined to close the PR unless you have other suggestions.

**Comment by tdykstra** [comment]
#please-close

**Pull request closed without merging**
