### PR TITLE
load-balancer-multivip.md: fix a couple typos

### PR DESCRIPTION
**Pull request by kevin-david**
The whole sentence might need rewriting, but this seemed like an easier fix for now

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kevin-david__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@joaoma - Joao, could you please review this PR in the public repo? Thx

**Comment by joaoma** [comment]
#sign-off

**Comment by tysonn** [comment]
@kevin-david - Thanks for the updates! Merging ---

**Pull request merged**
