### PR TITLE
Update automation-dsc-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Changed "\\" to "\" in a file path.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@coreyp-at-msft Corey, can review Aleksandar's contribution and let me know if it can be merged? Thanks

**Comment by coreyp-at-msft** [comment]
#sign-off

**Comment by Jim-Parker** [comment]
@alexandair Thanks for the contribution Aleksandar. I'll get these added to the article.

**Pull request merged**
