### PR TITLE
prepend a newline so the table renders correctly

### PR DESCRIPTION
**Pull request by grnadav**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@grnadav__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@grnadav : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@telmosampaio - Telmo, could you please review the proposed update? This include is used only in one of your articles.

**Comment by telmosampaio** [comment]
#sign-off

**Pull request merged**
