### PR TITLE
Update expressroute-howto-linkvnet-arm.md

### PR DESCRIPTION
**Pull request by kogesaka**
Sentence of expression, and command content is hard to understand that you want to run.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kogesaka__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@kogesaka : Thanks for your contribution to the Azure documentation! The author, @ganesr, has been notified to review your proposed change.

**Comment by ganesr** [comment]
#sign-off

**Comment by tysonn** [comment]
#hold-off - @ganesr - the pull request cannot be merged due to a merge conflict. See the [wiki for instructions](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx).

**Comment by ganesr** [comment]
@kogesaka please close the PR another PR addresses this.

**Pull request closed without merging**
