### PR TITLE
Update virtual-machines-windows-winrm.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @singhkay, has been notified to review your proposed change.

**Comment by singhkay** [comment]
lgtm @alexandair Thanks for the fix!

**Comment by tysonn** [comment]
@singhkay - Kay, this PR has a merge conflict. Please resolve the merge conflict - we have [instructions on the wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx).

**Comment by tysonn** [comment]
Thanks for fixing, Kay. @alexandair - Your updates were pulled over to the private, they should be published later today.

**Pull request closed without merging**
