### PR TITLE
Add Labels information

### PR DESCRIPTION
**Pull request by YoungjaeKim**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@YoungjaeKim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@YoungjaeKim : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by YoungjaeKim** [comment]
PS. Sorry for the bad English in this PR as I'm not good at English. I appreciate you to revise whole sentence.

**Comment by jomolnar** [comment]
@BryanLa Hi Bryan. Please review the proposed changes. Thanks.

**Comment by BryanLa** [comment]
@jomolnar - Hi Joseph - I should probably defer to @tysonn on this one, mainly because he owns the Contributor Guide. Also, I'm wondering if something like this would be better in one of the PR related topics, ie: contributor-guide-pull-request-comments.md or contributor-guide-pull-request-etiquette.md ?

**Comment by BryanLa** [comment]
Ping for @tysonn

**Comment by tysonn** [comment]
@YoungjaeKim - Could you check out my PR to your fork? https://github.com/YoungjaeKim/azure-content/pull/3. I submitted some revisions for you to review and merge.

**Comment by tysonn** [comment]
@YoungjaeKim - Merged, thank you!

**Pull request merged**
