### PR TITLE
Fixed spelling mistake

### PR DESCRIPTION
**Pull request by jakkaj**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jakkaj__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jakkaj : Thanks for your contribution to the Azure documentation! The author, @anuragdalmia, has been notified to review your proposed change.

**Comment by Erikre** [comment]
Checking with @ggailey777 to resolve merge conflict.

**Comment by ggailey777** [comment]
@jakkaj thanks for your contribution, but this article has already been removed from the repo.

**Pull request closed without merging**
