### PR TITLE
Update automation-dsc-getting-started.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@eslesar - Please review this pull request in the public repo with contributions from @alexandair

**Comment by eslesar** [comment]
@alexandair Thank you for contributing to improve our documentation!

**Comment by eslesar** [comment]
#SignOff

**Pull request merged**
