### PR TITLE
Updated service limit numbers of IoT Hub

### PR DESCRIPTION
**Pull request by jangelfdez**
Right now, documentation shows the service numbers previously to GA

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jangelfdez__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@nasing - Could you please review this update from @jangelfdez to your Service Fabric article and let me know if I can proceed with the merge?

**Comment by tysonn** [comment]
@dominicbetts - Would you be able to review this PR?

**Comment by dominicbetts** [comment]
@tysonn - it looks like these changes have already been made to the article.

**Comment by tysonn** [comment]
@jangelfdez - Thanks for this contribution; I'm closing it since the same updates were submitted by another contributor. .

**Pull request closed without merging**
