### PR TITLE
Corrected typo, organized tools

### PR DESCRIPTION
**Pull request by saraclay**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saraclay__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by davidwrede** [comment]
Hi @tfitzmac, can you take a look at this?

Thanks,
Dave

**Comment by rmcmurray** [comment]
#sign-off

**Comment by tfitzmac** [comment]
looks good to me

**Comment by ggailey777** [comment]
@rmcmurray or @tfitzmac if we still want this contribution can you work with @saraclay to fix the merge conflicts in her PR? Thanks.

**Comment by ggailey777** [comment]
@saraclay thanks for your attempt to contribute, but we need to close this because it looks like other changes were already made to fix this topic. We look forward to being able to use your contributions to Azure docs in the future.

**Pull request closed without merging**
