### PR TITLE
Update cloud-services-dotnet-diagnostics-performance-counters.md

### PR DESCRIPTION
**Pull request by gg90**
There is a missing space. Reference: https://msdn.microsoft.com/en-us/library/azure/gg557552.aspx

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gg90__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@rboucher - Rob, please review this change proposal.

**Comment by rboucher** [comment]
This is a valid change.  Please let it through.

**Comment by rboucher** [comment]
#sign-off

**Comment by rboucher** [comment]
#sign-off

**Comment by rboucher** [comment]
Hi gg90,
Thanks very much for your change request submission.  You have, indeed, found an error.  We'll certainly flow this change into the article.  Thanks again for taking the time to correct the article.

Rob Boucher Jr.
Microsoft Corporation

**Pull request merged**
