### PR TITLE
Change capitalization from DropBox to Dropbox

### PR DESCRIPTION
**Pull request by LazarusX**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@LazarusX__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (fangzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@LazarusX : Thanks for your contribution to the Azure documentation! The author, @luisherring, has been notified to review your proposed change.

**Comment by bjtucker** [comment]
Seems like a lot of simple changes have been languishing for months. Is anybody home?

**Comment by ktoliver** [comment]
@LazarusX - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/active-directory/active-directory-saas-dropboxforbusiness-tutorial](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-saas-dropboxforbusiness-tutorial). Thanks for your understanding.

**Pull request closed without merging**
