### PR TITLE
Update data-factory-build-your-first-pipeline-using-editor.md

### PR DESCRIPTION
**Pull request by rishigoutam**
Should be inputdata instead of scripts as I found when doing this tutorial

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rishigoutam__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@spelluru 
fyi

**Comment by spelluru** [comment]
This does not sound right. The HQL file should be in the script folder.

**Comment by spelluru** [comment]
From the Tutorial Overview page: The HQL file should be in the script folder, not the input folder. Please revert the changes if you can. Thanks. 

e.Repeat the previous two steps to upload the partitionweblogs.hql file to the script folder of the adfgetstarted container. Here is the command: 


Copy

AzCopy /Source:. /Dest:https://<storageaccountname>.blob.core.windows.net/adfgetstarted/script /DestKey:<storagekey>  /Pattern:partitionweblogs

**Comment by rmca14** [comment]
I reverted with PR https://github.com/Azure/azure-content/pull/5421
It should be in time to take effect. Thanks.

**Pull request merged**
