### PR TITLE
Updated Blade names appropriately in the steps.

### PR DESCRIPTION
**Pull request by vivek-dhayalan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivek-dhayalan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial / @cherylmc - Could you review this proposed update to a load balancer article by @vivek-dhayalan in the public repo?

**Comment by tysonn** [comment]
@jimdial /@cherylmc - second notice, please review

**Comment by jimdial** [comment]
#sign-off

Good catch, thanks!

**Pull request merged**
