### PR TITLE
Corrected auth code request description

### PR DESCRIPTION
**Pull request by gleslie2008**
The resource parameter is required for an authorization code request on Azure, not optional.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gleslie2008__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@gleslie2008 : Thanks for your contribution to the Azure documentation! The author, @priyamohanram, has been notified to review your proposed change.

**Comment by priyamohanram** [comment]
@gleslie2008: Thank you for your contribution! The "resource" parameter is actually optional in an authorization code request. If no resource parameter is mentioned, then the resource is by default the AAD graph.

**Comment by priyamohanram** [comment]
#please-close

**Comment by gleslie2008** [comment]
@priyamohanram the behavior of the Azure is inconsistent with the documentation, see [this comment](http://disq.us/p/1c30kak).  Not providing a resource will return a `invalid_resource` error.

**Pull request closed without merging**
