### PR TITLE
Added guidance for ASN number

### PR DESCRIPTION
**Pull request by aicaffre**
Currently there is a bug in Azure where we allow the user to select an invalid ASN number. If they do so, there is no error, and later they can't create BGP connections (with no error visible to them about what is wrong).

Hopefully this FAQ will save Azure users some pain.

I plan to also submit an update to the PowerShell cmd-lets to add a check for a valid ASN number.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aicaffre__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@aicaffre : Thanks for your contribution to the Azure documentation! The author, @adhurwit, has been notified to review your proposed change.

**Comment by adhurwit** [comment]
This is not my article.

**Comment by adhurwit** [comment]
@tysonn  I am not the author of this. Can you correct how this pr is assigned?

**Comment by tysonn** [comment]
@yushwang - Please review this public PR

**Comment by tysonn** [comment]
@yushwang - Can you please review this public PR?

**Comment by cherylmc** [comment]
Hi @aicaffre, @yushwang is working on updates to the FAQ. Thanks for suggesting this. I'm going to go ahead and close this pr, as there will be a merge conflict otherwise.  -Cheryl

**Comment by cherylmc** [comment]
#please-close

**Pull request closed without merging**
