### PR TITLE
Update expressroute-faqs.md

### PR DESCRIPTION
**Pull request by EvanBasalik**
Updated 50 Mbps value as per source

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EvanBasalik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@EvanBasalik : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by cherylmc** [comment]
Hi @EvanBasalik , Thanks! I had 3 other notifications about the same thing, which was awesome. Thanks for keeping an eye out on these and letting me know. I'm going to go ahead and close this, as the change is already in the works. We'll be pointing to the include file for services now so that it stays in sync.

**Comment by cherylmc** [comment]
#please-close

**Pull request closed without merging**
