### PR TITLE
Update virtual-machines-linux-diagnostic-extension.md

### PR DESCRIPTION
**Pull request by NingKuang**
Remove one known issue that is already fixed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NingKuang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ningk). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by NingKuang** [comment]
Thanks, please merge the change, we have fixed a known issue and need to update the doc.

**Comment by azurecla** [comment]
Hi __@NingKuang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ningk). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by NingKuang** [comment]
Thanks, please merge the change, we have fixed a known issue and need to update the doc.

**Comment by NingKuang** [comment]
#sign-off

**Comment by squillace** [comment]
Agreed; thanks @NingKuang ! #sign-off @tysonn

**Pull request merged**
