### PR TITLE
Remove repeated phrase

### PR DESCRIPTION
**Pull request by edsfocci**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@edsfocci__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@edsfocci : Thanks for your contribution to the Azure documentation! The author, @BYHAM, has been notified to review your proposed change.

**Comment by BYHAM** [comment]
#sign-off

**Comment by BYHAM** [comment]
Merge as-is Thank you for submitting this.

**Comment by BYHAM** [comment]
Merge as-is

**Comment by BYHAM** [comment]
Merge as-is

**Comment by tysonn** [comment]
Rick, you need to @ mention your PR review, Carolyn, in the comments. I will merge this time.

**Pull request merged**
