### PR TITLE
Add Note for deploying resources to a different Subnet

### PR DESCRIPTION
**Pull request by snobu**
See comments section:
https://azure.microsoft.com/en-us/documentation/articles/app-service-app-service-environment-intro/

Stefan Schackow:
>"Hmm - is the Linux VM in the *same* subnet as the ASE? I think what is happening is that 10.0.0.8 is in the subnet address range containing the ASE. If that is the case, the behavior is expected because we block connectivity (except for specific intra-ASE routing) to any other IP address in the subnet containing the ASE. If you can redeploy the Linux VM to a different subnet, then connectivity will work.

Hit the same problem myself. Deploying to a different Subnet fixes connectivity. Decided to send PR for make benefit glorious nation of cloud.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snobu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ggailey777** [comment]
@stefsch can you sign-off on the note this customer is adding?

**Comment by stefsch** [comment]
#sign-off

**Comment by ggailey777** [comment]
Thanks @stefsch  and thanks to @snobu for helping improve the quality of the Azure docs!

**Pull request merged**
