### PR TITLE
Make images clickable  + remove subscription ID info from sample image

### PR DESCRIPTION
**Pull request by yoavfrancis**
Hi,

The inline images are very small and cannot be read. I added the option for the user to click on the images to go to the original large PNG screenshots so he or she can properly read the text of the screenshot.

Another issue that I'd appreciate if you could fix is the removal/truncation of the subscription ID info from the network-alert.png file. This subscription ID should not be publicly visible. 

Thanks,
Yoav

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yoavfrancis__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@yoavfrancis : Thanks for your contribution to the Azure documentation! The author, @TerryLanfear, has been notified to review your proposed change.

**Comment by TerryLanfear** [comment]
@yoavfrancis - Thanks, Yoav, for this PR. I will remove the subscription id.  Making the images clickable is a great idea and I am working to do that too (in this article as well as others).  I'm confirming that the format you used is acceptable per our guidance.  As soon as I get that confirmation, I will update.  Thanks, Terry

**Comment by ktoliver** [comment]
@yoavfrancis - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/security-center/security-center-pricing](https://docs.microsoft.com/en-us/azure/security-center/security-center-pricing). Thanks for your understanding.

**Comment by TerryLanfear** [comment]
@yoavfrancis - Now that migration to the new location is complete, I will update the article to remove the subscription id.  I will also look into making the images clickable via our markdown rules.  As noted by ktoliver, you are welcome to resubmit your change.  If you do not resubmit, I will still work on making the changes you requested. Thanks.

**Pull request closed without merging**
