### PR TITLE
Update machine-learning-consume-web-service-with-web-app-template.md

### PR DESCRIPTION
**Pull request by khilscher**
Azure portal updates. RSS template fails to automatically open in Azure Portal. Provided instructions for use to find RSS template.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@khilscher__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@garyericson 
Please review and approve/disapprove with a comment. Thanks.

**Comment by rmca14** [comment]
Follow-up mail sent for review request.

**Comment by rmca14** [comment]
@garyericson 
Yes, **#sign-off** is fine. It won't trigger the **ready-to-merge** label, but it will indicate you'd like the PR merged. Thanks.

**Pull request merged**
