### PR TITLE
Update machine-learning-data-science-move-hive-tables.md

### PR DESCRIPTION
**Pull request by gopitk**
Feedback from previous workshops and content bash

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by MonicaRush** [comment]
@bradsev 
Brad -- Hi -- Would you like to review these changes and let me know if they're OK? Thanks -- Monica

**Comment by bradsev** [comment]
I have reviewed. Please accept these edits. Thx Monica. -Brad

**Comment by gopitk** [comment]
Monica/Brad - Looks like this content never got pushed to prod. Is that
automatic or does someobe have to do anything to push contributed content?
There are two other updates I submitted and were merged late last week.

Thanks,
Gopi Kumar
Sr PM, IMML

**Comment by MonicaRush** [comment]
@gopitk @bradsev 
Gopi -- I don't know why this article was not published. Can you please check again after 10:00 am? If it is not live let me know and I'll look into it further. Sorry for the delay -- Monica

**Pull request merged**
