### PR TITLE
Azure AD Connect: topology freshness update

### PR DESCRIPTION
**Pull request by AndKjell**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AndKjell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (andkjell). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AndKjell : Thanks for your contribution to the Azure documentation! The author, @AndKjell, has been notified to review your proposed change.

**Comment by billmath** [comment]
@sign-off

**Comment by AndKjell** [comment]
I think that should be...
#sign-off

**Comment by billmath** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by AndKjell** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@AndKjell @billmath - Andreas, I know that you're no longer at MS. I'm merging this one, but Bill, please update the GitHub alias with your alias for docs that you own now so this doesn't come up. Thanks! Katie

**Comment by AndKjell** [comment]
From: Tyson Nevil 
Sent: Friday, October 14, 2016 2:37 PM
To: Bill Mathers <billmath@microsoft.com>; Curtis Love <Curtis.Love@microsoft.com>; andreas.kjellman@knowledgefactory.se
Subject: RE: Contributing to the public repo

The confusion happening is because Andreas is still listed as the author, but he is external.  I have some outstanding refinements filed for the notifications as well to address some of this.

That said, because Andreas is now external, you guys are going to have to work together in a different way.

For new articles and major updates, Andreas should coordinate with the FTEs so they know when to expect new articles and major updates.

Andreas, you can submit new content and major updates through the public repo, but Bill or Curtis will need to pull the changes over to the private repository and then stage, validate, and sign off on the content. They’ll close the PR on the public side. If the pull from public to private is done right, the commit history will be maintained showing that Andreas made the changes. The wiki has instructions for pulling across repos.

All of the articles where Andreas would like to continue to be listed as author (implying he will keep them up to date) should list an FTE in the ms.author field so the FTE is notified when changes are made so they can sign off on updates. Anything coming from the outside has to be signed off by an FTE.

**Comment by billmath** [comment]
Doh!, you are right.  ☺

**Comment by AndKjell** [comment]
Tyson had a different view:

From: Tyson Nevil
Sent: Friday, October 14, 2016 2:37 PM
To: Bill Mathers <billmath@microsoft.com<mailto:billmath@microsoft.com>>; Curtis Love <Curtis.Love@microsoft.com<mailto:Curtis.Love@microsoft.com>>; andreas.kjellman@knowledgefactory.se<mailto:andreas.kjellman@knowledgefactory.se>
Subject: RE: Contributing to the public repo

The confusion happening is because Andreas is still listed as the author, but he is external.  I have some outstanding refinements filed for the notifications as well to address some of this.

That said, because Andreas is now external, you guys are going to have to work together in a different way.

For new articles and major updates, Andreas should coordinate with the FTEs so they know when to expect new articles and major updates.

Andreas, you can submit new content and major updates through the public repo, but Bill or Curtis will need to pull the changes over to the private repository and then stage, validate, and sign off on the content. They’ll close the PR on the public side. If the pull from public to private is done right, the commit history will be maintained showing that Andreas made the changes. The wiki has instructions for pulling across repos.

All of the articles where Andreas would like to continue to be listed as author (implying he will keep them up to date) should list an FTE in the ms.author field so the FTE is notified when changes are made so they can sign off on updates. Anything coming from the outside has to be signed off by an FTE.

**Pull request merged**
