### PR TITLE
Update Azure Images gallery, 9/2016

### PR DESCRIPTION
**Pull request by brendalee**
@Ryansoc - FYI, this is the september update for fairfax vm images

### CODE REVIEW

**Comment by brendalee** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@brendalee__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brendal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Ryansoc** [comment]
#sign-off

**Comment by PRmerger** [comment]
@brendalee : Thanks for your contribution to the Azure documentation! The author, @joharve2, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
