### PR TITLE
Must list intermediate certificates

### PR DESCRIPTION
**Pull request by Dmitry-Me**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Dmitry-Me__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@Thraka - Could you review this update from @Dmitry-Me and let me know if we can merge?

**Comment by Thraka** [comment]
@tysonn  Looks good.

**Comment by tysonn** [comment]
@Dmitry-Me - Merged, thank you!

**Pull request merged**
