### PR TITLE
Updates to Virtual network overview page

### PR DESCRIPTION
**Pull request by NarayanAnnamalai**
Updates made as part of the review done by the SDN team PMs on 12/2

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NarayanAnnamalai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by joaoma** [comment]
@tysonn , Pr reviewers, please approve to merge. this content came from the feature PM

**Comment by joaoma** [comment]
#sign-off

**Comment by BryanLa** [comment]
Hi @NarayanAnnamalai , @joaoma - please see below for feedback. Just LMK when you're ready for merge again...

virtual-networks-overview.md

•	All MSFT employees should be working in the private repo. It’s hard to do a thorough job with PR review on public repo submissions when they have more than simple changes (or new articles). The block rendering item below is a good example of where sandbox rendering would make this more obvious to them.
•	Tags.ms.date should be updated to current publishing date
•	The following AZURE.NOTE block under "Deployment Modes" doesn’t appear to be rendering correctly. I’ve tested in both the MarkdownPad preview and Github preview, and it appears that there are tabs in front of it that are causing it to render as a code block.

**Comment by NarayanAnnamalai** [comment]
+Joao: can you help with this.

**Comment by NarayanAnnamalai** [comment]
Bryan,

I fixed the indentation for the azure.net. #sign-off after quick review for me? Thanks for being a trooper and getting this done for me.

https://github.com/NarayanAnnamalai/azure-content/pull/1


From: Narayan Annamalai
Sent: Monday, December 7, 2015 9:24 AM
To: Azure/azure-content <reply@reply.github.com>; Azure/azure-content <azure-content@noreply.github.com>; Joao Madureira <joaoma@microsoft.com>
Subject: RE: [azure-content] Updates to Virtual network overview page (#5118)

+Joao: can you help with this.

**Comment by joaoma** [comment]
#sign-off

**Comment by BryanLa** [comment]
Merging to meet 10am deadline, but the AZURE.NOTE still needs to be fixed in virtual-networks-overview.md

**Pull request merged**
