### PR TITLE
Updates to Premium Storage Overview - Snapshots, VM diagnostics

### PR DESCRIPTION
**Pull request by ms-prkhad**
1) Added line about enabling and using VM diagnostics.
2) Updated the verbiage on snapshots, since new feature for snapshots was deployed with latest Storage build.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ms-prkhad__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@ms-prkhad Thanks for this contribution. I'll have the author review.

**Comment by tamram** [comment]
Looks good, except for one thing. In this bullet point, we say "follow this process", but we don't explain what the process is. @ms-prkhad, can you either elaborate on the process, or remove that phrase altogether?

Follow this process to copy snapshots from a premium storage account to a geo-redundant standard storage account by using AzCopy or Copy Blob.

**Comment by ms-prkhad** [comment]
Thanks for the feedback. I updated the sentence. Let me know if this looks okay.

To keep geo-redundant copies of your snapshots, you can copy snapshots from a premium storage account to a geo-redundant standard storage account by using AzCopy or Copy Blob.

**Comment by tamram** [comment]
Looks good, thanks.

**Pull request merged**
