### PR TITLE
fix package name for Ubuntu Linux

### PR DESCRIPTION
**Pull request by saschagottfried**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@saschagottfried__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ahmetalpbalkan** [comment]
LGTM

**Comment by tysonn** [comment]
@Jasontang501 - Jason, can you please review - thanks

**Comment by Jasontang501** [comment]
Hi @saschagottfried

Thanks for your contribution to improve the doc, proposed change looks good to me. 
I am OK to merge.

- Jason

**Pull request merged**
