### PR TITLE
Update app-service-web-arm-with-sql-database-provision.md

### PR DESCRIPTION
**Pull request by adamglick**
Changing name of SQL firewall rule from AllowAllWindowsAzureIps to AllowAllAzureIps since the name of the service has changed. :)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adamglick__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@adamglick : Thanks for your contribution to the Azure documentation! The author, @cephalin, has been notified to review your proposed change.

**Comment by cephalin** [comment]
@adamglick Sorry for the delay. Thank you for your contribution and the change looks good!

#sign-off

**Comment by cephalin** [comment]
#sign-off

**Comment by cephalin** [comment]
@ggailey777 Isn't the #sign-off comment supposed to work in this repo? Not getting the ready-to-merge tag.

**Pull request merged**
