### PR TITLE
Update date

### PR DESCRIPTION
**Pull request by zjalexander**
Minor typo, but otherwise content is good. Refreshing the data.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@zjalexander__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@zjalexander : Thanks for your contribution to the Azure documentation! The author, @zjalexander, has been notified to review your proposed change.

**Comment by zjalexander** [comment]
ok to merge #sign-off

**Comment by tysonn** [comment]
@zjalexander - Sorry, I have to close this. Please see [Authors working in the public repo](https://microsoft.sharepoint.com/teams/azurecontentguidance/article-author-working-in-the-public-repo)

**Pull request closed without merging**
