### PR TITLE
Update stream-analytics-introduction.md

### PR DESCRIPTION
**Pull request by stuartswift**
Added inclusion of IOT Event Hubs as an input source. This is already stated in Developer docs

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartswift__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@stuartswift 
Thank you for this contribution. I'll verify it and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@jeffstokes72 
Hi, Jeff, Please check this PR, and let me know whether I should accept it.
Thanks!

**Comment by jeffstokes72** [comment]
Accepted. The other one is not as it contains some of the same edits but not as many of them. I'll make a note on the other PR.

**Comment by jeffstokes72** [comment]
These two PRs he submits are good but both modify the same paragraph in different ways so conflict. I'll make a new PR to address.

**Pull request merged**
