### PR TITLE
Update code example to be a block instead of inline

### PR DESCRIPTION
**Pull request by moshegutman**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@moshegutman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@moshegutman : Thanks for your contribution to the Azure documentation! The author, @dragon119, has been notified to review your proposed change.

**Comment by dragon119** [comment]
@moshegutman, Thank you for fixing this. 

Please merge this PR as is.

**Comment by dragon119** [comment]
#sign-off

**Comment by moshegutman** [comment]
Do I need to take some action?

**Pull request merged**
