### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
i think it should be "are"?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @narayanannamalai, has been notified to review your proposed change.

**Comment by NarayanAnnamalai** [comment]
#merge-as-is 
Ready to merge
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by NarayanAnnamalai** [comment]
good to merge

**Comment by TerryLanfear** [comment]
@NarayanAnnamalai - 4c74356b41 let me know that there were PRs that seemed to be stalled.  Do you know who your pull request approver is?  Can you message your PR approver to merge?

**Comment by NarayanAnnamalai** [comment]
@jimdial and @tysonn  to help with the above question:
 Do you know who your pull request approver is? Can you message your PR approver to merge?

**Comment by NarayanAnnamalai** [comment]
I am the author of the document and I already approved the merge, 13 hours ago

**Comment by NarayanAnnamalai** [comment]
#merge as is. Approved to merge, changes look good.

**Comment by tysonn** [comment]
@NarayanAnnamalai  - The article lists the author this way `authors="narayanannamalai"`. Your actual GitHub account is NarayanAnnamalai. GitHub is case sensitive. That is why you were not able to sign off.

There's also a merge conflict that needs to be resolved before this can be merged. See [instructions on the wiki.](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx)

**Comment by NarayanAnnamalai** [comment]
What should I do now, sent out a spate CR fixing the author name?

**Comment by KatieCumming** [comment]
@NarayanAnnamalai - Hi Narayan, just go ahead and fix the merge conflict. Please see the instructions on the wiki in the link Tyson included above. Thanks, Katie

**Comment by jimdial** [comment]
@4c74356b41: There ended up being a merge conflict with this proposal and a separate change made to the author value for the article.  The author value was updated in this article, as was incorporation of your suggestion, but was done in a separate PR.  Sorry for the confusion, but you should see your proposed change on the live page.  Thanks for catching it. 

#please-close

**Comment by 4c74356b41** [comment]
its okay as long as the fixes are there ;)

**Pull request closed without merging**
