### PR TITLE
Update virtual-machines-windows-extensions-troubleshoot.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos in code.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@tysonn Can someone check out this PR, please?

**Comment by tysonn** [comment]
@kundanap - Could you review this update from @alexandair to your article?

**Comment by alexandair** [comment]
@tysonn Any follow up on this?

**Comment by KundanaP** [comment]
# sign off

**Comment by KundanaP** [comment]
#sign-off

**Pull request merged**
