### PR TITLE
Clean up documents which still make reference to xplat-cli 

### PR DESCRIPTION
**Pull request by devigned**
- remove or replace existing references to xplat-cli with Azure CLI 
- rephrase cross-platform references to Azure CLI

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@devigned__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dajustic). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
Nice! Finally. 😊

**Comment by devigned** [comment]
rebased based on current master. Should be up-to-date.

**Comment by squillace** [comment]
LGTM. Ship it.

**Comment by devigned** [comment]
@squillace thank you for the review.

**Comment by tysonn** [comment]
@devigned I'm going to try to move the commits over to the private repo so the changes are run through validation.

**Pull request closed without merging**
