### PR TITLE
more information: point to SF terminology overview

### PR DESCRIPTION
**Pull request by AlexZeitler**
Point to next document in navigation instead of previous

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlexZeitler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlexZeitler : Thanks for your contribution to the Azure documentation! The author, @msfussell, has been notified to review your proposed change.

**Comment by msfussell** [comment]
Alex,
Thanks for spotting this. Yes your change is correct, it should point to the next article. 

Mark

**Comment by KatieCumming** [comment]
@msfussell  - merging. Please use #sign-off in the future after you've approved a change. Thanks, Katie

**Comment by msfussell** [comment]
#sign-off

**Pull request merged**
