### PR TITLE
Fixed "Manger" typo to "Manager"

### PR DESCRIPTION
**Pull request by crpietschmann**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crpietschmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@crpietschmann : Thanks for your contribution to the Azure documentation! The author, @MikeRayMSFT, has been notified to review your proposed change.

**Comment by cynthn** [comment]
#sign-off @crpietschmann thank you for catching that!

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by crpietschmann** [comment]
#sign-off... Bueller..

**Comment by crpietschmann** [comment]
no problem, not the best PR, but I keep an eye out to where I can help contribute. :)

**Pull request merged**
