### PR TITLE
HBase docs mistakes

### PR DESCRIPTION
**Pull request by changhc**
I found some mistakes when following the instructions.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@changhc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@changhc__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@changhc : Thanks for your contribution to the Azure documentation! The author, @mumian, has been notified to review your proposed change.

**Comment by mumian** [comment]
For the sentiment article, the Twitter API has switched the coordinates in the latest API.  I have updated the article to specify the API version.

For the HBase getting started article, the paths appear to be fine with my test. There is one issue with putting spaces after commas in the column family.  I will update the article.

#please-close

**Pull request closed without merging**
