### PR TITLE
Add the time to live information for Azure Storage Queue message

### PR DESCRIPTION
**Pull request by FabienLavocat**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@FabienLavocat__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@tamram - Could you please review this update from @FabienLavocat  to a storage include and let me know if we can merge?

**Comment by tamram** [comment]
@FabienLavoca, thank you for the feedback. I will incorporate the change, but I want to put it in a slightly different place than where you have. I'll report back here once that change is in.

@tysonn, please go ahead and close this PR.

**Comment by tysonn** [comment]
Let's go ahead and merge so Fabien is logged as a contributor, then you can move in a separate PR.

**Comment by tamram** [comment]
Okay, great, please do.

**Comment by tysonn** [comment]
Thanks, @FabienLavocat , for the update

**Comment by FabienLavocat** [comment]
Thanks everyone for your help!

**Pull request merged**
