### PR TITLE
Change If-None-Match header to If-Match

### PR DESCRIPTION
**Pull request by Huachao**
Optimistic concurrency uses If-Match header.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Huachao__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dragon119 & @bennage - Can you review this update and let me know whether to merge? Thanks

**Comment by bennage** [comment]
Can you assign it to me? It helps me keep track of what I'm doing.

**Comment by tysonn** [comment]
@bennage / @dragon119 - Could you guys update the thread on this public repo PR?

**Comment by bennage** [comment]
Thanks for bumping this. I'm embarrassed that we overlooked it.

**Comment by tysonn** [comment]
@bennage - Could you have the team handle this, or let me know to close the proposed change?

**Comment by dragon119** [comment]
I'll take care of this.

**Comment by dragon119** [comment]
@Huachao, this scenario is slightly different from optimistic concurrency. If-None-Match is used for conditional requests in which it retrieves new entity if it's updated from specified version.  This [book](https://www.safaribooksonline.com/library/view/http-the-definitive/1565925092/re30.html) explains it very well.

**Comment by Huachao** [comment]
@dragon119, in the file I change, the url request method is PUT, so not retrieving new entity.

**Comment by dragon119** [comment]
@Huachao, Oops that's right. I was checking a different section. Thank you for reporting this.

@tysonn, please merge this PR.

**Pull request merged**
