### PR TITLE
Update sql-database-elastic-pool.md

### PR DESCRIPTION
**Pull request by anosov1960**
Fixing incorrect capture of the geo-replication behavior during the preview

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anosov1960__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@stevestein 
Please review this PR and note your approval/disapproval here. Thanks.

**Comment by stevestein** [comment]
@rmca14 
 Can we quickly edit and use this?

You can enable Geo-replication on a database that is already in the pool if the target server you specify has a pool with the same name as the source pool. Currently in the preview, you cannot enable Geo-Replication on a database that is already in a pool to a pool with a different name or to a single database as the secondary.

**Comment by rmca14** [comment]
I can't edit it. The pull request submitter will need to edit it. anosov1960 Please feel free to make the noted edit and resubmit the pull request. Thanks.

**Comment by rmca14** [comment]
@stevestein 
Sasha said he fixed it. Please let me know if I should merge the PR -- thanks.

**Comment by stevestein** [comment]
@rmca14; @anosov1960 
Yes, looks good to go. You can accept the PR.

Thanks.

**Pull request merged**
