### PR TITLE
In PS Create VM the ProbeProtocol should be TCP or HTTP

### PR DESCRIPTION
**Pull request by BlueBasher**
When creating a load-balanced endpoint the ProbeProtocol should either be tcp or http.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BlueBasher__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@BlueBasher__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by tysonn** [comment]
Marco, thanks for the contribution. @cynthn - Cynthia, could you please review?

**Comment by cynthn** [comment]
@tysonn this change looks fine #sign-off

**Pull request merged**
