### PR TITLE
Update machine learning linear regression article

### PR DESCRIPTION
**Pull request by KBaroni**
Updated the date to comply with article refresh ask.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@KBaroni__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@KBaroni : Thanks for your contribution to the Azure documentation! The author, @garyericson, has been notified to review your proposed change.

**Comment by garyericson** [comment]
@tysonn  This is okay to merge, it's just a date change. Kate didn't seem to have access to the private repo so she made the change here. I'll work to get her access.

**Comment by garyericson** [comment]
#sign-off

**Pull request merged**
