### PR TITLE
Update date after adding regions to include

### PR DESCRIPTION
**Pull request by Drewm3**
#signoff

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Drewm3__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (drewm@ntdev.microsoft.com). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Drewm3 : Thanks for your contribution to the Azure documentation! The author, @drewm3, has been notified to review your proposed change.

**Comment by Drewm3** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by KatieCumming** [comment]
@Drewm3 - Hi Drew, This change should be made in the private repo. For information about accessing the private repository, see https://github.com/Azure/azure-content#use-github-git-and-this-repository.
I'm closing this pull request. Thank you!

**Pull request closed without merging**
