### PR TITLE
Update note section

### PR DESCRIPTION
**Pull request by yuemlu**
Update the note section to include this clarification
Premium Storage currently does not support Azure Block Blobs, Azure Append Blobs, Azure Files, Azure Tables, or Azure Queues.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yuemlu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (yuemlu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@yuemlu : Thanks for your contribution to the Azure documentation! The author, @aungoo-msft, has been notified to review your proposed change.

**Comment by robinsh** [comment]
@yuemlu Thanks very much for contributing to the Azure documentation. Can you please share with me why you think this note needs to be added when it is pointed out in the second paragraph of the preceding section, the one titled "Premium Page Blob"?

**Comment by yuemlu** [comment]
@robinsh Yes, the added note is included in the second paragraph. Given that this is a long page, customers might not be reading line by line. We would like to add this in the Note as highlights. We did get a few customer escalations around this area.

**Comment by robinsh** [comment]
@yuemlu How about if we change the paragraph "Premium Page Blob" above that, and insert the note at the end of the paragraph? Then it's called out where we're talking about the types of storage.

**Comment by robinsh** [comment]
@yuemlu Can we make the change I've suggested above?

**Pull request closed without merging**
