### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**
and hopefully fixing image (there wasn't a newline before image)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
These look good.  Go ahead and merge.

**Comment by billmath** [comment]
These look good.  Go ahead an merge.

**Comment by billmath** [comment]
Changes good please merge.

**Comment by BryanLa** [comment]
Hi @billmath - per new protocol, you'll need to sign-off your PRs, which will trigger the ready-to-merge label, which will allow the review team to merge.

**Comment by billmath** [comment]
#sign-off

**Pull request merged**
