### PR TITLE
Multiple Site to Site VPN

### PR DESCRIPTION
**Pull request by omartin2010**
supported on the portal and reference to the article added to the table

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by yushwang** [comment]
#please-close

@omartin2010 Please take a look at the current table on the page. Cheryl added more comments and notes.

**Comment by omartin2010** [comment]
As long as it's clear in the actual documents - I had comments from a customer, hence the PR - it's perfect :)

**Pull request closed without merging**
