### PR TITLE
Update load-balancer-get-started-ilb-arm-template.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed the title and some other typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@joaoma or @cherylmc - Please review Alesandar's updates and let me know if they can be merged.

**Comment by cherylmc** [comment]
@joaoma, can you take a look. I am not a load-balancer guru.

**Comment by joaoma** [comment]
#sign-off

**Comment by tysonn** [comment]
@alexandair - Thank you!

**Pull request merged**
