### PR TITLE
added a reference to custom roles

### PR DESCRIPTION
**Pull request by jurajsucik**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jurajsucik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@jurajsucik - thanks very much for your contribution!
@kgremban - can you have a look at this PR? Juraj is a MSFT employee. The PR is currently in merge conflict, so it's probably best if you can review these and decide if they should be rolled into a different/internal PR. LMK and I can close this one after you have a chance to review. Thanks!

**Comment by kgremban** [comment]
@BryanLa This branch is in conflict because I separately made an update similar to the one @jurajsucik requested. This PR can be closed. Thank you for the feedback, Juraj!

**Comment by BryanLa** [comment]
@kgremban Done. Thanks again!

**Comment by azurecla** [comment]
Hi __@jurajsucik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@jurajsucik - please ignore the bot message. The GitHub UI hung for a second, causing a brief reopen/close.

**Pull request closed without merging**
