### PR TITLE
Fixed missing links - site-recovery-faq.md

### PR DESCRIPTION
**Pull request by kuniteru**
Fixed missing links

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kuniteru__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, can you please review Kuniteru's contributions? merge conflicts will need to be address before merge. thanks,

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, bumping this for your review.

**Comment by rayne-wiselman** [comment]
It looks as though the changes haven’t been made on the latest version of the file since my latest version already contains these changes. The author should update on latest version and then see if there are actually any changes that need to be made.

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, please work with the contributor to implement the fix to the correct version.

**Comment by rayne-wiselman** [comment]
We need to tell them to update master to get the latest version. Shall i do that?

Sent from Outlook<http://aka.ms/liysn4> on Android



On Mon, Feb 29, 2016 at 8:42 AM -0800, "Jim Parker" <notifications@github.com<mailto:notifications@github.com>> wrote:


@rayne-wiselman<https://github.com/rayne-wiselman> Rayne, please work with the contributor to implement the fix to the correct version.

-

**Comment by Jim-Parker** [comment]
@kuniteru @rayne-wiselman Kuniteru, thank you very much for your contribution. I've reviewed your suggestions and it turns out that Rayne (the author) has already addressed the broken links, so I'm going to close this pull request. If you see anything else, please let us know.

**Pull request closed without merging**
