### PR TITLE
Update versions to 0.9.0 (API V1)

### PR DESCRIPTION
**Pull request by dadoonet**
Still have to add API V2

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dadoonet__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@rmcmurray - Rob, can you review this contribution?

**Comment by rmcmurray** [comment]
Sure – I’ll look at that now.

Thanks!

**Comment by rmcmurray** [comment]
I have a series of changes which I am already working on in another branch which will include these changes.

**Comment by ggailey777** [comment]
@rmcmurray There are no conflicts in this PR at this point. If you can confirm that the changes suggested by @dadoonet are correct, I would like to merge this PR so that he can get credit for the contribution.

Thanks.

**Comment by ggailey777** [comment]
@rmcmurray there are still no conflicts, so I assume your updates in the private repo never made it in. Can we just use the customer's contribution?

**Comment by rmcmurray** [comment]
That include file should no longer be used (and can be deleted); it's an artifact from when we had three separate download pages for Mac, Linux, and Windows. We now have a single, consolidated download page which is version agnostic at https://azure.microsoft.com/documentation/articles/java-download-azure-sdk/.

**Comment by ggailey777** [comment]
@dadoonet It turns out this information has been moved to another topic, where is has already been corrected. Thanks for your attempt to contribute, we hope you continue to help us out with Azure docs in the future.

**Comment by dadoonet** [comment]
FYI, as I am in France (french laptop), I access to: https://azure.microsoft.com/fr-fr/documentation/articles/java-download-azure-sdk/

The maven list is:

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management-compute</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management-network</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management-sql</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management-storage</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-management-websites</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-media</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-servicebus</artifactId>
    <version>n.n.n</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-serviceruntime</artifactId>
    <version>n.n.n</version>
</dependency>
```

Which looks wrong to me as I wrote in my PR.

Not sure how I can check the english version as I'm always redirected to the french page.... :(

**Comment by rmcmurray** [comment]
@dadoonet - thanks again, we are working on a new version of the consolidated article which should improve the clarity and update the artifact IDs.

**Comment by rmcmurray** [comment]
@dadoonet - Can you verify the newly-published version of this article? It mentions the version-agnostic syntax a little better (e.g. replacing the "n.n.n" placeholders with the desired version numbers) and contains updated artifact IDs.

https://azure.microsoft.com/en-us/documentation/articles/java-download-azure-sdk/

Thanks again!

**Comment by dadoonet** [comment]
Hi @rmcmurray.

It looks now good to me.

That being said, I think it's a bit fuzzy to get what is the right version people should use. Because when you click on the "maven" [link](http://search.maven.org/#browse%7C1671162511): `http://search.maven.org/#browse%7C1671162511`, you get a full list of artifacts (old ones included). It requires some efforts (not a big deal though).

the central repository search engine google chrome aujourd hui at 08 37 43

May I suggest that you link instead to `http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20(a%3Aazure-serviceruntime%20OR%20a%3Aazure-servicebus%20OR%20a%3Aazure-svc-*)`: [example](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20(a%3Aazure-serviceruntime%20OR%20a%3Aazure-servicebus%20OR%20a%3Aazure-svc-*)) so it's super easy to get the current version number (and the release date) in one click?

the central repository search engine google chrome aujourd hui at 08 41 12

May be you should also think of renaming `azure-servicebus` to `azure-svc-bus` and `azure-serviceruntime` to `azure-svc-runtime`?
Even better, you should may be put all `azure-svc-*` artifacts under their own `groupId` such as `com.microsoft.azure.service` or whatever...

BTW, is there anyway to get notified each time a new version is pushed? I'd like to keep in sync as much as possible elasticsearch azure plugins with the SDK version...

I hope this helps.
Best!

**Comment by dadoonet** [comment]
Oh. I forgot.

You could add in your docs that people should better use a maven property to define their azure SDK version like:

```xml
<properties>
    <azure.version>0.9.3</azure.version>
</properties>
```

And then apply this to all dependencies:

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-compute</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-network</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-sql</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-storage</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-websites</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-media</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-servicebus</artifactId>
    <version>${azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-serviceruntime</artifactId>
    <version>${azure.version}</version>
</dependency>
```

Updating to the next version will be consistent (well, you reduce the risk of forgetting to upgrade one of the lib).

That being said, I guess that maven users already know that... :)

**Pull request closed without merging**
