### PR TITLE
Replace code image with code and other minor fixes

### PR DESCRIPTION
**Pull request by vladm123**
Added working code instead of image
Fixed `ileaner` to `ilearner`
Added long inline code inside code tag

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vladm123__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@vladm123__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by rmca14** [comment]
@garyericson 
Please review this PR and reply here with your approval/disapproval. Thanks.

**Comment by garyericson** [comment]
I'm going to need to review this carefully, and it's low priority for me right now. So I'm going to leave it sitting here for a few days. If that's not okay, let me know.

**Comment by rmca14** [comment]
Okay, thank you.

**Comment by rmca14** [comment]
@garyericson 
Gary, following up. Thanks.

**Comment by rmca14** [comment]
@garyericson 
Should we close this PR?

**Comment by garyericson** [comment]
Is there a way to direct this PR to raymondlaghaeian to have him look at it? He's the original author and I'd prefer he double-checked the suggested code samples.

**Comment by rmca14** [comment]
#sign-off

**Comment by rmca14** [comment]
His username isn't resolving in the comment window, so you can't send it to him via @raymondlaghaeian. Best thing is to send him email with a link to this PR, and then either he or you add a comment when it's ready to merge.

**Comment by garyericson** [comment]
Okay, I'll send email. Thanks.

**Comment by garyericson** [comment]
I accepted much of this, but made some changes in PR 14671. I'm not sure what to do with this PR now.

**Comment by rmca14** [comment]
If you made changes in another PR that replace the changes in this PR, feel free to close this PR (unmerged).

**Comment by garyericson** [comment]
I guess we can close this PR. It's replaced with 14671.

**Pull request closed without merging**
