### PR TITLE
Install permissions for SQL account

### PR DESCRIPTION
**Pull request by DamianWiese**
The current documentation states that SA in SQL server is required so that it can create a login in the SQL instance. This does not adhere to least privilege principles. Instead, this account only needs to be granted access to dbcreator and securityadmin roles. I updated the SQL permissions in the section "Install required components"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DamianWiese__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by BryanLa** [comment]
@DamianWiese - thanks very much for your contribution!
@billmath - Damian is a MSFT employee. Can you review and LMK if you're OK with merging? Thanks!

**Comment by billmath** [comment]
Verifying the technical accuracy with the PM.

**Comment by billmath** [comment]
It is currently not supported to not use SA, so this would be a DCR and not just a doc update.  At this point, the PR needs to be declined.

**Comment by BryanLa** [comment]
Closin per @billmath .

**Pull request closed without merging**
