### PR TITLE
Updating ADLS Java SDK article to reflect current Maven packages

### PR DESCRIPTION
**Pull request by matt1883**
Updating ADLS Java SDK article to reflect current Maven packages.

The new code and steps in this PR have been tested, and they work. The core changes include: updated steps for project creation so that it doesn't deal with POM.xml creation, the use of Maven instead of ADX Snapshot packages, and the refactorings required to use the new packages.

@begoldsm, could you ACK please?

@nitinme, @mumian, could one of your sign off on this, please?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt1883__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mahi). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by begoldsm** [comment]
Acknowledged. I'm looking this over now.

**Comment by PRmerger** [comment]
@matt1883 : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by begoldsm** [comment]
Looks good to me!

**Comment by matt1883** [comment]
Thanks, @begoldsm!

@mumian, since @nitinme is not available today, could you review when possible, please?

**Comment by mumian** [comment]
#sing-off

**Comment by mumian** [comment]
Nitin is OOF.  I have reviewed the changes. #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by matt1883** [comment]
@cjgronlund FYI this is ready to merge

**Comment by cjgronlund** [comment]
@mumian @matt1883 
This article is now in the private repo in this PR: https://github.com/Azure/azure-content-pr/pull/29370

Please sign-off there. 

This PR can be closed.

**Pull request closed without merging**
