### PR TITLE
Fix vm endpoint delete command syntax

### PR DESCRIPTION
**Pull request by fjaguero**
The last parameter is not the port but the endpoint-name (as in endpoint update). Add [options] as a parameter.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@fjaguero__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
Hi.... Is this in service or resource mode? Just want to make sure we are in the same mode.....

**Comment by fjaguero** [comment]
I think is service mode -> http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-command-line-tools/

**Comment by squillace** [comment]
Great! Thanks for the fix. Seems hard to miss, yes? :-)

**Comment by squillace** [comment]
@deneha Merge please. :-)

**Comment by fjaguero** [comment]
I'm building an internal app that automates the creation and provisioning (with custom software) of VMs so I'm using many of the features of the CLI :D

**Pull request merged**
