### PR TITLE
Update virtual-machines-linux-extensions-customscript.md

### PR DESCRIPTION
**Pull request by MartinGoodwell**
fixed some small typos

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MartinGoodwell__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MartinGoodwell : Thanks for your contribution to the Azure documentation! The author, @kundanap, has been notified to review your proposed change.

**Comment by KundanaP** [comment]
#sign-off

**Comment by KundanaP** [comment]
#sign-off

**Pull request merged**
