### PR TITLE
Fixing a few issues in .NET SDK article 

### PR DESCRIPTION
**Pull request by matt1883**
Fixing a few issues in .NET SDK article, having to do with the latest authentication package version.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt1883__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mahi). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@matt1883 : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@matt1883 - Thanks for submitting the PR.

In step 7, looks like the namespace declaration is outside the code block. This is probably because of a missing tab indentation. Could you please fix that and push the commit? Thanks.

**Comment by nitinme** [comment]
@matt1883 - Thanks for the changes.

#sign-off

**Comment by nitinme** [comment]
#hold-off

**Comment by nitinme** [comment]
#sign-off

**Comment by tysonn** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by nitinme** [comment]
#sign-off

**Comment by nitinme** [comment]
#sign-off

**Comment by nitinme** [comment]
Please close this PR. The changes were merged as part of another PR.

**Pull request closed without merging**
