### PR TITLE
Added Visual Studio prerequisites to getting-started

### PR DESCRIPTION
**Pull request by peteraritchie**
I could not get the sdk to work (debug) without update 2

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@peteraritchie__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@seanmck - Sean, could you review this update proposed by @peteraritchie in the public repo?

**Comment by tysonn** [comment]
@seanmck - Second notice, please review

**Comment by seanmck** [comment]
@peteraritchie: Thanks for the contribution. We actually hadn't realized that this Update 2 dependency had snuck in.

@tysonn: Since we now support multiple versions of VS, I will handle this in a slightly different way. You can go ahead and close without merging.

**Pull request closed without merging**
