### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**
and fixing link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @rgardler, has been notified to review your proposed change.

**Comment by rgardler** [comment]
#sign-off

**Comment by Ja-Dunn** [comment]
@rgardler - Hi Ross, could you resolve this merge conflict. Thanks!

**Comment by rgardler** [comment]
This document has been edited elsewhere with similar updates. This PR can be closed.

**Pull request closed without merging**
