### PR TITLE
Update sql-database-elastic-transactions-overview.md

### PR DESCRIPTION
**Pull request by SilviaDoomra**
Removing the limitation for DBs to belong to same logical server.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SilviaDoomra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sdoomra). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@torteng 
fyi

**Comment by torsteng** [comment]
This change is not (yet) correct. We have to wait until the corresponding change rolls out into production. Can we hold the change?

**Comment by torsteng** [comment]
Hi Ross, Silvia,

This change is not yet live. Hence, the change is not correct. Can we revert the change and wait until this has become live in production?

Thanks,
Torsten

**Comment by SilviaDoomra** [comment]
Hello everyone,

I have submitted a request to revert the change until the changes are in production. Torsten will submit the final doc changes once its ready.

Thanks,
Silvia Doomra | Program Manager II | Azure SQL Database | Microsoft Corporation

I support TEALS. How about you? Particpate in Giving, your way at //Give.

**Pull request merged**
