### PR TITLE
Update iot-azure-and-iot.md

### PR DESCRIPTION
**Pull request by ppatierno**
It should be a typo ... "device-to-cloud telemetry data" for machine learning and not "cloud-to-device"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ppatierno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sethmanheim - Could you review this contribution, please?

**Comment by sethmanheim** [comment]
@tysonn @dominicbetts Hey Dominic, this gets pulled into one of your articles, so can you please verify?

**Comment by dominicbetts** [comment]
@tysonn @sethmanheim it looks like this change has already been made so we don't need this PR.

**Comment by tysonn** [comment]
@ppatierno - Paolo, thanks for this update; it looks like it's been taken care of already, so I'm going to close. Thanks again for taking the time to make a suggestion!

**Pull request closed without merging**
