### PR TITLE
Update app-service-app-service-environment-custom-settings.md

### PR DESCRIPTION
**Pull request by naziml**
Adding FrontEnd SSL cipher suite ordering setting.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@naziml__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (naziml). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by naziml** [comment]
#sign-off

**Comment by PRmerger** [comment]
@naziml : Thanks for your contribution to the Azure documentation! The author, @stefsch, has been notified to review your proposed change.

**Comment by stefsch** [comment]
#sign-off

**Comment by tysonn** [comment]
@stefsch - I will merge, but you should follow up with an update to put the new note into the correct AZURE.NOTE syntax (see [custom markdown extensions](https://github.com/Azure/azure-content/blob/master/contributor-guide/custom-markdown-extensions.md)). In cases like this, it may make sense for you to pull the changes over to private master for staging given the scope of change. You can do that by running this command in your local private master branch:

`git pull https://github.com/naziml/azure-content.git patch-3`

Then add, commit, and push as usual.

**Pull request merged**
