### PR TITLE
Update service-fabric-get-started.md

### PR DESCRIPTION
**Pull request by MikkelHegn**
Changes link text to clarify Update 2 for VS2015 is a minimum requirement for the download.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MikkelHegn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mikhegn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@MikkelHegn : Thanks for your contribution to the Azure documentation! The author, @rwike77, has been notified to review your proposed change.

**Comment by rwike77** [comment]
Thanks @MikkelHegn, your change looks fine.

**Comment by rwike77** [comment]
#sign-off

**Pull request merged**
