### PR TITLE
Fix broken template link

### PR DESCRIPTION
**Pull request by dtzar**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dtzar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (davete). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@dtzar Thank you for this contribution.  I'll have the author review.

@squillace Would you please review this change and let me know if I should merge it?

**Comment by dtzar** [comment]
It's a simple broken-link fix, so not sure why you need to spend any cycles on this..

**Comment by squillace** [comment]
@dtzar Hi David, it took three days because I just got back from vacation; just bad timing in this case. :-) and :-(. That said, I've fixed this in the meanwhile by removing it in order to update the sample code: https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-deploy-rmtemplates-azure-cli.md. (This is why the PR has a merge conflict now.)

What I'm doing today is to redo and update all of that section so that we have absolutely equal sample code and template link. I'll drop the link to the PR in here for your reaction. Cheers....

**Comment by tysonn** [comment]
Closing this PR...based on the comment from @squillace, it sounds like the fix has already been introduced in the article. Please advise if I've misunderstood.

**Pull request closed without merging**
