### PR TITLE
Update Azure SQL Database resource limits

### PR DESCRIPTION
**Pull request by yiruxue**
Added two item limits "database per server" and "DTUs per server" to the existing "Other SQL Database limits" table.

- Databases per server: up to 5000

- DTUs per server: 45000

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yiruxue__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@yiruxue__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@yiruxue 
Thank you for your contribution. The change has been applied to content.

**Pull request closed without merging**
