### PR TITLE
Update hdinsight-documentation-backlog.md

### PR DESCRIPTION
**Pull request by confusionblinds**
I have added two development requests 1. Hive -  HCatalog Streaming API , Storm - Streaming API

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@confusionblinds__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@confusionblinds 
Thanks for this contribution. I'm sending this to the author to verify.
--Carolyn

**Comment by cjgronlund** [comment]
@nitinme 
Hi, Nitin, Please check this contribution, and let me know whether I should accept the PR.

**Comment by nitinme** [comment]
@confusionblinds.

Thanks for your inputs. As I understand, these are requests for APIs to be added for the service and I'll forward these to our product team. In this article, we are tracking the articles that you would like us to focus on as part of our help set.

**Comment by confusionblinds** [comment]
Hi Nitin, 
I agree with your comments for HCatalog Streaming API part of hive.

Storm version 0.10.0 which is part of HDInsight (3.3) now provides the ability to use this streaming API.
But SCP.Net SDK doesn't provide any bolt template /  documentation to make this feature available from .NET SDK .  I suggest we have some update on Streaming API usage from within SCP.Net SDK.

**Comment by cjgronlund** [comment]
@nitinme @confusionblinds 
I'll close this PR, and the changes to the article can be through another PR. You'll still have access to this content if you want it.

**Pull request closed without merging**
