### PR TITLE
Corrected Syntax For Android Register With Tags

### PR DESCRIPTION
**Pull request by cogree**
Each tag should be a separate parameter since they are varargs in the library. Also, ``,`` is an invalid tag character.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cogree__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@cogree : Thanks for your contribution to the Azure documentation! The author, @wesmc7777, has been notified to review your proposed change.

**Comment by wesmc7777** [comment]
You are correct. Thank you

**Comment by wesmc7777** [comment]
#sign-off

**Comment by Saisang** [comment]
@tysonn please merge this PR

**Pull request merged**
