### PR TITLE
Update expressroute-howto-circuit-arm.md

### PR DESCRIPTION
**Pull request by kogesaka**
Variable is wrong.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kogesaka__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Could you review the suggested change?

**Comment by kogesaka** [comment]
Sure, I can help you.

**Comment by cherylmc** [comment]
I will verify with the PM that owns this and ping back.

**Comment by cherylmc** [comment]
Reviewed and verified with the PM. I like to verify with him so that he's aware of the issues. All good here. Thanks so much, kogesaka, for bringing this to our attention. @tysonn, we've verified the info and are good with accepting the proposed changes. Thanks!

**Comment by tysonn** [comment]
@kogesaka - Thanks, merging!

**Pull request merged**
