### PR TITLE
Added logstash plugin

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SergeyKanzhelev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sergkanz). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SergeyKanzhelev : Thanks for your contribution to the Azure documentation! The author, @OlegAnaniev-MSFT, has been notified to review your proposed change.

**Comment by Erikre** [comment]
Requested Oleg review.

**Comment by OlegAnaniev-MSFT** [comment]
#sign-off

**Pull request merged**
