### PR TITLE
Update guidance-compute-single-vm-windows.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typos and removing unnecessary commas.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@alexandair - The comma usage in the original texts is actually correct. If you could revert the comma changes in the submission, the rest of the changes would be mergeable.

**Comment by alexandair** [comment]
@tysonn I think I've reverted all comma changes.

**Pull request merged**
