### PR TITLE
Update expressroute-faqs.md

### PR DESCRIPTION
**Pull request by ApekshaKunte**
Correct values for Number of Vnet links with Expressroute Premium 
50mbps-20
100mbps-25
200mbps-25

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ApekshaKunte__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ApekshaKunte : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by cherylmc** [comment]
hi @ApekshaKunte - We've had 4 requests in an hour for this change. I think everyone was at the same meeting or on the same thread. Thanks for letting me know, though. Better to have lots of notifications than to have none at all. I'm going to go ahead and close this. Thanks again! #please-close

**Comment by cherylmc** [comment]
#please-close

**Pull request closed without merging**
