### PR TITLE
Add a new article to create FreeBSD VM in Azure

### PR DESCRIPTION
**Pull request by KylieLiang**
This article is a HOW-TO create and upload a VHD which contains FreeBSD image to Azure. 
Written by Microsoft OSTC (open source technology center) Kylie Liang (kyliel@microsoft.com).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@KylieLiang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
No CLA needed, contributor is an employee.

**Comment by tysonn** [comment]
Reviewed - I sent you a list of a few things to fix; once those items are sorted, I can accept the pull request.

**Comment by tysonn** [comment]
Great, thanks for making the updates. This article should be available live around 11 AM on Wednesday (Pacific Time)

**Pull request merged**
