### PR TITLE
moving text to description field

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @tfitzmac, has been notified to review your proposed change.

**Comment by tfitzmac** [comment]
@4c74356b41 - thanks for making this change. We have to make sure the table isn't too wide, but I think 3 columns should be fine.

**Comment by tfitzmac** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@tfitzmac - Hi Tom, if you decide later not to go with 3 columns, another option would be to rename the second column "Value and description". Thanks, Katie

**Pull request merged**
