### PR TITLE
Release notes for Web SDK 2.0.0-beta4

### PR DESCRIPTION
**Pull request by abaranch**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@abaranch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (abaranch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by AlexBulankou** [comment]
Can you please merge the following PR: #5350 instead of this one.

**Comment by alancameronwills** [comment]
Anastasia, could you please close this PR. Thanks.

**Comment by AlexBulankou** [comment]
Anastasia is back next week and I don't have permissions.
Thanks!
Alex

On January 19, 2016 3:13:28 PM Alan Cameron Wills <notifications@github.com> wrote:

Anastasia, could you please close this PR. Thanks.

-

**Comment by ggailey777** [comment]
Closed per request

**Pull request closed without merging**
