### PR TITLE
Update stream-analytics-introduction.md

### PR DESCRIPTION
**Pull request by Luke2000**
Typo correction. This sentence has an unnecessary "to": "In addition, in-browser query testing against a sample data file to enables quick, iterative development."

Do you care about correcting such small things? I'm going through this documentation and was wondering whether I should tell you about them..

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Luke2000__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@jeffstokes72 
Please review and approve/disapprove with a comment here. Thanks.

**Comment by jeffstokes72** [comment]
#sign-off

**Comment by jeffstokes72** [comment]
@Luke2000 thanks for pointing this out. I appreciate it.

**Comment by jeffstokes72** [comment]
@rmca14 approved. Looks solid.

**Pull request merged**
