### PR TITLE
Update sql-database-cloud-migrate.md

### PR DESCRIPTION
**Pull request by joseidz**
Minor editing changes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@joseidz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (joseidz). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@joseidz 
Please correct typo in the first sentence so it's correct: "engineer"

thanks

**Comment by rmca14** [comment]
Please resolve the merge conflicts. For guidance, see http://sharepoint/sites/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx

Thanks.

**Comment by MonicaRush** [comment]
@joseidz 
Hi, Jose -- How would you like to handle this? You can resolve the conflict or close this PR and copy your article into a fresh local branch and then submit another PR. I'll wait to hear from you. Thanks -- Monica

**Comment by rmca14** [comment]
Closed due to inactivity.

**Pull request closed without merging**
