### PR TITLE
Update sql-database-develop-java-simple-windows.md

### PR DESCRIPTION
**Pull request by janety**
Remove brackets around password placeholder text for consistency with other placeholders

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@janety__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (janety). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@janety__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (janety). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
Janet, can you please edit your profile per these parameters so we know you're a Microsoft employee (so we don't have to repeatedly look you up in the GAL, and for other reasons, too)?
https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile
Thanks

**Comment by janety** [comment]
Sure thing- didn’t realize there was a convention.  I’ve just made the updates.

Thanks
Janet

**Pull request merged**
