### PR TITLE
Update virtual-machines-windows-client-images.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @iainfoulds, has been notified to review your proposed change.

**Comment by iainfoulds** [comment]
Thanks for the suggestions. They look fine, but the doc was just updated yesterday so Github is reporting a merge conflict. 

You can pull from upstream again, merge the two versions and commit. This will update the PR and resolve the conflict. 

Or you can close this out and create a new PR from the existing, updated doc. That might be easier since you only had a couple of minor updates.

**Comment by iainfoulds** [comment]
Hi alexandair. Please do let me know what you'd like to do with this PR regarding the merge conflict. It may easier just to close out this PR and create a fresh with the small number of changes that you had proposed.

**Comment by alexandair** [comment]
@iainfoulds I'll close it and open a new one. Give me a minute.

**Comment by alexandair** [comment]
Leave a comment

**Pull request closed without merging**
