### PR TITLE
Link correction

### PR DESCRIPTION
**Pull request by TheBeardedLlama**
Update the link to the SDK download to the actual doc where the download links live

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheBeardedLlama__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@TheBeardedLlama - can you merge the patch I submitted to your fork?

**Comment by TheBeardedLlama** [comment]
apologies! 

I did not check for link format :(

**Comment by tysonn** [comment]
Not your problem! Thanks for calling it out and fixing.

**Comment by TheBeardedLlama** [comment]
...and sorry for not forgetting to do a squash... I take it you would have preferred that?

**Comment by tysonn** [comment]
We aren't sufficiently git-sophisticated to do that as a general practice yet  :)

**Pull request merged**
