### PR TITLE
Add missing semicolons to C# statements.

### PR DESCRIPTION
**Pull request by thomas11**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thomas11__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@thomas11 
Thank you for your contribution. I'll verify with the author and get right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@HeidiSteen 
Please check this PR and let me know whether to accept it. Thanks!

**Comment by cjgronlund** [comment]
@HeidiSteen 
Ping. Check this one out, please. (That's what you get for getting to the other one...) :>)

**Comment by HeidiSteen** [comment]
#sign-off  Bruce accepted the change.  Thanks!

**Comment by cjgronlund** [comment]
@thomas11 
Good suggestion! Thanks for your contribution.
--Carolyn

**Pull request merged**
