### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @olivierbloch, has been notified to review your proposed change.

**Comment by olivierbloch** [comment]
Hi @4c74356b41, thanks for this contribution! 
@PRmerger , this one is ready to merge as-is
thanks

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by cynthn** [comment]
@olivierbloch you have to comment with "#sign-off" in order to get the change merged. There is a merge conflict now, that also needs to be fixed. When you are ready and do #sign-off, it has to be the first thing in the comment or it doesn't get seen by automation :)

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by dominicbetts** [comment]
#please-close
@4c74356b41 @olivierbloch it looks like these changes have already been. Thanks!

**Pull request closed without merging**
