### PR TITLE
Adding clarification, that Premium pricing tier is also an option for…

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**
… the relay namespace

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@sethmanheim - Could you please review this public repo pull request.

@AlekseiPolkovnikov - Thanks for the contribution!

**Comment by sethmanheim** [comment]
@AlekseiPolkovnikov Aleksei, thank you for your contribution. The intent of this section is not to describe the various messaging tiers available; it's a step by step how-to for setting up Service Bus relays. As such, I think mentioning the Premium option adds unnecessary details to the step in question as it's not relevant to the intent of the article (and the steps work as-is).

**Comment by sethmanheim** [comment]
@tysonn OK to close without merging.

**Pull request closed without merging**
