### PR TITLE
Minor fixes, adding considerations about NVA chain

### PR DESCRIPTION
**Pull request by pateixei**
pateixei - CSA

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pateixei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@pateixei : Thanks for your contribution to the Azure documentation! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by telmosampaio** [comment]
#sign-off

**Comment by tysonn** [comment]
@telmosampaio - Please resolve the merge conflict so the changes can be merged. See [Resolve a merge conflict](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx) on the internal wiki.

**Comment by telmosampaio** [comment]
Please close thus OR. I made the changes in https://github.com/Azure/azure-content-pr/pull/26902

**Pull request closed without merging**
