### PR TITLE
Minor correction

### PR DESCRIPTION
**Pull request by jiimaho**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jiimaho__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jiimaho : Thanks for your contribution to the Azure documentation! The author, @sethmanheim, has been notified to review your proposed change.

**Comment by sethmanheim** [comment]
Hi @jiimaho, thanks for catching this typo! We'll get it fixed right away. Again, many thanks for taking the time. #sign-off

**Comment by v-anpasi** [comment]
@tysonn Please merge this PR.

**Pull request merged**
