### PR TITLE
Edit hdinsight-hadoop-linux-information.md

### PR DESCRIPTION
**Pull request by ShawnJackson**
Edit complete.

The "Storage REST API" link goes to the "Blob Service REST API" page on the Azure site. Please confirm that this is the right URL.

Per naming guidelines, I changed most instances of "storage account" to "Storage account." Please confirm that this change is accurate at every mention and shouldn't be "Blob storage account" instead. (In cases of "Blob storage account" in other articles, I haven't been capitalizing "storage" because "Blob storage" is a separate term). 

Please confirm that the heading "HDFS, Azure Blob storage, and storage best practices" wouldn't be better as "Best practices for HDFS and Azure Blob storage."

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ShawnJackson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (v-shawja). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Blackmist** [comment]
This looks good, merge.

**Comment by rmca14** [comment]
Appears to be a merge conflict. Please resolve, thanks.

**Comment by rmca14** [comment]
I will resolve this merge conflict.

**Comment by Blackmist** [comment]
Thanks Ross.

**Comment by rmca14** [comment]
Couldn't repro/induce merge conflict by checking out this article and running "git pull upstream master", so I created another branch, implemented the edits into the content, got the edits approved, and submitted a new pull request.

**Pull request closed without merging**
