### PR TITLE
Update app-insights-ip-addresses.md

### PR DESCRIPTION
**Pull request by vkonev**
We added 4 extra GSM agents. Updating list of IP addresses to include new agents

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vkonev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@vkonev : Thanks for your contribution to the Azure documentation! The author, @alancameronwills, has been notified to review your proposed change.

**Comment by alancameronwills** [comment]
This update has already been published.
#please-close

**Comment by alancameronwills** [comment]
@vkonev please close this PR, as the new content is already published.

**Pull request closed without merging**
