### PR TITLE
Fixed styles in note and list

### PR DESCRIPTION
**Pull request by Noradrex**
There where extra characters in one of the lists and extra characters in one of the note that made the styles render wrong.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Noradrex__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Noradrex : Thanks for your contribution to the Azure documentation! The author, @markusvi, has been notified to review your proposed change.

**Comment by MarkusVi** [comment]
Hi @Noradrex, 

thanks for your help. This is highly appreciated.

Cheers,
Markus

**Comment by MarkusVi** [comment]
@curtand: Merge as-is

**Pull request merged**
