### PR TITLE
Reviewed content and updated date

### PR DESCRIPTION
**Pull request by charislove**
#sign-off

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@charislove__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@charislove : Thanks for your contribution to the Azure documentation! The author, @hning86, has been notified to review your proposed change.

**Comment by hning86** [comment]
good

**Comment by garyericson** [comment]
@tysonn This is ready to merge. @charislove - You can submit changes to the private azure-content-pr repo rather than the public azure-content repo, and then you can sign them off without needing further approval. It's explained in the instructions in my weekly freshness reminder email, but let me know if you have any questions.

**Comment by tysonn** [comment]
@garyericson - This PR has a merge conflict - can you resolve please to unblock this for merging?

**Comment by garyericson** [comment]
@tysonn @charislove - Let's just close this pull request.

I couldn't figure out how to find and resolve a merge conflict in someone else's branch of the public repo. The only change here was updating ms.date, so I made that change in the azure-content-pr repo and submitted a separate pull request for it.

**Pull request closed without merging**
