### PR TITLE
Remove Get-AzureRmSqlElasticPoolDatabaseActivity powershell command.

### PR DESCRIPTION
**Pull request by jierong**
there is no command named Get-AzureRmSqlElasticPoolDatabaseActivity in PS, so suggest the remove the content.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jierong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jierong). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@sidneyh 
Please check this change, and let me know whether to accept the PR.
Thanks!

**Comment by jierong** [comment]
I think we can use Get-AzureRmSqlDatabaseActivity to replace Get-AzureRmSqlElasticPoolDatabaseActivity

**Comment by tysonn** [comment]
@sidneyh - Can you please review this contribution?

**Comment by sidneyh** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@sidneyh 
This PR appears to be a dupe of https://github.com/Azure/azure-content/pull/6050. Please tell me specifically what you'd like me to do this this PR (6051). Close? Thanks!

**Comment by sidneyh** [comment]
Hi, you can close it then. Thanks!

**Comment by cjgronlund** [comment]
Duplicate of https://github.com/Azure/azure-content/pull/6050. Closing.

**Pull request closed without merging**
