### PR TITLE
Added How to create a map

### PR DESCRIPTION
**Pull request by Gordonby**
To simply explain how to create a map file.

### CODE REVIEW

**Comment by Gordonby** [comment]
Leave a comment

**Comment by azurecla** [comment]
Hi __@Gordonby__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gobyers). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Gordonby** [comment]
Yes, I'm an FTE.

**Comment by azurecla** [comment]
Hi __@Gordonby__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gobyers). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Gordonby : Thanks for your contribution to the Azure documentation! The author, @msftman, has been notified to review your proposed change.

**Comment by Erikre** [comment]
This looks okay to me. @msftman is OOF. @MandiOhlinger - Let us know if there are any issues you see. Adding @ggailey777 to overlook this PR.

**Comment by MandiOhlinger** [comment]
@Gordonby Thank you for the addition. Looks good. #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
