### PR TITLE
Pull Request - Updated CRM Online Connector documentation

### PR DESCRIPTION
**Pull request by vaneyckensteven**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vaneyckensteven__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@vaneyckensteven__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@vaneyckensteven : Thanks for your contribution to the Azure documentation! The author, @msftman, has been notified to review your proposed change.

**Comment by MSFTMan** [comment]
@azurecla Thank you for taking the time to submit this PR to help improve the docs for CRM. We are currently in the middle of overhauling all the connector docs as the connectors become generally available. We hope you find the changes helpful when they go live in about a week or two. If after those updates you still find that changes are needed, please resubmit your PR and we will take a look.

Thanks,
Deon

**Comment by MSFTMan** [comment]
@vaneyckensteven Thanks again for your contributions to this article. As I mentioned before, we were making some major changes to these docs for the Logic apps GA. Now that these updates are completed, please take a look at the current document and see if you would still like us to make your changes. If you do, please submit a new PR with you changes and I'll look at it promptly.

#hold-off

Thank you,
Deon

**Comment by MSFTMan** [comment]
#please-close

**Pull request closed without merging**
