### PR TITLE
Fix def function examples

### PR DESCRIPTION
**Pull request by pilor**
Def function examples were incorrectly using the examples from the div function

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pilor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (cheggert). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@pilor : Thanks for your contribution to the Azure documentation! The author, @bandersmsft, has been notified to review your proposed change.

**Comment by bandersmsft** [comment]
@jim-parker This is good to merge.
@pilor Thanks, Chris!

**Comment by Jim-Parker** [comment]
This should be merged as part of the regular process

**Comment by Jim-Parker** [comment]
@bandersmsft Bill, I think you need to add the "#" "sign-off" to these public PRs now.

**Comment by bandersmsft** [comment]
#sign-off

**Pull request merged**
