### PR TITLE
Add P11 Service Teirs

### PR DESCRIPTION
**Pull request by yamatoya**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yamatoya__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@stevestein 
Please review and approve/disapprove with a comment here, thanks.

**Comment by rmca14** [comment]
@stevestein 
Following up, thanks.

**Comment by stevestein** [comment]
@rmca14 @yamatoya 
These are great suggestions. These articles have both been part of a recent refresh and the relevant service tier information has been updated.

Thank you

**Pull request closed without merging**
