### PR TITLE
Update virtual-machines-windows-tag.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @mmccrory, has been notified to review your proposed change.

**Comment by alexandair** [comment]
@tysonn Could someone merge this one?

**Comment by mmccrory** [comment]
These changes look good. Thanks!

**Comment by alexandair** [comment]
@tysonn Do you know who can merge this one?

**Comment by tysonn** [comment]
@mmccrory - See the [comment automation article](https://github.com/Azure/azure-content/blob/master/contributor-guide/contributor-guide-pull-request-comments.md) in the contributor's guide for info on how to sign off on changes :)

**Comment by tysonn** [comment]
@alexandair - Merging, thanks!

**Pull request merged**
