### PR TITLE
Mark the swagger as json to make it readable

### PR DESCRIPTION
**Pull request by stuartleeks**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stuartleeks__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (stuartle). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@stuartleeks : Thanks for your contribution to the Azure documentation! The author, @steved0x, has been notified to review your proposed change.

**Comment by steved0x** [comment]
@stuartleeks Thank you! I am merging this contribution.

**Comment by steved0x** [comment]
#sign-off

**Comment by steved0x** [comment]
#sign-off

**Comment by steved0x** [comment]
#sign-off

**Comment by ktoliver** [comment]
@stuartleeks - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad). Thanks for your understanding.

**Comment by steved0x** [comment]
@stuartleeks I actually fixed the formatting of the swagger today on the new repo when I was fixing another issue, but I forgot about this PR and i didn't mark.it as swagger code. I can make the change, but i would like for you to be credited as a contributor. Please review the change at some time after today and if you want to make a new PR i will make sure to pick.it up right away. Otherwise i cam make the change.

Thanks again for your contribution!

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
