### PR TITLE
Update virtual-machines-windows-troubleshoot-deployment-new-vm.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @jiangchen79, has been notified to review your proposed change.

**Comment by JiangChen79** [comment]
I am OK with the change.

**Comment by JiangChen79** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
@JiangChen79 - Your sign off did not work with the comment automation because your GitHub account is listed incorrectly in the article metadata: `authors="jiangchen79"`

It needs to match your GitHub account EXACTLY, including capitalization. Please fix your GitHub account in all your articles after this is merged.

**Pull request merged**
