### PR TITLE
Fix indent of directory structure block.

### PR DESCRIPTION
**Pull request by minghan**
Fix indent of directory structure block.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@minghan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@minghan : Thanks for your contribution to the Azure documentation! The author, @bmscholl, has been notified to review your proposed change.

**Comment by bmscholl** [comment]
@minghan: Thanks for catching this. We really appreciate your contribution.
@tysonn: We can merge the PR.

**Comment by azurecla** [comment]
Hi __@minghan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Pull request merged**
