### PR TITLE
Two o's, not three in 'Tools'

### PR DESCRIPTION
**Pull request by edsfocci**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@edsfocci__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@edsfocci : Thanks for your contribution to the Azure documentation! The author, @stevestein, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@edsfocci Yikes! Too many ooo's! Thank you for the catch!

**Comment by JennieHubbard** [comment]
@sign-off
@cjgronlund – This PR can be merged
@stevestein

**Pull request merged**
