### PR TITLE
Update azure-stack-connect-azure-stack.md

### PR DESCRIPTION
**Pull request by hvredevoort**
I suppose you meant logging in using AzureStack\AzureStackAdmin for the service administrator

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hvredevoort__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@hvredevoort__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Byronr** [comment]
Thanks for your feedback! The information is correct in the document. The log in for the client VM is to be AzureStackUser, but the identity you use to log into the portal once on the client VM is the service administrator.

**Comment by tysonn** [comment]
Per author feedback, closing PR.

**Pull request closed without merging**
