### PR TITLE
virtual-networks-arm-asm-s2s.md

### PR DESCRIPTION
**Pull request by kraghu306**
In classicvnets.netcfg when we add ARM VNet name and the IP range. It should be mentioned as vnet02 and IP should be 10.2.0.0/16 but the documentation was mentioned wrong.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kraghu306__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@telmosampaio 
Telmo, I unintentionally merged this PR -- I thought you'd better take a look and make sure the edit is okay. Thanks.

**Comment by rmca14** [comment]
Telmo approved the edit.

**Comment by kraghu306** [comment]
Thanks @telmosampaio and @rmca14 :)

**Pull request merged**
