### PR TITLE
altered US Gov instructions to use default enviornment

### PR DESCRIPTION
**Pull request by shawnweisfeld**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@shawnweisfeld__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@robinsh - Robin, could you review these proposed updates in the public repo from @shawnweisfeld?

**Comment by robinsh** [comment]
#sign-off This looks fine to me. Thanks very much to @shawnweisfeld for contributing!

**Comment by tysonn** [comment]
Sorry that took so long!

**Comment by robinsh** [comment]
No worries. If it was critical, I would have let you know.

**Pull request merged**
