### PR TITLE
Small Typo

### PR DESCRIPTION
**Pull request by CharbelNemnom**
Small Typo

Set-AzureRmSiteRecoveryVaultSettings -ASRVault

Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@CharbelNemnom__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@CharbelNemnom : Thanks for your contribution to the Azure documentation! The author, @bsiva, has been notified to review your proposed change.

**Comment by bsiva** [comment]
@CharbelNemnom : Thanks for the suggestion, but this is in fact not a typo. We have two different parameters to set the vault context depending on how the vault was created. A recovery services vault (which is the combined backup + site recovery vault) that is either created via the new Azure portal or via PowerShell using the New-AzureRmRecoveryServicesVault cmdlet will take the parameter -ARSVault as is shown in this example. A Site Recovery vault which was created using the Classic portal will take the paramenter -ASRVault. Thanks for pointing this out however. We've received feedback from others as well that this is confusing and are working on making the parameters more distinct or unifying them so as to avoid the confusion

**Comment by CharbelNemnom** [comment]
Thank You @bsiva
Yes updating the parameters will help since it's confusing.
BR,
-Charbel

**Comment by Jim-Parker** [comment]
@CharbelNemnom @bsiva - is it okay to close this pull request?

**Comment by CharbelNemnom** [comment]
Yes please. Thank You!

**Pull request closed without merging**
