### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
@Jim-Parker 
The first change doesn't make sense grammatically. It will need to be fixed before merging.

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, please add the "#sign-off" message to the comments. That process was implemented for public PRs while you were OOF.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by rayne-wiselman** [comment]
This isn’t my pull request and I wasn’t sure I should add since I received this message

[cid:image001.jpg@01D1FD1C.193C7840]

**Comment by rayne-wiselman** [comment]
#sign-off

**Comment by Saisang** [comment]
@tysonn please merge this PR.

**Pull request merged**
