### PR TITLE
Mistype in template

### PR DESCRIPTION
**Pull request by DovydasNavickas**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DovydasNavickas__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@davidmu1 - David, could you review this update from @DovydasNavickas?

**Comment by davidmu1** [comment]
@tysonn - This change is not technically correct. The correct structure in the template is:

"osProfile": {
                  "computername": "[variables('vmName')]",
                  "adminUsername": "[parameters('adminUsername')]",
                  "adminPassword": "[parameters('adminPassword')]",
                },

**Comment by DovydasNavickas** [comment]
Hmm... When I submitted the PR, VS Code showed an error there, because of JSON schema, I suppose.
Now, it does not show error there anymore.. If it's correct, then it's just inconsistent naming, which IMHO should be streamlined.

**Comment by davidmu1** [comment]
DovydasNavickas, I appreciate the feedback about the element naming structure in the template and I will pass it on to the engineering team. Not sure why VS Code was flagging it as an error, please reach out again if you are having deployment issues.

**Pull request closed without merging**
