### PR TITLE
Swapping steps for health probe creation

### PR DESCRIPTION
**Pull request by mikewo**
This was pointed out by Aidan Finn via email to a distribution list. The Health probe was being used before it was created.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mikewo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@mikewo : Thanks for your contribution to the Azure documentation! The author, @sdwheeler, has been notified to review your proposed change.

**Comment by squillace** [comment]
@iainfoulds would you make sure to ingest this as well? :-)

**Comment by sdwheeler** [comment]
@tysonn - approved

**Comment by sdwheeler** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@sdwheeler - Hi Sean, please fix the merge conflict. If you need guidance, please see the [wiki](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx
) for instructions on fixing it.
#hold-off

**Comment by sdwheeler** [comment]
@mikewo - There have been a few changes to this content since you submitted your PR. I cannot merge it as is. We can either close this PR and I make the changes you want or we can close this PR and then you can submit the change again from the current version. What would you like to do?

**Comment by mikewo** [comment]
@sdwheeler I'll close this one and make the changes against the most current version. I'll then resubmit.

**Comment by mikewo** [comment]
Created #7604

**Pull request closed without merging**
