### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by 4c74356b41**
fixed some typos

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@tracsman - Jon, please review this proposed update from @4c74356b41 in the public repo.

**Comment by 4c74356b41** [comment]
Hello?

**Comment by tracsman** [comment]
@4c74356b41 Thanks for the attention to detail!
@tysonn this looks ready to merge.
#sign-off

**Pull request merged**
