### PR TITLE
Adding content for P10 and P20 premium

### PR DESCRIPTION
**Pull request by kevinlam1**
Clarified some billing points around premium plans and added content for P20 premium plans.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kevinlam1__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (klam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by krisragh** [comment]
@kevinlam1 looks great. #sign-off

**Comment by PRmerger** [comment]
@kevinlam1 : Thanks for your contribution to the Azure documentation! The author, @krisragh, has been notified to review your proposed change.

**Comment by krisragh** [comment]
looks great. #sign-off

**Pull request merged**
