### PR TITLE
Update multi-factor-authentication-whats-next.md

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by billmath** [comment]
Changes good please merge.

**Comment by billmath** [comment]
#sign-off

**Comment by KatieCumming** [comment]
@billmath - Please fix the merge conflict. If you need guidance, please see the [wiki.](https://microsoft.sharepoint.com/teams/azurecontentguidance/wiki/Pages/Resolve%20a%20local%20merge%20conflict%20yourself.aspx) Thanks, Katie
 #hold-off

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by billmath** [comment]
#sign-off

**Comment by billmath** [comment]
I have already updated this in the private repo.  Please close.

**Pull request closed without merging**
