### PR TITLE
Message size difference

### PR DESCRIPTION
**Pull request by SeanFeldman**
Without stating what's the max size of the brokered message on the premium tier, highlight this important different as it could be an important factor when choosing between standard and premium tier.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by SeanFeldman** [comment]
I'd also flip between the columns in the table. First show the standard, then the premium.

**Comment by tysonn** [comment]
@sethmanheim - Seth, could you review the update and suggestions in the comments from @SeanFeldman in the public repo?

**Comment by sethmanheim** [comment]
@tysonn OK to merge, @SeanFeldman thanks for the contribution!

**Pull request merged**
