### PR TITLE
Update notification-hubs-windows-store-dotnet-send-breaking-news.md

### PR DESCRIPTION
**Pull request by sethgr**
Minor edit.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sethgr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by sethgr** [comment]
(We're just making a minor change to better understand how the system works.)

**Comment by azurecla** [comment]
Hi __@sethgr__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by wesmc7777** [comment]
Ok, after reviewing your changes. I recommended accepting the PR to help you understand.  Looks like all that was changed was "etc." to "and so on"

**Pull request merged**
