### PR TITLE
Update cortana-analytics-technical-guide-demand-forecast.md with typo fixes and link to template

### PR DESCRIPTION
**Pull request by thdeltei**
@yijichen While deploying the solution, I found myself having to navigate back to Cortana intelligence suite, to the gallery, to find the solution template. I think it can be useful to have it on this page too, what do you think?

I was wondering also if it was worth mentioning the following:
- you need to be an admin of the subscription that you are using in order to be able to create the ML workspace during deployment (at least that's what support told me, and that might only be the case for the newest subscriptions)
- you need to have at least 10 free on demand nodes for HDInsight on your subscription

These 2 items led to failed deployments on my side.

Thanks

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thdeltei__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (thdeltei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@thdeltei : Thanks for your contribution to the Azure documentation! The author, @yijichen, has been notified to review your proposed change.

**Comment by yijichen** [comment]
@thdeltei Thanks a lot for finding the errors in the document!! Really appreciate.
@PRmerger this document is ready to merge. 

#sign-off

**Comment by PRmerger** [comment]
@thdeltei : Thanks for your contribution to the Azure documentation! The author, @yijichen, has been notified to review your proposed change.

**Pull request merged**
