### PR TITLE
New article - Create a Hello World App for Azure in Intellij

### PR DESCRIPTION
**Pull request by selvasingh**
@rmcmurray - this is the first draft, please review and take it from there. You may have to adjust one or two images - because my account is loading too many subscriptions.

@rmcmurray - suggest that you draft two more articles to cover Azure Toolkit for IntelliJ and Installing the Azure Toolkit for IntelliJ

@martinsawicki - FYI

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@selvasingh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (asirveda). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@selvasingh - This work needs to be handled through the private repository so the new article can be staged and validated prior to publication. See [the contributor's guide](https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github) if you need perms to the private repo.

**Comment by rmcmurray** [comment]
@selvasingh - I will take care of recreating this in the private branch.

**Comment by tysonn** [comment]
Closing per @rmcmurray

**Pull request closed without merging**
