### PR TITLE
Update active-directory-v2-flows.md

### PR DESCRIPTION
**Pull request by thomasclaudiushuber**
Just fixed a little typo. Should be «by sending» instead of «my sending»:

«Once registered, the app communicates with Azure AD my sending requests to the Azure…»

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thomasclaudiushuber__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@thomasclaudiushuber : Thanks for your contribution to the Azure documentation! The author, @dstrockis, has been notified to review your proposed change.

**Comment by BryanLa** [comment]
@dstrockis - this one is a small typo correction - drop a sign-off whenever you have a minute and we will get it merged for you.

**Comment by dstrockis** [comment]
#sign-off

**Pull request merged**
