### PR TITLE
Removed extra "[AZURE.NOTE]" text

### PR DESCRIPTION
**Pull request by gbellmann**
The text [AZURE.NOTE] was being shown int the doc page. Removed it so it looks as the new doc version.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gbellmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
The syntax was incorrect, but the content is intended as a Note in our style. The correct syntax includes a space after the angle bracket, so it should be > [AZURE.NOTE]

Please feel free to edit your pull request and we will merge it. Thanks for your contribution.

**Comment by gbellmann** [comment]
Hi @rmca14. I first thought of fixing the missing space after the angle bracket, as you noted, but when I checked the new version of the document (https://github.com/Azure/azure-content/blob/master/articles/hdinsight/hdinsight-provision-clusters.md) it has all the text as one [AZURE.NOTE] block, and not two as this document has. That's why I went the deletion way.

**Comment by rmca14** [comment]
@mumian 
Please review this PR and indicate here as a comment what the content should be. Thanks.

**Comment by mumian** [comment]
The edit looks good to me.  Thanks.

**Pull request merged**
