### PR TITLE
updated references to msysgit and GitHub for Windows

### PR DESCRIPTION
**Pull request by shiftkey**
These projects have been renamed in recent times, so the locations and
details are slightly different but the instructions remain largely the
same.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@shiftkey__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Thanks for this contribution - sending to the author for review.

**Comment by tysonn** [comment]
Resent request for review to @szarkos

**Comment by szarkos** [comment]
Sorry for the delay (traveling).  This looks good to me, thanks for updating those links!

**Pull request merged**
