### PR TITLE
Update azure-stack-deploy-template-powershell.md

### PR DESCRIPTION
**Pull request by hvredevoort**
Template does not deploy because of trailing space on line 92

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hvredevoort__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@ErikjeMS Erik, this looks like a good catch by Hans. Can you take a look and let me know if it can be merged? Thanks

**Comment by ErikjeMS** [comment]
Yep, that can be merged!

**Comment by ErikjeMS** [comment]
Thanks for finding that error, Hans!
#sign-off

**Pull request merged**
