### PR TITLE
Update virtual-machine-scale-sets-deploy-app.md

### PR DESCRIPTION
**Pull request by jboeshart**
Added link to the Azure document that provides further information on the process to roll out an OS upgrade across a VMSS. I also removed the link to the vmssupgrade tool since it's mentioned on the linked doc and is a bit redundant. Can add it back in though if you want to keep it on this page.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaboes). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Ja-Dunn** [comment]
@jboeshart - Thanks for your contribution. We are in the process of refactoring the Azure technical articles, so we can’t merge this PR. When the refactoring is complete, we can give you a link to the new location of the article you updated so you can resubmit your update, if you want to.

**Comment by jboeshart** [comment]
@Ja-Dunn that works for me. Let me know the new URL when you have it, I'll also keep an eye out post-migration as well for the new doc and will resubmit.

**Comment by gbowerman** [comment]
#sign-off 
thanks @jboeshart

**Comment by ktoliver** [comment]
@jboeshart - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-deploy-app](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-deploy-app). Thanks for your understanding.

**Comment by jboeshart** [comment]
PR created in new repo. 

https://github.com/Microsoft/azure-docs/pull/69

**Pull request closed without merging**
