### PR TITLE
Fix link to ThreadPool.SetMinThreads

### PR DESCRIPTION
**Pull request by boades**
Fixed broken link to ThreadPool.SetMinThreads article on msdn.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@boades__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@boades : Thanks for your contribution to the Azure documentation! The author, @robinsh, has been notified to review your proposed change.

**Comment by robinsh** [comment]
Hello @boades ! Thanks for contributing to our documentation; this change looks good.

@tysonn Please merge this change, it's good to go.

**Comment by robinsh** [comment]
#sign-off

**Pull request merged**
