### PR TITLE
Included all fields from page view

### PR DESCRIPTION
**Pull request by ljbotero**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ljbotero__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@noamben and @alancameronwills  - Could you please review this community contribution from ljbotero and let me know if it can be merged?

**Comment by alancameronwills** [comment]
Looks like a good contribution. I'll need to test it.

**Comment by ggailey777** [comment]
I think we also need @ljbotero to sign the CLA.

**Comment by alancameronwills** [comment]
#sign-off

**Comment by tysonn** [comment]
Yes, sorry about that mistake - the CLA needs to be signed prior to review and merge. Closing it at this point.

**Pull request closed without merging**
