### PR TITLE
New Vault settings blade

### PR DESCRIPTION
**Pull request by chintavasisht**
New Vault settings blade layout has changed. Updated the image.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chintavasisht__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@chintavasisht : Thanks for your contribution to the Azure documentation! The author, @cherylmc, has been notified to review your proposed change.

**Comment by tysonn** [comment]
@rayne-wiselman - Could you please review this update in the public repo?

**Comment by rayne-wiselman** [comment]
@Jim-Parker 
#sign-off
Good to go

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
