### PR TITLE
Update screenshot for Azure Functions images to reflect design

### PR DESCRIPTION
**Pull request by justsayno**
I have updated a screen shot and added another to reflect the new design of the Azure Functions portal.

I could not fit the same things into one screenshot as it was before due to the layout changes so I added an extra one.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@justsayno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@justsayno__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by PRmerger** [comment]
@justsayno : Thanks for your contribution to the Azure documentation! The author, @ggailey777, has been notified to review your proposed change.

**Comment by ggailey777** [comment]
@justsayno thanks for taking the time to clarify the screenshots. #sign-off

**Pull request merged**
