### PR TITLE
Update load-balancer-internal-overview.md

### PR DESCRIPTION
**Pull request by pcgeek86**
Added information aobut the 168.63.129.16 IP address

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@pcgeek86 Thank you for the contribution!  I've forwarded the change onto the author for review.

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
There's a merge conflict on this pull request.  I've forwarded the change to the author to make in another pull request.  Thanks for the contribution!

**Comment by joaoma** [comment]
@deneha and @pcgeek86  I will disapprove the current request because the same info is already on how to for ILB. @pcgeek86 I really liked your wording on the doc and create a PR for the get started with ILB to change the azure important note there. I will approve the change and show you as contributor for the doc.

**Comment by pcgeek86** [comment]
@joaoma Thank you for that. Do you need me to do anything?

**Comment by joaoma** [comment]
Yes! just change the doc load-balancer-internal-getstarted.md with where you see a label [AZURE.IMPORTANT] and the info inside. Submit a new PR for that change to show you as contributor for the page. I will approve when is done.

**Comment by pcgeek86** [comment]
@joaoma Completed here: https://github.com/Azure/azure-content/pull/3781#issuecomment-115838328

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by joaoma** [comment]
Thank you Trevor! I will be reviewing shortly.


-------- Original message --------

**Comment by joaoma** [comment]
Hi Trevor,

I just approved the merge. Should be done by Tuesday. Thank you for collaborating to the article! Keep providing feedback!

Joao

**Comment by pcgeek86** [comment]
@joaoma Thanks! Glad to be of assistance -- appreciate your help getting this merged.

**Pull request closed without merging**
