### PR TITLE
Group Type is missing

### PR DESCRIPTION
**Pull request by janvars**
It took me about 3 hours to overcome this tiny thing... ;o) "Security" group type does not work...little bit illogical, isn't it?
Thanks, Jan

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@janvars__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@mahesh-unnikrishnan - Mahesh, please review this PR in the public repo from @janvars and let @BryanLa know if it can be merged. Thanks.

**Comment by mahesh-unnikrishnan** [comment]
@janvars  - could you please email us using the link (https://azure.microsoft.com/en-us/documentation/articles/active-directory-ds-contact-us). The 'security' group type should work and we'd like to investigate and see why this isn't working for your tenant.

Thanks!

**Comment by tysonn** [comment]
@mahesh-unnikrishnan - Should we close or merge the text update?

**Comment by mahesh-unnikrishnan** [comment]
Please close this PR.

**Pull request closed without merging**
