### PR TITLE
Add Clarification to Publisher of Django Web App

### PR DESCRIPTION
**Pull request by ianleaman**
There are a couple Django apps when searched in the web store. None of them published by Microsoft.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ianleaman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ianleaman : Thanks for your contribution to the Azure documentation! The author, @huguesv, has been notified to review your proposed change.

**Comment by rmcmurray** [comment]
Thanks, @ianleaman - this seems like a great suggestion, and just as an FYI - I am following up with the author of the article, but he's out of town at the moment.

**Comment by huguesv** [comment]
#signoff

**Comment by huguesv** [comment]
@rmcmurray  it's ok to merge

**Comment by cephalin** [comment]
@ggailey777 This is ready to merge. I'd tell @huguesv to use #sign-off but it doesn't seem to be working right now in another PR of mine.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by huguesv** [comment]
#sign-off

**Pull request merged**
