### PR TITLE
Update site-recovery-vmware-to-azure-classic.md

### PR DESCRIPTION
**Pull request by BernieWhite**
Minor grammatical correction in section "Source environment considerations" > "Maximum daily change rate".

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@BernieWhite__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, can you please review Bernie's contributions and sign off if everything is okay? Thanks

**Comment by azurecla** [comment]
__@BernieWhite__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, could review Bernie's contribution and let us know if it's okay to merge? Thanks.

**Comment by BernieWhite** [comment]
Also relates to issue Azure/azure-content#5124

**Comment by rayne-wiselman** [comment]
Fine to merge

**Comment by BernieWhite** [comment]
@Jim-Parker Thanks. All good to merge.

**Pull request merged**
