### PR TITLE
Correcting sample code in documentdb-modeling-data.md

### PR DESCRIPTION
**Pull request by rohankapoor**
Since countOfBooks is 1, correcting the 'books' array to reflect only book b1

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rohankapoor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rohankapoor : Thanks for your contribution to the Azure documentation! The author, @stephbaron, has been notified to review your proposed change.

**Comment by mimig1** [comment]
@stephbaron - Can you add the #sign-off tag to get this incorporated.

**Comment by stephbaron** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
