### PR TITLE
Added GatewaySku when using New-AzureRmVirtualNetworkGateway

### PR DESCRIPTION
**Pull request by SenthuranSivananthan**
Added GatewaySku as it's required to create a Policy Based virtual network gateway.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SenthuranSivananthan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cherylmc - Can you review this proposed change?

**Comment by cherylmc** [comment]
@yushwang: Please verify that this is technically accurate. Thanks!

**Comment by yushwang** [comment]
Cheryl and I looked at this just now - let's not merge it as it's from a long time back (Feb.) We will have a separate update to add GatewaySku parameter.

Thanks,
Yushun

**Comment by tysonn** [comment]
Closing per feedback from article owners.

**Pull request closed without merging**
