### PR TITLE
Corrected xml validation and flat file decode links

### PR DESCRIPTION
**Pull request by padmavc**
Corrected xml validation and flat file decode links

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@padmavc__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (padmavc). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by padmavc** [comment]
#sign-off

**Comment by PRmerger** [comment]
@padmavc : Thanks for your contribution to the Azure documentation! The author, @MSFTMAN, has been notified to review your proposed change.

**Comment by padmavc** [comment]
@msftman is on vacation, looping his manager Erik to review my proposed change.

Thanks
Padma

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by padmavc** [comment]
Erik,

Could you provide sign off as @msftman is on vacation.


Thanks
Padma

**Comment by Erikre** [comment]
Looks okay. @ggailey777 could you help publish this? Thanks

**Pull request merged**
