### PR TITLE
Update automation-hybrid-runbook-worker.md

### PR DESCRIPTION
**Pull request by bgelens**
There was a lot of false information about SMA. I adjusted for a more fair comparison.
I deleted the statement where it was implied that Azure Automation was preferred because it could manage both Azure and On-prem where SMA supposedly could not. This is false statement as SMA Runbook workers can interface with Azure just as easily.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bgelens__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@bgelens : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@bgelens - thank you for taking the time to review this article and provide recommended changes.  I have reviewed your proposed changes, and I identified a few things that needed to be corrected.  I am proposing you copy/paste my updates to your PR:

[Service Management Automation (SMA)](https://technet.microsoft.com/library/dn469260.aspx) allows you to run the same runbooks that are supported by Azure Automation in your local data center. SMA is generally deployed together with Windows Azure Pack, as Windows Azure Pack contains a graphical interface for SMA management. Unlike Azure Automation, SMA requires a local installation that includes web servers to host the API, a database to contain runbooks and SMA configuration, and Runbook Workers to execute runbook jobs. Azure Automation provides these services in the cloud and only requires you to maintain the Hybrid Runbook Workers in your local environment.

SMA requires a local installation of its underlying components that are connected to Windows Azure Pack if a graphical management interface is required. More local resources will be needed with higher maintenance costs than Azure Automation, which only needs an agent installed on local runbook workers. The agents are managed by Operations Management Suite, further decreasing your  maintenance costs.

Azure Automation stores its runbooks in the cloud and delivers them to on-premises Hybrid Runbook Workers. If your security policy does not allow this behavior, then you should use SMA.

SMA is included with System Center; and therefore, requires a System Center 2012 R2 license. Azure Automation is based on a tiered subscription model.

Azure Automation has advanced features such as graphical runbooks that are not available in SMA.

Once you make those edits, I'll re-review and if all's good, I'll approve it.

#hold-off

**Comment by bgelens** [comment]
@MGoedtel Done. Thanks!

**Comment by MGoedtel** [comment]
Thanks for making those changes.  I approve of this PR.  #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
