### PR TITLE
Update fundamentals-introduction-to-azure.md

### PR DESCRIPTION
**Pull request by andygarcia**
Confusing references to paper changed to article to match intro

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@andygarcia__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@andygarcia : Thanks for your contribution to the Azure documentation! The author, @rboucher, has been notified to review your proposed change.

**Comment by rboucher** [comment]
Agreed.  This article started off as a paper (PDF download) before being moved to an article.

**Comment by rboucher** [comment]
Thanks @andygarcia. Accepting your changes.

**Comment by rboucher** [comment]
#sign-off

**Pull request merged**
