### PR TITLE
correct typo in first Actions example (custom roles in RBAC)

### PR DESCRIPTION
**Pull request by jmutchek-msft**
minor change to correct Microsoft.Computer/ provider name to Microsoft.Compute/ in documentation/articles/role-based-access-control-custom-roles/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jmutchek-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jmutchek-msft : Thanks for your contribution to the Azure documentation! The author, @kgremban, has been notified to review your proposed change.

**Comment by kgremban** [comment]
@jmutchek-msft Thanks for catching this error!

**Comment by kgremban** [comment]
#sign-off

**Pull request merged**
