### PR TITLE
Update sql-database-elastic-pool-reference.md

### PR DESCRIPTION
**Pull request by jierong**
There is no PS command named Get-AzureRmSqlElasticPoolDatabaseActivity, so suggest to remove the content from the doc.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jierong__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jierong). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@sidneyh 
Please check this change and let me know whether I should accept the PR.
Thanks!

**Comment by sidneyh** [comment]
The link is broken (it points back to the same article.) But there is an actual cmdlet by that name: https://msdn.microsoft.com/en-us/library/azure/mt603812.aspx

So I agree that you should change the link, but not delete it.

**Comment by sidneyh** [comment]
oh wait, the link goes to a slightly different article. Well, the name should be changed to that topic with the good link.

**Comment by cjgronlund** [comment]
@sidneyh 
Thanks for your reply. I'm confused about what needs to happen here. 
Replace: ?
With: ?
Thanks!

**Comment by jierong** [comment]
I think we can use Get-AzureRmSqlDatabaseActivity to replace Get-AzureRmSqlElasticPoolDatabaseActivity

**Comment by sidneyh** [comment]
OK. If you want to kill this pull request, I can do it. Otherwise, here's the text to change:

Replace:
Get-AzureRmSqlElasticPoolDatabaseActivity
with 
Get-AzureRmSqlDatabaseActivity

Replace:
https://msdn.microsoft.com/library/mt163669.aspx
with:
https://msdn.microsoft.com/en-us/library/mt603687.aspx

**Comment by cjgronlund** [comment]
@jierong @sidneyh 
Thanks for the good information. As soon as the changes are made, I can accept this PR.

**Comment by tysonn** [comment]
@sidneyh You can pull the commits from @jierong to your local branch, make the updates needed, and them push them to your fork. To pull these changes to your local master branch, run:
```
git pull https://github.com/jierong/azure-content.git patch-1

```
You can run this from the private repo side and it will work.

**Comment by cjgronlund** [comment]
@sidneyh 
Please check the fix I made. Thanks!

**Pull request merged**
