### PR TITLE
Fixed mistake in data-factory-azure-documentdb-connector.md

### PR DESCRIPTION
**Pull request by efraimbart**
A 'from' and 'to' got switched in the first paragraph causing the article to repeat itself.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@efraimbart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@efraimbart - Thanks for the contribution.

@spelluru - Please review this update in the public repo. If you decide to merge, you should run this command from the private repo to merge the changes to your branch, then resolve the merge conflict:

git pull https://github.com/efraimbart/azure-content.git patch-1

Then add, commit, push, and create a PR. If you do that, we'll then close this PR.

**Comment by spelluru** [comment]
@efraimbart - thanks for the contribution. I have made the same change and sent the content for live today. You should see the change in a few minutes. 

@tysonn - please close this PR because I have made the change as part of a PR that has already been merged. Thanks.

**Comment by cjgronlund** [comment]
@efraimbart 
Thank you for this contribution. The changes have been made to the article.

**Pull request closed without merging**
