### PR TITLE
Update virtual-machines-common-extensions-features.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@tysonn New PR.

**Comment by tysonn** [comment]
@cynthn - Could you please review these updates from @alexandair and let me know if we can merge?

**Comment by cynthn** [comment]
@tysonn @alexandair the changes look fine but there are merge conflicts?

**Comment by tysonn** [comment]
@cynthn : Merge conflicts don't scare me!

**Comment by tysonn** [comment]
@alexandair - I will merge from the private side. Thanks for resubmitting the updates.

**Pull request closed without merging**
