### PR TITLE
Small change to correct order of options

### PR DESCRIPTION
**Pull request by cauldnz**
Changed the order of data distribution options so that they align with the later commentary on what those options mean. Chose to list Round Robin first. i.e. keep the ordering based on the ordering of the following commentary.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cauldnz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@JennieHubbard 
Please review and approve/disapprove here, thanks.

**Comment by rmca14** [comment]
@barbkess

**Comment by JennieHubbard** [comment]
#sign-off

**Pull request merged**
