### PR TITLE
Limit of 5 readers per partition

### PR DESCRIPTION
**Pull request by ppatierno**
Regarding the consumer group, it's wrong to say " ... limit of 5 readers per consumer group ...". The limit of 5 readers is related to a single partition.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ppatierno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@jeffstokes72 
Please review this PR and note your approval/disapproval here. Thanks.

**Comment by jeffstokes72** [comment]
We are looking into this thank you!

**Comment by jeffstokes72** [comment]
This change is approved.

**Pull request merged**
