### PR TITLE
Provide a command-line copyable location for AzCopy

### PR DESCRIPTION
**Pull request by davkean**
Provide the direct location of AzCopy so that users can 
copy it and paste into a command-line window.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@davkean__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by davkean** [comment]
@rmca14 What's going on with this PR? It's been sitting for a week.

**Comment by tamram** [comment]
Looks good, thanks.

#sign-off

**Comment by tamram** [comment]
By the way, I've all been on vacation for Thanksgiving. That's why the PR hadn't been reviewed yet.

**Pull request merged**
