### PR TITLE
Update sql-data-warehouse-integrate-azure-data-factory.md

### PR DESCRIPTION
**Pull request by lodipalm**
Updating a link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lodipalm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@barbkess 
Please review and approve. Thanks.

**Comment by rmca14** [comment]
Hi, Jennie. Can you please review and let me know if I should merge this PR? Barb is apparently OOF. Thanks.

**Comment by JennieHubbard** [comment]
Approved!

**Pull request merged**
