### PR TITLE
Create sql-data-warehouse-get-started-load-samples.md

### PR DESCRIPTION
**Pull request by lodipalm**
Creating new file with loading samples.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lodipalm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@JennieHubbard 
Jennie, please review this PR and let me know if I should merge. Thanks.

**Comment by rmca14** [comment]
@barbkess 
FYI

**Comment by JennieHubbard** [comment]
Approved, but please remove the /en-us from the urls, or I can once the PR is accepted.

**Pull request merged**
