### PR TITLE
Update machine-learning-apps-anomaly-detection.md

### PR DESCRIPTION
**Pull request by alokkirpal**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alokkirpal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (alok). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by alokkirpal** [comment]
#sign-off

**Comment by PRmerger** [comment]
@alokkirpal : Thanks for your contribution to the Azure documentation! The author, @alokkirpal, has been notified to review your proposed change.

**Comment by tysonn** [comment]
Hi - I need to close this PR...please see [Article authors working in the public repo](https://microsoft.sharepoint.com/teams/azurecontentguidance/article-author-working-in-the-public-repo) for next steps.

**Pull request closed without merging**
