### PR TITLE
Update sql-database-business-continuity-design.md

### PR DESCRIPTION
**Pull request by anosov1960**
Fixed the design article link

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anosov1960__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@anosov1960 
Alexander, pleased edit the link to the proper syntax (and leave out the "en-us"), guidance here https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/create-links-markdown.md#markdown-syntax-for-acom-relative-links

(If I edit it, it'll create a pull request that you'd have to merge.)

Thanks.

**Comment by rmca14** [comment]
@jeffgoll 
Same situation here.
Jeff, he should be able to go to this version of the doc https://github.com/Azure/azure-content/pull/4885/files , click the little editing pen in the upper right margin, make the needed changes, and then click (I believe) the "Propose file change" button in the lower left.

Guidance for link syntax is https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/create-links-markdown.md

**Comment by rmca14** [comment]
He should also edit his GitHub username/profile to indicate he's a Microsoft employee.

**Comment by rmca14** [comment]
Just replaced link in my comment above to access this file to edit https://github.com/Azure/azure-content/pull/4835/files

**Comment by rmca14** [comment]
Sasha,you have the following link syntax (note the extra unneeded space in the link text):

[Designing Cloud Solutions for Disaster Recovery Using  Geo-Replication](https://azure.microsoft.com/documentation/articles/sql-database-designing-cloud-solutions-for-disaster-recovery)

That link syntax needs to be the following (with the extra unneeded space deleted):

[Designing Cloud Solutions for Disaster Recovery Using Geo-Replication](sql-database-designing-cloud-solutions-for-disaster-recovery.md)

Thanks.

**Pull request merged**
