### PR TITLE
Replace code images with powershell code blocks

### PR DESCRIPTION
**Pull request by bjtucker**
Replace png code images with code blocks using github's built-in PowerShell syntax highlighting.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bjtucker__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by bjtucker** [comment]
Nothin but love for you, robot, but with all due respect, I don't think you're right that a cla would be required here. I transcribed what was in the images. That's not my own code, it's exactly  what was in the pictures. :)

I see lots of similar edits tagged with no CLA required. Did the robot just get scared when it saw some curly braces, or do we actually need a CLA here?

**Comment by Jim-Parker** [comment]
@bjtucker Ben, first, thanks for the contribution. I can see your point, but in this case the requirement is based on scope of change, not the content of the change. We don’t have discretion on this. You'll need to sign the CLA for us to proceed. Thanks.

**Comment by bjtucker** [comment]
Closing this out, since I'm going on vacation and I'm not going to be able to address this ahead of that.
I can't possibly have copyright over a literal transcription of these images--i've done zero creative work here--so I don't think I'm doing harm by just trashing this pull request. If it's a good idea, someone else can just submit the same.

I'll get the CLA signed before I try again. Thanks!

**Pull request closed without merging**
