### PR TITLE
Update iot-hub-raspberry-pi-kit-node-get-started.md

### PR DESCRIPTION
**Pull request by yjianfeng**
Including info where to buy starter kit if user doesn't have a kit yet.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@yjianfeng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jeffya). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@yjianfeng : Thanks for your contribution to the Azure documentation! The author, @shizn, has been notified to review your proposed change.

**Comment by dominicbetts** [comment]
Hi, thanks for the update. Please correct the URL as follows:
https://azure.microsoft.com/develop/iot/starter-kits
Then we can accept the PR.
Thanks, Dominic

**Comment by shizn** [comment]
@yjianfeng Hi Jeff. The link in your PR need to be updated. Or you can close this PR and I will update this.

**Comment by dominicbetts** [comment]
@shizn @yjianfeng  - I've made the update directly. We have a publishing freeze starting later today in preparation for the migration to docs.microsoft.com.

**Comment by dominicbetts** [comment]
#please-close

**Pull request closed without merging**
