### PR TITLE
Update data-lake-store-offline-bulk-data-upload.md

### PR DESCRIPTION
**Pull request by sachincsheth**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sachincsheth__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@sachincsheth : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@sachincsheth - Thanks for the updates Sachin. You have two set of changes in your PR. In the first set you are swapping the first two paragraphs. I would like to keep that as is. Reason - The first para of the article should establish the intent of the article. The current para as-is talks about how offline copy to Azure Data Lake Store can be achieved. If I swap this with the second para, the intent is lost and it looks like the article is about Import/Export Service, which it is not.

Also, text from first para is featured in search engine results and so it is important to mention Azure Data Lake Store there.

For the second change, I agree with it.

So, if you could resubmit your PR with only the second change, that will be great.

**Comment by JennieHubbard** [comment]
@sachincsheth Hi Sachin. Were you able to submit the changes Nitin requested? We will need to close this PR next week if we do not hear from you. I really want to make sure we get your changes included and give you credit for them. :) All the best,
Jennie

**Comment by sachincsheth** [comment]
Will create another pulldown.

**Pull request closed without merging**
