### PR TITLE
Update virtual-machines-arm-log-on-windows-vm.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@cynthn Cynthia, can you take a look at Aleksandar's contribution and sign off when ready?

**Comment by cynthn** [comment]
#hold-off we aren't taking changes until we are done with the current rework of the VMs content. As soon as I can, I'll accept this and have it merged into the new file :)

**Comment by tysonn** [comment]
@cynthn & @squillace - VM pull request

**Pull request closed without merging**
