### PR TITLE
Include storage emulator concurrent merge issue

### PR DESCRIPTION
**Pull request by IlyaGrebnov**
Added information about storage emulator table service concurrent merge issue.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@IlyaGrebnov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tamram** [comment]
This is a bug that will be fixed soon in the storage emulator. We'd prefer not to publish bug information in this section, so we are declining this PR. Thank you for your submission, however, and your interest in improving our content.

**Comment by IlyaGrebnov** [comment]
Is it normal practice to hide unwanted content from ACOM?

PR reflect current state of Azure storage emulator in section dedicated for this type of differences. I also do not buying argument that issue will be fixes soon, because I opened this bug 5 months ago.

**Comment by jghanem** [comment]
Hi Ilya,
Thank you for your interest in documenting this bug; we will be looking at a better place to document such unexpected behavior moving forward.
However, as we mentioned to you over an email thread, this bug will be fixed as part of our next  emulator release early this summer.
We apologize for any inconvenience that this might have caused you.

Thanks,
Jean

**Pull request closed without merging**
