### PR TITLE
Update expressroute-howto-routing-arm.md

### PR DESCRIPTION
**Pull request by TaSato-MSFT**
Some users are not familiar with the word of "Layer 3 service provider". As result of it, they changes the peering setting by themselves and break the peering. So I would like to prevent their operation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TaSato-MSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@TaSato-MSFT : Thanks for your contribution to the Azure documentation! The author, @ganesr, has been notified to review your proposed change.

**Comment by ganesr** [comment]
This change does not add any value. Please close the PR.

**Comment by TaSato-MSFT** [comment]
OK.

**Pull request closed without merging**
