### PR TITLE
Implement CloseAsync and Abort needs to use this.webApp in StopWebServer()

### PR DESCRIPTION
**Pull request by snijhof**
```
private void StopWebServer()
{
    if (this.serverHandle != null)
    {
        try
        {
            this.serverHandle.Dispose();
        }
        catch (ObjectDisposedException)
        {
            // no-op
        }
    }
}
```

this needs to use this.webApp

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@snijhof__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@snijhof : Thanks for your contribution to the Azure documentation! The author, @vturecek, has been notified to review your proposed change.

**Comment by vturecek** [comment]
@snijhof great catch, thank you!

**Comment by vturecek** [comment]
#sign-off

**Pull request merged**
