### PR TITLE
Update data-factory-use-custom-activities.md

### PR DESCRIPTION
**Pull request by ahkim**
I propose a change as following as the sample creates a file dynamically but folder name is static. 

>> Output location is **adftutorial/customactivityoutput/YYYYMMDDHH/** where YYYYMMDDHH is the year, month, date, and hour of the slice being produced. See [Developer Reference][adf-developer-reference] for details.

to 

>>Output location is **adftutorial/customactivityoutput/** and output file name is yyyy-MM-dd-HH.txt where yyyy-MM-dd-HH is the year, month, date, and hour of the slice being produced. See [Developer Reference][adf-developer-reference] for details.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@ahkim 
Thank you for this contribution. I've sent this to the author for verification, and I'll right back to you.
--Carolyn

**Comment by cjgronlund** [comment]
@spelluru 
Hi, Sreedhar, Please let me know whether to accept this PR.
Thanks!

**Comment by spelluru** [comment]
#sign-off

**Pull request merged**
