### PR TITLE
Update service-fabric-reliable-actors-timers-reminders.md

### PR DESCRIPTION
**Pull request by keflem**
Updated method name from UnregisterReminder to UnregisterReminderAsync

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@keflem__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@keflem : Thanks for your contribution to the Azure documentation! The author, @vturecek, has been notified to review your proposed change.

**Comment by vturecek** [comment]
Thanks!

**Comment by vturecek** [comment]
#sign-off

**Pull request merged**
