### PR TITLE
Added a code example to read secrets

### PR DESCRIPTION
**Pull request by thomasberman**
Re-submitting this PR since it was not able to merge last time @BryanLa @cabailey:

Added a code example to authorize an app to read key vault secrets. I have submitted a PR with the same change in the CLI article.

https://github.com/Azure/azure-content/pull/4302

Thanks!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@thomasberman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by thomasberman** [comment]
Hey @deneha , is there something I need to do here? Was there another conflict?

**Comment by deneha** [comment]
@thomasberman There's a merge conflict on this request, so I can't merge it until that's fixed.

**Comment by thomasberman** [comment]
Should I re-fork and submit it again? Sorry, new to git in general.

**Comment by cabailey** [comment]
@thomasberman Sorry you're having problems with this - I don't know exactly what the merge conflict is but I've pinged @BryanLa in case it's something I've done wrong. I have problems with git as well!  Unfortunately, I think he's out until Monday so can you leave it with us for the time being?  We'll update the thread when we know more.  We'll get it sorted out!

**Comment by thomasberman** [comment]
Sure thing, thanks!

**Comment by deneha** [comment]
@thomasberman You could start another pull request like you did this one and close this pull request.  That is another option.

**Pull request closed without merging**
