### PR TITLE
Size accuracy

### PR DESCRIPTION
**Pull request by SeanFeldman**
1GB is 1024 MB

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SeanFeldman__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@SeanFeldman : Thanks for your contribution to the Azure documentation! The author, @SyntaxC4, has been notified to review your proposed change.

**Comment by SyntaxC4** [comment]
I have asked the dev team for verification as to what size in MB they used for the 1GB limit. Will update when I receive the information from the team.

**Comment by SyntaxC4** [comment]
The development team has responded and have explicitly said that they are using 1GB == 1000MB. I know that this doesn't reflect how 1GB is reflected in Windows, but this is the values which are in place.

This means that this document is valid and no update is needed. /cc: @PRmerger

**Comment by SeanFeldman** [comment]
Thank you @SyntaxC4 for confirmation. 
Too bad that the team chose the not so correct representation of 1GB :disappointed:

**Pull request closed without merging**
