### PR TITLE
Update virtual-machines-windows-index.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @dlepow, has been notified to review your proposed change.

**Comment by cynthn** [comment]
@tysonn these changes are fine to merge. @alexandair thank you for letting us know about the typos!

**Comment by dlepow** [comment]
@alexandair @cynthn - thanks for the helpful contribution!

**Pull request merged**
