### PR TITLE
Invalid url formatting and broken url

### PR DESCRIPTION
**Pull request by jeffpatton1971**
The original URL was not setup to actually be able to click, Additionally the original URL was invalid, I linked to the main portion of the template, as opposed to the raw dump of the azuredeploy.json file, which seems like better form to me.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jeffpatton1971__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@joaoma - Joao - please review this contribution

**Comment by joaoma** [comment]
#sign-off @jeffpatton1971  thank you for the contribution! the github repo had some changes lately and you caught one that I missed. I appreciate the help.

**Comment by jeffpatton1971** [comment]
Np, always happy to help!

**Pull request merged**
