### PR TITLE
Code was in plain text instead of in a code view.

### PR DESCRIPTION
**Pull request by seguler**
Modified line 43 "Install-Package ..." to be in a code view.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@seguler__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@seguler : Thanks for your contribution to the Azure documentation! The author, @seguler, has been notified to review your proposed change.

**Comment by seguler** [comment]
sign-off

**Comment by seguler** [comment]
#sign-off

**Pull request merged**
