### PR TITLE
add release notes for Core SDK 1.1 and 1.2

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
@Izikl  I received stale article notification and updated just Core SDK part of release notes. Please fill out changes you've made for windows SDK

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SergeyKanzhelev__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by SergeyKanzhelev** [comment]
Updated per @Izikl request

**Comment by deneha** [comment]
@SergeyKanzhelev Thank you for this update.  I'll notify the owner of the article.

@alancameronwills Would you please review and let me know if I should merge this?

**Comment by alancameronwills** [comment]
#sign-off

**Pull request merged**
