### PR TITLE
Update samples and changed note at the top

### PR DESCRIPTION
**Pull request by danieldobalian**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@danieldobalian__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dadobali). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@danieldobalian : Thanks for your contribution to the Azure documentation! The author, @billmath, has been notified to review your proposed change.

**Comment by danieldobalian** [comment]
@billmath

**Comment by billmath** [comment]
#sign-off

**Comment by BryanLa** [comment]
Hi @KatieCumming , @jomolnar  - Daniel was hoping to get this into a publishing build today. Any chance someone could review/merge by the 3pm build? Thanks!

**Comment by KatieCumming** [comment]
@danieldobalian - Hi Daniel. sure we're happy to review this for the 3:00 publish. Since there are so many changes, can you please open this in the private repo? (and then close this one) Thanks! Katie
(@BryanLa - thanks for your help with this)

**Comment by danieldobalian** [comment]
PR opened on private branch.

**Pull request closed without merging**
