### PR TITLE
Link: Formats Supported by the Media Encoder

### PR DESCRIPTION
**Pull request by kylegregory**
Add link to Formats Supported by the Media Encoder page on Azure Media Services documentation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kylegregory__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by deneha** [comment]
@kylegregory Thank you for this contribution! I've forwarded this to the author for review.

**Comment by Juliako** [comment]
#sign-off

**Comment by deneha** [comment]
@kylegregory This pull request has merge conflicts.  Please resolve the merge conflict so it can be merged.  Thank you.

**Comment by kylegregory** [comment]
@deneha Consider it done.

**Comment by deneha** [comment]
@kylegregory Thanks!

**Pull request merged**
