### PR TITLE
Update remoteapp-hybridtrouble.md

### PR DESCRIPTION
**Pull request by moumita11**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@moumita11__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mghosh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by moumita11** [comment]
adding more information on the troubleshooting guide .  When will the changes show up

**Comment by azurecla** [comment]
Hi __@moumita11__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mghosh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by moumita11** [comment]
Yes I am FTE at Microsoft

**Pull request merged**
