### PR TITLE
Typo inside the code sample Catch exception in line 374 from Ex to ex.

### PR DESCRIPTION
**Pull request by Tatsinnit**
Hiya @mmacy 

A quick typo change, in line 374 where instead of Ex it should be 'ex' I have checked with Felipe and he is cool with it. I am the dev who worked on this.  :shipit: 

Thanks,
^Tats

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Tatsinnit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tamishra). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@Tatsinnit : Thanks for your contribution to the Azure documentation! The author, @fayora, has been notified to review your proposed change.

**Comment by fayora** [comment]
👍 Approved!  

==>Anyone with right to merge: can you please merge it? 

Also, perhaps I need to be given merge rights on my doc? :)

**Comment by fayora** [comment]
#sign-off

**Pull request merged**
