### PR TITLE
Additional info on product features

### PR DESCRIPTION
**Pull request by LuisCabrer**
Added more information on feature types and quality of features.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@LuisCabrer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (luisca). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@LuisCabrer : Thanks for your contribution to the Azure documentation! The author, @luiscabrer, has been notified to review your proposed change.

**Comment by LuisCabrer** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request closed without merging**
