### PR TITLE
Update virtual-machines-common-extensions-customscript.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos (mostly casing).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@KundanaP Please review the proposed changes. Thanks.

**Comment by alexandair** [comment]
@KundanaP Could you please review the changes?

**Comment by KundanaP** [comment]
Adding Dan as I'm no longer with the team.

Thanks
Kundana
________________________________

**Comment by alexandair** [comment]
@KundanaP I don't see that Dan is added. :)

**Comment by cynthn** [comment]
@alexandair thank you for your contribution! I've pulled these changes over into our private repo to fix the merge conflicts. This PR will probably be closed once the changes get merged into the other repo.

**Pull request merged**
