### PR TITLE
Bad URL

### PR DESCRIPTION
**Pull request by jeffpatton1971**
Was pointing to potentially an old format of GitHub url, it returned a 404

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jeffpatton1971__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@joaoma - Joao, please review this update submitted by @jeffpatton1971. Thanks

**Comment by joaoma** [comment]
#sign-off

**Comment by joaoma** [comment]
#sign-off this was fixed before but for some reason came back. Will dig into it. Thank you for the feedback!

**Pull request merged**
