### PR TITLE
providing correct powershell module version number

### PR DESCRIPTION
**Pull request by giridharreddy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@giridharreddy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (giridham). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@giridharreddy : Thanks for your contribution to the Azure documentation! The author, @markgalioto, has been notified to review your proposed change.

**Comment by markgalioto** [comment]
@giridharreddy Thank you for updating this article. This information is correct, and this information should be merged.

**Comment by markgalioto** [comment]
#sign-off

**Comment by markgalioto** [comment]
@Ja-Dunn,  I should have let you know these changes can be merged as-is.

**Comment by markgalioto** [comment]
@Jim-Parker , can you take a look. This is ready to be merged.

**Pull request merged**
