### PR TITLE
Update virtual-machines-common-classic-agents-and-extensions.md

### PR DESCRIPTION
**Pull request by alexandair**
Thanks for your contribution! Here's a few guidelines to help speed review of your pull request:

- File name: Include the file name of the article you are updating in the title of the pull request.

- PMs and writers: If you are a core Azure product team PM or a content developer, please use the private repository. You can easily access the private repository from the article links by typing "-pr" after "azure-content" in the GitHub URL for the article. Instructions for requesting perms are posted in the [contributor's guide](https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github).

Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@tysonn New PR.

**Comment by tysonn** [comment]
@cynthn - Could you please review these updates from @alexandair and let me know if I can merge? Thanks

**Comment by cynthn** [comment]
#sign-off @tysonn these changes look fine :)

**Comment by tysonn** [comment]
@alexandair - I've merged the commits on the private side so I could resolve the merge conflicts, so I'm closing this PR. But the commits have been merged and the changes will go live later today.

**Pull request closed without merging**
