### PR TITLE
Update choose-web-site-cloud-service-vm.md

### PR DESCRIPTION
**Pull request by TheDarkCode**
Fix typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheDarkCode__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@TheDarkCode : Thanks for your contribution to the Azure documentation! The author, @tdykstra, has been notified to review your proposed change.

**Comment by tdykstra** [comment]
#sign-off

**Comment by tdykstra** [comment]
@TheDarkCode Thanks for the fix.

**Pull request merged**
