### PR TITLE
Modify New Relic store doc to simplify and direct users to the frequently updated New Relic hosted documentation

### PR DESCRIPTION
**Pull request by nickfloyd**
Simplifies page content so that all updates will be available through links to New Relic's documentation which is frequently updated.
This change modifies this [page](https://azure.microsoft.com/en-us/documentation/articles/store-new-relic-cloud-services-dotnet-application-performance-management/)

@PRMerger **Please note:** I am not a Microsoft author. But I am taking over as the main author of this article. See the related [PR](https://github.com/Azure/azure-content/pull/7345) for more information

sidekick: @cephalin

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nickfloyd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cephalin** [comment]
@PRmerger Please DO NOT close this PR without merging. @nickfloyd is THE AUTHOR of this article so he's the one that gets to sign-off on the article.

**Comment by PRmerger** [comment]
@nickfloyd : Thanks for your contribution to the Azure documentation! The author, @nickfloyd, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.

It�s easy to access the private repo version of your articles in GitHub. Just add �pr to the URL, as follows: 

Public repo URL: https://github.com/Azure/azure-content/blob/master/articles/azure-portal-overview.md

Private repo URL: https://github.com/Azure/azure-content-pr/blob/master/articles/azure-portal-overview.md

We've closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, see the contributor guide instructions.

**Comment by nickfloyd** [comment]
@cephalin,

Hmm.  It looks like there is some aspect of automation that is not working quite right for our scenario.  My guess is that perhaps the doc is either flagged or configured as a Microsoft "owned" doc.  

So what are our next steps?

**Comment by cephalin** [comment]
@nickfloyd I'm reaching out to internal folks to see what can be done here. I'll keep you posted.

**Comment by azurecla** [comment]
Hi __@nickfloyd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by KatieCumming** [comment]
@nickfloyd @cephalin @BryanLa - reopening and merging, as discussed.

**Comment by cephalin** [comment]
@KatieCumming Thank you Katie!
@nickfloyd Sorry for all this runaround and thank you for your contribution and for your patience with us.

**Pull request merged**
