### PR TITLE
Revising the timelines for AUX endpoint tests migration

### PR DESCRIPTION
**Pull request by SoubhagyaDash**
Revising the timelines for AUX endpoint tests migration

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SoubhagyaDash__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (sdash). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by SoubhagyaDash** [comment]
@alancameronwills please review.

**Comment by alancameronwills** [comment]
Hi Dash, I'll copy the changes to the endpoint-monitoring file.
But we can't delete app-insights-cloudservices.md without replacing it with something. There are various docs, forum responses and so on that point to it.

**Comment by alancameronwills** [comment]
#close

**Comment by alancameronwills** [comment]
#please-close

**Comment by PRmerger** [comment]
@SoubhagyaDash : Thanks for your contribution to the Azure documentation! The author, @soubhagyadash, has been notified to review your proposed change.

**Pull request closed without merging**
