### PR TITLE
Update data-factory-create-datasets.md

### PR DESCRIPTION
**Pull request by ahkim**
searched rest of "interval" and corrected values to be integer

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by cjgronlund** [comment]
@spelluru 
Sreedhar, please verify. Thanks!

**Comment by cjgronlund** [comment]
@ahkim 
Thank you for this fix. I'll verify with the author and get right back to you.

**Comment by spelluru** [comment]
#sign-off

**Comment by cjgronlund** [comment]
@ahkim 
Good suggestions on your PRs. Thank you!

**Pull request merged**
