### PR TITLE
Update virtual-machines-linux-how-to-attach-disk.md

### PR DESCRIPTION
**Pull request by woutercx**
What I had to do in the end to make the disk writable:
cd /datadisk
sudo chmod go+w datadisk/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@woutercx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Thank you for this contribution - sending to the author for review.

**Comment by cynthn** [comment]
@woutercx this is for attaching an existing data disk?

**Comment by woutercx** [comment]
Hi,

I don't remember exactly what I did, but yes, I think it was an existing 
data disk.
I took an image from the VM Depot Azure Gallery:
http://www.hanselman.com/blog/Over400VirtualMachineImagesOfOpenSourceSoftwareStacksInTheVMDepotAzureGallery.aspx
and in the end I had to make it writable.

**Comment by dsk-2015** [comment]
@woutercx thanks for your contribution. I just tried this with the new disk, and you do need to make it writable with that extra command. Please go ahead and merge this change, after making these changes: 
1) Replace datadisk by datadrive as that is used in the article 
2) Fix the typo in the second step, datadrive/ should be replaced with /datadrive 

Thanks again for doing this.

**Comment by tysonn** [comment]
@woutercx - Dhanashri submitted some patches to your fork for this - if you could accept her pull request in your fork of this project, we'll be able to move ahead and accept your update :)

Here's the link to that pull request: https://github.com/woutercx/azure-content/pull/1

**Comment by tysonn** [comment]
Thanks!

**Pull request merged**
