### PR TITLE
Fixing a typo

### PR DESCRIPTION
**Pull request by silverl**
s/ceneter/center/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@silverl__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@silverl : Thanks for your contribution to the Azure documentation! The author, @CarlRabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by CarlRabeler** [comment]
@tysonn OK to merge

**Pull request merged**
