### PR TITLE
Added missing parameter to code example

### PR DESCRIPTION
**Pull request by henrybeen**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@henrybeen__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@henrybeen : Thanks for your contribution to the Azure documentation! The author, @vturecek, has been notified to review your proposed change.

**Comment by vturecek** [comment]
#sign-off

@henrybeen thanks, good catch!

**Comment by vturecek** [comment]
@tysonn Please merge this change

**Pull request merged**
