### PR TITLE
proxy.SubscribeAsync<IGameEvents> example fix

### PR DESCRIPTION
**Pull request by troyanov**
SubscribeAsync<TEvent>

Summary:
Subscribe to a published actor event.

Type Parameters:
TEvent: The type of the event interface.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@troyanov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jessebenson - Could you please review this contribution from @troyanov and let me know if we can merge it?

**Comment by jessebenson** [comment]
:+1: Looks good!

**Comment by tysonn** [comment]
@troyanov - Thanks for the update!

**Pull request merged**
