### PR TITLE
updating date

### PR DESCRIPTION
**Pull request by nk773**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nk773__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@nk773 : Thanks for your contribution to the Azure documentation! The author, @cephalin, has been notified to review your proposed change.

**Comment by cephalin** [comment]
@nk773 I made a PR to your fork. Can you take a quick look?

**Comment by cephalin** [comment]
@nk773 Nevermind, the new ms.date is fine now :).

@ggailey777 This is ready to be merged.

**Pull request merged**
