### PR TITLE
Update iot-hub-devguide-messaging.md

### PR DESCRIPTION
**Pull request by kdotchkoff**
Documentation updates for the MQTT protocol implementation

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kdotchkoff__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kdotchko). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@kdotchkoff : Thanks for your contribution to the Azure documentation! The author, @dominicbetts, has been notified to review your proposed change.

**Comment by dominicbetts** [comment]
@kdotchkoff - thanks for this. Don't forget that you can make changes in azure-content-pr. That approach will streamline the process of getting your changes accepted.

**Comment by dominicbetts** [comment]
#sign-off

**Pull request merged**
