### PR TITLE
proposing change

### PR DESCRIPTION
**Pull request by 4c74356b41**
Since it doesn't make any sense the way it is now
Swapped "Failover and failback" and "VMware VM discovery" as it is obviously not right now

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @rayne-wiselman, has been notified to review your proposed change.

**Comment by rayne-wiselman** [comment]
@Jim-Parker 
#sign-off
Good to go

**Comment by Jim-Parker** [comment]
@rayne-wiselman Rayne, this branch has conflicts at this point, so I will need you help.

**Comment by rayne-wiselman** [comment]
Hi. The suggested changes are incorrect. The first vCenter user role permission (read only) refers to VMware VM discover and failover without shutdown. The second refers to Failover (with shutdown) and failback. I will update the exact wording with the dev team. In the meantime please close this pull request.

thx - Rayne

**Comment by 4c74356b41** [comment]
Can i talk to someone about this, because this doesn't make sense for me? At first you are saying that Azure_Site_Recovery role is for discovery only, and then you assign that role to a user and call it failover\failback?

**Comment by rayne-wiselman** [comment]
I’m clarifying with the SME. I’ll let you have that as soon as I can

**Comment by Ja-Dunn** [comment]
@rayne-wiselman - Hi Rayne, friendly reminder that we should close on this soon. Please fix the merge conflicts asap. Thanks!

**Comment by 4c74356b41** [comment]
Just a ping ;)

**Comment by jomolnar** [comment]
@rayne-wiselman - Hi Rayne, friendly reminder that we should close on this soon. Please fix the merge conflicts asap. Thanks!

**Comment by rayne-wiselman** [comment]
Apologies for not getting back on this – slipped through the loop.

Here’s how we’ll fix the table. Let me know if you think this is clearer or if you have any feedback.

I’ll submit the fix in a new PR since the original one is rather old.


Task

Role type

Permissions

Details

VMware discovery

Failover to Azure without shutting down source VM (useful for migration that doesn’t fail back)




Read-only VMware user



Data Center object –> Propagate to Child Object, role=Read-only



The user is assigned at datacenter level and thus has access to all the objects in the datacenter.
If you want to restrict the access, assign the No access role with the Propagate to child object to the child objects (vSphere hosts, datastores, VMs and networks).

Failover & failback

VMware user
This user will need to be able to perform operations such as creating and removing disks, powering on VMs etc.

We suggest you create a role (Azure_Site_Recovery) with the required permissions, and then assign the role to a VMware user or group

Data Center object –> Propagate to Child Object, role=Azure_Site_Recovery

Datastore -> Allocate space, browse datastore, low-level file operations, remove file, update virtual machine files

Network -> Network assign

Resource -> Assign VM to resource pool, migrate powered off VM, migrate powered on VM

Tasks -> Create task, update task

Virtual machine -> Configuration

Virtual machine -> Interact -> answer question, device connection, configure CD media, configure floppy media, power off, power on, VMware tools install

Virtual machine -> Inventory -> Create, register, unregister

Virtual machine -> Provisioning -> Allow virtual machine download, allow virtual machine files upload

Virtual machine -> Snapshots -> Remove snapshots


The user is assigned at datacenter level and thus has access to all the objects in the datacenter. If you want to restrict the access, assign the No access role with the Propagate to child object to the child object (vSphere hosts, datastores, VMs and networks).





From: Rayne Wiselman
Sent: Wednesday, August 24, 2016 11:02 AM
To: 'Azure/azure-content' <reply@reply.github.com>; Azure/azure-content <azure-content@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-content] proposing change (#7091)

I’m clarifying with the SME. I’ll let you have that as soon as I can

**Comment by 4c74356b41** [comment]
well, create a new pr and merge it, i cant comprehend this without formatting ;)

**Comment by rayne-wiselman** [comment]
Didnt realize there was formatting issue. I'll let you know when the PR is submitted



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Jim-Parker** [comment]
@rayne-wiselman Closing per conversation with Rayne

**Pull request closed without merging**
