### PR TITLE
Added CIFS port to the ILB to support FileTable

### PR DESCRIPTION
**Pull request by MindFlavor**
Updated step 5 script (Add-AzureEndpoint) to balance the CIFS ports. Without those the FileTable non transacted access functionality will not work correctly as it requires the CIFS ports to be open through the VNN of the listener (see https://msdn.microsoft.com/en-us/library/hh510261.aspx).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@MindFlavor__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@rothja 
Please review and approve/disapprove here with a comment, thanks. (**#sign-of** or **hold-off** is fine.)

**Comment by rmca14** [comment]
@rothja 
Following up, thanks.

**Comment by rmca14** [comment]
@rothja 
Following up. thanks.

**Comment by rmca14** [comment]
Author ack request 9/17.

**Comment by rmca14** [comment]
@rothja 
 Following up, thanks.

**Comment by rmca14** [comment]
@rothja 
Jason, closing this for now, but if needed feel free to reopen. Thanks.

**Pull request closed without merging**
