### PR TITLE
removed outlook 2016 paragraph

### PR DESCRIPTION
**Pull request by jobende**
removed outlook 2016 paragraph because office 2016 not support in ara

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jobende__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jobende). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by lizap** [comment]
@jobende - I'm going to have Eric Orman review this change, since he just had me add that para. I'll include you on that thread.

Thanks!

**Comment by lizap** [comment]
#sign-off - this change is ready to merge.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by BryanLa** [comment]
Merging per conversation w/@lizap, as the author is no longer in org/role.

**Pull request merged**
