### PR TITLE
Updated Business and Web tier retirement date text

### PR DESCRIPTION
**Pull request by crpietschmann**
Modified the mention that Business and Web service tiers being retired in September 2015 to be past tense since it's already happened.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@crpietschmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by Jarvis-arun** [comment]
1.  ,

Sent from my BlackBerry 10 smartphone.
From: Azure Contribution License Agreements
Sent: Thursday, June 30, 2016 4:53 PM
To: Azure/azure-content
Reply To: Azure/azure-content
Subject: Re: [Azure/azure-content] Updated Business and Web tier retirement date text (#6918)



Hi @crpietschmann<https://github.com/crpietschmann>, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
You've already signed the contribution license agreement. Thanks!
We will now validate the agreement and then real humans will evaluate your PR.

TTYL, AZPRBOT;

-

**Comment by PRmerger** [comment]
@crpietschmann : Thanks for your contribution to the Azure documentation! The author, @carlrabeler, has been notified to review your proposed change.

**Comment by CarlRabeler** [comment]
#sign-off

**Comment by JennieHubbard** [comment]
@cjgronlund – This PR can be merged

**Pull request merged**
