### PR TITLE
Update storsimple-remote-connect.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixed typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@alkohli - Another public repo PR for you to review

**Comment by alkohli** [comment]
@alexandair  Hi there, thank you so much for your contribution! @tysonn this PR is ready to merge as-is!

**Comment by alkohli** [comment]
@tysonn 
 Just wanted to make sure that no action is required on my part. I have already taken a look at the suggested changes. The PR is ready to be merged. Thanks!

**Pull request merged**
