### PR TITLE
Formatting updates to Azure Load Balancer document

### PR DESCRIPTION
**Pull request by pcgeek86**
- Removed unnecessary quotes from PowerShell code
- Replaced double quotes with single quotes, as best practice (avoids accidental, unintended interpolation)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
Thanks for the updates, Trevor. The author will need to review prior to merge.

**Comment by joaoma** [comment]
#sign-off

**Comment by joaoma** [comment]
will fix this later on.

**Pull request merged**
