### PR TITLE
Change Write-Host to Write-Output

### PR DESCRIPTION
**Pull request by qwergram**
"Script definition uses Write-Host. Avoid using Write-Host because it might not work in all hosts, does not work when there is no host, and (prior to PS 5.0) cannot be suppressed, captured, or redirected." Source: http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@qwergram__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@qwergram : Thanks for your contribution to the Azure documentation! The author, @thraka, has been notified to review your proposed change.

**Comment by Thraka** [comment]
@KatieCumming This is good.

**Comment by Thraka** [comment]
@Ja-Dunn

**Comment by Thraka** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Pull request merged**
