### PR TITLE
Simplified install and indentation changes

### PR DESCRIPTION
**Pull request by gopitk**
I am PM of the data science VM publishing a few changes. Pl review and push the same,

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gopitk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (gokuma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
I'm unable to identify **gopitk** as a MS employee. There is no name, alias, or MS designation associated with the GitHub user name. Please update your GitHub profile to follow this guidance
https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/tools-and-setup.md#create-a-github-account-and-set-up-your-profile

Thanks

**Comment by rmca14** [comment]
@bradsev 
Can you please approve/disapprove this PR with a comment? Thanks.

**Comment by bradsev** [comment]
These edits should be accepted. Gopi is the PM on my team.

**Pull request merged**
