### PR TITLE
Updated Powershell command in Step 5

### PR DESCRIPTION
**Pull request by bjeans**
Changed Step 5 PowerShell command from **Register-AzureRmProvider -ProviderNamespace Microsoft.Network** to **Register-AzureRmResourceProvider -ProviderNamespace Microsoft.Network**

Register-AzureRmProvider  looks to be the correct command - https://msdn.microsoft.com/en-us/library/mt603685.aspx

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bjeans__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@joaoma Hey Joao, can you please review this contribution?

**Comment by joaoma** [comment]
Approve merge. It changed from the previous powershell.

Joao

**Comment by tysonn** [comment]
Thanks for this contribution - I've merged it on the private side of our repo so the changes should be live this afternoon.

**Pull request closed without merging**
