### PR TITLE
Edits for Order By with strings

### PR DESCRIPTION
**Pull request by arramac**

### CODE REVIEW

**Comment by mimig1** [comment]
This PR is going to be closed and the author will open a new PR in the private repo.

**Comment by rmca14** [comment]
@mimig1 
Circling back to this PR. Thanks.

**Comment by mimig1** [comment]
Aravind - you said you were going to close this as you moved the changes to azure-content-pr. Please close.

**Comment by MonicaRush** [comment]
@arramac 
Aravind -- Did you get this message from Mimi? Can you please close the PR? Thanks a lot -- Monica

**Pull request closed without merging**
