### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@jimdial - Could you review this update in the public repo?

**Comment by jimdial** [comment]
#sign-off

**Comment by tysonn** [comment]
@4c74356b41 - Thanks for the fixes - merging :)

**Comment by 4c74356b41** [comment]
what does #sign-off mean? xD

**Comment by jimdial** [comment]
@4c74356b41 - It just means that I reviewed and approved it.  Thanks again for the fix!

**Comment by 4c74356b41** [comment]
ok, thanks!

**Pull request merged**
