### PR TITLE
Adding instructions for new graph runbooks

### PR DESCRIPTION
**Pull request by elcooper**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@elcooper__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (elcooper). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@mgoedtel - Please review this public repo PR

**Comment by MGoedtel** [comment]
I've reviewed and approve of Beth's modification to this article.  Thanks Beth for your help as always!

**Comment by MGoedtel** [comment]
#sign-off

**Pull request merged**
