### PR TITLE
Update vpn-gateway-table-gwtype-aggtput-include.md

### PR DESCRIPTION
**Pull request by EvanBasalik**
Including comment about Standard SKU

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@EvanBasalik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@EvanBasalik : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@cherylmc Hi Cheryl Please review the proposed change. Thanks.

**Comment by cherylmc** [comment]
Thanks, @EvanBasalik! #sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by cherylmc** [comment]
@jomolnar - I'm the owner of this include. I've signed off on the proposed change. Please merge.

**Comment by cherylmc** [comment]
@EvanBasalik - we're doing quite a few updates right now. I'm going to go ahead and close this, but add these changes to the updates. Otherewise, we'll get an ugly merge conflict. The update will have information talks about policybased vpns only being able to use the Basic SKU.

**Comment by cherylmc** [comment]
#please-close

**Pull request closed without merging**
