### PR TITLE
attempting to fix link

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @Rboucher, has been notified to review your proposed change.

**Comment by rboucher** [comment]
Thank you for fixing that link @4c74356b41, I appreciate it.

**Comment by rboucher** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
@rboucher - GitHub is usually case sensitive. The article metadata lists your github account as Rboucher, and your actual account is rboucher. Update the metadata to match your account name exactly.

**Comment by rboucher** [comment]
Due to the author naming issue with this article (rboucher vs Rboucher), also updating via private pull request to unblock this PR.  https://github.com/Azure/azure-content-pr/pull/29113.  I will report back when update is through.  Thanks for submitting @4c74356b41.  Sorry for the delay.

**Pull request merged**
