### PR TITLE
this is level 100 getting started doc for using xplat with Azure Storage

### PR DESCRIPTION
**Pull request by gangsir**
There is already one article for Powershell with Azure Storage. This is a peer article for  xplat.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gangsir__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by squillace** [comment]
@gangsir Hi! This looks great and I look forward to getting it in, but there are some things we need to modify and some things we need to clarify. 

1. "xplat" and "xplat-cli" have been changed to "Azure Command-line Interface for Mac, Linux, and Windows" on first mention, and "Azure CLI" everywhere else. So that means that the file names need to change to storage-azure-cli-guide-full.md and the same with the directory. 
2. You should point to the installation document for the Azure CLI at xplat-cli-install.md. (Yes, we will be changing that one soon, and we'll change your link to it in here. :-) )
3. You should point to the connecting document for the Azure CLI at xplat-cli-connect.md. (The same thing here. :-) )
4. You have this:
> +> [AZURE.NOTE] The [Getting started with Azure Storage and xplat-cli in 5 minutes](#Getting)
but there is no anchor that I could find right off with `#Getting` in it. I'm wondering whether I missed it...
5. The final thing is that nowhere does this say whether the commands you're issuing have to do with storage in the Azure CLI "arm" mode or "asm" mode. If there is no difference at all between the two modes, then can we say that, explicitly, at the top? If there is a difference, we need to mention that explicitly. 

Let me know if there are any issues or if this is unclear in some way! -- Ralph

**Comment by tamram** [comment]
Chungang, please incorporate Ralph's changes, and submit again for review (I'll review it then).

**Comment by gangsir** [comment]
Thanks, Tamra and Ralph. I will address the comments and submit again.

**Comment by squillace** [comment]
BTW, I love the contents. I'll be trying them all out today!

**Comment by gangsir** [comment]
Hi, Tamra and Ralph, I have update the content based on your comments. The changes include:
1. change the wording 'xplat' to 'Azure CLI'
2. update the title of the doc as well. 
3. add one note to mention that the commands and script in this guide run in asm mode and add one reference about arm commands. 

For the number 2, 3, 4 suggestions from Ralph, can you help me update in the doc directly? because I am not sure how to change a link to refer a doc in the repo with relative path. 

Thanks,
Chungang

**Comment by tamram** [comment]
Chungang, I can help you update the links. Let's get the doc into the repo, and I'll fix them from there. (The doc still needs to be hooked up to the left nav TOC before it will be discoverable.)

Approved for merge.

**Comment by deneha** [comment]
Requestor is MSFT employee - removed cla-required label.

**Pull request merged**
