### PR TITLE
Add .net framework support-ability in each cluster version

### PR DESCRIPTION
**Pull request by ahkim**
I have confirmed that version 3.3.0.941 cluster supports .Net Framework 4.5.2. .Net framework version matters to anyone who runs application on it. Please specify in the document from which version of cluster supports which version of .Net framework. Please see my post to refer the detail. 

http://ahkim.com/HDInsight-instance-supports-.Net-Framework-4.5.2.html

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahkim__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ahkim : Thanks for your contribution to the Azure documentation! The author, @mumian, has been notified to review your proposed change.

**Comment by cjgronlund** [comment]
@mumian
Jonathan, please review this contribution and let me know what you want done. Thanks!

**Comment by pablissima** [comment]
@mumian Jonathan, please review and let Carolyn know what to do

**Comment by mumian** [comment]
I haven't got a confirmation from the dev.  I will bring this up in the next content meeting.

**Comment by mumian** [comment]
I will fill a separate PR for the update.  Please close this PR.

**Comment by mumian** [comment]
#reject

**Comment by mumian** [comment]
I just received the confirmation. The article has been updated.  See https://github.com/Azure/azure-content-pr/pull/30894

**Comment by mumian** [comment]
Because this has been updated via another PR, please close this one. Thanks.

**Comment by mumian** [comment]
#please-close

**Pull request closed without merging**
