### PR TITLE
Update app-service-logic-transform-xml-documents.md

### PR DESCRIPTION
**Pull request by daviburg**
The BizTalk V1 API is obsolete.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@daviburg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@daviburg : Thanks for your contribution to the Azure documentation! The author, @anuragdalmia, has been notified to review your proposed change.

**Comment by Erikre** [comment]
Sent email to Mandi to take a look at.

**Comment by MandiOhlinger** [comment]
This topic is already deleted. So, we can close this PR.

**Pull request closed without merging**
