### PR TITLE
Remove Serializable attribute.

### PR DESCRIPTION
**Pull request by rustd**
This is not needed when you are using JSON.NET

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rustd__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pranavra). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by steved0x** [comment]
I made this fix to another pull request (https://github.com/Azure/azure-content-pr/pull/17318) so I am closing this one.

**Comment by steved0x** [comment]
This change looks good.

**Comment by steved0x** [comment]
#sign-off

**Pull request closed without merging**
