### PR TITLE
Update guidance-elasticsearch-configuring-resilience-and-recovery.md

### PR DESCRIPTION
**Pull request by allthedrones**
Added some detail & corrected the description of "yellow" and "red" cluster states.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@allthedrones__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@allthedrones : Thanks for your contribution to the Azure documentation! The author, @dragon119, has been notified to review your proposed change.

**Comment by dragon119** [comment]
According to elasticsearch doc, 'red' doesn't mean that all shards are missing.

The cluster health status is: green, yellow or red. On the shard level, a red status indicates that the specific shard is not allocated in the cluster, yellow means that the primary shard is allocated but replicas are not, and green means that all shards are allocated.

**Comment by ktoliver** [comment]
@allthedrones - Thanks for your contribution to the Azure docs. On November 16th, we announced the availability of our Azure technical documentation in a new location on [docs.microsoft.com](https://docs.microsoft.com). You can [read about it on our team blog](https://docs.microsoft.com/teamblog/docs-november-update). This change means the article source lives in a new GitHub repository. Because there are some changes in the source markdown as a result of the move, we can’t pull your contribution over to the new repo without creating a ton of merge conflicts. We invite you to resubmit the change (if you are willing) to the new version of the article at [https://docs.microsoft.com/en-us/azure/guidance/guidance-elasticsearch-configuring-resilience-and-recovery](https://docs.microsoft.com/en-us/azure/guidance/guidance-elasticsearch-configuring-resilience-and-recovery). Thanks for your understanding.

**Pull request closed without merging**
