### PR TITLE
Add two docs with right format of meta data

### PR DESCRIPTION
**Pull request by SuperScottz**
Add below 2 docs:
How to install MySQL on Azure
How to update Azure Linux Agent to latest version from Github

### CODE REVIEW

**Comment by tysonn** [comment]
@SuperScottz - Please review articles for typos and words run together. And, the second article contains a link with /en-us/ in it. Remove the locale from MSDN/ACOM links - it breaks the localized content experience when these are left in the articles.

**Comment by Thraka** [comment]
Also, The first letter of each item being bold is not really a standard style. If you want to call anything out, embolden the entire word.

**Comment by SuperScottz** [comment]
@tysonn , @Thraka , thanks for comment, I have updated based on your comment. any other comment?

**Comment by tysonn** [comment]
@SuperScottz : Please move these new articles to the private repo and stage first.

**Pull request closed without merging**
