### PR TITLE
How to connect Azure Redis Cache (SSL) to Redsmin

### PR DESCRIPTION
**Pull request by FGRibreau**
This was asked by a lot of our users so we took the time to explain how to do it!

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@FGRibreau__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by davidwrede** [comment]
Hi FGRibreau,

Thanks for adding the pointer! We will include your link as part of a larger update to the topic which should go up early next week.

- Dave

**Comment by FGRibreau** [comment]
@davidwrede great! Please let me know when it's online :)

**Comment by steved0x** [comment]
I have included this link in the following topic: http://azure.microsoft.com/en-us/documentation/articles/cache-dotnet-how-to-use-azure-redis-cache/ and it should go live in a couple of days.

Like this:

Next Steps
Now that you've learned the basics of Azure Redis Cache, follow these links to learn how to do more complex caching tasks.
•	Learn more about the StackExchange.Redis client: StackExchange.Redis cache client documentation
o	Azure Redis Cache can be accessed from many Redis clients and development languages. For more information, see http://redis.io/clients and Develop in other languages for Azure Redis Cache.
o	Azure Redis Cache can also be used with services such as Redsmin. For more information, see  How to retrieve an Azure Redis connection string and use it with Redsmin.
•	See the redis documentation and read about redis data types and a fifteen minute introduction to Redis data types.
•	See the MSDN Reference: Azure Redis Cache

**Comment by FGRibreau** [comment]
Great! Thanks @steved0x :)

**Pull request closed without merging**
