### PR TITLE
Add example on keyVault reference during deployment.

### PR DESCRIPTION
**Pull request by wenwu449**
Add example and reference about how to use keyVault reference during deployment.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@wenwu449__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (wenwu). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tfitzmac** [comment]
@davidwrede or @ggailey777 - this pull request can be merged. Thanks.

**Comment by ggailey777** [comment]
@wenwu449 or @tfitzmac this PR now has merge conflicts. If we still need this PR, please resolve the conflicts.

**Comment by wenwu449** [comment]
Conflicts resolved.

**Comment by ggailey777** [comment]
Thanks @wenwu449

**Pull request merged**
