### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by 4c74356b41**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@4c74356b41__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@4c74356b41 : Thanks for your contribution to the Azure documentation! The author, @ccompy, has been notified to review your proposed change.

**Comment by stefsch** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by ChrisCompy** [comment]
#sign-off

**Comment by 4c74356b41** [comment]
@ChrisCompy I'm afraid PRmerger expects your another account? Or am I missing something?

**Comment by ChrisCompy** [comment]
I have two GitHub accounts and it looks like I sadly did something with my personal account.  For whatever reason my 2FA isn't working and I can't sign in with that account.  I have requests out to GitHub and as soon as I can get in with it I will approve.

**Comment by TerryLanfear** [comment]
@ChrisCompy - Hi, 4c74356b41 reached out to me about stalled PRs. Do you know who your Pull Request approver is?  I think you can message the PR approver to merge this one for you.

**Comment by ChrisCompy** [comment]
@TerryLanfear @tysonn I think it is Tyson who I just included.  If you can do it manually that would be awesome.

**Comment by tysonn** [comment]
I can merge. The **properties>author** value in the article needs to be updated, either to list **ChrisCompy** as the author or to list **stefsch** as the author. It currently lists ccompy, which won't work with the automation.

**Pull request merged**
