### PR TITLE
Update machine-learning-recommendation-api-documentation.md to include header info for post requests

### PR DESCRIPTION
**Pull request by abhi1509**
Added  
HEADER   |`"Content-Type", "text/xml"`
for all the POST requests that contain xml request body.
Without this header, it causes http 502 error.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@abhi1509__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@LuisCabrer 
Please review this PR and approve/disapprove with a comment here, thanks.

**Comment by rmca14** [comment]
@LuisCabrer 
Following up, thanks.

**Comment by LuisCabrer** [comment]
This is good. Please take it.

**Comment by LuisCabrer** [comment]
This is a good change, please take it.
 
Date: Tue, 15 Sep 2015 08:34:10 -0700

**Comment by abhi1509** [comment]
Thanks.

**Pull request merged**
