### PR TITLE
Docker updates for tooling and ASP.NET 5 -> Core change per Cesar feedback

### PR DESCRIPTION
**Pull request by spboyer**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@spboyer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (shboyer). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@spboyer : Thanks for your contribution to the Azure documentation! The author, @azdocprs, has been notified to review your proposed change.

**Comment by jomolnar** [comment]
@allclark Hi Allen. Please review these proposed changes. Thanks.

**Comment by spboyer** [comment]
@allclark Can we get a look at this?

**Comment by mlearned** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by mlearned** [comment]
ok I'm not assigned as of yet (but will be), can we get it approved and pushed out or do I need to wait to be assigned?

**Comment by jomolnar** [comment]
@mlearned. Thanks for the sign off, Michael. I can merge this pull request.

**Comment by allclark** [comment]
#sign-off

**Comment by mike16546** [comment]
yes   i   sign  off

**Comment by mike16546** [comment]
im   out  of  it

**Pull request merged**
