### PR TITLE
add info re: creation of containers within storage accounts

### PR DESCRIPTION
**Pull request by m1nkeh**
Added some clarity on uploading data to Azure Storage accounts via Visual Studio as needing to create the blob containers first.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@m1nkeh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@m1nkeh 
Please feel free to resolve the merge conflicts. Thanks for your contribution.

**Comment by m1nkeh** [comment]
hmm.. i genuinely have no idea where these conflicts are, i can't see them to resolve! (I am just using github.com btw)

**Comment by rmca14** [comment]
The short version of how to resolve a merge conflict in the command line is the following:
git checkout <your working branch>
git pull upstream master
Using an editor such as Atom, open the md file, and then note all merge-conflicted content via the merge conflict markers
Delete the merge-conflicted conflict you don't want and all merge conflict markers
git add .
git commit -m "<your comment>"
git push origin <your working branch>

**Pull request closed without merging**
