### PR TITLE
fix blog->blob typo

### PR DESCRIPTION
**Pull request by gdusbabek**
Intended word was "blob"

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gdusbabek__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@gdusbabek : Thanks for your contribution to the Azure documentation! The author, @jeffstokes72, has been notified to review your proposed change.

**Comment by jeffstokes72** [comment]
#sign-off

**Comment by jeffstokes72** [comment]
@gdusbabek thank you for taking the time here. I appreciate the edit and will see it done.
Jeff

**Comment by jeffstokes72** [comment]
@cjgronlund please merge this request.

**Pull request merged**
