### PR TITLE
Update virtual-machines-windows-prepare-for-upload-vhd-image.md

### PR DESCRIPTION
**Pull request by rkyttle**
Fixed dispart san policy=onlineall typo

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rkyttle__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@rkyttle : Thanks for your contribution to the Azure documentation! The author, @genlin, has been notified to review your proposed change.

**Comment by genlin** [comment]
@rkyttle Thank you very much for pointing our the typo. 

@Ja-Dunn , please help merge the PR.

**Comment by genlin** [comment]
#sign-off

**Pull request merged**
