### PR TITLE
Fix language on automation

### PR DESCRIPTION
**Pull request by allclark**
The original language here says the opposite of what it means (increased time to value instead of reduced time to value).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@allclark__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@allclark : Thanks for your contribution to the Azure documentation! The author, @jodoglevy, has been notified to review your proposed change.

**Comment by jodoglevy** [comment]
@eamonoreilly @elcooper should be the owners of this article going forward

**Comment by elcooper** [comment]
@PRmerger this change looks good to me

**Comment by jodoglevy** [comment]
i think @PRmerger is a bot @elcooper. You may need to update the article's markdown to list you as the owner/author instead of me.

**Comment by jodoglevy** [comment]
#sign-off

**Comment by jodoglevy** [comment]
Hmm thought #sign-off was how i give approval but looks like it didn't do anything...

**Pull request merged**
