### PR TITLE
Update virtual-machines-automation-with-chef.md

### PR DESCRIPTION
**Pull request by diegoviso**
Reviewed for currency

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@diegoviso__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (diviso). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@diegoviso Diego, can you please submit this request via the private repo?

**Comment by diegoviso** [comment]
Updated on azure-content-pr

Thanks
Diego

**Comment by tysonn** [comment]
Closing per comment.

**Pull request closed without merging**
