### PR TITLE
Update configure-ssl-web-site.md

### PR DESCRIPTION
**Pull request by cristhianu**
Adding a note explaining the behavior when having both an IP Based SSL binding and an SNI binding with a different certificate for the same Web App.
In line 458 adding:
&gt; [AZURE.NOTE] If you add an **IP based SSL** to a Web App that already had an **SNI binding** with a different certificate, as soon as IP SSL is enabled for the Web App, we'll remap the site's hostname to that IP address, so if any other hostname is CNAME'd to that site's hostname it will also get traffic on IP SSL address. 
For such cases we created one more DNS entry: sni.&lt;nameofyourWebApp&gt;.azurewebsites.net where &lt;nameofyourWebApp&gt; is the name of your Azure App Service Web App. So, you should change your DNS records pointing to the name used in your SNI binding, so that it points to sni.&lt;nameofyourWebApp&gt;.azurewebsites.net instead.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cristhianu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@cephalin - Please review this proposed change from @cristhianu in the public repository.

**Comment by cephalin** [comment]
@cristhianu, 

Thanks a bunch for your contribution! Can you do us a favor? Right now the XML tags in your note (like &lt;...>) are not rendering properly. Can you change all instances of the **&lt;** character to **&amp;lt;** ? That will make your note show up properly in the rendered article.

Great addition, by the way!

**Comment by cristhianu** [comment]
@cephalin 
Done. Does it look good now?

**Comment by cephalin** [comment]
@cristhianu I don't see the change in your fork yet.

**Comment by cristhianu** [comment]
Done, now. Can you see it?

**Comment by cephalin** [comment]
@cristhianu  Awesome! Thanks!

@PRmerger Go ahead and merge.

**Comment by cephalin** [comment]
@tysonn This is ready to merge.

**Pull request merged**
