### PR TITLE
Update data-lake-store-secure-data.md

### PR DESCRIPTION
**Pull request by a-tan**
Hi Nitin, small update to the number of ACL entries allowed. For customers this number is 9, we reserve 3 entries for System use.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@a-tan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zhictan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@nitinme 
Please review and approve/disapprove this PR with a comment here. Thanks.

**Comment by nitinme** [comment]
Approved.
@rmca14 - Could you please update the ms.date so that the article shows the last updated date?

**Comment by rmca14** [comment]
@nitin, @a-tan  
I would update the date, but then that would generate a pull request that the original contributor would have to merge (a task they're probably unfamiliar with). Will be best to have the original contributor make any changes, including updating the date. Thanks.

**Comment by rmca14** [comment]
@nitin, @a-tan
I would update the date, but then that would generate a pull request that the original contributor would have to merge (a task they're probably unfamiliar with), and then another pull request that I've have to merge.

Will be best to have the original contributor make any changes, including updating the date. Thanks.

**Comment by nitinme** [comment]
@rmca14 
In that case, please go ahead and merge the PR as-is. We can update the date later.

**Pull request merged**
