### PR TITLE
Loading with Redgate article

### PR DESCRIPTION
**Pull request by TwoUnder**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TwoUnder__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@TwoUnder__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by TwoUnder** [comment]
#sign-off

**Comment by PRmerger** [comment]
@TwoUnder : Thanks for your contribution to the Azure documentation! The author, @mausher, has been notified to review your proposed change.

**Comment by TwoUnder** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by KatieCumming** [comment]
@TwoUnder - Hi Matt, please resubmit this through the private repo. Thanks, Katie

**Pull request closed without merging**
