### PR TITLE
Update machine-learning-create-workspace.md

### PR DESCRIPTION
**Pull request by hning86**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hning86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@garyericson - Please review this public repo PR

**Comment by garyericson** [comment]
@hning86 Thanks for making the change.
@tysonn This change looks good, you can go ahead and merge.

**Comment by garyericson** [comment]
@mention This change looks good, you can go ahead and merge.

**Pull request merged**
