### PR TITLE
Update automation-scenario-remove-resourcegroup.md

### PR DESCRIPTION
**Pull request by alexandair**
Fix typos.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by alexandair** [comment]
@mgoedtel The article mentions 3 parameters when actual runbook on PowerShell Gallery has only two parameters. The name of the runbook is Remove-ResourceGroup. One of the screenshots wrongly contains "Remove-ResourceGroups" (plural).

**Comment by MGoedtel** [comment]
@alexandair Thanks for bringing this to my attention.  I've updated that plus a few other items I decided to change after re-review of it.  We re-wrote this runbook a few times earlier his week while I was testing/re-writing part of the article, I didn't catch the filename change and my account must not have been working with the latest runbook when I pulled it down.  Anyway, I'm getting ready to submit the PR with new updates.

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@alexandair I had already updated the items and submitted in a new PR on Friday that went live over the weekend, and submitted an updated PR today to refine some points in the article, which combined also includes changes which addresses what you have in your PR.  I am not going to approve this PR being I have already resolved and is pending release.  It should go live tonight.
#please-close

**Pull request closed without merging**
