### PR TITLE
Fix reference in DefaultRunAsPolicy

### PR DESCRIPTION
**Pull request by chrisbardon**
You had a reference in the DefaultRunAsPolicy to run as MyDefaultUser, but didn't define that user in the Principals.  Not sure if that'll work or not.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chrisbardon__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@msfussell Hey Mark, can you please review this contribution? If it's appropriate, merge conflicts will need to be resolved.

**Comment by mwfussell** [comment]
This change is correct and should be merged into the document.

**Comment by tysonn** [comment]
@chrisbardon - Thanks for the update/correction!

**Pull request merged**
