### PR TITLE
Update machine-learning-retrain-models-programmatically.md

### PR DESCRIPTION
**Pull request by raymondlaghaeian**
Added link to sample code for endpoint mgmt.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@raymondlaghaeian__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (raymondl). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@raymondlaghaeian 
It will be better to follow our link guidance and not use the format to click "here." Please adjust the link format -- thank you. https://github.com/Azure/azure-content/blob/master/contributor-guide/create-links-markdown.md

link format

**Comment by rmca14** [comment]
@raymondlaghaeian 
Please resolve the merge conflict. Thanks.

**Comment by rmca14** [comment]
@raymondlaghaeian 
If you need help with link formatting and this merge conflict, let me know. Closing due to inactivity.

**Pull request closed without merging**
