### PR TITLE
Update changelog for 2.0.0-beta3

### PR DESCRIPTION
**Pull request by abaranch**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@abaranch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (abaranch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by alancameronwills** [comment]
editors, please pull

**Comment by davidwrede** [comment]
@abaranch, if this PR is still relevant, please resolve any merge conflicts.

Thanks,
Dave

**Comment by abaranch** [comment]
Abandoning this and recreating a new one #5243 so I do not have to resolve conflicts.

**Pull request closed without merging**
