### PR TITLE
Update expressroute-howto-linkvnet-arm.md

### PR DESCRIPTION
**Pull request by shchauh**
Converted important point to a Note

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@shchauh__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ganesr - Please review this proposed change in the public repo. 

@shchauh - Thanks for the update - would you be able to update this to use the correct markdown style?
```
> [AZURE.NOTE] To complete this tutorial...
```

**Comment by ganesr** [comment]
@tysonn change looks good. We can sign off once the style is fixed. I couldn't fix the files. Once Shailendra fixes it I will sign off.

**Comment by tysonn** [comment]
Contributor made update in another PR.

**Pull request closed without merging**
