### PR TITLE
Update virtual-machines-windows-troubleshoot-rdp-connection.md

### PR DESCRIPTION
**Pull request by NeilGo**
Add instructions for RDP login to azure Windows VM using a "Microsoft Account", such as with the Azure MSDN Windows 10 VM gallery images. (Note: Given the complexity, a SWAY walkthrough might be better)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NeilGo__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@dsk-2015 - Dhanashri, could you please review this contribution from @NeilGo?

**Comment by dsk-2015** [comment]
Thanks @NeilGo for your contribution. I'll take a look at this PR in the next couple days.

**Comment by dsk-2015** [comment]
@NeilGo I have been trying to work through your steps, but find that it wasn't very easy for me to get it all right. Would like to talk with you to get a some more in-depth idea about these steps. What is the best way to contact you?

**Comment by tysonn** [comment]
I'm going to close this for now. @NeilGo - If you are able to reply to @dsk-2015 and work through her questions, feel free to re-open the PR. Thanks

**Pull request closed without merging**
