### PR TITLE
Update sql-database-elastic-database-client-library.md

### PR DESCRIPTION
**Pull request by SilviaDoomra**
Elastic database client library is now open sourced! Adding information about it.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@SilviaDoomra__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by sidneyh** [comment]
#sign-off
@SilviaDoomra

**Comment by rmca14** [comment]
@SilviaDoomra @sidneyh 
Please remove the "en-us" language locale from the inserted link, thanks.

**Comment by SilviaDoomra** [comment]
Done! Updated the URL

**Pull request merged**
