### PR TITLE
Update virtual-networks-multiple-nics.md

### PR DESCRIPTION
**Pull request by stegag**
I am proposing the article to reflect the exact text its predecessor used to have, including the important piece of mentioning that a single-NIC VM cannot become a multinic VM.
This is creating a lot of support calls.

https://msdn.microsoft.com/en-us/library/azure/dn848315.aspx 

Multi-NIC VMs and single-NIC VMs are not supported in the same deployment. If you attempt to add a multi-NIC VM to a deployment that contains a single-NIC VM, or vice-versa, you will receive the following error: "Virtual machines with secondary network interfaces and virtual machines with no secondary network interfaces are not supported in the same deployment, also a virtual machine having no secondary network interfaces cannot be updated to have secondary network interfaces and vice-versa."

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stegag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@telmosampaio - Telmo, could you review this proposed change?

**Comment by tysonn** [comment]
@telmosampaio - Telmo, can you please review (2nd notice)

**Comment by telmosampaio** [comment]
I’ll get to this tomorrow, Monday the latest.

**Comment by tysonn** [comment]
@telmosampaio - Could you review?

**Comment by telmosampaio** [comment]
#sign-off

**Comment by tysonn** [comment]
@stegag - Thanks, merged!

**Pull request merged**
