### PR TITLE
[Azure Stack] Update the Azure PowerShell link

### PR DESCRIPTION
**Pull request by ostrich75**
The previous link would download the version 1.2.2, which doesn't support api version Azure stack use. Replace use the download link for version 1.2.1 instead.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ostrich75__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (larryzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ostrich75** [comment]
#sign-off

**Comment by azurecla** [comment]
Hi __@ostrich75__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (larryzh). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@ostrich75 - See mail about working in the private repo, please

**Pull request closed without merging**
