### PR TITLE
Update active-directory-get-started-premium.md

### PR DESCRIPTION
**Pull request by ScottSchnoll**
Updating name for EMS to Enterprise Mobility + Security

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ScottSchnoll__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ScottSchnoll : Thanks for your contribution to the Azure documentation! The author, @markusvi, has been notified to review your proposed change.

**Comment by MarkusVi** [comment]
Thanks, @ScottSchnoll.

**Comment by MarkusVi** [comment]
Hi @curtand , can you please merge this?

**Pull request merged**
