### PR TITLE
Update data-factory-build-your-first-pipeline-using-vs.md

### PR DESCRIPTION
**Pull request by adfteam**
Updated StorageLinkedService to AzureStorageLinkedService1

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@adfteam__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rmca14** [comment]
@spelluru 
Please review and approve/disapprove this PR here, thanks.

**Comment by spelluru** [comment]
I have made exact same changes as part of another PR today. Please close this. I have already communicated this to Wee Hyong. Thanks.

**Comment by spelluru** [comment]
Here is the duplicate PR: https://github.com/Azure/azure-content-pr/pull/14065.

**Pull request closed without merging**
