### PR TITLE
Updated service-fabric-get-started-with-a-local-cluster.md

### PR DESCRIPTION
**Pull request by slapointe**
Updated broken link to WordCount app url from http://localhost:8081/wordcount/index to http://localhost:8081/wordcount/index.html in the article and screenshots

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@slapointe__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by tysonn** [comment]
@seanmck - Sean, could you review these updates proposed by @slapointe in the public repo?

**Comment by seanmck** [comment]
Already fixed - you can close.

**Comment by tysonn** [comment]
@slapointe - Thanks for the update - I apologize for the delayed review. Closing per the author's feedback.

**Pull request closed without merging**
