### PR TITLE
update for transit network for BGP VPNs

### PR DESCRIPTION
**Pull request by omartin2010**
added that for clarity, as it's now supported.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@omartin2010__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (omartin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@omartin2010 : Thanks for your contribution to the Azure documentation! The author, @yushwang, has been notified to review your proposed change.

**Comment by yushwang** [comment]
#please-close

@omartin2010 - Thanks for the suggestion - it's a bit more involved. I am working with Cheryl to fix that entry. RDFE or Classic still does not work. So we will change the entry to Classic only, and refer to the BGP FAQ for  transit with ARM

**Comment by omartin2010** [comment]
Awesome!

**Pull request closed without merging**
