### PR TITLE
Update web-sites-godaddy-custom-domain-name.md

### PR DESCRIPTION
**Pull request by TheDarkCode**
Fix typo.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TheDarkCode__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@TheDarkCode : Thanks for your contribution to the Azure documentation! The author, @erikre, has been notified to review your proposed change.

**Comment by Erikre** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by Erikre** [comment]
@ggailey777 - It looks like I'm still the author. Please allow this update. Thanks

**Pull request merged**
