### PR TITLE
Update machine-learning-r-csharp-lexicon-based-sentiment-analysis.md

### PR DESCRIPTION
**Pull request by pengxiads**
update ms-date as required

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pengxiads__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (pengxia). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@pengxiads : Thanks for your contribution to the Azure documentation! The author, @pengxia, has been notified to review your proposed change.

**Comment by JennieHubbard** [comment]
@pengxiads please add the #sign-off in the comments to trigger PR acceptance.

**Comment by pengxiads** [comment]
#sign-off

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by tysonn** [comment]
@pengxiads - Your sign off did not work because your GitHub account is listed incorrectly in the article. After this PR is merged, please update your GitHub account in the properties>authors metadata attribute.

**Pull request merged**
