### PR TITLE
Update operations-management-suite-overview.md

### PR DESCRIPTION
**Pull request by alexandair**
Fixing typo. (There were two "data center" and one "datacenter".)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @bwren, has been notified to review your proposed change.

**Comment by bwren** [comment]
@alexandair Thanks for these.  We'll put these changes through.

**Comment by bwren** [comment]
#sign-off

**Pull request merged**
