### PR TITLE
Word corrections -> 'on-premise' to 'on-premises'

### PR DESCRIPTION
**Pull request by 1brianjones**
Changed a couple of occurrences of on-premise to on-premises.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@1brianjones__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@1brianjones : Thanks for your contribution to the Azure documentation! The author, @adrianhall, has been notified to review your proposed change.

**Comment by azurecla** [comment]
Hi __@1brianjones__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by adrianhall** [comment]
#sign-off

**Pull request merged**
