### PR TITLE
Clarified fixed VHD, NUMA, VHD resizing

### PR DESCRIPTION
**Pull request by magaal**
Added details on requiring a fixed VHD, NUMA bug no longer applicable, and VHD resizing from the generic article.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@magaal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mikegaal). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Jim-Parker** [comment]
@magaal thanks for the updates Mike.

**Comment by Jim-Parker** [comment]
@SuperScottz hey Scott, could you please review this contribution?

**Comment by SuperScottz** [comment]
@Jim-Parker @magaal Sorry for late, I think most of change in this PR has been updated, and I will double check first.

**Comment by SuperScottz** [comment]
@magaal 
Mike
I have merged your PR update into this file, and created another PR https://github.com/Azure/azure-content-pr/pull/20445.
I think we could close this PR if you have no concern, thank you!

**Comment by tysonn** [comment]
Closing based on @SuperScottz comment.

**Pull request closed without merging**
