### PR TITLE
Update app-service-logic-monitor-your-logic-apps.md

### PR DESCRIPTION
**Pull request by jboeshart**
Added details to note that the runtime output is encrypted at rest and access can be controlled through Azure RBAC.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jboeshart__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaboes). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@jboeshart : Thanks for your contribution to the Azure documentation! The author, @jeffhollan, has been notified to review your proposed change.

**Comment by jeffhollan** [comment]
Thanks @jboeshart looks good.  @KatieCumming this is ready to be merged.

**Comment by KatieCumming** [comment]
@jeffhollan - Hi Jeff, please update the added note to address the editing issues. Updated version is below. Thanks! Katie
">[AZURE.NOTE] All runtime details and events are encrypted at rest within the Logic App service. They are only decrypted upon a view request from a user. Access to these events can also be controlled by Azure Role-Based Access Control (RBAC)."

**Comment by jboeshart** [comment]
@KatieCumming just updated the PR with your suggestions, thanks!

**Comment by KatieCumming** [comment]
@jboeshart - thanks Jason!! Merging.

**Pull request merged**
