### PR TITLE
Incorrectly classified in Python and not PHP

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lmazuel__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lmazuel). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by lmazuel** [comment]
#sign-off

**Comment by PRmerger** [comment]
@lmazuel : Thanks for your contribution to the Azure documentation! The author, @devinrader, has been notified to review your proposed change.

**Comment by PRmerger** [comment]
Only the author of the article can use the sign off comment to add the ready-to-merge label.

**Comment by KatieCumming** [comment]
@devinrader - Hi Devin, can you please review this change? Thanks! Katie

**Comment by KatieCumming** [comment]
@devinrader - Hi Devin, can you have a look? Thanks!

**Comment by jomolnar** [comment]
@Imazuel Hi Laurent
This change should be made in the private repository.
For information about how to get permissions and access the private repository, see https://github.com/Azure/azure-content#use-github-git-and-this-repository.

Please close this pull request and submit the change in the private repository. Thanks.

**Comment by jomolnar** [comment]
@Imazuel Hi Laurent
Closing this pull request so that change can be made in the private repository.

**Pull request closed without merging**
