### PR TITLE
Minor correction in Step 16, point 16

### PR DESCRIPTION
**Pull request by venkatveeramanidaasan**
Change from Get-AzureRmContext to Set-AzureRmContext as the following points are talking about setting the property of Set-AzureRmContext.

Thanks
Venkat

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@venkatveeramanidaasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@venkatveeramanidaasan : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@venkatveeramanidaasan thank you for catching that error and submitting a request to correct it.  I'll approve so it gets addressed quickly.

**Comment by MGoedtel** [comment]
#sign-off

**Comment by venkatveeramanidaasan** [comment]
Thanks to you and MS for enabling us to contribute through github.

**Pull request merged**
