### PR TITLE
Update billing-troubleshoot-azure-sign-up-issues.md

### PR DESCRIPTION
**Pull request by JiangChen79**
Thanks for your contribution! Here's a few guidelines to help speed review of your pull request:

- File name: Include the file name of the article you are updating in the title of the pull request.

- PMs and writers: If you are a core Azure product team PM or a content developer, please use the private repository. You can easily access the private repository from the article links by typing "-pr" after "azure-content" in the GitHub URL for the article. Instructions for requesting perms are posted in the [contributor's guide](https://github.com/Azure/azure-content/blob/master/contributor-guide/tools-and-setup.md#permissions-in-github).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@JiangChen79__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (cjiang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by JiangChen79** [comment]
Fix list issues

**Comment by JiangChen79** [comment]
#sign-off

**Comment by JiangChen79** [comment]
@tysonn New PR.

**Comment by tysonn** [comment]
@JiangChen79 - Please resubmit via the private repo so updates can be staged and validated. Thanks!

**Pull request closed without merging**
