### PR TITLE
Update application-gateway-create-url-route-arm-ps.md

### PR DESCRIPTION
**Pull request by ShuheiUda**
PowerShell cmdlet is incorrect.
There is not difine variable. ($appgwName, $rgname)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ShuheiUda__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@ShuheiUda : Thanks for your contribution to the Azure documentation! The author, @joaoma, has been notified to review your proposed change.

**Comment by joaoma** [comment]
@sign-off

**Comment by joaoma** [comment]
Thank you for catching that, @ShuheiUda . I approved the merge.

**Pull request merged**
