### PR TITLE
Added -verbose mode clarification

### PR DESCRIPTION
**Pull request by AlekseiPolkovnikov**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AlekseiPolkovnikov__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (alpolko). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@AlekseiPolkovnikov : Thanks for your contribution to the Azure documentation! The author, @georgewallace, has been notified to review your proposed change.

**Comment by georgewallace** [comment]
@AlekseiPolkovnikov  Thanks again for your contributions.  I created a pull request your fork for this.  Can we remove the -verbose flag instead as it provides no value to the cmdlet.  I think that would clear up the confusion.  Once again thanks for catching these issues in the articles.

**Comment by AlekseiPolkovnikov** [comment]
@georgewallace I agree, way to go as well, thanks, done.

**Comment by georgewallace** [comment]
#sign-off

**Pull request merged**
