### PR TITLE
Update automation-starting-a-runbook.md

### PR DESCRIPTION
**Pull request by alexandair**
Remove a section about how to start a runbook in the classic portal.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@alexandair__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@alexandair : Thanks for your contribution to the Azure documentation! The author, @mgoedtel, has been notified to review your proposed change.

**Comment by MGoedtel** [comment]
@alexandair thank you for taking the time to submit a request to suggest recommended corrections/updates to this article.  I have reviewed them and approve them to be merged.

**Comment by mike16546** [comment]
im  out  of  it

**Comment by alexandair** [comment]
@tysonn Could you merge it, please?

**Comment by tysonn** [comment]
@MGoedtel - Matt, can you please remember to use the comment automation to get PRs merged? See https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-pull-request-comments.md. Using the correct comments speeds up the process considerably.

**Comment by alexandair** [comment]
@tysonn That link gives me 404. Maybe this one is correct: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-pull-request-comments.md /cc @MGoedtel

**Comment by tysonn** [comment]
@alexandair - You would have to access it via the public repo: https://github.com/Azure/azure-content/blob/master/contributor-guide/contributor-guide-pull-request-comments.md.

**Comment by MGoedtel** [comment]
#sign-off

**Pull request merged**
