### PR TITLE
Update hdinsight-apache-spark-jupyter-notebook-install-locally.md

### PR DESCRIPTION
**Pull request by GaryHope**
corrected syntax for print(os.path.expanduser('~'))

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@GaryHope__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by PRmerger** [comment]
@GaryHope : Thanks for your contribution to the Azure documentation! The author, @nitinme, has been notified to review your proposed change.

**Comment by nitinme** [comment]
@GaryHope - Thanks for the recommended updates.

**Comment by nitinme** [comment]
#sign-off

**Pull request merged**
